// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function widgetterm_wgtTerm(p,q,y){function r(){var a={prompt:"> ",name:"prompt",xheight:400,xenabled:!1,greetings:l+c+m,keypress:function(c){if(96==c.which)return $("#ge-prompt").slideToggle("fast"),!1}};$("#ge-prompt").hide();n=$("#ge-prompt").terminal(function(a,d){var h=a.indexOf(" "),f=a,g="";0<=h&&(f=a.substring(0,h),g=a.substring(h+1,a.length));0<f.length&&(e(c),!1===t(f,g)&&(h=b.ajaxRequestCreate("system_processcommand",[{name:"command",value:a}]),b.ajaxCall(URL_WEBSERVICE,h,u,v)))},a)}function t(a,
s){var d=!1;"help"===a?(e(m),d=!0):"about"===a?(e(l),d=!0):"broadcast"===a?(b.broadcast(w,"core",s),d=!0):"browser"===a?(e(b.getBrowser().name+" version "+b.getBrowserVersion()+" ("+b.getBrowser().major+")"+c+b.getAgent()+c+"Support for your browser is "+b.getBrowser().support+". "+b.getBrowserRecommendation()+c),d=b.getBrowser().capabilities.split(","),processArray(d,function(a){e(a+c)}),d=!0):"debug"===a?("TRUE"===DEBUG_JS?e("debug is on"+c):e("debug is off"+c),d=!0):"debugoff"===a?(e("debug is off"+
c),DEBUG_JS="FALSE",d=!0):"debugon"===a?(b.hasCapability("console")?(e("debug is on"+c),DEBUG_JS="TRUE"):e("debug is not supported in this browser"+c),d=!0):"logout"===a?(b.dialogConfirm("Are you sure you wish to logout?<br><br>Please be sure you have saved your data before continuing.",function(){var a=b.ajaxRequestCreate("public_logout",[]);b.ajaxCall(URL_WEBSERVICE,a,x,b.ajaxError)}),d=!0):"maps"===a?(0<b.getMapProvider().length?e(b.getMapProvider()+c):e("none"+c),d=!0):"modules"===a?(d=CLIENTMODULES.split(","),
processArray(d,function(a){e(a+c)}),d=!0):"os"===a?(e(b.getOS()+c),d=!0):"printer"===a?(b.isPrinterRegistered()?(e("printer version: "+b.getPrinterVersion()+c),e("default printer: "+b.getDefaultPrinter()+c),d=b.getPrinters(),processArray(d,function(a){e(a.description+c)})):e("printer is not registered"+c),d=!0):"tabs"===a?(b.hasCapability("multimon")?f(b.getTabs(),g):e("multimon is not supported"+c),d=!0):"timers"===a?(f(b.getTimers(),g),d=!0):"version"===a?(e(b.getVersion()+c+OS_COPYRIGHT+c),d=!0):
"viewport"===a?(b.hasCapability("viewport")?e(b.getViewPort().width+"x"+b.getViewPort().height+c):e("viewport is not supported in this browser"+c),d=!0):"windows"===a&&(f(b.getForms(),g),d=!0);"zoom"===a?(e(b.getZoom()+"%"+c),d=!0):a==k&&(d=!0);return d}function g(a,b){e(a+" : "+b+c)}function f(a,c){for(var b in a)"function"!==typeof a[b]&&(c.apply(this,[b,a[b]]),"object"==typeof a[b]&&f(a[b],c))}function e(a){n.echo('<font color="yellow">'+a+"</font>",{raw:!0})}function v(){e("invalid command"+c);
e(k+c)}function u(a){null!==a&&void 0!==a&&(f(a,g),e(k+c))}function x(a){b.logout("","wgtTerm")}var b=p,w=q,c="\n",k="ready",l=APP_NAME+" "+APP_VERSION+c+APP_COPYRIGHT+c+c+b.getVersion()+c+OS_COPYRIGHT+c,m="help, about, broadcast, browser, clear, debug, debugon, debugoff, logout, maps, modules, os, printer, tabs, timers, version, windows, zoom"+c,n=null;this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!1};this.Form_onBroadcast=function(a,b){if(0===b.indexOf("cli ")){var d=
b.substring(4,b.length);e(d+c);e(k+c)}};this.Form_onLoad=function(){r()};this.Form_onPermissionCheck=function(){return!0}};
