// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function widgetpanel_wgtContent(a,b,d){var c=this;a.toBoolean(a.getProperty("enablebranches"));d=str_replace(a.getProperty("branchname")," ","&nbsp;");0===d.length&&(d="Branches");var e,f=[{location:"root",title:"Icons",layout:[["icoClock","icoZoom"]]}],g=[{id:"-",caption:"",classes:"",style:"width:235px; height:235px; background-size: contain;",permissions:[],action:"",actionData:null,tip:"",type:"toolbarbutton"},{id:"icoClock",caption:"",classes:"gi-alarm",style:"width:235px; height:235px; background-size: contain;",
permissions:function(){return a.isModuleLoaded("widgetclock")},action:function(c){a.broadcast(b,"panel","actionShowForm",c,!1)},actionData:"widgetclock.wgtClock",tip:"Click here to show the clock.",toptip:!0,type:"toolbarbutton"},{id:"icoFullscreen",caption:"",classes:"gi-fullscreen",style:"width:235px; height:235px; background-size: contain;",permissions:[],action:function(){a.broadcast(b,"panel","actionToggleFullScreen","",!1)},actionData:null,tip:"Click here to switch between full screen mode and normal window mode.",
toptip:!0,type:"toolbarbutton"},{id:"icoZoom",caption:"",classes:"gi-showdesktop",style:"width:235px; height:235px; background-size: contain;",permissions:[],action:function(){a.broadcast(b,"panel","actionZoom","",!1)},actionData:null,tip:"Click here to zoom.",toptip:!0,type:"toolbarbutton"}];this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!1};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onMouseEnter=function(){a.showMDIClose(b)};this.Form_onMouseLeave=
function(){a.hideMDIClose(b)};this.Form_onPermissionCheck=function(){return!0};this.Form_onLoad=function(){a.unbindEvents(b,"gb-form-close,ge-content,gb-form");a.bindEvent(c,b,".gb-form","Form","onDblClick");a.bindEvent(c,b,".gb-form","Form","onMouseEnter");a.bindEvent(c,b,".gb-form","Form","onMouseLeave");a.bindEvent(c,b,".gb-form-close","FormClose","onClick");a.bindEvent(c,b,".ge-content","Content","onClick");e=new jDock(a,{map:f,tiles:g,mode:"horizontalmenu",alwayshidemorebutton:!0});e.render(b,
".ge-content")};this.FormClose_onClick=function(){a.closeForm(b)};this.Content_onClick=function(){document.documentElement.requestFullscreen?document.documentElement.requestFullscreen():document.documentElement.msRequestFullscreen?document.documentElement.msRequestFullscreen():document.documentElement.mozRequestFullscreen?document.documentElement.mozRequestFullscreen():document.documentElement.webkitRequestFullscreen&&document.documentElement.webkitRequestFullscreen(element.ALLOW_KEYBOARD_INPUT)}}
;
