// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function leaflet_frmMap(A,B,t){function C(a){function b(){for(var d=0,g=0,e;!(e=a.charCodeAt(c)-63,c++,d+=(e&31)*Math.pow(2,g),g+=5,32>e););return d&1?~(d>>1):d>>1}for(var d=[],c=0,e=a.length,l=0,k=0;c<e;)l+=b(),k+=b(),d.push([1E-5*l,1E-5*k]);return d}function D(a){var b="";processArray(u,function(d){if(d.groupid===a)return b=d.colour,!0});return b}function E(a){var b="";processArray(s,function(d){if(d.grouplocalityid===a||d.grouplocalityid===htmlEncode(a))return b=d.groupid,!0});return b}function F(a){var b=
"";processArray(s,function(d){if(d.grouplocalityid===a||d.grouplocalityid===htmlEncode(a))return b=d.grouplocalityid,!0});return b}function G(a){var b=-1,d=0;processArray(h,function(c){c.groupid===a&&(b=d);d++});return b}function v(a){n&&n.remove();n=L.marker([a.lat,a.lon]).addTo(e);a.bbox&&a.bbox.lat1!==a.bbox.lat2&&a.bbox.lon1!==a.bbox.lon2?e.fitBounds([[a.bbox.lat1,a.bbox.lon1],[a.bbox.lat2,a.bbox.lon2]],{padding:[100,100]}):e.setView([a.lat,a.lon],18)}function H(){var a=b.addUniqueID(b.element(c,
".ge-map"));e=L.map(a).setView([-37.813628,144.963058],18);var g,d;"OPENMAPS"===w?(g="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",d="Powered by Geoapify | \u00a9 OpenMapTiles \u00a9 OpenStreetMap contributors"):"GOOGLE"===w&&(g="https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",d="Powered by Google Maps. Map data \u00a92025 Google.");L.tileLayer(g,{maxZoom:18,attribution:d,apiKey:GEOAPIFY_APIKEY,mapStyle:"osm-bright-smooth"}).addTo(e);a=L.control.addressSearch(GEOAPIFY_APIKEY,{position:"topright",
value:I,resultCallback:v,suggestionsCallback:function(a){0<a.length&&v(a[0])}});e.addControl(a);p=L.control({position:"topleft"});p.onAdd=function(a){a=L.DomUtil.create("div","ge-legend");a.style.background="white";a.style.padding="10px";a.style.borderRadius="5px";a.style.boxShadow="0 0 15px rgba(0,0,0,0.2)";a.style.maxHeight="70%";a.style.overflowY="auto";a.innerHTML="";return a};p.addTo(e);r=(void 0)[0];q(!0);e.setZoom(10);b.registerServerEvent("mapping",c);b.enableServerEventQueue("mapping");b.ajaxCall(URL_WEBSERVICE,
b.ajaxRequestCreate("esb_registerbroadcaster",[{name:"eventqueue",value:"mapping"}]),doNothing,doNothing);b.ajaxCall(URL_WEBSERVICE,b.ajaxRequestCreate("esb_registerlistener",[{name:"eventqueue",value:"mapping"}]),doNothing,doNothing)}function J(a,c,d,f){var h,l,k,m,n=a.polylinedataformat;try{0<a.startgeolocation.length&&(k=JSON.parse(a.startgeolocation)),0<a.endgeolocation.length&&(m=JSON.parse(a.endgeolocation)),0<a.polylinedata.length&&(l=JSON.parse(a.polylinedata))}catch(q){b.dialogAlertScroll(q,
function(){})}f&&(void 0!==l&&"GOOGLE"===n&&(h=[],processArray(l,function(a){0<a.routes.length&&h.push(a.routes[0].polyline.encodedPolyline)})),void 0!==k&&void 0!==m&&(k.lat===m.lat&&k.lng===m.lng?L.marker([k.lat,k.lng],{icon:L.divIcon({className:"custom-icon",html:'<div style="cursor:default; width: 20px; height: 20px; font-size: 12px; color: yellow; background-color: #ff0000; border-radius: 50%; text-align: center; line-height: 20px;">SE</div>',iconSize:[20,20]})}).addTo(e):(L.marker([k.lat,k.lng],
{icon:L.divIcon({className:"custom-icon",html:'<div style="cursor:default; width: 20px; height: 20px; font-size: 12px; color: yellow; background-color: #ff0000; border-radius: 50%; text-align: center; line-height: 20px;">S</div>',iconSize:[20,20]})}).addTo(e),L.marker([m.lat,m.lng],{icon:L.divIcon({className:"custom-icon",html:'<div style="cursor:default; width: 20px; height: 20px; font-size: 12px; color: yellow; background-color: #ff0000; border-radius: 50%; text-align: center; line-height: 20px;">E</div>',
iconSize:[20,20]})}).addTo(e))),processArray(a.localities,function(b){var c=JSON.parse(b.geolocation);L.marker([c.lat,c.lng],{icon:L.divIcon({className:"custom-icon",html:'<div class="ge-grouplocality" style="width: 20px; height: 20px; font-size: 12px; color: yellow; background-color: '+d+'; border-radius: 50%; text-align: center; line-height: 20px;" grouplocalityid="'+htmlEncode(b.id)+'">'+htmlEncode(b.sequence)+"</div>",iconSize:[20,20]})}).addTo(e);s.push({groupid:a.groupid,grouplocalityid:b.id})}),
"GOOGLE"===n&&void 0!==h&&processArray(h,function(a){a=C(a);0<a.length&&L.polyline(a,{color:d}).addTo(e)}));l="";f&&(l="checked");c='<div style="display: flex; align-items: center; margin-bottom: 10px;">'+('<div class="ge-colour-circle group-color-circle" groupindex="'+c+'" style="cursor:pointer; width: 20px; height: 20px; background-color: '+d+'; border-radius: 50%; margin-right: 5px;"></div><input class="ge-togglegroup" groupindex="'+c+'" style="vertical-align:top; margin-right: 5px;" type="checkbox"'+
l+">")+"<div>";c+="</div>";c+="</div>";p.getContainer().innerHTML+=c;$(".ge-colour-circle").on("click",function(){var a=parseInt($(this).attr("groupindex"),10),a=r.groups[a];0<a.localities.length&&(a=JSON.parse(a.localities[0].geolocation),e.panTo([a.lat,a.lng]))})}function q(a){p.getContainer().innerHTML="";e.eachLayer(function(a){(a instanceof L.Polyline||a instanceof L.Marker)&&e.removeLayer(a)});if(0<r.groups.length){var g="";a&&(g="checked");a='<div style="display: flex; align-items: center; margin-bottom: 10px;">'+
('<input class="ge-toggleall" style="vertical-align:top; margin-right: 5px;" type="checkbox"'+g+">")+"<div>";a+="<div><b>Toggle All</b></div>";a+="</div>";a+="</div>";p.getContainer().innerHTML+=a}processArray(r.groups,function(a){var c=D(a.groupid);0===c.length&&(c=K.shift(),u.push({groupid:a.groupid,colour:c}));var e=!0,g=G(a.groupid);0<=g?e=h[g].visible:(g=h.length,h.push({groupid:a.groupid,visible:!0}));try{J(a,g,c,e)}catch(f){b.dialogAlertScroll(f,function(){})}});b.unbindEvents(c,"ge-grouplocality,ge-toggleall,ge-togglegroup");
b.bindEvent(f,c,".ge-grouplocality","GroupLocality","onClick");b.bindEvent(f,c,".ge-toggleall","ToggleAll","onClick");b.bindEvent(f,c,".ge-togglegroup","ToggleGroup","onClick")}var w="GOOGLE",b=A,f=this,c=B,x="TRUE"==TESTSCROLL&&!b.hasCapability("regionscroll")&&b.hasCapability("mobile");x&&(b.element(c,".ge-content-panel").removeClass("gb-scrollable-panel"),b.element(c,".ge-thecontent").removeClass("gb-scrollable-content"),b.element(c,".gb-form").removeClass("gb-resizable"),b.element(c).css({position:"relative",
height:"auto"}));var y=t.caption,I=t.search,K="red orange magenta purple pink brown gray black turquoise yellow darkred coral hotpink violet crimson sienna olive teal salmon gold firebrick tomato orchid plum fuchsia peru tan khaki lime greenyellow darkorange orangered deeppink mediumvioletred maroon chocolate saddlebrown darkkhaki lawngreen chartreuse darkgreen forestgreen limegreen mediumseagreen seagreen darkseagreen mediumaquamarine aquamarine cadetblue lightseagreen yellowgreen springgreen mediumspringgreen green bluegreen blue blueviolet darkslateblue slateblue mediumslateblue indigo darkblue steelblue royalblue dodgerblue skyblue lightblue powderblue cornflowerblue lightsteelblue mediumpurple darkmagenta palevioletred mediumorchid darkviolet purple darkgray olivedrab burlywood rosybrown sandybrown lightsalmon lightcoral palegreen thistle mistyrose seashell peachpuff navajowhite lemonchiffon honeydew mintcream azure lightcyan paleturquoise gainsboro whitesmoke lightgray aliceblue ghostwhite".split(" ").slice(),
u=[],r,s=[],h=[],e,n=null,p,z,M=[{location:"root",title:"Home",layout:[["CloseButton","ToggleLegendButton"]]}],N=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){f.FormClose_onClick()},actionData:null,tip:"Click here to close map.",type:"toolbarbutton"},{id:"ToggleLegendButton",caption:"Toggle Legend",classes:"",permissions:[],action:function(){f.ToggleLegend_onClick()},
actionData:null,tip:"Click here to show or hide the legend.",type:"toolbarbutton"}];this.Form_onBroadcast=function(a,b,c){};this.Form_onClick=function(){b.setFormFocus(f,c)};this.FormClose_onClick=function(){b.closeForm(c)};this.Form_onDblClick=function(){b.formToFront(c)};this.Form_onResize=function(a,g){var d=b.getFormCanvasHeight(c)-80;x?doNothing():(b.element(c,".ge-content-panel").height(d+"px"),b.element(c,".ge-content-panel").width("100%"),b.element(c,".ge-thecontent").height("100%"),b.element(c,
".ge-thecontent").width("100%"),e.invalidateSize())};this.Form_onLoad=function(){z=new jDock(b,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:M,tiles:N});z.render(c,".ge-button-panel");void 0!==y&&b.element(c,".ge-form-title").text(y);var a=b.getCanvasTop(),e=b.getCanvasHeight(),d,h;768<b.getCanvasWidth()?(d=b.getCanvasLeft()+0.5*b.getCanvasWidth(),h=0.5*b.getCanvasWidth()):(d=b.getCanvasLeft(),h=b.getCanvasWidth());b.element(c,".gs-form-standard").css("position","absolute").css("top",a).css("left",
d).css("width",h+"px").css("height",e+"px");H();b.unbindEvents(c,"gb-form-close,gb-form,gb-formtitle-inner-panel,ge-legend");b.bindEvent(f,c,".gb-form-close","FormClose","onClick");b.bindEvent(f,c,".gb-form","Form","onClick");b.bindEvent(f,c,".gb-form","Form","onDblClick");b.bindEvent(f,c,".gb-formtitle-inner-panel","FormTitle","onClick");b.bindEvent(f,c,".ge-legend","Legend","onClick");b.bindEvent(f,c,".ge-legend","Legend","onDblClick")};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=
function(){b.formToFront(c)};this.GroupLocality_onClick=function(a){a=b.element(a).attr("grouplocalityid");a=F(a);E(a)};this.Legend_onClick=function(a,b,c){c.stopPropagation()};this.Legend_onDblClick=function(a,b,c){c.stopPropagation()};this.ToggleLegend_onClick=function(){var a=b.element(c,".ge-legend");a.is(":visible")?a.hide():a.show()};this.ToggleAll_onClick=function(a){var c=b.element(a).prop("checked");processArray(h,function(a){a.visible=c});q(c)};this.ToggleGroup_onClick=function(a){a=b.element(a);
a=parseInt(a.attr("groupindex"),10);h[a].visible=!h[a].visible;q(!1)};this.TabEnd_onFocus=function(){b.element(c,".CloseButton").focus()};this.TabStart_onFocus=function(){b.element(c,".ge-periodend-field").focus()}};
