// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function widgetdock_wgtDock(p,q,b){function l(){h=a.hasCapability("widgets")&&"TRUE"===ENABLE_WIDGETS?new jDock(a,{map:r,tiles:f,mode:"horizontalmenu",alwayshidemorebutton:!0}):new jDock(a,{map:s,tiles:f,mode:"horizontalmenu",alwayshidemorebutton:!0});m=new jDock(a,{map:t,tiles:f,mode:"horizontalmenu",alwayshidemorebutton:!0});h.render(c,".ge-notification-panelleft");u||m.render(c,".ge-notification-panelright")}function v(e,c,d,b){e=a.ajaxRequestCreate("entity_customoperationexecute",[{name:"entitycode",
value:e},{name:"id",value:d},{name:"operationcode",value:c}]);a.ajaxCall(URL_WEBSERVICE,e,b,a.ajaxError)}var a=p,k=this,c=q,u=a.hasCapability("mobile"),n=a.toBoolean(a.getProperty("enablebranches")),g="";n&&(g=str_replace(a.getProperty("branchname")," ","&nbsp;"),0===g.length&&(g="Branches"));var h,m,r=[{location:"root",title:"Icons",layout:["icoConnection icoTransmission icoPrinter icoClock icoFullscreen icoZoom icoSizer".split(" ")]}],s=[{location:"root",title:"Icons",layout:[["icoConnection","icoTransmission",
"icoPrinter","icoFullscreen","icoZoom"]]}],t=[{location:"root",title:"Icons",layout:[["icoBranch"]]}],f=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"toolbarbutton"},{id:"icoClock",caption:"",classes:"gi-alarm",permissions:function(){return a.toBoolean(b.clock)&&a.isModuleLoaded("widgetclock")},action:a.showForm,actionData:"widgetclock.wgtClock",tip:"Click here to show the clock.",toptip:!0,type:"toolbarbutton"},{id:"icoConnection",caption:"",classes:"gb-indicator-connection gi-connectiongreen",
permissions:function(){return a.toBoolean(b.connection)},action:"tip",actionData:null,tip:"This indicator goes red when connection with the server goes down.",toptip:!0,type:"toolbarbutton"},{id:"icoFullscreen",caption:"",classes:"gi-fullscreen",permissions:function(){return a.toBoolean(b.fullscreen)},action:function(){!document.FullscreenElement&&!document.mozFullscreenElement&&!document.webkitFullscreenElement&&!document.msFullscreenElement?document.documentElement.requestFullscreen?document.documentElement.requestFullscreen():
document.documentElement.msRequestFullscreen?document.documentElement.msRequestFullscreen():document.documentElement.mozRequestFullscreen?document.documentElement.mozRequestFullscreen():document.documentElement.webkitRequestFullscreen&&document.documentElement.webkitRequestFullscreen(element.ALLOW_KEYBOARD_INPUT):document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullscreen?document.mozCancelFullscreen():document.webkitExitFullscreen&&
document.webkitExitFullscreen()},actionData:null,tip:"Click here to switch between full screen mode and normal window mode.",toptip:!0,type:"toolbarbutton"},{id:"icoPrinter",caption:"",classes:"gi-printer",permissions:function(){return a.toBoolean(b.printer)&&hasPermission(["VW_PRINTJOB"])},action:function(c){a.showForm("entity.frmLister",c)},actionData:{type:"form",entity:"systemform",formentity:"PRINTJOB",formentitydescription:"Print Job",formcode:"PRINTJOB",mode:"renderer",title:"Print Jobs"},
tip:"Click here to view print jobs.",toptip:!0,type:"toolbarbutton"},{id:"icoSizer",caption:"",classes:"gi-desktopsizer",permissions:function(){return a.toBoolean(b.sizer)&&a.isMDI()&&a.isModuleLoaded("widgetdesktopsizer")},action:a.showForm,actionData:"widgetdesktopsizer.wgtDesktopSizer",tip:"Click here to define a desktop area.",toptip:!0,type:"toolbarbutton"},{id:"icoTransmission",caption:"",classes:"gb-indicator-transmission gi-xmitgrey",permissions:function(){return a.toBoolean(b.transmission)},
action:"tip",actionData:null,tip:"This indicator blinks green when communicating with the server.",toptip:!0,type:"toolbarbutton"},{id:"icoZoom",caption:"",classes:"gi-showdesktop",permissions:function(){return a.toBoolean(b.zoom)&&a.hasCapability("zoom")&&a.isMDI()},action:a.zoomInOut,actionData:null,tip:"Click here to zoom.",toptip:!0,type:"toolbarbutton"},{id:"icoBranch",caption:g,classes:"gi-text",captionclasses:"gs-buttontextbold ge-branchcaption",permissions:function(){return n&&hasPermission(["MYBRANCHSELECT"])},
action:function(e){a.showFormPopup("entity.frmEntityChooser",e,function(b){if(0<b.length){var d=b[0].id;v(e.entity,e.operation,d,function(b){a.setProperty("branchid",d);a.setProperty("branchname",b.branchname);b=str_replace(a.getProperty("branchname")," ","&nbsp;");a.element(c,".ge-branchcaption").html(b)})}},!1,!0)},actionData:{type:"form",entity:"systemform",formentity:"BRANCH",mode:"select",title:"Branch Selection",operation:"mybranchselect"},tip:function(){return g},toptip:!0,reversetip:!0,type:"menuitem"}];
this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!1};this.Form_onBroadcast=function(b,f,d){"core"===b&&"loginFormSuccess"===f&&l();if("branchchange"===b){var h=d.branchname;a.setProperty("branchid",d.branchid);a.setProperty("branchname",h);g=d=str_replace(a.getProperty("branchname")," ","&nbsp;");a.element(c,".ge-branchcaption").html(d)}"viewport"===b&&"change"===f&&a.registerAndUpdateFooter(k,c)};this.Form_onClick=function(){a.formToFront(c)};this.Form_onLoad=
function(){a.registerAndUpdateFooter(k,c);a.registerMicrophoneStatus(k,c);a.unbindEvents(c,"gb-form");a.bindEvent(k,c,".gb-form","Form","onClick");l();a.registerServerEvent("branchchange",c);a.enableServerEventQueue("branchchange");a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerbroadcaster",[{name:"eventqueue",value:"branchchange"}]),doNothing,doNothing);a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerlistener",[{name:"eventqueue",value:"branchchange"}]),doNothing,doNothing)};
this.Form_onPermissionCheck=function(){return!0}};
