<?php

// database connection settings
define('DBSYSTEM_REQUIREDSCHEMAVERSION', '%DBSYSTEM_REQUIREDSCHEMAVERSION%');
define('DBSYSTEM_ISOLATIONLEVEL', 'READ UNCOMMITTED');

define('DBSYSTEM_CREATEDROP', '%DBSYSTEM_CREATEDROP%');						// TRUE for wamp, FALSE for ventra
define('DBSYSTEM_FILESIZE', '%DBSYSTEM_FILESIZE%');							// TRUE for wamp, FALSE for ventra
define('DBSYSTEM_LOADDATA', '%DBSYSTEM_LOADDATA%');							// TRUE for wamp, FALSE for ventra
define('DBSYSTEM_LOCALINFILE', '%DBSYSTEM_LOCALINFILE%');						// TRUE for ventra, FALSE for wamp
define('DBSYSTEM_SIMULATEDLOCALOUTFILE', '%DBSYSTEM_SIMULATEDLOCALOUTFILE%');	// TRUE for ventra, TRUE or FALSE for wamp
define('DBSYSTEM_ENGLISHNAME', '%DBSYSTEM_ENGLISHNAME%');

define('DBSYSTEMMAIN_HOSTNAME', '%DBSYSTEMMAIN_HOSTNAME%');
define('DBSYSTEMMAIN_LOGIN', '%DBSYSTEMMAIN_LOGIN%');
define('DBSYSTEMMAIN_PASSWORD', '%DBSYSTEMMAIN_PASSWORD%');
define('DBSYSTEMMAIN_DATABASENAME', '%DBSYSTEMMAIN_DATABASENAME%');

define('DBSYSTEMHISTORY_HOSTNAME', '%DBSYSTEMHISTORY_HOSTNAME%');
define('DBSYSTEMHISTORY_LOGIN', '%DBSYSTEMHISTORY_LOGIN%');
define('DBSYSTEMHISTORY_PASSWORD', '%DBSYSTEMHISTORY_PASSWORD%');
define('DBSYSTEMHISTORY_DATABASENAME', '%DBSYSTEMHISTORY_DATABASENAME%');

define('DBSYSTEMTEMP_HOSTNAME', '%DBSYSTEMTEMP_HOSTNAME%');
define('DBSYSTEMTEMP_LOGIN', '%DBSYSTEMTEMP_LOGIN%');
define('DBSYSTEMTEMP_PASSWORD', '%DBSYSTEMTEMP_PASSWORD%');
define('DBSYSTEMTEMP_DATABASENAME', '%DBSYSTEMTEMP_DATABASENAME%');

?>