<?php

// database connection settings
define('DBCLIENT_REQUIREDSCHEMAVERSION', '%DBCLIENT_REQUIREDSCHEMAVERSION%');
define('DBCLIENT_ISOLATIONLEVEL', 'READ UNCOMMITTED');

define('DBCLIENT_CREATEDROP', '%DBCLIENT_CREATEDROP%');						// TRUE for wamp, FALSE for ventra
define('DBCLIENT_FILESIZE', '%DBCLIENT_FILESIZE%');							// TRUE for wamp, FALSE for ventra
define('DBCLIENT_LOADDATA', '%DBCLIENT_LOADDATA%');							// TRUE for wamp, FALSE for ventra
define('DBCLIENT_LOCALINFILE', '%DBCLIENT_LOCALINFILE%');						// TRUE for ventra, FALSE for wamp
define('DBCLIENT_SIMULATEDLOCALOUTFILE', '%DBCLIENT_SIMULATEDLOCALOUTFILE%');	// TRUE for ventra, TRUE or FALSE for wamp
define('DBCLIENT_ENGLISHNAME', '%DBCLIENT_ENGLISHNAME%');

define('DBCLIENTMAIN_HOSTNAME', '%DBCLIENTMAIN_HOSTNAME%');
define('DBCLIENTMAIN_LOGIN', '%DBCLIENTMAIN_LOGIN%');
define('DBCLIENTMAIN_PASSWORD', '%DBCLIENTMAIN_PASSWORD%');
define('DBCLIENTMAIN_DATABASENAME', '%DBCLIENTMAIN_DATABASENAME%');

define('DBCLIENTHISTORY_HOSTNAME', '%DBCLIENTHISTORY_HOSTNAME%');
define('DBCLIENTHISTORY_LOGIN', '%DBCLIENTHISTORY_LOGIN%');
define('DBCLIENTHISTORY_PASSWORD', '%DBCLIENTHISTORY_PASSWORD%');
define('DBCLIENTHISTORY_DATABASENAME', '%DBCLIENTHISTORY_DATABASENAME%');

define('DBCLIENTTEMP_HOSTNAME', '%DBCLIENTTEMP_HOSTNAME%');
define('DBCLIENTTEMP_LOGIN', '%DBCLIENTTEMP_LOGIN%');
define('DBCLIENTTEMP_PASSWORD', '%DBCLIENTTEMP_PASSWORD%');
define('DBCLIENTTEMP_DATABASENAME', '%DBCLIENTTEMP_DATABASENAME%');

?>