// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmChangePassword(B,C,D){function w(){h(!0)}function x(){var b="";l=!1;"account"===d.mode?b="Password - change "+m:"user"===d.mode?b="Password - change "+m:"edit"===d.mode?b="Password - change "+m:"editself"===d.mode?b="Password - change my password":"view"===d.mode&&(b="Password - view "+m,l=!0);!1===l?(a.element(c,".ge-password-field").prop("disabled",!1),a.element(c,".ge-confirmpassword-field").prop("disabled",!1),a.limitInput(c,".ge-password-field",20),a.limitInput(c,".ge-confirmpassword-field",
20)):(a.element(c,".ge-password-field").prop("disabled",!0),a.element(c,".ge-confirmpassword-field").prop("disabled",!0));a.element(c,".ge-form-title").text(b)}function p(){e={id:"",login:"",password:""}}function E(){var b=F();0<b.length?a.dialogAlertScroll(b,function(){}):(h(!1),e.id=k,e.login=a.element(c,".ge-login-field").val(),e.password=a.element(c,".ge-password-field").val(),"account"===d.mode?s():"user"===d.mode?s():"edit"===d.mode?s():"editself"===d.mode&&G())}function h(a){t=a;l?g.disableButtons("SaveButton",
"gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty"):t?(g.disableButtons("SaveButton","gs-darkblue-background-colour"),g.enableButtons("SaveButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty")):(g.disableButtons("SaveButton","gs-red-background-colour gs-glow-dirty"),g.enableButtons("SaveButton","gs-darkblue-background-colour gs-glow-focusborder"))}function F(){var b="";0===$.trim(a.element(c,".ge-login-field").val()).length&&(b+="<li>User Name is required.</li>");
0===$.trim(a.element(c,".ge-password-field").val()).length&&(b+="<li>Password is required.</li>");0===$.trim(a.element(c,".ge-confirmpassword-field").val()).length&&(b+="<li>Password confirmation is required.</li>");$.trim(a.element(c,".ge-confirmpassword-field").val())!=$.trim(a.element(c,".ge-password-field").val())&&(b+="<li>Passwords do not match.</li>");0<b.length&&(b="<ul>"+b+"</ul>");return b}function y(){H();m=e.login;x();"editself"===d.mode?a.element(c,".ge-login-field").val(a.getProperty("login")):
a.element(c,".ge-login-field").val(e.login);a.element(c,".ge-password-field").val(e.password);a.element(c,".ge-confirmpassword-field").val("");z();a.element(c,".ge-password-field").focus();h(!1)}function I(){0===q&&a.ajaxError();q++}function J(a){e=a[0];r++;u==r&&y()}function A(b){h(!1);a.closeForm(c)}function G(){var b="security_userpasswordupdate";"account"===d.mode&&(b="security_userpasswordupdatebyaccount");b=a.ajaxRequestCreate(b,[{name:"id",value:""},{name:"login",value:e.login},{name:"password",
value:e.password},{name:"editself",value:!0}]);a.ajaxCall(URL_WEBSERVICE,b,A,a.ajaxError,w)}function s(){var b="security_userpasswordupdate";"account"===d.mode&&(b="security_userpasswordupdatebyaccount");b=a.ajaxRequestCreate(b,[{name:"id",value:k},{name:"login",value:e.login},{name:"password",value:e.password},{name:"editself",value:!1}]);a.ajaxCall(URL_WEBSERVICE,b,A,a.ajaxError,w)}function n(b){b?(u=1,q=r=0,b="security_userfetch","account"===d.mode&&(b="security_userfetchbyaccount"),b=a.ajaxRequestCreate(b,
[{name:"id",value:k}]),a.ajaxCall(URL_WEBSERVICE,b,J,I)):(u=1,q=r=0,y())}function H(){a.unbindEvents(c,v);a.onDirty(c,v,function(){h(!0)})}function K(){var b="",d=a.element(c,".ge-password-field").val(),e=a.element(c,".ge-confirmpassword-field").val();d!=e&&(b="Please ensure passwords match");return b}function z(){a.unbindEvents(c,"ge-tab-start,ge-tab-end");a.bindEvent(f,c,".ge-tab-start","TabStart","onFocus");a.bindEvent(f,c,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(c,"ge-tab-start,CloseButton,SaveButton,"+
v+",ge-tab-end")}var a=B,f=this,c=C,d=D,l=!1,t=!1,u=0,r=0,q=0,v="ge-password-field,ge-confirmpassword-field",k="",m="",e=null,g,L=[{location:"root",title:"Home",layout:[["CloseButton","SaveButton"]]}],M=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){f.FormClose_onClick()},actionData:null,tip:"Click here to close the password.",type:"toolbarbutton"},
{id:"SaveButton",caption:"Save",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:["CHPWD_USER"],action:function(){f.SaveButton_onClick()},actionData:null,tip:"Click here to save the password.",type:"toolbarbutton"}];this.Form_isDirty=function(){return t};this.Form_onClick=function(){a.setFormFocus(f,c)};this.Form_onDblClick=function(){a.formToFront(c)};this.Form_onFocus=function(){z()};this.Form_onResize=function(b,d){var e=a.getFormCanvasHeight(c)-80;a.element(c,".ge-content-panel").height(e+
"px");a.element(c,".ge-thecontent").height("100%")};this.Form_onLoad=function(){l=!1;k=d.id;void 0===k&&(k="");x();g=new jDock(a,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:L,tiles:M});g.render(c,".ge-button-panel");a.unbindEvents(c,"gb-form-close,gb-form,gb-formtitle-inner-panel");a.bindEvent(f,c,".gb-form-close","FormClose","onClick");a.bindEvent(f,c,".gb-form","Form","onClick");a.bindEvent(f,c,".gb-form","Form","onDblClick");a.bindEvent(f,c,".gb-formtitle-inner-panel","FormTitle","onClick");
"account"===d.mode?(p(),n(!0)):"user"===d.mode?(p(),n(!0)):"edit"===d.mode?(p(),n(!0)):"editself"===d.mode?(p(),n(!1)):"view"===d.mode&&n(!0)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){a.formToFront(c)};this.FormClose_onClick=function(){a.closeForm(c)};this.SaveButton_onClick=function(){var b=K();if(0===b.length){if(f.Form_isDirty())try{E()}catch(c){h(!0)}}else a.dialogAlert(b,function(){})};this.TabEnd_onFocus=function(){a.element(c,".CloseButton").focus()};
this.TabStart_onFocus=function(){a.element(c,".ge-confirmpassword-field").focus()}};
