// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmGallery(E,F,G){function H(a){var b=!1;processArray(p,function(c){if(c.url==a.url)return b=!0});b||p.push(a);return!b}function t(a){I&&(a='<font size="4">TOTALFETCHED: '+f+", LASTFIT: "+k+", RENDERED: "+p.length+", LASTFETCHED: "+a+", ENDOG: "+g+"</font>",b.element(c,".ge-form-title").html(a))}function x(){var a=b.element(c,".ge-content-panel").width()-30;return parseInt(a/q,10)}function y(){var a=b.element(c,".ge-content-panel").height()-z;return parseInt(a/A,10)+1}function B(){var a=
x(),b=y();return a*b}function J(){var a=B()-f;0>a&&(a=0);return a}function K(){var a=x();y();a+=a-f%a;0>a&&(a=0);return a}function u(){p=[];r="";g=!1;l=0;h=[];f=k=0;b.element(c,".ge-renderer-content").html("")}function C(a){var e="";processArray(a,function(a){if(H(a)){f++;var b=a.url,b=0<b.length?a.url:APP_DOMAIN_PATH+"fetch.php?token="+encodeURIComponent(SECURITY_TOKEN)+"&image="+encodeURIComponent(a.id),b='<img class="ge-lazy-image" imageid="'+htmlEncode(a.id)+'" src="'+b+'" data-original="'+b+
'" data-description="'+htmlEncode(a.tags)+'" width="'+D+'" height="'+v+'">',c='<div class="gs-imagepicker gb-button" style="display:inline-block; margin:5px; width:'+(q-14)+"px; height:"+(A-14)+'px;">',c=c+('<div style="float:left; width:'+(q-14)+'px; height:10px;">&nbsp;</div>'),c=c+('<div style="float:left; width:'+L+"px; height:"+(v+10)+'px;">&nbsp;</div>'),c=c+('<div style="float:left; width:'+D+"px; height:"+v+'px; ">'+b+"</div>"),c=c+('<div style="float:left; text-align:center; width:'+(q-14)+
'px; font-size:8px; overflow:ellipsis;">'+htmlEncode(a.tags)+"</div>");e+=c+"</div>";r=a.id}});0<e.length&&(b.element(c,".ge-renderer-content").append(e),b.unbindEvents(c,"ge-lazy-image,gb-imagepicker-zoom"),b.bindEvent(d,c,".ge-lazy-image","LazyImage","onClick"),b.bindEvent(d,c,".gb-imagepicker-zoom","ZoomImage","onClick"),t(a.length))}function m(){var a=B();if(a!==k||0===k||a>f)k=a,a>f&&M()}function M(){function a(a){l--;0===a.length&&(g=!0,t(0));C(a);0>=l&&!g&&m()}var c=J();l++;0===c||g?a([]):
(c=b.ajaxRequestCreate("docs_imagethumbsfetchnext",[{name:"imagetype",value:w.mode},{name:"fetchcount",value:c},{name:"filter",value:n},{name:"lastfetched",value:r}]),b.ajaxCall(URL_WEBSERVICE,c,a,b.ajaxError,doNothing,!0))}function N(){function a(a){0===a.length&&(g=!0,t(0));C(a)}if(g)a([]);else if(0===l){var c=K(),c=b.ajaxRequestCreate("docs_imagethumbsfetchnext",[{name:"imagetype",value:w.mode},{name:"fetchcount",value:c},{name:"filter",value:n},{name:"lastfetched",value:r}]);b.ajaxCall(URL_WEBSERVICE,
c,a,b.ajaxError,doNothing,!0)}}var b=E,d=this,c=F,w=G,I=!1,p=[],r="",g=!1,l=0,h=[],k=0,f=0,q=195,A=180,L=30,D=120,v=120,n="",z=50,s,O=[{location:"root",title:"Home",layout:[["CloseButton","SelectButton"]]}],P=[{id:"-",caption:"",classes:"",permissions:[],action:"",tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"btn-success",permissions:[],action:function(){d.FormClose_onClick()},tip:"Click here to close the form",type:"toolbarbutton"},{id:"SelectButton",caption:"Select",classes:"btn-disabled",
permissions:[],action:function(){b.closeForm(c)},tip:"Click here to select an image",type:"toolbarbutton"}];this.Form_allowMultipleInstances=function(){return!0};this.Form_onBroadcast=function(a,e,d){"hash"===a&&"change"===e&&b.closeForm(c)};this.Form_canClose=function(){return!0};this.Form_onClick=function(){b.setFormFocus(d,c)};this.Form_onFocus=function(){doNothing()};this.Form_onDblClick=function(){b.formToFront(c)};this.Form_onLoad=function(){var a=b.getViewPort().width,e=b.getViewPort().height;
b.resizeAndRepositionForm(c,0.1*e,0.1*a,0.8*e,0.8*a);s=new jDock(b,{alwaysvisiblebuttoncount:2,map:O,tiles:P});s.render(c,".ge-button-panel");b.unbindEvents(c,"gb-form-close,gb-form,gb-formtitle-inner-panel,ge-content-panel");b.bindEvent(d,c,".gb-form-close","FormClose","onClick");b.bindEvent(d,c,".gb-form","Form","onClick");b.bindEvent(d,c,".gb-form","Form","onDblClick");b.bindEvent(d,c,".gb-formtitle-inner-panel","FormTitle","onClick");b.bindEvent(d,c,".ge-content-panel","ContentPanel","onScroll");
b.unbindEvents(c,"ge-search-input,ge-search-button,ge-searchclear-button");b.bindEvent(d,c,".ge-search-button","btnSearch","onClick");b.bindEvent(d,c,".ge-searchclear-button","btnSearchClear","onClick");b.bindEvent(d,c,".ge-search-input","SearchField","onEnterKey");!1===b.hasCapability("regionscroll")&&b.element(c,".ge-renderer-content").attr("style","width:100%;");b.element(c,".ge-form-title").html(w.caption)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(c)};
this.FormResult=function(){return h};this.Form_onResize=function(a,e){var d=b.getFormCanvasHeight(c)-20-z;b.element(c,".ge-content-panel").height(d+"px");b.element(c,".ge-thecontent").height("100%");b.after(100,m)};this.ContentPanel_onScroll=function(a,b,c){a=c.target;a.scrollHeight-a.scrollTop===a.clientHeight&&N()};this.FormClose_onClick=function(){h=[];b.closeForm(c)};this.ImageSelected_onClick=function(a){a={id:b.element(a).attr("imageid")};h.push(a);b.closeForm(c)};this.LazyImage_onClick=function(a,
e,d,f,g){h=[{id:$(a).attr("imageid")}];b.element(c,".gs-imagepicker").removeClass("selected");$(a).parents(".gs-imagepicker").addClass("selected");0<h.length?s.enableButtons("SelectButton","btn-primary"):s.disableButtons("SelectButton","btn-primary")};this.btnSearch_onClick=function(){n=b.element(c,".ge-search-input").val();u();b.after(100,m)};this.btnSearchClear_onClick=function(){n="";u();b.after(100,m);b.element(c,".ge-search-input").val("");b.element(c,".ge-search-input").focus()};this.SearchField_onEnterKey=
function(a){n=b.element(a).val();u();b.after(100,m)};this.ZoomImage_onClick=function(a){var c=$(a).parents(".gs-imagepicker").find("img");a=c.data("description");c=c.attr("imageid");b.showFormPopup("core.frmImageViewer",{imageid:c,title:a})}};
