// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmHealth(e,g,q){function m(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(c,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(c,b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,ge-close-button,ge-tab-end")}var a=e,c=this,b=g;a.toBoolean(a.getProperty("batch"));a.toBoolean(a.getProperty("default"));a.toBoolean(a.getProperty("isemployer"));a.toBoolean(a.getProperty("isindividual"));a.toBoolean(a.getProperty("owner"));a.toBoolean(a.getProperty("public"));
a.toBoolean(a.getProperty("developer"));a.toBoolean(a.getProperty("sysadmin"));a.hasCapability("mobile");a.isModuleLoaded("widgetprintertray");a.after(1E3,function(){$("#tubular-container").remove()});var h="TRUE"==TESTSCROLL&&!a.hasCapability("regionscroll")&&a.hasCapability("mobile");h&&(a.element(b,".ge-content-panel").removeClass("gb-scrollable-panel"),a.element(b,".ge-thecontent").removeClass("gb-scrollable-content"),a.element(b,".gb-form").removeClass("gb-resizable"),a.element(b).css({position:"relative",
height:"auto"}));this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!0};this.Form_onBroadcast=function(a,b){("orientation"===a||"viewport"===a)&&"change"===b&&c.Form_onResize()};this.Form_onClick=function(){a.setFormFocus(c,b)};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onFocus=function(){m();c.Form_onResize()};this.Form_onLoad=function(){a.unbindEvents(b,"gb-form");a.unbindEvents(b,"gb-form-close");a.bindEvent(c,b,".gb-form","Form","onClick");
a.bindEvent(c,b,".gb-form-close","FormClose","onClick");a.bindEvent(c,b,".gb-form","Form","onDblClick");var n="Build: "+APP_SHORT_NAME+" "+APP_VERSION+".",d="OS: "+a.getOS()+". Browser: "+a.getBrowser().name+" version "+a.getBrowserVersion()+" ("+a.getBrowser().major+").",d=d+(" Screen size: "+screen.width+"x"+screen.height+".");a.hasCapability("viewport")&&(d+=" Viewport size: "+a.getViewPort().width+"x"+a.getViewPort().height+".");var d=d+(" Support for your browser is "+a.getBrowser().support+
". "+a.getBrowserRecommendation()),p=a.getHealth(),e=a.getBrowser().incapabilities,g="Agent: "+a.getAgent(),f=a.getMapProvider();0===f.length&&(f="none");var k=a.getPrinterProvider();0===k.length&&(k="none");var l=a.getSpeechProvider();0===l.length&&(l="none");f="Map Provider: "+f+", Printer Provider: "+k+", Speech Provider: "+l;a.element(b,".ge-health-content").html('<font color="black">&nbsp;'+htmlEncode(n)+"<br><br>&nbsp;"+htmlEncode(d)+"<br>&nbsp;"+htmlEncode(g)+"<br>&nbsp;"+htmlEncode(f)+"<br><br>&nbsp;"+
e+"<br>&nbsp;"+p+"</font>");h?a.element(b,".gb-form").addClass("gs-content-autoheight"):a.resizeDockedForm(b);m()};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(c,d){var e=a.getFormCanvasHeight(b)-20;h?doNothing():(a.element(b,".ge-content-panel").height(e+"px"),a.element(b,".ge-thecontent").height("100%"))};this.FormClose_onClick=function(){a.closeForm(b)};this.TabEnd_onFocus=function(){};this.TabStart_onFocus=function(){}};
