// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmLogin(v,w,x){function r(b){a.hasCapability("themes")?(b=a.ajaxRequestCreate("security_userinfo",[]),a.ajaxCall(URL_WEBSERVICE,b,y,a.ajaxError,doNothing,!0)):l()}function m(b){a.setUnloadPrompt(!1);a.hasCapability("timers")&&a.deleteTimersAll();f()}function n(b,c){var e="loggedin=true";setDesktopRegions(b.desktopregions);setPermissions(b.permissions);setProducts(b.products);a.setProperty("clientdb",b.clientdb);a.setProperty("loginas",b.loginas);a.setProperty("client",b.clientid);a.setProperty("clientname",
b.clientname);a.setProperty("businessname",b.businessname);a.setProperty("login",b.login);a.setProperty("username",b.username);a.setProperty("sysadmin",b.sysadmin);a.setProperty("developer",b.developer);a.setProperty("public",b.ispublic);a.setProperty("batch",b.isbatch);a.setProperty("default",b.idefault);a.setProperty("owner",b.isowner);a.setProperty("licensed",b.licensed);a.setProperty("expirydate",b.expirydate);a.setProperty("expirydays",b.expirydays);a.setProperty("selectedtheme",SELECTED_THEME);
a.setProperty("defaultcountry",b.defaultcountry);a.setProperty("devicename",b.devicename);a.setProperty("theme",b.theme);a.setProperty("isemployer",b.isemployer);a.setProperty("isindividual",b.isindividual);var d=a.toBoolean(b.displaytooltips);a.enableTips(d);c?(d=a.getProperty("theme"),a.hasCapability("themes")||(d=DEFAULT_THEME),0<d.length&&(e+="&theme="+encodeURIComponent(d))):doNothing();a.reboot(e,"frmLogin")}function A(a){n(a,!1)}function y(a){n(a,!0)}function l(){var b=a.ajaxRequestCreate("security_userinfo",
[]);a.ajaxCall(URL_WEBSERVICE,b,A,a.ajaxError,doNothing,!0)}function f(){var b=p(!1);a.element(c,".ge-accountcode-field").val();0<b.length?a.dialogAlertScroll(b,function(){}):B()}function B(){var b=a.element(c,".ge-accountcode-field").val(),z=a.element(c,".ge-login-field").val(),e=a.element(c,".ge-password-field").val(),d="N";a.element(c,".ge-stayloggedin-field").is(":checked")&&(d="Y");var q=a.getAgent(),h=a.getBrowserCapabilities(),b=a.ajaxRequestCreate("public_login",[{name:"clientcode",value:b},
{name:"login",value:z},{name:"password",value:e},{name:"stayloggedin",value:d},{name:"useragent",value:q},{name:"capabilities",value:h}]);a.ajaxCall(URL_WEBSERVICE,b,r,C,doNothing,!0)}function C(b,c){var d=DEFAULT_ENTITY,g=DEFAULT_LOGIN,q=DEFAULT_PASSWORD,h=a.getAgent(),f=a.getBrowserCapabilities();a.ajaxError(b,c);d=a.ajaxRequestCreate("public_login",[{name:"clientcode",value:d},{name:"login",value:g},{name:"password",value:q},{name:"stayloggedin",value:"N"},{name:"useragent",value:h},{name:"capabilities",
value:f}]);a.ajaxCall(URL_WEBSERVICE,d,l,a.ajaxError,doNothing,!0)}function k(b){b?a.dialogConfirm("Are you sure you wish to logout and login as another user?<br><br>Please be sure you have saved your data before continuing.",function(){var b=a.ajaxRequestCreate("public_logout",[]);a.ajaxCall(URL_WEBSERVICE,b,m,a.ajaxError)}):(b=a.ajaxRequestCreate("public_logout",[]),a.ajaxCall(URL_WEBSERVICE,b,m,a.ajaxError))}function D(){var b=p(!0);if(0<b.length)a.dialogAlertScroll(b,function(){});else{var b=
a.element(c,".ge-accountcode-field").val(),d=a.element(c,".ge-login-field").val(),b=a.ajaxRequestCreate("public_passwordreset",[{name:"clientcode",value:b},{name:"login",value:d}]);a.ajaxCall(URL_WEBSERVICE,b,doNothing,a.ajaxError,doNothing,!0)}}function p(b){var d="";0===$.trim(a.element(c,".ge-accountcode-field").val()).length&&(d="<li>Account Code is required.</li>");0===$.trim(a.element(c,".ge-login-field").val()).length&&(d+="<li>Email Address / Login is required.</li>");b||0===$.trim(a.element(c,
".ge-password-field").val()).length&&(d+="<li>Password is required.</li>");0<d.length&&(d="<ul>"+d+"</ul>");return d}function s(b){var d="",e=".ge-2factorcode-register-field";b||(e=".ge-2factorcode-verify-field");0===$.trim(a.element(c,e).val()).length&&(d="<li>6 Digit code is required.</li>");0<d.length&&(d="<ul>"+d+"</ul>");return d}function t(b){try{var d=a.element(c,".ge-accountcode-field").val(),e=a.element(c,".ge-login-field").val(),g=a.element(c,".ge-password-field").val(),f="N",h=".ge-2factorcode-register-field";
b||(h=".ge-2factorcode-verify-field");var k=a.element(c,h).val();a.element(c,".ge-stayloggedin-field").is(":checked")&&(f="Y");var l=a.getAgent(),m=a.getBrowserCapabilities(),n=a.ajaxRequestCreate("public_login",[{name:"clientcode",value:d},{name:"login",value:e},{name:"password",value:g},{name:"stayloggedin",value:f},{name:"useragent",value:l},{name:"capabilities",value:m},{name:"twofactorcode",value:k}]);a.ajaxCall(URL_WEBSERVICE,n,r,function(b){a.dialogConfirm("Code Entered is no longer valid, Please enter a new one",
doNothing)},doNothing,!0)}catch(p){alert(p)}}function u(){a.unbindEvents(c,"ge-tab-start,ge-tab-end");a.bindEvent(d,c,".ge-tab-start","TabStart","onFocus");a.bindEvent(d,c,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(c,"ge-tab-start,ge-accountcode-field,ge-login-field,ge-password-field,ge-login-button,ge-tab-end")}var a=v,d=this,c=w,g=x.logoutFirst;void 0==g&&(g=!1);this.Form_allowMultipleInstances=function(){return!0};this.Form_canClose=function(){return!1};this.Form_onBroadcast=function(a,c){("orientation"===
a||"viewport"===a)&&"change"===c&&d.Form_onResize()};this.Form_onClick=function(){a.setFormFocus(d,c)};this.FormClose_onClick=function(){a.closeForm(c)};this.Form_onFocus=function(){u();a.closeExclusive(c)};this.Form_onFocusLost=function(){};this.Form_onLoad=function(){a.hasCapability("mobile")?a.element(c,".ge-nonmobile").remove():a.element(c,".ge-nonmobile").removeClass("gb-hidden");a.element(c,".ge-form").show();a.element(c,".ge-form-title").html("Account Login");"TRUE"===ALLOW_STAY_LOGGEDIN?a.element(c,
".ge-stayloggedin-panel").show():a.element(c,".ge-stayloggedin-panel").hide();"TRUE"===ENABLE_REGISTER&&"TRUE"===CLIENT_ALLOWJOIN?a.element(c,".ge-register-link").show():a.element(c,".ge-register-link").hide();a.unbindEvents(c,"gb-form-close,ge-login-button,gb-form,ge-password-field");a.bindEvent(d,c,".gb-form-close","FormClose","onClick");a.bindEvent(d,c,".ge-login-button","LoginButton","onClick");a.bindEvent(d,c,".ge-login-button","LoginButton","onEnterKey");a.bindEvent(d,c,".gb-form","Form","onClick");
a.bindEvent(d,c,".ge-password-field","PasswordField","onEnterKey");a.bindEvent(d,c,".ge-resetpassword-button","ResetPasswordButton","onClick");a.bindEvent(d,c,".ge-resetpassword-button","ResetPasswordButton","onClick");a.bindEvent(d,c,".ge-verify-button","VerifyButton","onClick");a.bindEvent(d,c,".ge-twofactor-verify-button","VerifyOneTimeCodeButton","onClick");a.limitInput(c,".ge-accountcode-field",40,!0);a.limitInput(c,".ge-login-field",100,!0);a.limitInput(c,".ge-password-field",20,!0);u();a.element(c,
".ge-accountcode-field").focus();a.formToFront(c)};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(b,d){var e=a.getCanvasHeight();a.hasCapability("mobile")?a.element(c,".ge-top-formgap").remove():e-=60;550<=e&&(e=550);a.element(c,".ge-panel-content").height(e+"px");a.element(c,".ge-panel-content").css("overflow-x","hidden");a.element(c,".ge-panel-content").css("overflow-y","auto")};this.LoginButton_onClick=function(){g?k(!1):f()};this.LoginButton_onEnterKey=function(){g?
k(!1):f()};this.PasswordField_onEnterKey=function(){g?k(!1):f()};this.ResetPasswordButton_onClick=function(){D()};this.VerifyButton_onClick=function(){var b=s(!0);0<b.length?a.dialogAlertScroll(b,function(){}):t(!0)};this.VerifyOneTimeCodeButton_onClick=function(){var b=s(!1);0<b.length?a.dialogAlertScroll(b,function(){}):t(!1)};this.TabEnd_onFocus=function(){a.element(c,".ge-accountcode-field").focus()};this.TabStart_onFocus=function(){a.element(c,".ge-login-button").focus()}};
