// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmLicensing(q,r,s){function t(){f(!0)}function m(){var c="";g=!1;"edit"===h.mode?c="Licensing - edit licensing":"view"===h.mode&&(c="Licensing - view licensing",g=!0);!1===g?a.element(b,".ge-licencekey-panel").show():a.element(b,".ge-licencekey-panel").hide();a.element(b,".ge-form-title").text(c)}function u(){var b=v();0<b.length?a.dialogAlertScroll(b,function(){}):(f(!1),w())}function w(){var c=a.element(b,".ge-licencekey-field").val();"edit"===h.mode&&(c=a.ajaxRequestCreate("security_updatelicence",
[{name:"licencekey",value:c}]),a.ajaxCall(URL_WEBSERVICE,c,x,a.ajaxError,t))}function f(a){k=a;g?e.disableButtons("SaveButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty"):k?(e.disableButtons("SaveButton","gs-darkblue-background-colour"),e.enableButtons("SaveButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty")):(e.disableButtons("SaveButton","gs-red-background-colour gs-glow-dirty"),e.enableButtons("SaveButton","gs-darkblue-background-colour gs-glow-focusborder"))}
function v(){var c="";0===$.trim(a.element(b,".ge-licencekey-field").val()).length&&(c+="<li>Licence Code is required.</li>");0<c.length&&(c="<ul>"+c+"</ul>");return c}function n(){var c=parseInt(a.getProperty("expirydays"),10);y();m();a.element(b,".ge-todaysdate-field").val(a.todayISO());a.element(b,".ge-expirydate-field").val(a.getProperty("expirydate"));0<c?a.element(b,".fldWarning").html("("+c+" days remaining)"):a.element(b,".fldWarning").html("");p();a.element(b,".ge-licencekey-field").focus();
f(!1)}function x(b){a.setProperty("licensed",b.licensed);a.setProperty("expirydate",b.expirydate);a.setProperty("expirydays",b.expirydays);f(!1);a.dialogAlert("Licensing updated, please login again for it to take effect.",function(){});n()}function y(){a.unbindEvents(b,l);a.onDirty(b,l,function(){f(!0)})}function p(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(d,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(d,b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,CloseButton,SaveButton,"+
l+",ge-tab-end")}var a=q,d=this,b=r,h=s,g=!1,k=!1,l="ge-licencekey-field",e,z=[{location:"root",title:"Home",layout:[["CloseButton","SaveButton"]]}],A=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){d.FormClose_onClick()},actionData:null,tip:"Click here to close the licensing form.",type:"toolbarbutton"},{id:"SaveButton",caption:"Save",
classes:"gb-cell-disabled-xxx",permissions:["EDT_LICENSING"],action:function(){d.SaveButton_onClick()},actionData:null,tip:"Click here to update your licensing.",type:"toolbarbutton"}];this.Form_isDirty=function(){return k};this.Form_onClick=function(){a.setFormFocus(d,b)};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onFocus=function(){p()};this.Form_onLoad=function(){g=!1;m();e=new jDock(a,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:z,tiles:A});e.render(b,".ge-button-panel");
a.unbindEvents(b,"gb-form-close,gb-form,gb-formtitle-inner-panel");a.bindEvent(d,b,".gb-form-close","FormClose","onClick");a.bindEvent(d,b,".gb-form","Form","onClick");a.bindEvent(d,b,".gb-form","Form","onDblClick");a.bindEvent(d,b,".gb-formtitle-inner-panel","FormTitle","onClick");n()};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){a.formToFront(b)};this.FormClose_onClick=function(){a.closeForm(b)};this.SaveButton_onClick=function(){if(d.Form_isDirty())try{u()}catch(a){f(!0)}};
this.TabEnd_onFocus=function(){a.element(b,".CloseButton").focus()};this.TabStart_onFocus=function(){a.element(b,".ge-licencekey-field").focus()}};
