// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmLister(d,D,E){function q(f){var a=!1;processArray(B.actions,function(b){b.id==f&&(a=$.isFunction(b.permissions)?b.permissions():0===b.permissions.length?!0:hasPermission(b.permissions));return a});return a}function F(f){var b;processArray(B.actions,function(a){var c=!1;a.id==f&&(b=a,c=!0);return c});return b}function G(f){var b=null;processArray(H,function(a){a.id==f&&(b=a)});return b}function g(a){var c,r="";if(q(a)){var h=F(a),e=l.returns,d=p.getSelection(e),g=h.multiSelect;void 0===
g&&(g=!1);var k=h.requiresSelection;void 0===k&&(k=!0);var m=h.prompt;void 0===m&&(m=!1);m&&"DeleteButton"===a&&(r="Continue and delete the "+l.title+" selection?");k?0<d.length&&(g?(c=[],processArray(d,function(a){void 0===e?c.push(a.id):c.push(a)})):c=void 0===e?d[0].id:d[0],void 0!==c&&$.isFunction(h.action)&&(0<r.length?b.dialogConfirm(r,function(){h.action(c)}):h.action(c))):$.isFunction(h.action)&&(0<r.length?b.dialogConfirm(r,function(){h.action()}):h.action())}}function I(a){var b=null;processArray(J,
function(c){c.id==a&&(b=c)});return b}function C(){b.unbindEvents(c,"ge-tab-start,ge-tab-end");b.bindEvent(e,c,".ge-tab-start","TabStart","onFocus");b.bindEvent(e,c,".ge-tab-end","TabEnd","onFocus");b.setTabOrder(c,"ge-tab-start,CloseButton,ViewButton,EditButton,DeleteButton,ge-tab-end")}var b=d,e=this,c=D,a=E,m="",l,B,p,s=a.entity;void 0===s&&(s="");var t=a.entityid;void 0===t&&(t="");void 0!==a.fixedfilter&&0<a.fixedfilter.length&&JSON.parse(decodeURIComponent(a.fixedfilter));var u=a.formcode;void 0===
u&&(u="");var v=a.formentity;void 0===v&&(v="");var w=a.formentityid;void 0===w&&(w="");var x=a.mode;void 0===x&&(x="renderer");var y=a.searchkeyword;void 0===y&&(y="");var z=a.title;void 0===z&&(z="");var A=a.type;void 0===A&&(A="");d=a.relationship;void 0===d&&(d="");d=a.relationshipid;void 0===d&&(d="");d=a.relationshiptitle;void 0===d&&(d="");var k,K=[{location:"root",title:"Home",layout:[["CloseButton","ViewButton","EditButton","DeleteButton"]]}],L=[{id:"-",caption:"",classes:"",permissions:[],
action:"",tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"btn-success",permissions:[],action:function(){e.FormClose_onClick()},tip:"Click here to close the "+m+" list.",type:"toolbarbutton"},{id:"DeleteButton",caption:"Delete",classes:"gb-cell-disabled",permissions:function(){return q("DeleteButton")},action:g,actionData:"DeleteButton",tip:"Click here to delete.",type:"toolbarbutton"},{id:"EditButton",caption:"Edit",classes:"gb-cell-disabled",permissions:function(){return q("EditButton")},
action:g,actionData:"EditButton",tip:"Click here to edit.",type:"toolbarbutton"},{id:"ViewButton",caption:"View",classes:"gb-cell-disabled",permissions:function(){return q("ViewButton")},action:g,actionData:"ViewButton",tip:"Click here to view.",type:"toolbarbutton"}],J=[{id:LIST_DATAAUDITLOGS,title:"Data Audit Logs",ws:"core_dataauditlogslist",columns:[{id:"rownum",name:"#",field:"rownum",behavior:"select",cssClass:"gs-gridcell-selection",width:40,cannotTriggerInsert:!0,resizable:!1,selectable:!1},
{id:"client",name:"Client",field:"client",sortable:!0,editor:Slick.Editors.Text},{id:"user",name:"User",field:"user",sortable:!0,editor:Slick.Editors.Text},{id:"category",name:"Category",field:"category",sortable:!0,editor:Slick.Editors.Text},{id:"description",name:"Description",field:"description",sortable:!0,editor:Slick.Editors.Text},{id:"modifydatetime",name:"Date Modified",field:"modifydatetime",sortable:!0,editor:Slick.Editors.Text}]}],H=[{id:LIST_DATAAUDITLOGS,actions:[],broadcasts:[{messages:["deleted",
"edited"],action:"refresh"}]}];this.Form_allowMultipleInstances=function(){return b.isMDI()};this.Form_canClose=function(){return!0};this.Form_onBroadcast=function(a,b){var c;processArray(B.broadcasts,function(a){processArray(a.messages,function(f){var e=m+f;e.toLowerCase()==b.toLowerCase()?c=a.action:f.toLowerCase()==b.toLowerCase()&&(c=a.action);return void 0!==c});return void 0!==c});void 0!==c&&($.isFunction(c)?c():"refresh"===c&&p.refresh())};this.Form_onClick=function(){b.setFormFocus(e,c)};
this.Form_onDblClick=function(a,e,d){b.formToFront(c);d.stopPropagation();b.zoomFormInOut(c)};this.Form_onFocus=function(b){if(void 0!==b&&null!==b&&(a.entity!==b.entity||a.entityid!==b.entityid||a.fixedfilter!==b.fixedfilter||a.formcode!==b.formcode||a.formentity!==b.formentity||a.formentityid!==b.formentityid||a.mode!==b.mode||a.searchkeyword!==b.searchkeyword||a.title!==b.title||a.type!==b.type))a=b,s=a.entity,void 0===s&&(s=""),t=a.entityid,void 0===t&&(t=""),void 0!==a.fixedfilter&&0<a.fixedfilter.length&&
JSON.parse(decodeURIComponent(a.fixedfilter)),u=a.formcode,void 0===u&&(u=""),v=a.formentity,void 0===v&&(v=""),w=a.formentityid,void 0===w&&(w=""),x=a.mode,void 0===x&&(x="renderer"),y=a.searchkeyword,void 0===y&&(y=""),z=a.title,void 0===z&&(z=""),A=a.type,void 0===A&&(A=""),e.Form_onLoad();C()};this.Form_onFocusLost=function(){};this.Form_onLoad=function(){b.element(c,".ge-form-title").text("");b.unbindEvents(c,"gb-form-close,gb-form,gb-formtitle-inner-panel");b.bindEvent(e,c,".gb-form-close",
"FormClose","onClick");b.bindEvent(e,c,".gb-form","Form","onClick");b.bindEvent(e,c,".gb-form","Form","onDblClick");b.bindEvent(e,c,".gb-formtitle-inner-panel","FormTitle","onClick");b.unbindEvents(c,"ge-search-input,ge-search-button,ge-searchclear-button");b.bindEvent(e,c,".ge-search-button","btnSearch","onClick");b.bindEvent(e,c,".ge-searchclear-button","btnSearchClear","onClick");b.bindEvent(e,c,".ge-search-input","SearchField","onEnterKey");m=a.mode;l=I(m);B=G(m);var f=a.title;void 0===f&&(f=
"");var d=l.parent_id;void 0===d&&(d="");var g=a.parent_id,h=l.params,n=l.returns;void 0===n&&(n=["id"]);n={autoHeight:!1,cbOnSelection:e.Grid_onDblClick,cbOnSelectionChange:e.Grid_onSelectionChange,columns:l.columns,filterType:"all",parameters:[],extraParameters:[],returnFields:n,webServiceFunction:l.ws};void 0!==h&&(n.parameters=h);0<d.length&&(n.parameters=$.merge(n.parameters,[{name:d,value:g}]));b.element(c,".panelHome").hide();b.element(c,".ge-entity-grid").show();k=new jDock(b,{alwaysvisiblebuttoncount:2,
map:K,tiles:L});k.render(c,".ge-button-panel");k.disableButtons("ViewButton,EditButton,DeleteButton","disabled");p=new jDatatableRenderer(b,n);p.render(c,".ge-entity-grid");0===f.length&&(f=l.title);b.element(c,".ge-form-title").text(f);f=b.element(c,".gb-form").height();d=b.element(c,".gb-form").width();e.Form_onResize(d,f);b.hasCapability("mobile")||b.element(c,".ge-search-input").focus();C()};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(c)};this.Form_onResize=
function(a,d){b.element(c,".ge-entity-grid").width(a-20+"px");b.element(c,".ge-entity-grid").height(d-150+"px");b.element(c,".ge-entity-grid");p.resize()};this.FormClose_onClick=function(){b.closeForm(c)};this.Grid_onDblClick=function(b){q("EditButton")?g("EditButton"):q("LISTITEMS")?g("LISTITEMS"):q("EDT")?g("EDT"):g("ViewButton")};this.Grid_onFetchData=function(b){};this.Grid_onSelectionChange=function(b){void 0!==k&&null!==k&&(0<b.length?k.enableButtons("ViewButton,EditButton,DeleteButton","gs-darkblue-background-colour gs-glow-focusborder"):
k.disableButtons("ViewButton,EditButton,DeleteButton","gs-darkblue-background-colour gs-glow-focusborder"))};this.btnSearch_onClick=function(){var a=b.element(c,".ge-search-input").val(),a=massageKeyword(a);p.search(a)};this.btnSearchClear_onClick=function(){p.search("");b.element(c,".ge-search-input").val("");b.element(c,".ge-search-input").focus()};this.SearchField_onEnterKey=function(a){a=b.element(a).val();a=massageKeyword(a);p.search(a)};this.TabEnd_onFocus=function(){b.element(c,".CloseButton").focus()};
this.TabStart_onFocus=function(){}};
