// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmMenu(m,n,p){function g(c){a.element(b,".ge-menu-panel").height()>e?a.element(b,".ge-navbar").css("overflow-y","scroll"):a.element(b,".ge-navbar").css("overflow-y","hidden")}function h(){a.registerMenu(c,b);k=new jDock(a,{addtorecent:!1,cbOnRender:g,closeonselect:a.hasCapability("mobile"),map:d,mode:"verticalmenu",renderblanks:!0,tiles:f.getTiles(),recent:l});k.render(b,".ge-menu-panel")}var a=m,f=new JNav(a,"bootstrap"),c=this,b=n,k,l="RecentItem1Button RecentItem2Button RecentItem3Button RecentItem4Button RecentItem5Button RecentItem6Button RecentItem7Button".split(" "),
e=0,d=f.getMap("menu");this.Form_canClose=function(){return 0===d.length};this.Form_allowMultipleInstances=function(){return!1};this.Form_onBroadcast=function(a,b){"core"===a&&"loginFormSuccess"===b&&(l="RecentItem1Button RecentItem2Button RecentItem3Button RecentItem4Button RecentItem5Button RecentItem6Button RecentItem7Button".split(" "),e=0,d=f.getMap("menu"),h())};this.Form_onClick=function(){a.setFormFocus(c,b)};this.Form_onDblClick=function(c,e,d){a.formToFront(b);d.stopPropagation();a.zoomFormInOut(b)};
this.Form_onFocus=function(){a.setTabOrder(b,"ge-tab-start,ge-tab-end");a.hasCapability("mobile")?doNothing():a.toBoolean(a.getProperty("public"))?(a.hideMenu(),a.destroyMenu()):a.toBoolean(a.getProperty("isindividual"))?a.hideMenu():a.showMenu()};this.Form_onFocusLost=function(){};this.Form_onLoad=function(){0===d.length?a.closeForm(b):(a.isModuleLoaded("widgettube")&&a.hasCapability("tube")&&(a.element(b,".gb-form").removeClass("gi-background-form"),a.element(b,".gb-form").addClass("gi-background-transparent")),
a.element(b,".ge-form-title").text(""),a.unbindEvents(b,"gb-form,gb-formtitle-inner-panel"),a.bindEvent(c,b,".gb-form-close","FormClose","onClick"),a.bindEvent(c,b,".gb-form","Form","onClick"),a.bindEvent(c,b,".gb-form","Form","onDblClick"),a.bindEvent(c,b,".gb-formtitle-inner-panel","FormTitle","onClick"),h(),a.createMenu())};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(c,d){e=d;a.element(b,".gb-form").height(e+"px");a.element(b,".ge-navbar").height(e-4+"px");g()};
this.FormTitle_onClick=function(){a.formToFront(b)};this.FormClose_onClick=function(){a.closeForm(b)};this.TabEnd_onFocus=function(){doNothing()};this.TabStart_onFocus=function(){doNothing()}};
