// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmPayment(T,U,h){function V(){a.dialogConfirm("Are you sure you wish to clear your cart?",function(){var b=a.ajaxRequestCreate("cart_clear",[]);a.ajaxCall(URL_WEBSERVICE,b,doNothing,a.ajaxError,doNothing,!0);a.closeForm(c)})}function W(b){var a;processArray(s,function(c){if(c.id===b)return a=c,!0});return a}function X(){var b="",d=a.element(c,".ge-paymentmethod-field:checked"),l=".ge-paymentmethod-"+d.data("code"),b=a.element(c,l),l={},d=d.val();l.ccaccountname=a.element(b,".ge-ccaccountname-field").val();
l.ccnumber=a.element(b,".ge-ccnumber-field").val();l.ccmonth=a.element(b,".ge-ccmonth-field").val();l.ccyear=a.element(b,".ge-ccyear-field").val();l.ccsecuritycode="";b=Y(l);0<b.length?a.dialogAlertScroll(b,function(){}):I(d,l)}function t(){a.element(c,".ge-step-checkouterror").hide();a.element(c,".ge-step-cart").hide();a.element(c,".ge-step-payer").hide();a.element(c,".ge-step-paymentmethods").hide();a.element(c,".ge-step-products").hide();a.element(c,".ge-step-addproducts").hide();a.element(c,".ge-step-thankyou").hide()}
function J(){m="products";t();Z();K(".ge-cartcontent1");a.unbindEvents(c,"ge-productaddtocart-button,ge-productnext-button,ge-cartcancel-button");a.bindEvent(f,c,".ge-productaddtocart-button","ProductAddToCartButton","onClick");a.bindEvent(f,c,".ge-productnext-button","ProductNextButton","onClick");a.bindEvent(f,c,".ge-cartcancel-button","CartCancelButton","onClick");L?(a.element(c,".ge-step-addproducts").show(),a.element(c,".ge-cartmessage-wrapper").show()):0===e.transactionlines.length?(a.element(c,
".ge-cartmessage-wrapper").hide(),a.element(c,".ge-step-addproducts").show()):(a.element(c,".ge-step-addproducts").hide(),a.element(c,".ge-cartmessage-wrapper").show());a.unbindEvents(c,"ge-removeproduct-button,ge-cartcancel-button");a.bindEvent(f,c,".ge-removeproduct-button","RemoveProductButton","onClick");a.bindEvent(f,c,".ge-cartcancel-button","CartCancelButton","onClick");a.element(c,".ge-step-products").show()}function v(){m="payer";t();a.element(c,".ge-payername-field").val(e.payername);a.element(c,
".ge-payeraddressline1-field").val(e.payeraddressline1);a.element(c,".ge-payeraddressline2-field").val(e.payeraddressline2);a.element(c,".ge-payersuburb-field").val(e.payersuburb);a.element(c,".ge-payerstate-field").val(e.payerstate);a.element(c,".ge-payerpostcode-field").val(e.payerpostcode);a.element(c,".ge-payernotes-field").val(e.payernotes);a.unbindEvents(c,"ge-payerproceed-button,ge-cartcancel-button");a.bindEvent(f,c,".ge-payerproceed-button","PayerProceedButton","onClick");a.bindEvent(f,c,
".ge-cartcancel-button","CartCancelButton","onClick");a.element(c,".ge-step-payer").show()}function y(){if(0<e.transactionlines.length){m="cart";t();var b=K(".ge-cartcontent2");a.unbindEvents(c,"ge-cartnext-button,ge-cartpayer-button,ge-cartviewreceipt-button,ge-removeproduct-button,ge-cartcancel-button");a.bindEvent(f,c,".ge-cartnext-button","CartNextButton","onClick");a.bindEvent(f,c,".ge-cartpayer-button","CartPayerButton","onClick");a.bindEvent(f,c,".ge-cartviewreceipt-button","ViewReceiptButton",
"onClick");a.bindEvent(f,c,".ge-removeproduct-button","RemoveProductButton","onClick");a.bindEvent(f,c,".ge-cartcancel-button","CartCancelButton","onClick");0<b?(a.element(c,".ge-step-cart .ge-cartnext-button").removeAttr("disabled"),a.element(c,".ge-step-cart .ge-cartviewreceipt-button").removeAttr("disabled")):(a.element(c,".ge-step-cart .ge-cartnext-button").attr("disabled","disabled"),a.element(c,".ge-step-cart .ge-cartviewreceipt-button").attr("disabled","disabled"));a.element(c,".ge-step-cart").show()}else m=
"",J()}function aa(){t();ba();ca();a.unbindEvents(c,da);a.unbindEvents(c,"ge-paymentmethodsconfirm-button,ge-paymentmethodscart-button,ge-paymentmethodsviewreceipt-button,ge-paymentmethod-option,ge-cartcancel-button");a.bindEvent(f,c,".ge-paymentmethodsconfirm-button","PaymentMethodsConfirmButton","onClick");a.bindEvent(f,c,".ge-paymentmethodscart-button","PaymentMethodsCartButton","onClick");a.bindEvent(f,c,".ge-paymentmethodsviewreceipt-button","ViewReceiptButton","onClick");a.bindEvent(f,c,".ge-paymentmethod-option",
"PaymentMethodSelect","onClick");a.bindEvent(f,c,".ge-cartcancel-button","CartCancelButton","onClick");0<w&&a.element(c,".ge-paymentmethodsconfirm-button").attr("disabled","disabled");a.element(c,".ge-step-paymentmethods").show()}function ea(){var b="";"products"===m?0===e.transactionlines.length&&(a.element(c,".ge-products-option").is(":checked")||(b+="<li>Product / Subscription is required.</li>")):"paymentmethods"===m&&z&&(a.element(c,".ge-paymentmethod-field").is(":checked")||(b+="<li>Payment Method is required.</li>"));
0<b.length&&(b="<ul>"+b+"</ul>");return b}function Y(b){var a="";0===$.trim(b.ccaccountname).length&&(a+="<li>Account Name is required.</li>");0===$.trim(b.ccnumber).length&&(a+="<li>Credit Card Number is required.</li>");0===$.trim(b.ccmonth).length&&(a+="<li>Credit Card Expiry Month is required.</li>");0===$.trim(b.ccyear).length&&(a+="<li>Credit Card Expiry Year is required</li>");0<a.length&&(a="<ul>"+a+"</ul>");return a}function fa(){var a="";n===M&&(0===u.length?a="<li>Product is required.</li>":
(processArray(s,function(a){a.id===u&&(A=a)}),void 0===A&&(a="<li>The product is not available</li>")));0<a.length&&(a="<ul>"+a+"</ul>");return a}function ga(){a.closeForm(c);a.dialogAlertScroll("Product added to cart",doNothing)}function N(){var b="",b=fa();0<b.length?(a.closeForm(c),a.dialogAlertScroll(b,doNothing)):n===M?O([A.id],"cart",ga):n===P?0<e.progress.length&&(m=e.progress):n===ha?v():"payer"===m?v():"cart"===m?y():(a.element(c,".ge-cartmessage-wrapper").show(),J())}function K(b){var d=
0,l=0,f=0,q=0,h=0,k=0,g="",m="",n="",g=g+'<table class="table orderreview table-bordered">',g=g+"<thead>",g=g+'<tr><th>Details</th><th style="text-align:center">Remove</th><th>Total (Inc-GST)</th></tr>',g=g+"</thead>",g=g+"<tbody>";processArray(e.transactionlines,function(b){a.toBoolean(b.ingraceperiod)?(d=l=0,n="$"+a.formatMoney(d),m="&nbsp;(grace)"):(l=b.priceexgst,d=b.priceincgst,n="$"+a.formatMoney(d),m="");f+=0.01*parseInt(100*l,10);q+=0.01*parseInt(100*d,10);g+="<tr>";g+="<td>"+htmlEncode(b.description)+
"</td>";g+='<td style="text-align:center"><span class="gb-button ge-removeproduct-button" data-id="'+htmlEncode(b.id)+'"><i class="ge-trash'+k+' glyphicon glyphicon-trash"></i></span></td>';g+="<td>"+n+m+"</td>";g+="</tr>";k++});g+="</tbody>";g+="<tfoot>";h=0.01*parseInt(100*q-100*f,10);g+='<tr><td colspan="2">GST:</td><td>$'+a.formatMoney(h)+"</td></tr>";g+='<tr><td colspan="2">Total (Inc-GST):</td><td>$'+a.formatMoney(q)+"</td></tr>";g+="</tfoot>";g+="</table>";z=0<q;w=q;0<k?(a.element(c,b).html(g),
k=0,processArray(e.transactionlines,function(b){a.showTip(c,".ge-trash"+k,"bottom center","top center",2,"Remove this item from the cart");k++})):(g="Your cart is empty.",a.element(c,b).html(g));return k}function ba(){var b="",d="";0<w&&(b+='<div style="margin:10px 0;"><b>Total (Inc-GST):&nbsp;&nbsp;$'+a.formatMoney(w)+"</b></div><br>");b+='<ul class="list-items">';z?processArray(B,function(c){if(a.toBoolean(c.enabled)){d="";null!==e.paymentmethodid&&0<e.paymentmethodid.length&&e.paymentmethodid===
c.id&&(d="checked");var f=c.description;a.toBoolean(c.is_cc)&&0<c.paymentproviderdescription.length&&(f+=" ("+c.paymentproviderdescription+")");b+='<li class="radio">';b+="<label>";b+='<input type="radio" '+d+' class="ge-paymentmethod-option ge-paymentmethod-field" name="ge-paymentmethod" data-code="'+htmlEncode(c.code)+'" data-iscreditcard="'+htmlEncode(c.is_cc)+'" value="'+htmlEncode(c.id)+'"  />&nbsp;'+htmlEncode(f);b+="</label>";b+="</li>"}}):b+="<b>No payment is required.</b><br/><br/>To proceed please press the <b>Confirm Purchase</b> button below.";
b+="</ul><br>";a.element(c,".ge-paymentmethodscontent").html(b)}function ca(){var b="",d="",b=b+'<ul class="ge-paymentmethodfields list-items">';processArray(B,function(c){d=" gb-hidden";null!==e.paymentmethodid&&0<e.paymentmethodid.length&&e.paymentmethodid===c.id&&(d="");b+='<li class="ge-paymentmethod-'+htmlEncode(c.code)+d+'">';a.toBoolean(c.enabled)&&(a.toBoolean(c.is_cc)?(0<c.notes.length&&(b+="<div>"+htmlEncode(c.notes)+"</div><br><br>"),b+="<h4>Credit Card Details</h4>",b+='<div class="form-group">',
b+="<label>Account Name:</label>",b+='<input type="text" class="form-control ge-ccaccountname-field" placeholder="Account Name">',b+="</div>",b+='<div class="form-group">',b+="<label>Credit Card Number:</label>",b+='<input type="text" class="form-control ge-ccnumber-field" placeholder="Credit Card Number">',b+="</div>",b+='<div class="form-group row">',b+='<div class="col-md-6">',b+="<label>Expiry Date MM:</label>",b+='<input type="text" class="form-control ge-ccmonth-field" placeholder="MM">',b+=
"</div>",b+='<div class="col-md-6">',b+="<label>Expiry Date YYYY:</label>",b+='<input type="text" class="form-control ge-ccyear-field" placeholder="YYYY">',b+="</div>",b+="</div>"):b+="<div>"+htmlEncode(c.notes)+"</div>",b+="</li>")});b+="</ul>";a.element(c,".ge-paymentmethodfields").html(b)}function Z(){var b=0,d="",e="0.00",f="",d=d+'<ul class="list-items">';processArray(s,function(c){a.toBoolean(c.ingraceperiod)?(e="$0.00",f="&nbsp;(grace)"):(e="$"+a.formatMoney(c.price_incgst),f="");d+='<li class="radio">';
d=L?d+('<label><input type="checkbox" class="ge-products-option" name="ge-product[]" value="'+htmlEncode(c.id)+'"  />&nbsp;'+htmlEncode(c.description)+"&nbsp;&nbsp;"+e+f+"</label>"):d+('<label><input type="radio" class="ge-products-option" name="ge-product" value="'+htmlEncode(c.id)+'"  />&nbsp;'+htmlEncode(c.description)+"&nbsp;&nbsp;"+e+f+"</label>");b++;d+="</li>"});d+="</ul>";0<p.length&&a.element(c,".ge-applicantname-header").html(htmlEncode(p));a.element(c,".ge-productscontent").html(d);0<b?
a.element(c,".ge-step-addproducts").show():a.element(c,".ge-step-addproducts").hide();a.element(c,".ge-step-products").show()}function x(){C++;Q==C&&N()}function ia(a){e=a[0];x()}function ja(a){B=a;x()}function ka(a){s=a;x()}function la(b){D=!1;t();a.element(c,".ge-step-thankyou").show()}function ma(b){e=b[0];b=a.ajaxRequestCreate("cart_fetchproducts",[{name:"filter",value:E}]);a.ajaxCall(URL_WEBSERVICE,b,na,a.ajaxError,doNothing,!0)}function na(a){s=a;n=oa;N()}function pa(b){a.element(c,".ge-thankyoucontent").html(b[0].content);
x()}function O(b,c,f){var h=a.ajaxRequestCreate("cart_add",[{name:"id",value:b[0]},{name:"idlist",value:b},{name:"applicantname",value:p}]);a.ajaxCall(URL_WEBSERVICE,h,function(a){var h="",k;processArray(b,function(b){k=W(b);h=0<p.length?k.description+" for "+p:k.description;e.transactionlines.push({id:a,productid:b,description:h,priceincgst:k.price_incgst,priceexgst:k.price_exgst,ingraceperiod:k.ingraceperiod})});r(c,f,!1)},a.ajaxError,doNothing,!0)}function I(b,c){var e=a.ajaxRequestCreate("cart_commit",
[{name:"paymentmethodid",value:b},{name:"card",value:c}]);a.ajaxCall(URL_WEBSERVICE,e,la,a.ajaxError,doNothing,!0)}function R(){var b=a.ajaxRequestCreate("cart_fetch",[]);a.ajaxCall(URL_WEBSERVICE,b,ma,a.ajaxError,doNothing,!0)}function r(b,c,f){b=a.ajaxRequestCreate("cart_updateprogress",[{name:"progress",value:b},{name:"updatepayer",value:f},{name:"payername",value:e.payername},{name:"payeraddressline1",value:e.payeraddressline1},{name:"payeraddressline2",value:e.payeraddressline2},{name:"payersuburb",
value:e.payersuburb},{name:"payerstate",value:e.payerstate},{name:"payerpostcode",value:e.payerpostcode},{name:"payernotes",value:e.payernotes}]);a.ajaxCall(URL_WEBSERVICE,b,c,a.ajaxError,doNothing,!0)}var a=T,f=this,c=U,Q=0,C=0,da="ge-ccaccountname-field,ge-ccnumber-field,ge-ccmonth-field,ge-ccyear-field,ge-cctype-option,ge-ccsecuritycode-field",E="",u="",z=!1,B=null,s=null,e=null,m="",w=0,D=!1,A,F=h.title;void 0===F&&(F="");var p=h.applicantname;void 0===p&&(p="");var L=a.toBoolean(h.multi),G=h.producttypeheading;
void 0===G&&(G="");var H=h.producttype;void 0===H&&(H="");u=h.productid;void 0===u&&(u="");var M="addtocart",ha="checkout",P="continue",n=h.mode;void 0===n&&(n=P);var oa=n,S,qa=[{location:"root",title:"Home",layout:[["CloseButton"]]}],ra=[{id:"-",caption:"",classes:"",permissions:[],action:"",tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"btn-success",permissions:[],action:function(){f.FormClose_onClick()},tip:"Click here to close the form",type:"toolbarbutton"}];this.Form_allowMultipleInstances=
function(){return!1};this.Form_canClose=function(){return!0};this.Form_isDirty=function(){return!1};this.Form_onClick=function(){a.setFormFocus(f,c)};this.Form_onFocus=function(b){a.unbindEvents(c,"ge-tab-start,ge-tab-end");a.bindEvent(f,c,".ge-tab-start","TabStart","onFocus");a.bindEvent(f,c,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(c,"ge-tab-start,ge-save-button,ge-tab-end")};this.Form_onLoad=function(){void 0!==h.filter&&0<h.filter.length&&(E=h.filter);var b=a.getViewPort().width,d=a.getViewPort().height;
a.resizeAndRepositionForm(c,0.1*d,0.1*b,0.8*d,0.8*b);a.element(c,".ge-form-title").text(F);a.element(c,".ge-popupblockerurl").attr("href",POPUPBLOCKER+a.getBrowser().name);a.element(c,".ge-producttypeheading").text(G);a.element(c,".ge-producttype").text(H);S=new jDock(a,{alwaysvisiblebuttoncount:2,map:qa,tiles:ra});S.render(c,".ge-button-panel");a.unbindEvents(c,"gb-form");a.bindEvent(f,c,".gb-form-close","FormClose","onClick");a.bindEvent(f,c,".gb-form","Form","onClick");a.bindEvent(f,c,".gb-formtitle-inner-panel",
"FormTitle","onClick");Q=4;C=0;b=a.ajaxRequestCreate("cart_fetch",[]);a.ajaxCall(URL_WEBSERVICE,b,ia,a.ajaxError,doNothing,!0);b=a.ajaxRequestCreate("cart_fetchpaymentmethods",[]);a.ajaxCall(URL_WEBSERVICE,b,ja,a.ajaxError,doNothing,!0);b=a.ajaxRequestCreate("cart_fetchproducts",[{name:"filter",value:E}]);a.ajaxCall(URL_WEBSERVICE,b,ka,a.ajaxError,doNothing,!0);b=a.ajaxRequestCreate("cart_fetchcmsthankyou",[]);a.ajaxCall(URL_WEBSERVICE,b,pa,a.ajaxError,doNothing,!0)};this.Form_onPermissionCheck=function(){return!0};
this.Form_onResize=function(b,d){a.element(c,".gb-overflow").height(d-127+"px");a.element(c,".gb-overflow").css("overflow-y","scroll")};this.FormClose_onClick=function(){a.closeForm(c)};this.CartCancelButton_onClick=function(a){V()};this.CartNextButton_onClick=function(a){r("cartpage",aa,!1)};this.CartPayerButton_onClick=function(a){r("payerpage",v,!1)};this.PaymentMethodsCartButton_onClick=function(a){r("cartpage",y,!1)};this.ProductAddToCartButton_onClick=function(b){b=a.element(c,".ge-products-option:checked");
var d=[];processArray(b,function(a){d.push(a.value)});0<d.length?O(d,"cartpage",R):a.dialogAlertScroll("<ul><li>Product or subscription are required.</li></ul>",function(){})};this.ProductNextButton_onClick=function(b){0<e.transactionlines.length?r("payerpage",v,!1):a.dialogAlertScroll("<ul><li>You have no products or subscriptions in your cart.</li></ul>",function(){})};this.PayerProceedButton_onClick=function(b){e.payername=a.element(c,".ge-payername-field").val();e.payeraddressline1=a.element(c,
".ge-payeraddressline1-field").val();e.payeraddressline2=a.element(c,".ge-payeraddressline2-field").val();e.payersuburb=a.element(c,".ge-payersuburb-field").val();e.payerstate=a.element(c,".ge-payerstate-field").val();e.payerpostcode=a.element(c,".ge-payerpostcode-field").val();e.payernotes=a.element(c,".ge-payernotes-field").val();r("cartpage",y,!0)};this.PaymentMethodsConfirmButton_onClick=function(){if(!D){D=!0;var b="",b=ea();if(0<b.length)a.dialogAlertScroll(b,function(){});else if(b=a.element(c,
".ge-paymentmethod-field:checked"),a.toBoolean(b.data("iscreditcard")))X();else{var d="",b=a.element(c,".ge-paymentmethod-field");processArray(b,function(b){a.element(c,b).is(":checked")&&(d=htmlDecode(a.element(c,b).val()))});I(d,null)}}};this.PaymentMethodSelect_onClick=function(b){b=a.element(c,".ge-paymentmethod-option:checked").data("code");var d=a.element(c,".ge-paymentmethodfields");a.element(d,"ul li").addClass("gb-hidden");a.element(d,"ul li.ge-paymentmethod-"+htmlEncode(b)).removeClass("gb-hidden");
a.element(c,".ge-paymentmethodsconfirm-button").removeAttr("disabled")};this.ViewReceiptButton_onClick=function(b){b=a.ajaxRequestCreate("cart_getreceipt",[]);a.ajaxCall(URL_WEBSERVICE,b,doNothing,a.ajaxError,doNothing,!0)};this.RemoveProductButton_onClick=function(b){b=a.element(b);var c=[];c.push(b.data("id"));0<c.length&&(b=a.ajaxRequestCreate("cart_productsremove",[{name:"id",value:c[0]},{name:"idlist",value:c}]),a.ajaxCall(URL_WEBSERVICE,b,R,a.ajaxError,doNothing,!0))};this.TabEnd_onFocus=function(){};
this.TabStart_onFocus=function(){}};
