// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmRegister(x,y,X){function n(){var c=stripChars(a.element(b,".ge-accountname-field").val()),e=stripChars(a.element(b,".ge-fullname-field").val()),c=a.str_left(c,6),c=c+a.str_left(e,3),c=c.toUpperCase();a.element(b,".ge-clientcode-field").val(c)}function A(){B.bind();C.bind();D.bind();E.bind();a.element(b,".ge-venuecountry-field").val(a.getProperty("defaultcountry"));a.element(b,".ge-contactcountry-field").val(a.getProperty("defaultcountry"));a.element(b,".ge-contactcountry-2-field").val(a.getProperty("defaultcountry"));
a.element(b,".ge-appname-field").html(APP_NAME);t();"TRUE"===ENABLE_REGISTER?a.element(b,".rowAllowRegister").show():a.element(b,".rowAllowRegister").hide();a.element(b,".ge-english-name").text(DATABASENAME);a.element(b,".ge-app-name").text(APP_NAME);a.element(b,".ge-app-copyright").text(APP_COPYRIGHT);a.element(b,".ge-client-version").text("version "+APP_VERSION);a.limitInput(b,".ge-clientcode-field",100,!0);a.limitInput(b,".ge-login-field",40,!0);a.limitInput(b,".ge-password-field",20,!0);var c=
0,z="",d="",g="",h="",f=" ge-registrationtype-option1",k=0,F=0,c=m.length;1===c&&(z=' checked="checked"');processArray(m,function(a){"Y"==a.is_employer?(g+="<tr>",g+='    <td width="80%"><b>'+htmlEncode(a.description)+"</b></td>",g+='    <td><input type="radio" name="registrationtype" class="ge-registrationtype-option'+f+'" value="'+htmlEncode(a.id)+'" is_employer="Y"'+z+"></td>",g+="</tr>",g+="<tr>",g+="    <td><br>"+htmlEncode(a.longdescription)+"<br><br></td>",g+="    <td>&nbsp;</td>",g+="</tr>",
k+=1):(h+="<tr>",h+='    <td width="80%"><b>'+htmlEncode(a.description)+"</b></td>",h+='    <td><input type="radio" name="registrationtype" class="ge-registrationtype-option'+f+'" value="'+htmlEncode(a.id)+'" is_employer="N"'+z+"></td>",h+="</tr>",h+="<tr>",h+="    <td><br>"+htmlEncode(a.longdescription)+"<br><br></td>",h+="    <td>&nbsp;</td>",h+="</tr>",F+=1);f=""});0<F&&(d+='<tr>    <td colspan="2" width="100%"><center><u><b>I am registering as an individual</b></u></center></td>',d+="</tr>",d+=
"<tr>",d+='    <td colspan="2" width="100%">&nbsp;</td>',d+="</tr>",d+=h);d+="<tr>";d+='    <td colspan="2" width="100%"><hr></td>';d+="</tr>";0<k&&(d+="<tr>",d+='    <td colspan="2" width="100%"><center><u><b>I am registering as a business</b></u></center></td>',d+="</tr>",d+="<tr>",d+='    <td colspan="2" width="100%">&nbsp;</td>',d+="</tr>",d+=g);a.element(b,".gb-registrationtype-field").html(d);a.bindEvent(e,b,".ge-registrationtype-option","RegistrationTypeButton","onClick");u();1===c&&(a.element(b,
".ge-accountprev-button").hide(),e.RegistrationTypeButton_onClick(),e.RegistrationTypeNextButton_onClick(),l("AccountPanel"))}function v(){a.element(b,".gb-panel-registrationtype").hide();a.element(b,".gb-panel-account").hide();a.element(b,".gb-panel-venue").hide();a.element(b,".gb-panel-contact").hide();a.element(b,".gb-panel-contact2").hide();a.element(b,".gb-panel-about").show();k&&a.element(b,".ge-businessname-field").focus();l("AboutPanel")}function p(){a.element(b,".gb-panel-registrationtype").hide();
a.element(b,".gb-panel-account").show();a.element(b,".gb-panel-venue").hide();a.element(b,".gb-panel-contact").hide();a.element(b,".gb-panel-contact2").hide();a.element(b,".gb-panel-about").hide();k?a.element(b,".ge-accountname-field").focus():a.element(b,".ge-fullname-field").focus();l("AccountPanel")}function q(c){a.element(b,".gb-panel-registrationtype").hide();a.element(b,".gb-panel-account").hide();a.element(b,".gb-panel-venue").hide();a.element(b,".gb-panel-contact").show();a.element(b,".gb-panel-contact2").hide();
a.element(b,".gb-panel-about").hide();a.element(b,".ge-contactfullname-field").focus();l("ContactPanel")}function t(){a.element(b,".gb-panel-registrationtype").show();a.element(b,".gb-panel-account").hide();a.element(b,".gb-panel-venue").hide();a.element(b,".gb-panel-contact").hide();a.element(b,".gb-panel-contact2").hide();a.element(b,".gb-panel-about").hide();l("RegistrationTypePanel")}function K(b){"TRUE"===IMMEDIATE_REGISTRATION?a.gotoURL("#!core.frmRegisterConfirmation",""):a.gotoURL("#!core.frmRegisterVerification",
"")}function G(a){m=a;r++;w==r&&A()}function H(){var c=a.getAgent(),e=a.getBrowserCapabilities(),d="",g=a.element(b,".ge-registrationtype-option");processArray(g,function(c){a.element(b,c).is(":checked")&&(d=a.element(b,c).val())});var g=a.element(b,".ge-accountname-field").val(),h=a.element(b,".ge-fullname-field").val(),f=a.element(b,".ge-clientcode-field").val(),k=a.element(b,".ge-login-field").val(),l=a.element(b,".ge-password-field").val(),m=a.element(b,".ge-salespersoncode-field").val(),n=a.element(b,
".ge-venuename-field").val(),p=a.element(b,".ge-venueaddressline1-field").val(),q=a.element(b,".ge-venueaddressline2-field").val(),r=a.element(b,".ge-venuesuburb-field").val(),s=a.element(b,".ge-venuestate-field").val(),t=a.element(b,".ge-venuepostcode-field").val(),u=a.element(b,".ge-venuecountry-field").val(),v=a.element(b,".ge-venuephonenumber-field").val(),w=a.element(b,".ge-venueemailaddress-field").val(),x=a.element(b,".ge-contactfullname-field").val(),y=a.element(b,".ge-contactaddressline1-field").val(),
A=a.element(b,".ge-contactaddressline2-field").val(),B=a.element(b,".ge-contactsuburb-field").val(),C=a.element(b,".ge-contactstate-field").val(),D=a.element(b,".ge-contactpostcode-field").val(),E=a.element(b,".ge-contactcountry-field").val(),G=a.element(b,".ge-contactphonenumber-field").val(),H=a.element(b,".ge-contactemailaddress-field").val(),L=a.element(b,".ge-contactfullname-2-field").val(),M=a.element(b,".ge-contactaddressline1-2-field").val(),N=a.element(b,".ge-contactaddressline2-2-field").val(),
O=a.element(b,".ge-contactsuburb-2-field").val(),P=a.element(b,".ge-contactstate-2-field").val(),Q=a.element(b,".ge-contactpostcode-2-field").val(),R=a.element(b,".ge-contactcountry-2-field").val(),S=a.element(b,".ge-contactphonenumber-2-field").val(),T=a.element(b,".ge-contactemailaddress-2-field").val(),U=a.element(b,".ge-businessname-field").val(),V=a.element(b,".ge-abn-field").val(),W=a.element(b,".ge-about-field").val(),I="N";a.element(b,".ge-termsconditions-field").is(":checked")&&(I="Y");var J=
"N";a.element(b,".ge-privacy-field").is(":checked")&&(J="Y");c=a.ajaxRequestCreate("public_register",[{name:"useragent",value:c},{name:"registrationtype_id",value:d},{name:"accountname",value:g},{name:"fullname",value:h},{name:"clientcode",value:f},{name:"login",value:k},{name:"password",value:l},{name:"salespersoncode",value:m},{name:"venuename",value:n},{name:"venueaddressline1",value:p},{name:"venueaddressline2",value:q},{name:"venuesuburb",value:r},{name:"venuestate",value:s},{name:"venuepostcode",
value:t},{name:"venuecountry",value:u},{name:"venuephonenumber",value:v},{name:"venueemailaddress",value:w},{name:"contactfullname",value:x},{name:"contactaddressline1",value:y},{name:"contactaddressline2",value:A},{name:"contactsuburb",value:B},{name:"contactstate",value:C},{name:"contactpostcode",value:D},{name:"contactcountry",value:E},{name:"contactphonenumber",value:G},{name:"contactemailaddress",value:H},{name:"contactfullname_2",value:L},{name:"contactaddressline1_2",value:M},{name:"contactaddressline2_2",
value:N},{name:"contactsuburb_2",value:O},{name:"contactstate_2",value:P},{name:"contactpostcode_2",value:Q},{name:"contactcountry_2",value:R},{name:"contactphonenumber_2",value:S},{name:"contactemailaddress_2",value:T},{name:"businessname",value:U},{name:"abn",value:V},{name:"about",value:W},{name:"termsconditions",value:I},{name:"privacy",value:J},{name:"capabilities",value:e}]);a.ajaxCall(URL_WEBSERVICE,c,K,a.ajaxError,doNothing,!0)}function u(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(e,
b,".ge-tab-start","TabStart","onFocus");a.bindEvent(e,b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,"+f+",ge-tab-end")}function l(c){var f="";a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(e,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(e,b,".ge-tab-end","TabEnd","onFocus");switch(c){case "AccountPanel":f="ge-accountname-field,ge-fullname-field,ge-clientcode-field,ge-login-field,ge-password-field,ge-confirmpassword-field,ge-salespersoncode-field,ge-accountnext-button,ge-accountprev-button";
break;case "AboutPanel":f="ge-businessname-field,ge-abn-field,ge-about-field,ge-termsconditions-field,ge-privacy-field,ge-aboutnext-button,ge-aboutprev-button";break;case "VenuePanel":f="ge-venuename-field,ge-venueaddressline1-field,ge-venueaddressline2-field,ge-venuesuburb-field,ge-venuestate-field,ge-venuepostcode-field,ge-venuecountry-field,ge-venuephonenumber-field,ge-venueemailaddress-field,ge-venuenext-button,ge-venueprev-button";break;case "ContactPanel":f="ge-contactfullname-field,ge-contactaddressline1-field,ge-contactaddressline2-field,ge-contactsuburb-field,ge-contactstate-field,ge-contactpostcode-field,ge-contactcountry-field,ge-contactphonenumber-field,ge-contactemailaddress-field,ge-contactnext-button,ge-contactprev-button";
break;case "ContactPanel2":f="ge-contactfullname-2-field,ge-contactaddressline1-2-field,ge-contactaddressline2-2-field,ge-contactsuburb-2-field,ge-contactstate-2-field,ge-contactpostcode-2-field,ge-contactcountry-2-field,ge-contactphonenumber-2-field,ge-contactemailaddress-2-field,ge-register-button,ge-contactprev-2-button";break;case "RegistrationTypePanel":f="ge-accounttype-field,ge-accounttype-option1,ge-accounttype-option,ge-accounttypenext-button";break;default:doNothing()}a.setTabOrder(b,"ge-tab-start,"+
f+",ge-tab-end")}var a=x,e=this,b=y,k=!0,m=null,s=null,w=0,r=0,f="ge-registrationtype-field,ge-registrationtype-option1,ge-registrationtype-option,ge-registrationtypenext-button",f=f+"ge-accountname-field,ge-fullname-field,ge-clientcode-field,ge-login-field,ge-password-field,ge-confirmpassword-field,ge-salespersoncode-field,ge-accountnext-button,ge-accountprev-button",f=f+"ge-businessname-field,ge-abn-field,ge-about-field,ge-termsconditions-field,ge-privacy-field,ge-aboutnext-button,ge-aboutprev-button",
f=f+"ge-venuename-field,ge-venueaddressline1-field,ge-venueaddressline2-field,ge-venuesuburb-field,ge-venuestate-field,ge-venuepostcode-field,ge-venuecountry-field,ge-venuephonenumber-field,ge-venueemailaddress-field,ge-venuenext-button,ge-venueprev-button",f=f+"ge-contactfullname-field,ge-contactaddressline1-field,ge-contactaddressline2-field,ge-contactsuburb-field,ge-contactstate-field,ge-contactpostcode-field,ge-contactcountry-field,ge-contactphonenumber-field,ge-contactemailaddress-field,ge-contactnext-button,ge-contactprev-button",
f=f+"ge-contactfullname-2-field,ge-contactaddressline1-2-field,ge-contactaddressline2-2-field,ge-contactsuburb-2-field,ge-contactstate-2-field,ge-contactpostcode-2-field,ge-contactcountry-2-field,ge-contactphonenumber-2-field,ge-contactemailaddress-2-field,ge-register-button,ge-contactprev-2-button",f=f+"ge-terms-link,ge-privacy-link",B=new suburbFinder(a,b,"ge-venuesuburb-field","ge-venuestate-field","ge-venuepostcode-field","ge-venuecountry-field",a.getProperty("defaultcountry")),C=new suburbFinder(a,
b,"ge-contactsuburb-field","ge-contactstate-field","ge-contactpostcode-field","ge-contactcountry-field",a.getProperty("defaultcountry")),D=new suburbFinder(a,b,"ge-contactsuburb-2-field","ge-contactstate-2-field","ge-contactpostcode-2-field","ge-contactcountry-2-field",a.getProperty("defaultcountry")),E=new abnFinder(a,b,"ge-abn-field","ge-businessname-field","BusinessName",!0,"ge-abnsearch-button");this.PrivacyPolicyLink_onClick=function(){a.showFormLocal("entity.frmHTMLForm",{entity:"systemform",
formentity:"CMS",formcode:"CMS",mode:"view",title:APP_SHORT_NAME+" Privacy Policy",code:"PRIVACY_POLICY"},null,!0)};this.TermsConditionLink_onClick=function(){a.showFormLocal("entity.frmHTMLForm",{entity:"systemform",formentity:"CMS",formcode:"CMS",mode:"view",title:APP_SHORT_NAME+" Terms and Conditions",code:"TERMS_CONDITIONS"},null,!0)};this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!1};this.Form_onClick=function(){a.setFormFocus(e,b)};this.Form_onFocus=
function(){u();768>a.getViewPort().width?a.element(b,".ge-form").css("width","315px"):a.element(b,".ge-form").css("width","420px");a.closeExclusive(b)};this.Form_onLoad=function(){a.unbindEvents(b,f);a.bindEvent(e,b,".ge-form","Form","onClick");a.bindEvent(e,b,".ge-registrationtypenext-button","RegistrationTypeNextButton","onClick");a.bindEvent(e,b,".ge-accountprev-button","AccountPrevButton","onClick");a.bindEvent(e,b,".ge-accountnext-button","AccountNextButton","onClick");a.bindEvent(e,b,".ge-aboutnext-button",
"AboutNextButton","onClick");a.bindEvent(e,b,".ge-aboutprev-button","AboutPrevButton","onClick");a.bindEvent(e,b,".ge-accountname-field","CodeCriteria","onKeyUp");a.bindEvent(e,b,".ge-fullname-field","CodeCriteria","onKeyUp");a.bindEvent(e,b,".ge-venuenext-button","VenueNextButton","onClick");a.bindEvent(e,b,".ge-venueprev-button","VenuePrevButton","onClick");a.bindEvent(e,b,".ge-contactnext-button","ContactNextButton","onClick");a.bindEvent(e,b,".ge-contactprev-button","ContactPrevButton","onClick");
a.bindEvent(e,b,".ge-contactprev-2-button","Contact2PrevButton","onClick");a.bindEvent(e,b,".ge-register-button","RegisterButton","onClick");a.bindEvent(e,b,".ge-terms-link","TermsConditionLink","onClick");a.bindEvent(e,b,".ge-privacy-link","PrivacyPolicyLink","onClick");w=1;r=0;var c=a.ajaxRequestCreate("core_registrationtypesfetchactive",[]);a.ajaxCall(URL_WEBSERVICE,c,G,a.ajaxError,doNothing,!0)};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(c,e){a.element(b,".ge-panel-content").height(e+
"px");a.element(b,".ge-panel-overflow").height("100%");a.element(b,".ge-panel-overflow").css("overflow-x","hidden");a.element(b,".ge-panel-overflow").css("overflow-y","auto")};this.AboutNextButton_onClick=function(){var c;c="";k&&(0===$.trim(a.element(b,".ge-businessname-field").val()).length&&(c+="<li>Business Name is required.</li>"),0===$.trim(a.element(b,".ge-abn-field").val()).length&&(c+="<li>An ABN is required.</li>"));a.element(b,".ge-termsconditions-field").is(":checked")||(c+="<li>The terms and conditions has not been agreed to yet.</li>");
a.element(b,".ge-privacy-field").is(":checked")||(c+="<li>The privacy policy has not been agreed to yet.</li>");0<c.length?a.dialogAlertScroll("<ul>"+c+"</ul>",doNothing):q()};this.AboutPrevButton_onClick=function(){p()};this.AccountNextButton_onClick=function(){var c;c="";k?0===$.trim(a.element(b,".ge-accountname-field").val()).length&&(c+="<li>Trading Name is required.</li>"):0===$.trim(a.element(b,".ge-fullname-field").val()).length&&(c+="<li>First Name is required.</li>");if(0===$.trim(a.element(b,
".ge-login-field").val()).length)c+="<li>Email Address is required.</li>";else{var e=a.element(b,".ge-login-field").val();a.isEmailAddress(e)||(c+="<li>Email Address must be valid.</li>")}0===$.trim(a.element(b,".ge-password-field").val()).length&&(c+="<li>Password is required.</li>");0===$.trim(a.element(b,".ge-confirmpassword-field").val()).length?c+="<li>Confirm Password is required.</li>":a.element(b,".ge-password-field").val()!=a.element(b,".ge-confirmpassword-field").val()&&(c+="<li>The passwords do not match.</li>");
0<c.length?a.dialogAlertScroll("<ul>"+c+"</ul>",doNothing):(c=a.element(b,".ge-fullname-field").val(),0===a.element(b,".ge-contactfullname-field").val().length&&a.element(b,".ge-contactfullname-field").val(c),c=a.element(b,".ge-login-field").val(),0===a.element(b,".ge-contactemailaddress-field").val().length&&a.element(b,".ge-contactemailaddress-field").val(c),v())};this.AccountPrevButton_onClick=function(){t()};this.RegistrationTypeButton_onClick=function(){var c=a.element(b,".ge-registrationtype-option"),
e;processArray(c,function(c){a.element(b,c).is(":checked")&&(k=a.toBoolean(a.element(b,c).attr("is_employer")),e=a.element(b,c).val())});k?(a.element(b,".gb-isindividual").hide(),a.element(b,".gb-isemployer").show()):(a.element(b,".gb-isemployer").hide(),a.element(b,".gb-isindividual").show());processArray(m,function(a){a.id==e&&(s=a)})};this.CodeCriteria_onChange=function(){n()};this.CodeCriteria_onKeyUp=function(){n()};this.ContactNextButton_onClick=function(){var c;c="";0===$.trim(a.element(b,
".ge-contactfullname-field").val()).length&&(c+="<li>First Name is required.</li>");a.toBoolean(s.is_addressline1mandatory)&&0===$.trim(a.element(b,".ge-contactaddressline1-field").val()).length&&(c+="<li>Address Line 1 is required.</li>");0===$.trim(a.element(b,".ge-contactsuburb-field").val()).length&&(c+="<li>Suburb is required.</li>");0===$.trim(a.element(b,".ge-contactstate-field").val()).length&&(c+="<li>State is required.</li>");0===$.trim(a.element(b,".ge-contactpostcode-field").val()).length&&
(c+="<li>Postcode is required.</li>");0===$.trim(a.element(b,".ge-contactcountry-field").val()).length&&(c+="<li>Country is required.</li>");0===$.trim(a.element(b,".ge-contactphonenumber-field").val()).length&&(c+="<li>Phone Number is required.</li>");0===$.trim(a.element(b,".ge-contactemailaddress-field").val()).length&&(c+="<li>Email Address is required.</li>");0<c.length?a.dialogAlertScroll("<ul>"+c+"</ul>",doNothing):(a.element(b,".gb-panel-registrationtype").hide(),a.element(b,".gb-panel-account").hide(),
a.element(b,".gb-panel-venue").hide(),a.element(b,".gb-panel-contact").hide(),a.element(b,".gb-panel-contact2").show(),a.element(b,".gb-panel-about").hide(),a.element(b,".ge-contactfullname-2-field").focus(),l("ContactPanel2"))};this.ContactPrevButton_onClick=function(){v()};this.Contact2PrevButton_onClick=function(){q()};this.RegisterButton_onClick=function(){var b="",b="";0<b.length?a.dialogAlertScroll("<ul>"+b+"</ul>",doNothing):H()};this.RegistrationTypeNextButton_onClick=function(){var c;c="";
a.element(b,".ge-registrationtype-option").is(":checked")||(c+="<li>You must choose a profile to proceed.</li>");0<c.length?a.dialogAlertScroll("<ul>"+c+"</ul>",doNothing):(k?a.element(b,".ge-fullname-field").val(""):a.element(b,".ge-accountname-field").val(""),n(),p())};this.VenueNextButton_onClick=function(){var c;c="";0===$.trim(a.element(b,".ge-venuename-field").val()).length&&(c+="<li>Venue Name is required.</li>");a.toBoolean(s.is_addressline1mandatory)&&0===$.trim(a.element(b,".ge-venueaddressline1-field").val()).length&&
(c+="<li>Address Line 1 is required.</li>");0===$.trim(a.element(b,".ge-venuesuburb-field").val()).length&&(c+="<li>Suburb is required.</li>");0===$.trim(a.element(b,".ge-venuestate-field").val()).length&&(c+="<li>State is required.</li>");0===$.trim(a.element(b,".ge-venuepostcode-field").val()).length&&(c+="<li>Postcode is required.</li>");0===$.trim(a.element(b,".ge-venuecountry-field").val()).length&&(c+="<li>Country is required.</li>");0===$.trim(a.element(b,".ge-venuephonenumber-field").val()).length&&
(c+="<li>Phone Number is required.</li>");0===$.trim(a.element(b,".ge-venueemailaddress-field").val()).length&&(c+="<li>Email Address is required.</li>");0<c.length?a.dialogAlertScroll("<ul>"+c+"</ul>",doNothing):q()};this.VenuePrevButton_onClick=function(){p()};this.TabEnd_onFocus=function(){a.element(b,".ge-registrationtype-option1").focus()};this.TabStart_onFocus=function(){a.element(b,".ge-register-button").focus()}};
