// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmRecordChooser(p,q,r){function l(a,f,d,e){b.element(c,"."+a).text("");!1===b.hasCapability("regionscroll")&&(e="");b.element(c,".ge-status-panel").append('<div class="gs-canvastext gs-cell-xxx '+a+'" style="top:'+d+"px; left:"+f+'px">'+e+"</div>")}function m(){e=new jDock(b,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:s,tiles:t});e.render(c,".ge-button-panel");e.disableButtons("SelectButton","disabled")}function n(a,d,e){a={cbOnSelection:f.Grid_onDblClick,cbOnSelectionChange:f.Grid_onSelectionChange,
columns:d,filterType:"all",parameters:[],extraParameters:[],returnFields:h,webServiceFunction:a};void 0!==e&&0<e.length&&(a.parameters=$.merge(a.parameters,e));b.element(c,".panelHome").hide();b.element(c,".ge-entity-grid").show();m();g=new jDatatableRenderer(b,a);g.render(c,".ge-entity-grid")}var b=p,f=this,c=q,d=r,k=[],h=["id"],g;void 0!==d.resultfields&&0<d.resultfields.length&&(h=d.resultfields);var e,s=[{location:"root",title:"Home",layout:[["CloseButton","SelectButton"]]}],t=[{id:"-",caption:"",
classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"",permissions:[],action:function(){f.FormClose_onClick()},actionData:null,tip:"Click here to close the select form.",type:"toolbarbutton"},{id:"SelectButton",caption:"Select",classes:"disabled",permissions:[],action:function(){f.SelectButton_onClick()},actionData:null,tip:"Click here to select.",type:"toolbarbutton"}];this.Form_onBroadcast=function(a,d,f){"hash"===a&&"change"===d&&b.closeForm(c)};
this.Form_onClick=function(){b.setFormFocus(f,c)};this.Form_onDblClick=function(){b.formToFront(c)};this.Form_onFocus=function(a){void 0!==a&&null!==a&&d.resultfields!==a.resultfields&&(d=a,void 0!==d.resultfields&&0<d.resultfields.length&&(h=d.resultfields));b.unbindEvents(c,"ge-tab-start,ge-tab-end");b.bindEvent(f,c,".ge-tab-start","TabStart","onFocus");b.bindEvent(f,c,".ge-tab-end","TabEnd","onFocus");b.setTabOrder(c,"ge-tab-start,CloseButton,SelectButton,grdEntities,grdEntitiesEOG,ge-tab-end")};
this.Form_onLoad=function(){var a=d.title;b.element(c,".ge-form-title").text(a);var a=b.getViewPort().width,e=b.getViewPort().height;b.resizeAndRepositionForm(c,0.1*e,0.1*a,0.8*e,0.8*a);m();b.unbindEvents(c,"gb-form-close,gb-form,gb-formtitle-inner-panel");b.bindEvent(f,c,".gb-form-close","FormClose","onClick");b.bindEvent(f,c,".gb-form","Form","onClick");b.bindEvent(f,c,".gb-form","Form","onDblClick");b.bindEvent(f,c,".gb-formtitle-inner-panel","FormTitle","onClick");b.unbindEvents(c,"ge-search-input,ge-search-button");
b.bindEvent(f,c,".ge-search-button","btnSearch","onClick");b.bindEvent(f,c,".ge-search-input","SearchField","onEnterKey");a=[];d.mode===LIST_FILEFORMATINSTALLABLE?a=[{id:"rownum",name:"#",field:"rownum",behavior:"select",cssClass:"gs-gridcell-selection",width:40,cannotTriggerInsert:!0,resizable:!1,selectable:!1},{id:"code",name:"Code",field:"code",sortable:!0,editor:Slick.Editors.Text},{id:"description",name:"Description",field:"description",sortable:!0,editor:Slick.Editors.Text},{id:"default",name:"Default",
field:"default",sortable:!0,editor:Slick.Editors.Text},{id:"enabled",name:"Enabled",field:"enabled",sortable:!0,editor:Slick.Editors.Text}]:d.mode===LIST_PROFILEINSTALLABLE&&(a=[{id:"rownum",name:"#",field:"rownum",behavior:"select",cssClass:"gs-gridcell-selection",width:40,cannotTriggerInsert:!0,resizable:!1,selectable:!1},{id:"description",name:"Description",field:"description",sortable:!0,editor:Slick.Editors.Text},{id:"admin",name:"Admin",field:"admin",sortable:!0,editor:Slick.Editors.Text},{id:"default",
name:"Default",field:"default",sortable:!0,editor:Slick.Editors.Text},{id:"enabled",name:"Enabled",field:"enabled",sortable:!0,editor:Slick.Editors.Text}]);d.mode===LIST_FILEFORMATINSTALLABLE?n("import_fileformatinstallablelist",a):d.mode===LIST_PROFILEINSTALLABLE&&n("security_profilesinstallablelist",a);b.hasCapability("mobile")||b.element(c,".ge-search-input").focus()};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(c)};this.Form_onResize=function(a,
d){b.element(c,".ge-entity-grid").width(a-20+"px");b.element(c,".ge-entity-grid").height(d-150+"px");b.element(c,".ge-entity-grid");g.resize()};this.FormResult=function(){return k};this.FormClose_onClick=function(){k=[];b.closeForm(c)};this.Grid_onSelectionChange=function(a){void 0!==e&&null!==e&&(0<a.length?e.enableButtons("SelectButton","disabled"):e.disableButtons("SelectButton","disabled"))};this.Grid_onDblClick=function(a){f.SelectButton_onClick()};this.Grid_onFetchData=function(a){void 0===
a||null===a||0===a.length?l("divStatus",5,476,"No records shown."):l("divStatus",5,476,"Showing "+a.length+" of "+a[0].recordcount+" records&nbsp;(max. "+a[0].limited+" records are shown at a time).")};this.SelectButton_onClick=function(){k=g.getSelection();b.closeForm(c)};this.btnSearch_onClick=function(){var a=b.element(c,".ge-search-input").val();g.search(a)};this.SearchField_onEnterKey=function(a){a=b.element(a).val();g.search(a)};this.TabEnd_onFocus=function(){b.element(c,".CloseButton").focus()};
this.TabStart_onFocus=function(){b.element(c,".SelectButton").focus()}};
