// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmTaskbarExtend(w,x,A){function y(){e=e=[{id:"-",caption:"",classes:"",permissions:[],action:"",tip:"",type:"blank"},{id:"HamburgerMenu",caption:"",classes:g,permissions:[],action:d.Burger_onClick,tip:"Click here to open the menu.",type:"hamburgermenu"},{id:"CloseTabMenuItem",caption:'<i class="glyphicon glyphicon-log-out"></i>&nbsp;Close',classes:"gs-transparent-background-colour gs-menuitem gs-from768",permissions:function(){return!a.toBoolean(a.getProperty("public"))},action:m,tip:"Click here to close this window.",
reversetip:!0,type:"menuitem"},{id:"MyMessagesMenuItem",caption:'<i class="glyphicon glyphicon glyphicon-envelope"></i>&nbsp;My Messages&nbsp;<span class="ge-unread-badge badge gb-hidden"></span>',classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&hasPermission(["VW_ACCOUNT"])&&hasPermission(["VW_INTERNALMESSAGE"])},action:n,tip:"Click here to see your messages.",type:"menuitem"},{id:"SearchMenuItem",caption:'<div class="input-group" style="width:150px"><input type="text" class="form-control ge-search-input" placeholder="Search..." style="xwidth:100px"/><span class="input-group-btn"><button class="btn btn-default ge-searchclear-button" type="button">X</button></span></div>',
classes:"gs-transparent-background-colour gs-menuitem",permissions:[],action:doNothing,tip:"Search",type:"menuitem"},{id:"FormSupportMenuItem",caption:'<i class="glyphicon glyphicon-earphone"></i>&nbsp;Support',classes:"gs-transparent-background-colour gs-menuitem",permissions:[],action:p,actionData:APP_SUPPORT,tip:"Click here for "+APP_SHORT_NAME+" support.",reversetip:!0,type:"menuitem"},{id:"CloseTabMenuItem768",caption:'<i class="glyphicon glyphicon-log-out"></i>&nbsp;Close',classes:"gs-transparent-background-colour gs-menuitem gs-to768",
permissions:function(){return!a.toBoolean(a.getProperty("public"))},action:m,tip:"Click here to close this window.",type:"menuitem"},{id:"HamburgerMenu768",caption:"",classes:g,permissions:[],action:d.Burger_onClick,tip:"Click here to open the menu.",type:"hamburgermenu"},{id:"MyMessagesMenuItem768",caption:'<i class="glyphicon glyphicon glyphicon-envelope"></i>&nbsp;My Messages&nbsp;<span class="ge-unread-badge badge gb-hidden"></span>',classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&
hasPermission(["VW_ACCOUNT"])&&hasPermission(["VW_INTERNALMESSAGE"])},action:n,tip:"Click here to see your messages.",type:"menuitem"},{id:"SearchMenuItem768",caption:'<div class="input-group" style="width:150px"><input type="text" class="form-control ge-search-input" placeholder="Search..." style="xwidth:100px"/><span class="input-group-btn"><button class="btn btn-default ge-searchclear-button" type="button">X</button></span></div>',classes:"gs-transparent-background-colour gs-menuitem",permissions:[],
action:doNothing,tip:"Search",type:"menuitem"},{id:"FormSupportMenuItem768",caption:'<i class="glyphicon glyphicon-earphone"></i>&nbsp;Support',classes:"gs-transparent-background-colour gs-menuitem",permissions:[],action:p,actionData:APP_SUPPORT,tip:"Click here for "+APP_SHORT_NAME+" support.",type:"menuitem"}];q=new jDock(a,{map:h,tiles:e,alwayshidemorebutton:!0});r=new jDock(a,{map:h,tiles:e,mode:"horizontalmenu",alwayshidemorebutton:!0});s=new jDock(a,{map:h,tiles:e,mode:"horizontalmenu",alwayshidemorebutton:!0})}
function m(){a.dialogConfirm("Are you sure you wish to close this window?\n\nPlease be sure you have saved your data before continuing.",function(){a.setUnloadPrompt(!1);a.closeTab()})}function n(){a.showForm("msg.frmMyMessages")}function p(a){window.open(a,"_blank")}function t(){var c=a.toBoolean(a.getProperty("public"));y();q.render(b,".ge-burger-panel","hamburger");r.render(b,".ge-menu-panel","menu");s.render(b,".ge-signup-panel","signup");a.showElement(b,".ge-burger-panel768",!c)}function z(c){c=
c[0];0<c.unreadcount?(a.element(b,".ge-unread-badge").show(),a.element(b,".ge-unread-badge").text(c.unreadcount)):a.element(b,".ge-unread-badge").hide()}function u(){var b=a.ajaxRequestCreate("msg_messagestatsfetch",[]);a.ajaxCall(URL_WEBSERVICE,b,z,a.ajaxError)}var a=w,d=this,b=x,q,r,s,f=a.getProperty("loginas"),k=a.getProperty("clientname"),l=a.getProperty("username"),v="";a.hasCapability("mobile")||(v="fms.frmConnote");var h=[{location:"hamburger",title:"Home",layout:[["HamburgerMenu","SearchMenuItem",
"MyMessagesMenuItem"]]},{location:"hamburger768",title:"Home",layout:[["HamburgerMenu768"]]},{location:"menu",title:"Home",layout:[["SearchMenuItem768","MyMessagesMenuItem768","FormSupportMenuItem768","CloseTabMenuItem768"]]},{location:"signup",title:"Home",layout:[["FormSupportMenuItem","CloseTabMenuItem"]]}],e=[],g="ge-burgermenu gi-burgermenu gs-burgermenu";a.toBoolean(a.getProperty("public"))&&(g="ge-burgermenu gi-burgermenu gs-burgermenu hidden");this.Form_allowMultipleInstances=function(){return!1};
this.Burger_onClick=function(){a.toggleMenu()};this.Form_canClose=function(){return!1};this.Form_onBroadcast=function(c,d){"core"===c&&"loginFormSuccess"===d&&(t(),a.toBoolean(a.getProperty("public"))?(a.hideMenu(),a.destroyMenu(b)):(a.createMenu(b),a.toBoolean(a.getProperty("isindividual"))?a.hideMenu():a.showMenu()));"messages"===c&&"messagecount"===d&&u()};this.Form_onClick=function(){a.formToFront(b)};this.Form_onLoad=function(){if("Public"!==f){var c="";a.element(b,".ge-loginas").removeClass("gb-hidden");
"System"===f?(a.element(b,".ge-loginas").css("background-color","red"),a.element(b,".ge-loginas").css("color","yellow"),c="You are logged in as: "+f+" - "+k+" - "+l):"Client"===f?(a.element(b,".ge-loginas").css("background-color","blue"),a.element(b,".ge-loginas").css("color","yellow"),c="You are logged in as: "+f+" - "+k+" - "+l):(a.element(b,".ge-loginas").css("background-color","green"),a.element(b,".ge-loginas").css("color","yellow"),c="You are logged in as: "+k+" - "+l);a.element(b,".ge-loginas").html(c)}a.registerTaskbar(d,
b);a.element(b,".ge-taskbar").show();a.hasCapability("timers")&&(a.hasCapability("mobile")?a.createTimer(a.checkServerEvents,TIMER_SERVEREVENTS_FREQUENCY_MOB,!0):a.createTimer(a.checkServerEvents,TIMER_SERVEREVENTS_FREQUENCY,!0),a.registerServerEvent("messages",b),a.enableServerEventQueue("messages"),a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerbroadcaster",[{name:"eventqueue",value:"messages"}]),doNothing,doNothing),a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerlistener",
[{name:"eventqueue",value:"messages"}]),doNothing,doNothing));a.element(b,".fldFormTitle").text("");a.unbindEvents(b,"gb-form");a.bindEvent(d,b,".gb-form","Form","onClick");t();u();a.unbindEvents(b,"ge-search-input,ge-searchclear-button");a.bindEvent(d,b,".ge-search-input","SearchField","onEnterKey");a.bindEvent(d,b,".ge-searchclear-button","SearchClearButton","onClick")};this.Form_onPermissionCheck=function(){return!0};this.SearchField_onEnterKey=function(b){b=a.element(b).val();0<$.trim(b.length)&&
a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"CONNOTE",formentitydescription:"Consignment",formcode:"CONNOTE",mode:"renderer",title:"Consignments (All)",component:v,searchkeyword:b,fixedfilter:[{field:"is_deleted",value:"N"}]})};this.SearchClearButton_onClick=function(){a.element(b,".ge-search-input").val("");a.element(b,".ge-search-input").focus()}};
