// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmThemes(k,l,m){function n(){var f=a.getViewPort().width,c=a.getViewPort().height;a.resizeAndRepositionForm(b,0.1*c,0.1*f,0.8*c,0.8*f);a.element(b,".ge-form-title").text("Themes - selection")}function g(){var b=a.getProperty("selectedtheme"),b=a.ajaxRequestCreate("core_themesave",[{name:"themecode",value:b}]);a.ajaxCall(URL_WEBSERVICE,b,c.themeSaved,a.ajaxError)}function p(b,c){a.dialogConfirm("Would you like to choose the '"+b+"' theme?<br><br>Please be sure you have saved your data before continuing.",
function(){var b="";0<c.length&&(b=0<b.length?b+("&theme="+encodeURIComponent(c)):"theme="+encodeURIComponent(c));a.reboot(b,"frmThemes")})}function d(c){(e=c)?(a.element(b,".SaveButton").addClass("gs-glow-dirty"),a.element(b,".SaveButton").removeClass("gs-darkblue-background-colour"),a.element(b,".SaveButton").addClass("gs-red-background-colour")):(a.element(b,".SaveButton").removeClass("gs-glow-dirty"),a.element(b,".SaveButton").removeClass("gs-red-background-colour"),a.element(b,".SaveButton").addClass("gs-darkblue-background-colour"))}
var a=k,c=this,b=l,e=!1,h,q=[{location:"root",title:"Home",layout:[["CloseButton","SaveButton"]]}],r=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){c.FormClose_onClick()},actionData:null,tip:"Click here to close the theme selection form.",type:"toolbarbutton"},{id:"SaveButton",caption:"Save",classes:"gs-darkblue-background-colour gs-glow-focusborder",
permissions:[],action:function(){c.SaveButton_onClick()},actionData:null,tip:"Click here to save the chosen theme.",type:"toolbarbutton"}];this.themeSaved=function(a){d(!1)};this.Form_allowMultipleInstances=function(){return!1};this.Form_isDirty=function(){return e};this.Form_onClick=function(){a.setFormFocus(c,b)};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onFocus=function(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(c,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(c,
b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,CloseButton,SaveButton,ge-tab-end")};this.Form_onLoad=function(){a.toBoolean(m.onstartup)&&(hasPermission(["CHG_THEME"])&&a.hasCapability("themes")&&0<a.getProperty("theme").length&&a.getProperty("selectedtheme")!=a.getProperty("theme")?(d(!0),a.dialogAlert("Your theme is now set to '"+a.getProperty("selectedtheme")+"'.<br><br>Remember to save your current theme.",function(){})):a.closeForm(b));n();a.unbindEvents(b,"gb-form-close,gb-form,gb-formtitle-inner-panel,ge-default-theme");
a.bindEvent(c,b,".gb-form-close","FormClose","onClick");a.bindEvent(c,b,".gb-form","Form","onClick");a.bindEvent(c,b,".gb-form","Form","onDblClick");a.bindEvent(c,b,".gb-formtitle-inner-panel","FormTitle","onClick");a.bindEvent(c,b,".ge-default-theme","DefaultTheme","onClick");h=new jDock(a,{alwaysvisiblebuttoncount:2,map:q,tiles:r});h.render(b,".ge-button-panel");d(e)};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(c,d){var e=d-150;a.element(b,".ge-panel-content").height(e+
"px");a.element(b,".ge-panel-overflow").height("100%");a.element(b,".ge-panel-overflow").css("overflow-y","auto")};this.FormTitle_onClick=function(){a.formToFront(b)};this.FormClose_onClick=function(){a.closeForm(b)};this.SaveButton_onClick=function(){if(c.Form_isDirty())try{g()}catch(e){d(!0)}else g(),a.closeForm(b)};this.DefaultTheme_onClick=function(){p("Default",DEFAULT_THEME)};this.TabEnd_onFocus=function(){a.element(b,".CloseButton").focus()};this.TabStart_onFocus=function(){a.element(b,".SaveButton").focus()}}
;
