// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmTaskbar(z,A,G){function B(){e=e=[{id:"-",caption:"",classes:"",permissions:[],action:"",tip:"",type:"blank"},{id:"HamburgerMenu",caption:"",classes:h,permissions:[],action:d.Burger_onClick,tip:"Click here to open the menu.",type:"hamburgermenu"},{id:"MyMessagesMenuItem",caption:'<i class="glyphicon glyphicon glyphicon-envelope"></i>&nbsp;My Messages&nbsp;<span class="ge-unread-badge badge gb-hidden"></span>',classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&
hasPermission(["VW_ACCOUNT"])&&hasPermission(["VW_INTERNALMESSAGE"])},action:n,tip:"Click here to see your messages.",type:"menuitem"},{id:"SearchMenuItem",caption:'<div class="input-group" style="width:150px"><input type="text" class="form-control ge-search-input" placeholder="Search..." style="xwidth:100px"/><span class="input-group-btn"><button class="btn btn-default ge-searchclear-button" type="button">X</button></span></div>',classes:"gs-transparent-background-colour gs-menuitem",permissions:["DISABLED"],
action:doNothing,tip:"Search",type:"menuitem"},{id:"FormSupportMenuItem",caption:'<i class="glyphicon glyphicon-earphone"></i>&nbsp;Support',classes:"gs-transparent-background-colour gs-menuitem",permissions:[],action:p,actionData:APP_SUPPORT,tip:"Click here for "+APP_SHORT_NAME+" support.",reversetip:!0,type:"menuitem"},{id:"JoinMenuItem",caption:"Register",classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return a.toBoolean(a.getProperty("public"))&&"TRUE"===ENABLE_REGISTER&&
"TRUE"===CLIENT_ALLOWJOIN},action:q,tip:"Click here to register.",type:"menuitem",reversetip:!0},{id:"LoginMenuItem",caption:"Log In",classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return a.toBoolean(a.getProperty("public"))},action:r,tip:"Click here to log in.",reversetip:!0,type:"menuitem"},{id:"LogoutMenuItem",caption:'<i class="glyphicon glyphicon-log-out"></i>&nbsp;Logout ('+f+")",classes:"gs-transparent-background-colour gs-menuitem gs-from768",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&
hasPermission(["VW_LOGOUT"])},action:s,tip:"Click here to logout.",reversetip:!0,type:"menuitem"},{id:"ReturnMenuItem",caption:'<i class="glyphicon glyphicon-log-out"></i>&nbsp;Return to Client',classes:"gs-transparent-background-colour gs-menuitem gs-from768",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&hasPermission(["VW_RETURN"])},action:t,tip:"Click here to return to your previous client.",reversetip:!0,type:"menuitem"},{id:"HamburgerMenu768",caption:"",classes:h,permissions:[],
action:d.Burger_onClick,tip:"Click here to open the menu.",type:"hamburgermenu"},{id:"MyMessagesMenuItem768",caption:'<i class="glyphicon glyphicon glyphicon-envelope"></i>&nbsp;My Messages&nbsp;<span class="ge-unread-badge badge gb-hidden"></span>',classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&hasPermission(["VW_ACCOUNT"])&&hasPermission(["VW_INTERNALMESSAGE"])},action:n,tip:"Click here to see your messages.",type:"menuitem"},
{id:"SearchMenuItem768",caption:'<div class="input-group" style="width:150px"><input type="text" class="form-control ge-search-input" placeholder="Search..." style="xwidth:100px"/><span class="input-group-btn"><button class="btn btn-default ge-searchclear-button" type="button">X</button></span></div>',classes:"gs-transparent-background-colour gs-menuitem",permissions:["DISABLED"],action:doNothing,tip:"Search",type:"menuitem"},{id:"FormSupportMenuItem768",caption:'<i class="glyphicon glyphicon-earphone"></i>&nbsp;Support',
classes:"gs-transparent-background-colour gs-menuitem",permissions:[],action:p,actionData:APP_SUPPORT,tip:"Click here for "+APP_SHORT_NAME+" support.",type:"menuitem"},{id:"JoinMenuItem768",caption:"Register",classes:"gs-transparent-background-colour gs-menuitem",permissions:function(){return a.toBoolean(a.getProperty("public"))&&"TRUE"===ENABLE_REGISTER&&"TRUE"===CLIENT_ALLOWJOIN},action:q,tip:"Click here to register.",type:"menuitem"},{id:"LoginMenuItem768",caption:"Log In",classes:"gs-transparent-background-colour gs-menuitem",
permissions:function(){return a.toBoolean(a.getProperty("public"))},action:r,tip:"Click here to log in.",type:"menuitem"},{id:"LogoutMenuItem768",caption:'<i class="glyphicon glyphicon-log-out"></i>&nbsp;Logout ('+f+")",classes:"gs-transparent-background-colour gs-menuitem gs-to768",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&hasPermission(["VW_LOGOUT"])},action:s,tip:"Click here to logout.",type:"menuitem"},{id:"ReturnMenuItem768",caption:'<i class="glyphicon glyphicon-log-out"></i>&nbsp;Return to Client',
classes:"gs-transparent-background-colour gs-menuitem gs-to768",permissions:function(){return!a.toBoolean(a.getProperty("public"))&&hasPermission(["VW_RETURN"])},action:t,tip:"Click here to return to your previous client.",type:"menuitem"}];u=new jDock(a,{map:k,tiles:e,alwayshidemorebutton:!0});v=new jDock(a,{map:k,tiles:e,mode:"horizontalmenu",alwayshidemorebutton:!0});l=new jDock(a,{map:k,tiles:e,mode:"horizontalmenu",alwayshidemorebutton:!0})}function r(){a.gotoURL("#!core.frmLogin")}function n(){a.showForm("msg.frmMyMessages")}
function p(a){window.open(a,"_blank")}function w(){a.toBoolean(a.getProperty("public"));B();u.render(b,".ge-burger-panel","hamburger");v.render(b,".ge-menu-panel","menu");l.render(b,".ge-signup-panel","signup");l.render(b,".ge-signup-panel768","signup768")}function C(){if("Public"!==g){var c="";a.element(b,".ge-loginas").removeClass("gb-hidden");"System"===g?(a.element(b,".ge-loginas").css("background-color","red"),a.element(b,".ge-loginas").css("color","yellow"),c="You are logged in as: "+g+" - "+
m+" - "+f):"Client"===g?(a.element(b,".ge-loginas").css("background-color","blue"),a.element(b,".ge-loginas").css("color","yellow"),c="You are logged in as: "+g+" - "+m+" - "+f):(a.element(b,".ge-loginas").css("background-color","green"),a.element(b,".ge-loginas").css("color","yellow"),c="You are logged in as: "+m+" - "+f);a.element(b,".ge-loginas").html(c)}a.registerTaskbar(d,b);a.element(b,".ge-taskbar").show();a.hasCapability("timers")&&(a.hasCapability("mobile")?a.createTimer(a.checkServerEvents,
TIMER_SERVEREVENTS_FREQUENCY_MOB,!0):a.createTimer(a.checkServerEvents,TIMER_SERVEREVENTS_FREQUENCY,!0),a.registerServerEvent("messages",b),a.enableServerEventQueue("messages"),a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerbroadcaster",[{name:"eventqueue",value:"messages"}]),doNothing,doNothing),a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerlistener",[{name:"eventqueue",value:"messages"}]),doNothing,doNothing));a.element(b,".fldFormTitle").text("");a.unbindEvents(b,"gb-form");
a.bindEvent(d,b,".gb-form","Form","onClick");w();x();a.unbindEvents(b,"ge-search-input,ge-searchclear-button");a.bindEvent(d,b,".ge-search-input","SearchField","onEnterKey");a.bindEvent(d,b,".ge-searchclear-button","SearchClearButton","onClick");"TRUE"===ENABLE_DEVELOPER_NOTES&&a.dialogAlertScroll(DEVELOPER_NOTES,function(){})}function q(){a.gotoURL("#!core.frmRegister")}function D(b){a.logout("","frmTaskbar")}function E(b){a.clientReturn("","frmTaskbar")}function F(c){c=c[0];0<c.unreadcount?(a.element(b,
".ge-unread-badge").show(),a.element(b,".ge-unread-badge").text(c.unreadcount)):a.element(b,".ge-unread-badge").hide()}function x(){var b=a.ajaxRequestCreate("msg_messagestatsfetch",[]);a.ajaxCall(URL_WEBSERVICE,b,F,a.ajaxError)}function s(){a.dialogConfirm("Are you sure you wish to logout?<br><br>Please be sure you have saved your data before continuing.",function(){var b=a.ajaxRequestCreate("public_logout",[]);a.ajaxCall(URL_WEBSERVICE,b,D,a.ajaxError)})}function t(){a.dialogConfirm("Are you sure you wish to return to your previous client?<br><br>Please be sure you have saved your data before continuing.",
function(){var b=a.ajaxRequestCreate("public_return",[]);a.ajaxCall(URL_WEBSERVICE,b,E,a.ajaxError)})}var a=z,d=this,b=A,u,v,l,g=a.getProperty("loginas"),m=a.getProperty("clientname"),f=a.getProperty("username"),y="";a.hasCapability("mobile")||(y="fms.frmConnote");var k=[{location:"hamburger",title:"Home",layout:[["HamburgerMenu","SearchMenuItem","MyMessagesMenuItem"]]},{location:"menu",title:"Home",layout:[["SearchMenuItem768","MyMessagesMenuItem768","FormSupportMenuItem768","LogoutMenuItem768",
"ReturnMenuItem768"]]},{location:"signup",title:"Home",layout:[["FormSupportMenuItem","JoinMenuItem","LoginMenuItem","LogoutMenuItem","ReturnMenuItem"]]},{location:"signup768",title:"Home",layout:[["HamburgerMenu768"]]}],e=[],h="ge-burgermenu gi-burgermenu gs-burgermenu";a.toBoolean(a.getProperty("public"))&&(h="ge-burgermenu gi-burgermenu gs-burgermenu hidden");this.Form_allowMultipleInstances=function(){return!1};this.Burger_onClick=function(){a.toggleMenu()};this.Form_canClose=function(){return!1};
this.Form_onBroadcast=function(c,d,e){"core"===c&&"loginFormSuccess"===d&&(w(),a.toBoolean(a.getProperty("public"))?(a.hideMenu(),a.destroyMenu(b)):(a.createMenu(b),a.toBoolean(a.getProperty("isindividual"))?a.hideMenu():a.showMenu()));"messages"===c&&"messagecount"===d&&x()};this.Form_onClick=function(){a.formToFront(b)};this.Form_onLoad=function(){C()};this.Form_onPermissionCheck=function(){return!0};this.SearchField_onEnterKey=function(b){b=a.element(b).val();0<$.trim(b.length)&&a.showForm("entity.frmLister",
{type:"form",entity:"systemform",formentity:"CONNOTE",formentitydescription:"Consignment",formcode:"CONNOTE",mode:"renderer",title:"Consignments (All)",component:y,searchkeyword:b,fixedfilter:[{field:"is_deleted",value:"N"}]})};this.SearchClearButton_onClick=function(){a.element(b,".ge-search-input").val("");a.element(b,".ge-search-input").focus()}};
