// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmUpload(J,K,A){function L(){doNothing()}function D(a,b){var d="";return d=0<=a&&1024>a?a+" B":1024<=a&&1048576>a?(a/1024).toFixed(b)+" KB":1048576<=a&&1073741824>a?(a/1048576).toFixed(b)+" MB":1073741824<=a&&1099511627776>a?(a/1073741824).toFixed(b)+" GB":1099511627776<=a?(a/1099511627776).toFixed(b)+" TB":a+" B"}function h(){a.toBoolean(r);0<e.length&&0<l.length?(s(!0),t=!0):(s(!1),t=!1)}function M(a){var b;processArray(u,function(d){if(d.id==a)return b=d,!0});return b}function N(a){var b;
processArray(u,function(d){if(d.code==a)return b=d,!0});return b}function B(c){a.element(b,".ge-progressallbar .progress-bar").attr("aria-valuenow",c);a.element(b,".ge-progressallbar .progress-bar").css("width",c+"%");a.element(b,".ge-progressallbar .progress-bar").html(c+"%")}function s(a){(O=a)?(m.enableButtons("StartUploadButton,RemoveAllFilesButton","btn-primary"),m.enableButtons("CancelUploadButton","btn-danger")):(m.disableButtons("StartUploadButton,RemoveAllFilesButton","btn-primary"),m.disableButtons("CancelUploadButton",
"btn-danger"))}function n(c,d,e){c?a.element(b,".ge-progressallbar").removeClass("gb-hidden"):a.element(b,".ge-progressallbar").addClass("gb-hidden");d?(a.element(b,".ge-progressalltext").removeClass("gb-hidden"),a.element(b,".ge-progressalltext").html(e)):(a.element(b,".ge-progressalltext").addClass("gb-hidden"),a.element(b,".ge-progressalltext").html(""))}function x(){t=!1;e=[];y=0;a.element(b,".file").remove();h()}function p(){var c="";"GENERIC"==f?(c="Import Files",a.element(b,".ge-function-field").val("import_generic")):
"SUBURBS"==f?(c="Import Suburbs",a.element(b,".ge-function-field").val("import_suburbs")):"IMAGES"==f?(c="Import Images",a.element(b,".ge-function-field").val("import_images")):"ADDRESS"==f?(c="Import Addresses",a.element(b,".ge-function-field").val("import_address")):"RATESCHEDULEBUY"==f?(c="Import Buy Rate Schedules",a.element(b,".ge-function-field").val("import_rateschedulebuy")):"RATESCHEDULESELL"==f?(c="Import Sell Rate Schedules",a.element(b,".ge-function-field").val("import_rateschedulesell")):
"SURCHARGESCHEDULEBUY"==f?(c="Import Buy Surcharge Schedules",a.element(b,".ge-function-field").val("import_surchargeschedulebuy")):"SURCHARGESCHEDULESELL"==f?(c="Import Sell Surcharge Schedules",a.element(b,".ge-function-field").val("import_surchargeschedulesell")):"ZONESCHEDULEBUY"==f?(c="Import Buy Zone Schedules",a.element(b,".ge-function-field").val("import_zoneschedulebuy")):"ZONESCHEDULESELL"==f&&(c="Import Sell Zone Schedules",a.element(b,".ge-function-field").val("import_zoneschedulesell"));
a.element(b,".ge-functionid-field").val(z);a.element(b,".ge-form-title").text(c)}function P(){processArray(u,function(c){a.element(b,".ge-filetypes-list").append('<li><a class="ge-filetype-option gb-button" data-id="'+htmlEncode(c.id)+'">'+htmlEncode(c.description)+"</a></li>")});a.populateList(b,"ge-filetypedropdown-field",u,!0,!1);var c=N(f);void 0!==c&&(l=c.id,r=c.definable,a.element(b,".ge-filetypeselected-label").html(htmlEncode(c.description)),a.toBoolean(r)?(a.element(b,".ge-fileformatdropdown").show(),
E(),p(),h()):(a.element(b,".ge-fileformatdropdown").hide(),doNothing()))}function Q(c){k=c;a.populateList(b,"ge-fileformatdropdown-field",k,!0,!1);0<k.length?(z=k[0].id,a.element(b,".ge-fileformatselected-label").html(k[0].description)):a.element(b,".ge-fileformatselected-label").html("File Format");p();h();a.unbindEvents(b,"ge-fileformatdropdown-field-option");a.bindEvent(d,b,".ge-fileformatdropdown-field-option","FileFormatOption","onClick")}function R(c){u=c;c=a.element(b,".ge-dropzone");a.element(b,
".ge-uploader");a.element(b,".ge-uploader").fileupload();a.element(b,".ge-uploader").fileupload("option",{url:"ws/upload.php",disableImageResize:/Android(?!.*Chrome)|Opera/.test(window.navigator.userAgent),maxFileSize:MAXUPLOADFILESIZE,acceptFileTypes:/(\.|\/)(gif|jpe?g|png)$/i,dropZone:c});p();a.element(b,".ge-flags-field").val(v);a.element(b,".ge-securitytoken-field").val(SECURITY_TOKEN);a.element(b,".ge-clientversion-field").val(CLIENT_VERSION);a.element(b,".ge-callerid-field").val(CALLERID_PUBLIC);
a.element(b,".ge-maxfilesize-label").html("Maximum file size allowed for upload: "+D(MAXUPLOADFILESIZE));P();F();s(!1)}function S(c){n(!1,!0,"<font color='green'><b>Files(s) successfully uploaded and processed</b></font>");x();G=c;H&&a.closeForm(b)}function E(){var b=a.ajaxRequestCreate("import_fileformatsfetchbyfiletypeid",[{name:"filetype_id",value:l}]);a.ajaxCall(URL_WEBSERVICE,b,Q,d.asyncError)}function F(){a.unbindEvents(b,"ge-uploader,ge-close-button,ge-filetypedropdown-field-option,ge-removefile-button,ge-addfilesupload-button");
a.bindEvent(d,b,".ge-uploader","Uploader","onFileUploadAdd");a.bindEvent(d,b,".ge-uploader","Uploader","onFileUploadDone");a.bindEvent(d,b,".ge-uploader","Uploader","onFileUploadSend");a.bindEvent(d,b,".ge-uploader","Uploader","onFileUploadProgress");a.bindEvent(d,b,".ge-uploader","Uploader","onFileUploadProgressAll");a.bindEvent(d,b,".ge-close-button","CloseButton","onClick");a.bindEvent(d,b,".ge-removefile-button","RemoveFileButton","onClick");a.bindEvent(d,b,".ge-addfilesupload-button","AddFilesButton",
"onClick");a.bindEvent(d,b,".ge-filetypedropdown-field-option","FileTypeOption","onClick")}var a=J,d=this,b=K,f=A.mode,f=void 0===f?"GENERIC":f.toUpperCase(),v=A.flags;void 0===v&&(v="");var r="N";v.split(" ").indexOf("nobatch");v.split(" ").indexOf("select");var O=!1,H=!1,e=[],y=0,I=0,q=0,C,l="",u=null,z="",k=null,t=!1,G=[],m,T=[{location:"root",title:"Home",layout:[["CloseButton","StartUploadButton","CancelUploadButton","AddFileButton","RemoveAllFilesButton"]]}],U=[{id:"-",caption:"",classes:"",
permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour",permissions:[],action:function(){d.FormClose_onClick()},actionData:null,tip:"Click here to close the form builder.",type:"toolbarbutton"},{id:"AddFileButton",caption:"Add Files",classes:"gs-darkblue-background-colour",permissions:[],action:function(){d.AddFilesButton_onClick()},actionData:null,tip:"Click here to add files.",type:"toolbarbutton"},{id:"StartUploadButton",
caption:"Start Upload",classes:"gs-darkblue-background-colour",permissions:[],action:function(){d.StartUploadButton_onClick()},actionData:null,tip:"Click here to start the upload.",type:"toolbarbutton"},{id:"CancelUploadButton",caption:"Cancel Upload",classes:"gs-red-background-colour",permissions:[],action:function(){d.CancelUploadButton_onClick()},actionData:null,tip:"Click here to start the upload.",type:"toolbarbutton"},{id:"RemoveAllFilesButton",caption:"Remove All",classes:"gs-darkblue-background-colour",
permissions:[],action:function(){d.RemoveAllButton_onClick()},actionData:null,tip:"Click here to remove all files.",type:"toolbarbutton"}];this.Form_allowMultipleInstances=function(){return!1};this.Form_onBroadcast=function(c,d,e){"hash"===c&&"change"===d&&a.closeForm(b)};this.Form_onClick=function(){a.setFormFocus(d,b)};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onFocus=function(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(d,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(d,
b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,CloseButton,AddFileButton,StartUploadButton,CancelUploadButton,RemoveAllFilesButton,ge-filetypedropdown-field,ge-fileformatdropdown-field,ge-tab-end")};this.Form_onLoad=function(){a.element(b,".ge-filemode-options").show();a.toBoolean(A.autoclose)&&(H=!0);var c=a.getViewPort().width,e=a.getViewPort().height;a.resizeAndRepositionForm(b,0.1*e,0.1*c,0.8*e,0.8*c);m=new jDock(a,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:T,tiles:U});
m.render(b,".ge-button-panel");a.unbindEvents(b,"gb-form-close,gb-form,gb-formtitle-inner-panel,xge-filetypedropdown-field,xge-fileformatdropdown-field");a.bindEvent(d,b,".gb-form-close","FormClose","onClick");a.bindEvent(d,b,".gb-form","Form","onClick");a.bindEvent(d,b,".gb-form","Form","onDblClick");a.bindEvent(d,b,".gb-formtitle-inner-panel","FormTitle","onClick");c=a.ajaxRequestCreate("import_filetypesfetchimport",[]);a.ajaxCall(URL_WEBSERVICE,c,R,d.asyncError)};this.Form_onPermissionCheck=function(){return!0};
this.FormTitle_onClick=function(){a.formToFront(b)};this.Form_onResize=function(c,d){a.element(b,".gb-panel-resize").css("height",d-100+"px")};this.AddFilesButton_onClick=function(){a.element(b,".ge-files-field").trigger("click")};this.CloseButton_onClick=function(){a.closeForm(b)};this.CancelUploadButton_onClick=function(){t&&(void 0!==C&&C.abort(),a.element(b,".ge-progressallbar").hide(),a.element(b,".ge-progressalltext").css({"margin-top":"19px"}),n(!1,!0,"<font color='red'><b>File(s) upload cancelled</b></font>"),
a.element(b,".lblStatus").html("<font color='red'><b>File(s) upload cancelled</b></font>"),x())};this.FormClose_onClick=function(){a.closeForm(b)};this.FormResult=function(){return G};this.RemoveAllButton_onClick=function(){x()};this.RemoveFileButton_onClick=function(c,d,f,w){d=$(c).closest(".file").attr("arrayidx");e.splice(d,1);$(c).closest(".file").remove();var g=0;a.element(b,".file").each(function(){$(this).attr("arrayidx",g);g++});y=e.length;0===e.length&&x();h()};this.StartUploadButton_onClick=
function(){if(t){var c=[];e.length>MAXUPLOADFILES?(c=e.slice(0,MAXUPLOADFILES),e=e.slice(-(e.length-MAXUPLOADFILES))):(c=e,e=[]);I=c.length;n(!0,!0,"Uploading...");C=a.element(b,".ge-uploader").fileupload("send",{files:c}).error(function(b,c,d){"abort"===d?s(!1):a.dialogAlert(d,function(){})})}};this.Uploader_onFileUploadAdd=function(c,d,f,w){n(!1,!1,"");B(0);q=0;a.element(b,".ge-uploadlist-panel").fadeTo("fast",1);c="";e=$.merge(e,w.files);y=e.length;f=e.length-1;c=e[f].name;d=e[f].size;var g=getGUID();
w.files[0].fileId=g;w="<div class='file file-"+g+"' arrayidx='"+f+"'><table width='100%' cellpadding='0px' cellspacing='0px' style='margin-top:5px;'><tr><td rowspan='2' width='10%'><img src='"+DYNAMIC_APP_DIR_URL+"images/themes/default/filetypeicons/";f=c.split(".").pop().toUpperCase();g="";g=0<="JS,ASP,BMP,CSS,CSV,FLA,GIF,HTM,INFO,JPEG,JPG,JS,PHP,PNG,SWF,XLS,XML,".indexOf(","+f+",")?"JPG"===f||"JPEG"===f?"JPG.png":f+".png":"OTH.png";c=w+g+"' border='0' /></td><td width='84%'>"+c+"&nbsp;&nbsp;"+c.split(".").pop().toUpperCase()+
"&nbsp;&nbsp;"+D(d,2)+"<td width='5%' style='text-align:right;'></td><td rowspan='2' width='1%'>&nbsp;</td></tr><tr><td><div class='lblStatus'><font color='black'><b>Ready to upload</b></font></div></td><td style='text-align:right;'><div class='ge-removefile-button' style='cursor:pointer;'><u>Remove</u></div></td></tr><tr><td colspan='4' style='border-bottom:1px solid #888888;'></td></tr></table></div>";a.element(b,".ge-uploadfiles-field").append(c);h();F()};this.Uploader_onFileUploadDone=function(){if(0<
e.length)this.StartUploadButton_onClick();else{n(!1,!0,"<font color='green'><b>File(s) uploaded successfully</b></font>");B(100);a.element(b,".ge-removefile-button").show();n(!0,!0,"<font color='black'><b>Files(s) processing...</b></font>");var c=a.ajaxRequestCreate("import_processuploads",[]);a.ajaxCall(URL_WEBSERVICE,c,S,a.ajaxError,L);h()}};this.Uploader_onFileUploadSend=function(){s(!1)};this.Uploader_onFileUploadProgress=function(c,d,f,e){var g=0;processArray(e.files,function(c){g=parseInt(100*
(e.loaded/e.total),10);a.element(b,".file-"+c.fileId).find(".progress .bar").css("width",g+"%")})};this.Uploader_onFileUploadProgressAll=function(c,d,e,f){c=parseInt(100*(f.loaded/f.total),10);q+=parseInt(I/y*c,10);100<q&&(q=100);B(q);a.element(b,".lblStatus").html("<font color='black'><b>Uploading...</b></font>")};this.FileFormatOption_onClick=function(c){c=a.element(c);z=c.attr("value");a.element(b,".ge-fileformatselected-label").html(c.html());p()};this.FileTypeOption_onClick=function(c){c=a.element(c);
l=c.attr("value");a.element(b,".ge-filetypeselected-label").html(c.html());c=M(l);void 0!==c&&(f=c.code,r=c.definable,z="",k=[],0<l.length?a.toBoolean(r)?(a.element(b,".ge-fileformatdropdown").show(),E()):(a.element(b,".ge-fileformatdropdown").hide(),a.populateList(b,"ge-fileformatdropdown-field",k,!0,!1),a.element(b,".ge-fileformatselected-label").html("File Format"),h(),p()):(a.populateList(b,"ge-fileformatdropdown-field",k,!0,!1),a.element(b,".ge-fileformatselected-label").html("File Format"),
h(),p()))};this.TabEnd_onFocus=function(){a.element(b,".CloseButton").focus()};this.TabStart_onFocus=function(){a.element(b,".ge-fileformatdropdown-field").focus()}};
