// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function core_frmWikiForm(q,r,s){function t(g){k=g[0].wiki;a.element(b,".ge-form-title").text(htmlEncode(d));g=cyborgWikiToHtml(k,"wiki=","wiki/images/",[{placeholder:"%APPNAME%",value:APP_NAME}]);a.element(b,".ge-thecontent").html(g);a.unbindEvents(b,"ge-cancel-button");a.bindEvent(c,b,".ge-cancel-button","CancelButton","onClick");a.resizeDockedForm(b);a.unbindEvents(b,"gecw-internallink");a.bindEvent(c,b,".gecw-internallink","InternalLink","onClick");l()}function h(){var b=a.ajaxRequestCreate("public_fetchwiki",
[{name:"wiki",value:e}]);a.ajaxCall(URL_WEBSERVICE,b,t,a.error,a.afterAjaxError)}function l(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(c,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(c,b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,CloseButton,PrevVersionButton,NextVersionButton,"+u+",ge-tab-end")}var a=q,c=this,b=r,f=s,u="ge-form-title",e=f.wiki;void 0===e&&(e="");var d=f.title;void 0===d&&(d="");var m=e,n=d,k="",p,v=[{location:"root",title:"Home",layout:[["CloseButton",
"HomeButton"]]}],w=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){c.FormClose_onClick()},actionData:null,tip:"Click here to close the help form.",type:"toolbarbutton"},{id:"HomeButton",caption:"Home",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:[],action:function(){c.HomeButton_onClick()},actionData:null,
tip:"Click here to return to the home page of this help.",type:"toolbarbutton"}];this.InternalLink_onClick=function(a,b,c){e=b.attr("wiki");d=b.attr("title");h()};this.Form_allowMultipleInstances=function(){return a.isMDI()};this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return"R"};this.Form_isDirty=function(){return!1};this.Form_onBroadcast=function(a,b,c){doNothing()};this.Form_onClick=function(){a.setFormFocus(c,b)};this.Form_onDblClick=function(c,d,e){a.formToFront(b);
e.stopPropagation();a.zoomFormInOut(b)};this.Form_onFocus=function(a){if(void 0!==a&&null!==a&&(f.wiki!==a.wiki||f.title!==a.title))f=a,e=f.wiki,void 0===e&&(e=""),d=f.title,void 0===d&&(d=""),m=e,n=d,c.Form_onLoad();l()};this.Form_onLoad=function(){p=new jDock(a,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:v,tiles:w});p.render(b,".ge-button-panel");a.unbindEvents(b,"gb-form-close,gb-form,gb-formtitle-inner-panel");a.bindEvent(c,b,".gb-form-close","FormClose","onClick");a.bindEvent(c,b,
".gb-form","Form","onClick");a.bindEvent(c,b,".gb-form","Form","onDblClick");a.bindEvent(c,b,".gb-formtitle-inner-panel","FormTitle","onClick");h()};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){a.formToFront(b)};this.Form_onResize=function(c,e){var d=a.getFormCanvasHeight(b)-80;a.element(b,".ge-content-panel").height(d+"px");a.element(b,".ge-thecontent").height("100%")};this.CancelButton_onClick=function(){a.closeForm(b)};this.FormClose_onClick=function(){a.closeForm(b)};
this.HomeButton_onClick=function(){e=m;d=n;h()};this.TabEnd_onFocus=function(){a.element(b,".CloseButton").focus()};this.TabStart_onFocus=function(){a.element(b,".ge-code-field").focus()}};
