// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function JCalendar(N,f,O){function D(){processArray(z,function(a){p.showTip("#"+l,"."+a.CellGUID,"bottom center","top center",2,a.Tip)})}function E(a){var d=new Date;d.setMonth(a.getMonth());d.setDate(a.getDate());d.setFullYear(a.getFullYear());d.setHours(a.getHours());d.setMinutes(a.getMinutes());d.setSeconds(a.getSeconds());return d}function y(a){return a.getFullYear()+"-"+(a.getMonth()+1)+"-"+a.getDate()+" "+a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()}function c(a){r+=a}function k(a){s+=
a}function x(a){var d="";return d="January February March April May June July August September October November December".split(" ")[a.getMonth()]+" "+a.getFullYear()}function G(a){var d=!1,b=new Date;a.setHours(0,0,0,0)==b.setHours(0,0,0,0)&&(d=!0);return d}function H(){var a="";e.todayLabel&&(a=' <i><font color="red"> Today</font></i>');return a}function I(a,d,b){var c=!1;processArray(J,function(g){var f=g.eventDate;f.setHours(0,0,0,0);var l=new Date(a);l.setHours(0,0,0,0);0===l-f&&(a.getHours()==
g.eventStartTime&&g.eventStartTime>=e.dayStart&&g.eventStartTime<=e.dayEnd)&&(f="",g.eventCode==K&&(f=" gs-calendar-eventselected"),l=!0,b&&("MONTHVIEW"===d&&t>=e.maxCellEvents)&&(l=!1),l&&(g.eventSelectable?k('<tr><td class="gs-calendar-eventselectable '+g.eventStyle+f+'">'):k('<tr><td class="gs-calendar-event '+g.eventStyle+f+'">'),k(a.getHours()+":00 - "+htmlEncode(g.eventName)+"<br>"),k("</td></tr>"),t++),c=!0)});!1===c&&"DAYVIEW"===d&&(a.getHours()>=e.dayStart&&a.getHours()<=e.dayEnd)&&(k('<tr><td class="gs-calendar-noevent">'),
k(a.getHours()+":00<br>"),k("</td></tr>"))}function L(a){s="";t=0;processArray([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],function(d){a.setHours(d);k('<tr><td class="gs-calendar-event">');I(a,"DAYVIEW",!1);k("</td></tr>")})}function u(){r="";z=[];A=0;c('<table class="gs-calendar" cols="1">');c('<tr class="gs-calendar-titlerow">');f.navigateMonths?c('<td class="gs-calendar-title" colspan="1"><div class="gi-calendar-arrowleft"></div><div class="gs-calendar-titleday">'+(b.getDate()+
" "+x(b))+'</div><div class="gi-calendar-arrowright"></div></td>'):c('<td class="gs-calendar-title" colspan="1">'+(b.getDate()+" "+x(b))+"</td>");c("</tr>");var a=b.getDay();c('<th colspan="1">'+C[a]+"</th>");c('<tr class="gs-calendar-oddrow">');c('<td><div class="gs-calendar-cellday gs-calendar-cellselectable">');c('<table class="gs-calendar-eventtable">');L(b);c(s);c("</table>");c("</div></td>");c("</tr>");c("</table>");$("#"+l).html(r);D();f.navigateMonths&&(p.bindEvent(v,"#"+l,".gi-calendar-arrowleft",
"cmdDayPrevious","onClick"),p.bindEvent(v,"#"+l,".gi-calendar-arrowright","cmdDayNext","onClick"))}function w(){var a;r="";z=[];A=0;c('<table class="gs-calendar" cols="'+m+'">');c('<tr class="gs-calendar-titlerow">');f.navigateMonths?c('<td class="gs-calendar-title" colspan="'+m+'"><div class="gi-calendar-arrowleft"></div><div class="gs-calendar-titlemonth">'+x(b)+'</div><div class="gi-calendar-arrowright"></div></td>'):c('<td class="gs-calendar-title" colspan="'+m+'"><div class="gs-calendar-titlemonth">'+
x(b)+"</div></td>");c("</tr>");c("<tr>");for(a=0;a<m;a++){var d=new Date;d.setDate(b.getDate()-3);d.setHours(0,0,0,0);d=(new Date(d.getFullYear(),d.getMonth(),d.getDate()+(a+B))).getDay();c("<th>"+C[d]+"</th>")}c("</tr>");c('<tr class="gs-calendar-oddrow">');for(a=0;a<m;a++){var n=b,d=a,h=new Date;h.setDate(n.getDate()-3);h.setHours(0,0,0,0);var d=new Date(h.getFullYear(),h.getMonth(),h.getDate()+(d+B)),g=h="";G(d)&&(h=" gs-calendar-celltoday",g=H());if(n.getMonth()==d.getMonth()&&n.getFullYear()==
d.getFullYear()){var n=getGUID(),k=y(d),t="";k==q&&(t=" gs-calendar-cellselectedweek");c('<td><div class="gs-calendar-cellselectable gs-calendar-cellweek '+n+h+t+'" id="'+k+'">');c('<span class="gs-calendar-day">'+d.getDate()+g+"</span>");c('<table class="gs-calendar-eventtable">');L(d);c(s);c("</table>");c("</div></td>")}else e.overhangDays?(c('<td><div class="gs-calendar-cellweek'+h+'">'),c('<span class="gs-calendar-dayfaded">'+d.getDate()+"</span>"),c("</div></td>")):c('<td><div class="gs-calendar-cellweek"></div></td>')}c("</tr>");
c("</table>");$("#"+l).html(r);D();f.navigateMonths&&(p.bindEvent(v,"#"+l,".gi-calendar-arrowleft","cmdWeekPrevious","onClick"),p.bindEvent(v,"#"+l,".gi-calendar-arrowright","cmdWeekNext","onClick"))}function M(a,d){s="";t=0;processArray([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],function(b){a.setHours(b);k('<tr><td class="gs-calendar-event">');I(a,"MONTHVIEW",d);k("</td></tr>")})}function F(){var a;r="";z=[];A=0;c('<table class="gs-calendar" cols="'+m+'">');c('<tr class="gs-calendar-titlerow">');
f.navigateMonths?c('<td class="gs-calendar-title" colspan="'+m+'"><div class="gi-calendar-arrowleft"></div><div class="gs-calendar-titlemonth">'+x(b)+'</div><div class="gi-calendar-arrowright"></div></td>'):c('<td class="gs-calendar-title" colspan="'+m+'"><div class="gs-calendar-titlemonth">'+x(b)+"</div></td>");c("</tr>");c("<tr>");for(a=0;a<m;a++)c("<th>"+C[(a+B)%m]+"</th>");c("</tr>");for(var d=1;d<=P;d++){0===d%2?c('<tr class="gs-calendar-oddrow">'):c('<tr class="gs-calendar-evenrow">');for(a=
0;a<m;a++){var n=b,h=(d-1)*m+a,g=n;g.setDate(1);g.setHours(0,0,0,0);var k=g.getDay();B>k&&(k+=m);h=new Date(g.getFullYear(),g.getMonth(),g.getDate()+(h-k+B));k=g="";G(h)&&(g=" gs-calendar-celltoday",k=H());if(n.getMonth()==h.getMonth()&&n.getFullYear()==h.getFullYear()){var n=getGUID(),u=y(h),w="";u==q&&(w=" gs-calendar-cellselected");c('<td><div class="gs-calendar-cell gs-calendar-cellselectable '+n+g+w+'" id="'+u+'">');c('<span class="gs-calendar-day">'+h.getDate()+k+"</span>");c('<table class="gs-calendar-eventtable">');
M(h,!0);c(s);0<t&&(M(h,!1),h='<div class="gs-calendar-day">'+(h.getDate()+" "+x(h))+k+'</div><table class="gs-calendar-eventtable">'+s+"</table>",z[A]={CellGUID:n,Tip:h},A++);c("</table>");c("</div></td>")}else e.overhangDays?(c('<td><div class="gs-calendar-cell'+g+'">'),c('<span class="gs-calendar-dayfaded">'+h.getDate()+"</span>"),c("</div></td>")):c('<td><div class="gs-calendar-cell"></div></td>')}c("</tr>")}c("</table>");$("#"+l).html(r);D();f.navigateMonths&&(p.bindEvent(v,"#"+l,".gi-calendar-arrowleft",
"cmdMonthPrevious","onClick"),p.bindEvent(v,"#"+l,".gi-calendar-arrowright","cmdMonthNext","onClick"));e.selectableDays&&p.bindEvent(v,"#"+l,".gs-calendar-cellselectable","cmdCell","onClick");$.isFunction(e.cbOnEventSelect)&&p.bindEvent(v,"#"+l,".gs-calendar-eventselectable","cmdEvent","onClick")}var p=N,v=this,e={cbOnDaySelect:null,cbOnEventSelect:null,cbOnFetchPreviousMonth:null,cbOnFetchNextMonth:null,dayStart:0,dayEnd:23,maxCellEvents:3,navigateMonths:!0,overhangDays:!0,selectableDays:!0,startOfWeek:"SUNDAY",
todayLabel:!0};void 0!==f.cbOnDaySelect&&(e.cbOnDaySelect=f.cbOnDaySelect);void 0!==f.cbOnEventSelect&&(e.cbOnEventSelect=f.cbOnEventSelect);void 0!==f.cbOnFetchPreviousMonth&&(e.cbOnFetchPreviousMonth=f.cbOnFetchPreviousMonth);void 0!==f.cbOnFetchNextMonth&&(e.cbOnFetchNextMonth=f.cbOnFetchNextMonth);void 0!==f.dayStart&&(e.dayStart=f.dayStart);void 0!==f.dayEnd&&(e.dayEnd=f.dayEnd);void 0!==f.maxCellEvents&&(e.maxCellEvents=f.maxCellEvents);void 0!==f.navigateMonths&&(e.navigateMonths=f.navigateMonths);
void 0!==f.overhangDays&&(e.overhangDays=f.overhangDays);void 0!==f.selectableDays&&(e.selectableDays=f.selectableDays);void 0!==f.startOfWeek&&(e.startOfWeek=f.startOfWeek.toUpperCase());void 0!==f.todayLabel&&(e.todayLabel=f.todayLabel);var l,b,J=O,r="",s="",t=0,q="",K="",z=[],A=0,m=7,P=6,C="SUNDAY MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY".split(" "),B=function(a){var d=-1,b=0;processArray(C,function(c){c==a&&(d=b);b++});return d}(f.startOfWeek);this.renderDay=function(a,d){l=a;b=E(d);
b.setHours(0,0,0,0);u()};this.renderMonth=function(a,d){l=a;b=E(d);b.setHours(0,0,0,0);F()};this.renderWeek=function(a,d){l=a;b=E(d);b.setHours(0,0,0,0);w()};this.setEvents=function(a){J=a};this.setSelection=function(a){K=a};this.cmdCell_onClick=function(a,b,c){if(e.selectableDays){b=$(a).attr("id");c=b.indexOf(" ");var f="",g="",g=new Date,f=[],g=[];0<=c?(f=b.substring(0,c),g=b.substring(c,b.length),f=f.split("-"),g=g.split(":"),g=new Date(f[0],f[1]-1,f[2],g[0],g[1],g[2])):(f=b.split("-"),g=new Date(f[0],
f[1]-1,f[2]));c=g;0<q.length&&($(".gs-calendar-cellselectable","#"+l).removeClass("gs-calendar-cellselected"),q="");0<b.length&&(q=b,$(a).addClass("gs-calendar-cellselected"));$.isFunction(e.cbOnDaySelect)&&e.cbOnDaySelect(c)}};this.cmdDayNext_onClick=function(){var a=b.getMonth();b.setDate(b.getDate()+1);var c=b.getMonth();e.selectableDays&&(b.setHours(0,0,0,0),q=y(b),$.isFunction(e.cbOnDaySelect)&&e.cbOnDaySelect(b),a!==c?$.isFunction(e.cbOnFetchNextMonth)?e.cbOnFetchNextMonth(b,"DAYVIEW"):u():
u())};this.cmdDayPrevious_onClick=function(){var a=b.getMonth();b.setDate(b.getDate()-1);var c=b.getMonth();e.selectableDays&&(b.setHours(0,0,0,0),q=y(b),$.isFunction(e.cbOnDaySelect)&&e.cbOnDaySelect(b),a!==c?$.isFunction(e.cbOnFetchPreviousMonth)?e.cbOnFetchPreviousMonth(b,"DAYVIEW"):u():u())};this.cmdEvent_onClick=function(){$.isFunction(e.cbOnEventSelect)&&e.cbOnEventSelect()};this.cmdMonthNext_onClick=function(){var a=b;a.setDate(1);a.setHours(0,0,0,0);b=a;b.setMonth(b.getMonth()+1);$.isFunction(e.cbOnFetchNextMonth)?
e.cbOnFetchNextMonth(b,"MONTHVIEW"):F()};this.cmdMonthPrevious_onClick=function(){var a=b;a.setDate(1);a.setHours(0,0,0,0);b=a;b.setMonth(b.getMonth()-1);$.isFunction(e.cbOnFetchPreviousMonth)?e.cbOnFetchPreviousMonth(b,"MONTHVIEW"):F()};this.cmdWeekNext_onClick=function(){var a=b.getMonth();b.setDate(b.getDate()+1);var c=b.getMonth();e.selectableDays&&(b.setHours(0,0,0,0),q=y(b),$.isFunction(e.cbOnDaySelect)&&e.cbOnDaySelect(b),a!==c?$.isFunction(e.cbOnFetchNextMonth)?e.cbOnFetchNextMonth(b,"WEEKVIEW"):
w():w())};this.cmdWeekPrevious_onClick=function(){var a=b.getMonth();b.setDate(b.getDate()-1);var c=b.getMonth();e.selectableDays&&(b.setHours(0,0,0,0),q=y(b),$.isFunction(e.cbOnDaySelect)&&e.cbOnDaySelect(b),a!==c?$.isFunction(e.cbOnFetchPreviousMonth)?e.cbOnFetchPreviousMonth(b,"WEEKVIEW"):w():w())}};
