// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function getNavMapSysOwner(c){var a,b=[{location:"root",title:"Menu",layout:["MenuGroup FormWelcomeButton TabExtendButton FormMyMessagesButton FormCheckoutButton ListSpacerButton ListTodoButton ListWorkQueueButton ListMyRemindersButton ListContactsButton ListWikiPagesButton".split(" ")]}];hasPermission(["VW_PROJLYGROUP"])&&(a="ProjectGroup ProjectDashButton -- ListProjectAllIssuesButton ListProjectBugsButton ListProjectRequirementsButton ListProjectSupportButton ListProjectTasksButton ListProjectWishListButton -- ListProjectBugsCompletedButton ListProjectRequirementsCompletedButton ListProjectSupportCompletedButton ListProjectTasksCompletedButton -- ListProjectParticipantActivityButton ListProjectResourceActivityButton ListRosterButton ListRosterTemplateButton -- ListProjectButton ListSprintsButton -- ListRNDQuestionButton ListRNDGrantButton -- ListProjectBillingCategoriesButton ListProjectCostCategoriesButton ListProjectCampaignTasksButton ListProjectCampaignsButton -- ListProjectParticipantsButton ListProjectResourcesButton ListProjectStakeholdersButton".split(" "),
b[0].layout.push(a));hasPermission(["VW_LICENCEMANAGERGROUP"])&&(a=["LicenceManagerGroup","ListSoftwareLicencesButton","ListSoftwareLicenceTypesButton"],b[0].layout.push(a));hasPermission(["VW_PRINTINGGROUP"])&&(a="PrintingGroup ListPrintJobButton ListPrintJobLogButton -- ListMyPrintersButton ListPublicPrintersButton -- ListMyPrivatePrinterQueuesButton ListMyPublicPrinterQueuesButton".split(" "),b[0].layout.push(a));hasPermission(["VW_IMPORTGROUP"])&&(a=["ImportGroup","ListImportsButton","FormImportDocumentsButton",
"FormImportImagesButton"],b[0].layout.push(a));hasPermission(["VW_DOCUMENTGROUP"])&&(a=["DocumentsGroup","ListDocumentButton","ListDocumentRepositoryButton","ListVideosButton","ListVideoCategoriesButton"],b[0].layout.push(a));hasPermission(["VW_INTEGRATIONGROUP"])&&(a="IntegrationGroup ListIntegrationOutboundTaskButton ListIntegrationOutboundsButton ListServersButton ListAPICallsButton ListAPICallTypesButton ListAPIKeysButton -- ListIntegrationInboundTaskButton ListIntegrationInboundsButton -- ListFileSystemsButton ListFileTypesButton".split(" "),
b[0].layout.push(a));hasPermission(["VW_SETTINGGROUP"])&&(a="SettingsGroup ListMyDevicesButton ListUserFormDeviceButton FormChangePasswordButton FormMyUserSettingsButton FormMyUserButton".split(" "),b[0].layout.push(a));hasPermission(["VW_MYACCOUNTGROUP"])&&(a="MyAccountGroup FormProductAboutButton FormAccountButton FormClientDispatchSettingsButton FormClientSettingsButton -- ListMyProductsButton ListReceiptsButton ListPaymentsButton ListTransactionPendingButton ListTransactionButton ListTransactionHistoryButton -- LogoutButton ReturnButton".split(" "),
b[0].layout.push(a));hasPermission(["VW_CONFIGURATIONPROJLYGROUP"])&&(a="ConfigurationProjlyGroup ListProjectCampaignStatusButton ListProjectCampaignTypeButton ListProjectIssuePriorityButton ListProjectIssueStatusButton ListProjectIssueTypesButton ListProjectParticipantTypesButton ListProjectPrioritiesButton ListProjectStatusButton ListProjectTypesButton ListProjectResourceTypesButton ListProjectTaskPriorityButton ListProjectTaskStatusButton".split(" "),b[0].layout.push(a));hasPermission(["VW_CONFIGURATIONGROUP"])&&
(a="ConfigurationSystemGroup FormLicensingButton ListCMSButton ListColoursButton ListContactStatusesButton ListContactTypesButton ListDesktopRegionsButton ListDocumentRetentionTypesButton ListDocumentTypesButton ListEmployerSizesButton ListFAQButton ListGenderButton ListHonorificButton ListIconButton ListIndustryTypesButton ListInternalMessageFoldersButton ListMessageTemplateTypesButton ListMessageTemplatesButton ListNegotiatedDiscountsButton ListNegotiatedRatesButton ListPaymentMethodsButton ListPaymentStatusButton ListPrinterPurposesButton ListPrinterTypesButton ListProductsButton ListProductTypesButton ListRegistrationTypesButton ListSequencesButton ListServerProtocolsButton ListStartupItemsButton ListStatesButton ListSuburbsButton ListTodoStatusesButton ListTransactionStatusButton ListUserStatusButton ListVideoSourcesButton ListWorkQueueItemTypesButton ListWorkQueueStatusesButton".split(" "),
b[0].layout.push(a));hasPermission(["VW_SECURITYGROUP"])&&(a="SecurityGroup SecurityDashButton -- ListAccountButton ListBranchesButton ListClientsButton ListMyClientsButton ListDataAuditLogsButton ListDevicesButton ListDeviceLogButton ListMyProfilesButton ListRegistrationsButton ListResetPasswordButton ListMyUsersButton".split(" "),b[0].layout.push(a));hasPermission(["VW_SYSTEMGROUP"])&&(a="SystemGroup FormHealthButton ListBatchJobsButton ListConfigsButton -- ListDBProcessButton -- ListSchemaChangesPendingButton ListSchemaChangesDoneButton -- ListSystemFlagValuesButton".split(" "),
b[0].layout.push(a));hasPermission(["VW_DEVELOPMENTGROUP"])&&(a=["--"],b[0].layout.push(a),a=["DevelopmentGroup","ListApplicationsButton","ListModulesButton"],b[0].layout.push(a));hasPermission(["DEVELOPER"])&&"TRUE"===DEVELOPER&&(a=["--"],b[0].layout.push(a),a=["DeveloperGroup","ListPermissionsButton"],b[0].layout.push(a));c.hasCapability("mobile")&&(a=["--"],b[0].layout.push(a),a=["LogoutMobileButton","ReturnMobileButton"],b[0].layout.push(a));return b};
