// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function abnFinder(a,d,l,h,q,b,n){var f=this,g=" %ABN% | %BUSINESSNAME% | %STATE% | %POSTCODE% ";this.fetchByBusinessName=function(e,m){var f=e.term;if(b){if(!a.element(d,"."+h).hasClass("gs-abnsearch"))return}else if(f.length<ABNLOOKUP_CHARACTER_LENGTH)return;f=a.ajaxRequestCreate("core_businessnamelookup",[{name:"filter",value:[{field:"abn",value:f}]}]);a.ajaxCall(URL_WEBSERVICE,f,function(f){var e=[],k=0;processArray(f,function(a){var c=g,c=c.replace("%ABN%",a.id),c=c.replace("%BUSINESSNAME%",
a.businessname),c=c.replace("%STATE%",a.state),c=c.replace("%POSTCODE%",a.postcode);e[k]={value:c,id:a.id,businessname:a.businessname,state:a.state,postcode:a.postcode};k++});m(e);b&&a.element(d,"."+h).removeClass("gs-abnsearch")},function(){m([])})};this.fetchByABN=function(f,b){var d=a.ajaxRequestCreate("core_abnlookup",[{name:"filter",value:[{field:"abn",value:f.term}]}]);a.ajaxCall(URL_WEBSERVICE,d,function(a){var f=[],e=0;processArray(a,function(a){var c=g,c=c.replace("%ABN%",a.id),c=c.replace("%BUSINESSNAME%",
a.businessname),c=c.replace("%STATE%",a.state),c=c.replace("%POSTCODE%",a.postcode);f[e]={value:c,id:a.id,businessname:a.businessname,state:a.state,postcode:a.postcode};e++});b(f)},function(){b([])})};this.selectByBusinessName=function(f,b){a.after(200,function(){a.element(d,"."+l).val(b.item.id);a.element(d,"."+h).val(b.item.businessname)})};this.selectByABN=function(f,b){a.after(200,function(){a.element(d,"."+l).val(b.item.id);a.element(d,"."+h).val(b.item.businessname)})};this.bind=function(){a.toBoolean(ENABLE_DYNAMICABNSEARCH)&&
(b&&a.element(d,"."+n).bind("click",function(){var b="",b="BusinessName"===q?h:l,f=a.element(d,"."+b).val();a.element(d,"."+b).addClass("gs-abnsearch");a.element(d,"."+b).autocomplete("search",f)}),"BusinessName"===q?a.element(d,"."+h).autocomplete({delay:ABNLOOKUP_DELAY_TIME,source:f.fetchByBusinessName,select:f.selectByBusinessName}):a.element(d,"."+l).autocomplete({delay:ABNLOOKUP_DELAY_TIME,source:f.fetchByABN,select:f.selectByABN}))};this.setOutputFormat=function(a){g=a}}
function predictiveTextFinder(a,d,l,h){var q=this,b=d,n,f=!1,g=[],e=[],m=l,k="",p=!0;this.fetchByPredictiveText=function(f,d){function e(a){var f=[],c=0;processArray(a,function(a){var b=k;processArray(g,function(f){b=b.replace("%"+f.toUpperCase()+"%",a[f])});f[c]={value:b,id:a.id};processArray(g,function(b){f[c][b]=a[b]});c++});m.raiseRendererEvent("Entity",b,u.locator,"onChangePending");d(f)}function c(){d([])}var r=f.term,u=m.getDataSourceByDataSourceID(h),w=u.source.split("|"),n=w[0];if(0===r.length)m.raiseRendererEvent("Entity",
b,u.locator,"onClear"),p=!0;else if(p=!1,r.length<MINPREDICTIVECHARS)m.raiseRendererEvent("Entity",b,u.locator,"onChangeStart");else{var l="";3===w.length&&(l=w[2],l=str_replace(l,"'",'"'));r=a.ajaxRequestCreate("entity_formdatalist",[{name:"entitycode",value:"systemform"},{name:"formentityid",value:""},{name:"formentitycode",value:n},{name:"entityid",value:""},{name:"order",value:""},{name:"filter",value:r},{name:"fixedfilter",value:l},{name:"relationship",value:""},{name:"relativeid",value:""},
{name:"relative",value:""},{name:"offset",value:0},{name:"limit",value:0}]);a.ajaxCall(URL_WEBSERVICE,r,e,c)}};this.selectByPredictiveClick=function(f,d){var g=m.getDataSourceByDataSourceID(h),c=$.Event("keypress");c.which=13;a.element(b,g.locator).trigger(c,d)};this.selectByPredictiveText=function(f,d){var g=m.getDataSourceByDataSourceID(h),c=d.item;null!==c&&void 0!==c?0===c.id.length?(m.raiseRendererEvent("Entity",b,g.locator,"onClear"),p=!0):(p=!1,$.isFunction(n)?n("Entity",b,g.locator,"onChange",
c.id,c.value):a.after(200,function(){a.element(b,g.locator+"epv").val(c.id);a.element(b,g.locator+"epd").val(c.value);m.raiseRendererEvent("Entity",b,g.locator,"onChange")})):p||m.raiseRendererEvent("Entity",b,g.locator,"onClear")};this.bind=function(d,l){var p=m.getDataSourceByDataSourceID(h),c=p.source.split("|"),r="['code','description']";n=d;r=1===c.length?"['code','description']":c[1];r=str_replace(r,"'",'"');g=JSON.parse(r);e=[];processArray(g,function(a){e.push("%"+a.toUpperCase()+"%")});k=
e.join(" | ");a.element(b,p.locator).autocomplete({autoFocus:!0,delay:200,minLength:0,source:q.fetchByPredictiveText,change:q.selectByPredictiveText,select:q.selectByPredictiveText,open:function(){f=!0},close:function(){f=!1}});a.element(b,p.locator).on("keydown",function(a){if(f&&(40===a.originalEvent.keyCode||38===a.originalEvent.keyCode)){a.stopPropagation();a.preventDefault();try{a.originalEvent.keyCode=0}catch(b){}}})};this.setOutputFormat=function(a){k=a}}
function suburbFinder(a,d,l,h,q,b,n,f,g){var e=this,m="%SUBURB% | %STATE% | %POSTCODE%",k="%SUBURB%",p="",v="!",s="!",t="!",c="!";0<n.length&&"!"===c&&(c=n);this.fetchByCountry=function(b,f){var c=a.ajaxRequestCreate("core_suburbsearchbycountry",[{name:"filter",value:[{field:"country",value:b.term}]},{name:"order",value:[{field:"country",ascending:!1}]}]);a.ajaxCall(URL_WEBSERVICE,c,function(a){var b=[],c=0;processArray(a,function(a){b[c]={value:a.country,id:a.id};c++});f(b)},function(){f([])})};
this.fetchByPostcode=function(a,b){};this.fetchByState=function(a,b){};this.fetchBySuburb=function(b,g){function e(a){var b=[],f=0;processArray(a,function(a){var c=m,c=c.replace("%SUBURB%",a.suburb),c=c.replace("%STATE%",a.state),c=c.replace("%POSTCODE%",a.postcode),c=c.replace("%COUNTRY%",a.country);b[f]={value:c,id:a.id};f++});g(b)}function h(){g([])}var k=b.term;p=k;$.isFunction(f)&&f(k);"#"===k.substring(0,1)?a.element(d,"."+l).autocomplete("close"):(k=a.ajaxRequestCreate("core_suburbsearchbysuburb",
[{name:"filter",value:[{field:"suburb",value:k},{field:"country",value:c}]},{name:"order",value:[{field:"suburb",ascending:!1}]}]),a.ajaxCall(URL_WEBSERVICE,k,e,h))};this.fetchBySuburbID=function(f){var e=a.ajaxRequestCreate("core_suburbfetch",[{name:"id",value:f}]);a.ajaxCall(URL_WEBSERVICE,e,function(e){v=e[0].suburb;s=e[0].state;t=e[0].postcode;c=e[0].country;$.isFunction(g)&&g(p,f,v,s,t,c);e=k;e=e.replace("%SUBURB%",v);e=e.replace("%STATE%",s);e=e.replace("%POSTCODE%",t);e=e.replace("%COUNTRY%",
c);a.element(d,"."+l).val(e);a.element(d,"."+h).val(s);a.element(d,"."+q).val(t);a.element(d,"."+b).val(c)},function(){doNothing()})};this.selectByCountry=function(b,f){c=f.item.id;a.element(d,"."+l).focus()};this.selectByPostcode=function(a,b){};this.selectByState=function(a,b){};this.selectBySuburb=function(a,b){e.fetchBySuburbID(b.item.id)};this.bind=function(){a.element(d,"."+b).autocomplete({delay:500,source:e.fetchByCountry,select:e.selectByCountry});a.element(d,"."+l).autocomplete({autoFocus:!0,
delay:0,source:e.fetchBySuburb,select:e.selectBySuburb})};this.setOutputFormat=function(a){m=a};this.setSuburbResultFormat=function(a){k=a}}
function childTabHandler(a){var d=this,l=getGUID(),h={id:a.id,caption:"Child ("+a.id+")",window:a.window,opener:a.window.opener};$(a.window).bind("message",function(d){if($.isFunction(a.cbOnBroadcast)){var b=null;try{b=JSON.parse(d.originalEvent.data)}catch(h){}null!==b&&(void 0==b.queue?doNothing():a.cbOnBroadcast(b.queue,b.message,b.messagedata))}});d.broadcast=function(a,b,d){h.opener.postMessage(JSON.stringify({tabid:h.id,originid:h.id,origindescription:h.caption,queue:a,message:b,messagedata:d}),
"*")};d.canCreateTab=function(){return!1};d.getHandlerID=function(){return l};d.getTabInfo=function(){return h};d.getTabs=function(){return[{id:h.id,caption:h.caption}]};d.ping=function(){d.broadcast("system","ping","ping")}}
function parentTabHandler(a){function d(a){var g=a.source||a.originalEvent.source,e=null;try{e=JSON.parse(a.originalEvent.data)}catch(d){}if(null!==e){var h=!0;processArray(b,function(a){if(a.id==e.originid)return h=!1,!0});if(h){a=n;var l={id:e.originid,caption:e.origindescription,window:null,opener:null};n++;b[a]=l;l.window=g}}}function l(a){var g=null;try{g=JSON.parse(a.originalEvent.data)}catch(e){}null!==g&&processArray(b,function(a){"0"!==a.id&&a.id!==g.originid&&a.window.postMessage(JSON.stringify({tabid:"0",
originid:g.originid,origindescription:g.origindescription,queue:g.queue,message:g.message,messagedata:g.messagedata}),"*")})}var h=this,q=getGUID(),b=[];b[0]={id:"0",caption:"Parent",window:a.window,opener:null};var n=1;$(a.window).bind("message",function(b){d(b);l(b);if($.isFunction(a.cbOnBroadcast)){var g=null;try{g=JSON.parse(b.originalEvent.data)}catch(e){}null!==g&&(void 0==g.queue?doNothing():a.cbOnBroadcast(g.queue,g.message,g.messagedata))}});h.broadcast=function(a,g,e){processArray(b,function(d){"0"!==
d.id&&d.window.postMessage(JSON.stringify({tabid:"0",originid:"0",origindescription:b[0].caption,queue:a,message:g,messagedata:e}),"*")})};h.canCreateTab=function(){return!0};h.createTab=function(a,d,e){var h=n,k=getGUID();void 0===d&&(d="");void 0===e&&(e="");k={id:k,caption:"Child ("+k+")",window:null,opener:null};n++;b[h]=k;k.window=window.open(a+"?tabid="+k.id+d+e,k.caption);return k.window};h.getHandlerID=function(){return q};h.getTabInfo=function(a){return b[a]};h.getTabs=function(){var a=[];
processArray(b,function(b){a.push({id:b.id,caption:b.caption})});return a};h.ping=function(){h.broadcast("system","ping","ping")}};
