// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function jDock(Y,z){function R(c){var f,a,b,k,e;if(0<m.length&&(b=r(m[0]),e=$.isFunction(b.caption)?b.caption():b.caption,a=$.isFunction(c.caption)?c.caption():c.caption,e!=a)){e=M();D(c,e);for(c=0;c<m.length;c++)if(a=r(m[c]),a=$.isFunction(a.caption)?a.caption():a.caption,f=$.isFunction(e.caption)?e.caption():e.caption,a==f){for(f=c;f<m.length-1;f++)a=r(m[f+1]),k=r(m[f]),D(a,k);a=r(m[m.length-1]);a.caption="";a.classes="";a.permissions=[];a.action="";a.actionData=null;a.actionData2=null;a.actionData3=
null;a.actionShifted="";a.actionDataShifted=null;a.actionDataShifted2=null;a.actionDataShifted3=null;a.significant=!1;a.tip="";a.renderwidth=0;a.reversetip=!1;a.tempclasses="";a.toptip=!1;a.type="blank"}for(c=m.length-2;0<=c;c--)a=r(m[c]),f=$.isFunction(a.caption)?a.caption():a.caption,0<f.length&&(k=r(m[c+1]),D(a,k),k.significant=!0);D(e,b);b.significant=!0;S&&(E=m);S=!0;w.setLocation(C);E=[]}}function Z(c){var f=!1;0===E.length?f=!0:processArray(E,function(a){if(c.id==a)return f=!0});return f}function A(c){var f=
!1;return f=$.isFunction(c.permissions)?c.permissions():0<c.permissions.length?hasPermission(c.permissions):!0}function aa(){0<E.length?processArray(E,function(c){$("."+c+"DIV","#"+t).remove()}):$("#"+t).html("")}function D(c,f){var a="",a=$.isFunction(c.classes)?c.classes():c.classes;f.caption=c.caption;f.classes=a;f.permissions=c.permissions;f.action=c.action;f.actionData=c.actionData;f.actionData2=c.actionData2;f.actionData3=c.actionData3;f.actionShifted=c.actionShifted;f.actionDataShifted=c.actionDataShifted;
f.actionDataShifted2=c.actionDataShifted2;f.actionDataShifted3=c.actionDataShifted3;f.significant=c.significant;f.tip=c.tip;f.renderwidth=c.renderwidth;f.reversetip=c.reversetip;f.tempclasses=c.tempclasses;f.toptip=c.toptip;f.type=c.type}function M(){return{id:"",caption:"",classes:"",permissions:[],action:"",actionData:null,actionData2:null,actionData3:null,actionShifted:"",actionDataShifted:null,actionDataShifted2:null,actionDataShifted3:null,significant:!1,tip:"",renderwidth:0,reversetip:!1,tempclasses:"",
toptip:!1,type:"blank"}}function H(c){if($.isFunction(T)){var f=$(N,g).height();"buttongrid"===x&&(f=62.5*(c-1));T(f)}}function ba(c){var f;processArray(ca,function(a){if(a.location==c)return f=a,!0});return f}function r(c){var f=null;processArray(O,function(a){if(a.id==c){f=a;var b="",b=$.isFunction(a.classes)?a.classes():a.classes;f.classes=b}});return f}function I(c,f,a,b,k){if(Z(b)){var q,n,y,p,F="",l,s="",h,d,r="",B=b.id,u,m,v=$("#"+t).width();0<k.length&&(s+=" "+k+"ROWHEAD");p=$.isFunction(b.caption)?
b.caption():b.caption;l="";void 0==b.tempclasses||(b.tempclasses.length=0)?(l=$.isFunction(b.classes)?b.classes():b.classes,b.tempclasses=l):l=b.tempclasses;void 0===l&&(l="gs-darkgrey-background-colour");F=void 0!==b.captionclasses?b.captionclasses:"gs-buttontext";n=b.style;void 0===n&&(n="");void 0!==b.iconClasses&&(r="gs-buttonicon "+b.iconClasses);m=b.url;void 0===m&&(m="");u=b.tip;void 0===u&&(u="");c=b.reversetip;void 0===u&&(c=!1);q=b.toptip;void 0===u&&(q=!1);y=b.buttonkeytext;void 0===y&&
(y="");"-"!==k&&"-"===B?(B="blank",p="-",s+=" gb-collapsable hidden"):k==B?s+=" gb-noncollapsable":0<k.length?s=b.noncollapsable?s+" gb-noncollapsable":s+" gb-collapsable hidden":doNothing();k=b.type;"verticalmenu"===x?k="menuitem":"horizontalmenu"===x?k="menuitem":"verticallinks"===x?k="linkitem":"horizontallinks"===x&&(k="linkitem");if("button"===k)n=G?v-125*f:125*(f-1),a=62*(a-1),d="",h=B,e.hasCapability("symbols")&&(p=str_replace(p,"&gt;","&#9658;")),d='<div class="'+(h+"DIV")+' gs-cell-xxx gs-cell-125x62-xxx" style="top:'+
a+"px; left:"+n+'px">',0<m.length&&(d+='<a href="'+m+'">'),d+='<div class="'+h+" gb-button gs-cell-content-xxx gs-cellcontent-125x62-xxx "+l+'">',0<r.length&&(d+='<i class="'+r+'">'+p+"</i>"),d+='<div class="'+F+'">'+p+"</div>",0<y.length&&(d+='<div class="gs-buttonkeytext">'+y+"</div>"),d+="</div>",0<m.length&&(d+="</a>"),d+="</div>";else if("menuitem"===k)d="",h=B,e.hasCapability("symbols")&&(p=str_replace(p,"&gt;","&#9658;")),a=h+"DIV"+s,d="verticalmenu"===x?'<div class="'+a+' gs-menuitem-container-vertical">':
'<div class="'+a+' gs-menuitem-container">',0<m.length&&(d+='<a href="'+m+'">'),"-"===p?d+='<div class="'+h+" gb-button "+l+'"><hr style="width: 99%; color: #cccccc; height: 1px; background-color:#cccccc; margin:5px; '+n+'" /></div>':(d+='<div class="'+h+" gb-button gs-button gs-cell-content-xxx "+l+'" style="'+n+'">',0<r.length&&(d+='<i class="'+r+'"></i>'),d+='<div class="'+F+'">'+p+"</div>",0<y.length&&(d+='<div class="gs-buttonkeytext">'+y+"</div>"),d+="</div>"),0<m.length&&(d+="</a>"),d+="</div>";
else if("linkitem"===k)d="",h=B,e.hasCapability("symbols")&&(p=str_replace(p,"&gt;","&#9658;")),a=h+"DIV"+s,d="verticallinks"===x?'<div class="'+a+' gs-menuitem-container-vertical">':'<div class="'+a+' gs-menuitem-container">',0<m.length&&(d+='<a href="'+m+'">'),"-"===p?d+='<div class="'+h+" gb-linksbutton "+l+'"><hr style="width: 99%; color: #cccccc; height: 1px; background-color:#cccccc; margin:5px; '+n+'" /></div>':(d+='<div class="'+h+" gb-button gs-linksbutton gs-cell-content-xxx "+l+'" style="'+
n+'">',0<r.length&&(d+='<i class="'+r+'"></i>'),d+='<div class="'+F+'">'+p+"</div>",0<y.length&&(d+='<div class="gs-buttonkeytext">'+y+"</div>"),d+="</div>"),0<m.length&&(d+="</a>"),d+="</div>";else if("hamburgermenu"===k)d="",h=B,e.hasCapability("symbols")&&(p=str_replace(p,"&gt;","&#9658;")),d='<div class="'+(h+"DIV"+s)+' gs-burger-container">',0<m.length&&(d+='<a href="'+m+'">'),d+='<div class="'+h+" gb-button gs-button gs-cell-content-xxx "+l+'">',d+='<div class="'+F+'">'+p+"</div>",0<y.length&&
(d+='<div class="gs-buttonkeytext">'+y+"</div>"),d+="</div>",0<m.length&&(d+="</a>"),d+="</div>";else if("icon"===k)d="",h=B,a=h+"DIV"+s,d=0<n.length?'<div class="'+a+' gs-cell-62x62-xxx" style="'+n+'">':'<div class="'+a+' gs-cell-62x62-xxx" style="left:10px; top:10px;">',d+='<div class="'+h+" gs-cell-content-xxx gs-cellcontent-62x62-xxx "+l+'"></div>',d+="</div>";else if("toolbarbutton"===k){d="";h=B;if(""===l||void 0===l)l="btn-primary";0<=l.indexOf("gs-green-background-colour")&&(l=l.replace("gs-green-background-colour",
"btn-success"));0<=l.indexOf("gs-red-background-colour")&&(l=l.replace("gs-red-background-colour","btn-danger"));0<=l.indexOf("gb-cell-disabled-xxx")&&(l=l.replace("gb-cell-disabled-xxx","btn-disabled"));0<=l.indexOf("gb-cell-disabled")&&(l=l.replace("gb-cell-disabled","btn-disabled"));-1===l.indexOf("btn-default")&&(-1===l.indexOf("btn-primary")&&-1===l.indexOf("btn-success")&&-1===l.indexOf("btn-danger")&&-1===l.indexOf("btn-disabled"))&&(l+=" btn-primary");e.hasCapability("symbols")&&(p=str_replace(p,
"&gt;","&#9658;"));d='<span class="'+h+" "+(h+"DIV"+s)+" btn "+l+' gb-button" style="'+n+'">';d+=p;d+="</span>"}else if("toolbardevicebutton"===k){d="";h=B;if(""===l||void 0===l)l="btn-primary btn-toolbar-device-button";0<=l.indexOf("gs-green-background-colour")&&(l=l.replace("gs-green-background-colour","btn-success"));0<=l.indexOf("gs-red-background-colour")&&(l=l.replace("gs-red-background-colour","btn-danger"));0<=l.indexOf("gb-cell-disabled-xxx")&&(l=l.replace("gb-cell-disabled-xxx","btn-disabled"));
0<=l.indexOf("gb-cell-disabled")&&(l=l.replace("gb-cell-disabled","btn-disabled"));-1===l.indexOf("btn-default")&&(-1===l.indexOf("btn-primary")&&-1===l.indexOf("btn-success")&&-1===l.indexOf("btn-danger")&&-1===l.indexOf("btn-disabled"))&&(l+=" btn-primary");e.hasCapability("symbols")&&(p=str_replace(p,"&gt;","&#9658;"));d+='<div class="btn-group">';d+='<span class="'+h+" "+(h+"DIV"+s)+" btn "+l+' gb-button dropdown-toggle" data-toggle="dropdown">';d+=p+'&nbsp;<span class="caret"></span>';d+="</span>";
d+='<ul class="gs-button-panel-dropdown-menu dropdown-menu">';processArray(b.actionDataList,function(b){d+='<li><a class="gs-dropdown-tile btn btn-primary '+b.id+'">'+b.caption+"</a></li>"});d+="</ul>";d+="</div>"}$("#"+t).append(d);$.isFunction(b.action)||0<b.action.length?(e.unbindEvents(g,h),e.bindEvent(w,g,"."+h,"Tile","onClick",b),e.bindEvent(w,g,"."+h,"Tile","onEnterKey",b),q?c?2>=f?e.showTip(g,"."+h,"bottom right","top center",2,u):6>=f?e.showTip(g,"."+h,"bottom center","top center",2,u):e.showTip(g,
"."+h,"bottom left","top center",2,u):2>=f?e.showTip(g,"."+h,"bottom left","top center",2,u):6>=f?e.showTip(g,"."+h,"bottom center","top center",2,u):e.showTip(g,"."+h,"bottom right","top center",2,u):c?2>=f?e.showTip(g,"."+h,"top right","bottom center",2,u):6>=f?e.showTip(g,"."+h,"top center","bottom center",2,u):e.showTip(g,"."+h,"top left","bottom center",2,u):2>=f?e.showTip(g,"."+h,"top left","bottom center",2,u):6>=f?e.showTip(g,"."+h,"top center","bottom center",2,u):e.showTip(g,"."+h,"top right",
"bottom center",2,u),e.element(g,"."+h).hasClass("gb-cell-disabled-xxx")&&(e.element(g,"."+h).qtip("hide",!0),e.element(g,"."+h).qtip("disable",!0))):(e.bindEvent(w,g,"."+h,"Tile","onClick",b),e.bindEvent(w,g,"."+h,"Tile","onEnterKey",b));"toolbardevicebutton"===k&&processArray(b.actionDataList,function(b){e.unbindEvents(g,b.id);e.bindEvent(w,g,"."+b.id,"Tile","onClick",b)})}}function da(c,f){if(!P){P=!0;var a,b=1,k=1,q,n="",m=U,p=f;void 0===p&&(p=0);processArray(c,function(c){var l=0;processArray(c,
function(b){q=r(b);null!==q?(a=q.significant,void 0===a&&(a=!0),a&&A(q)&&l++):doException("renderVerticalMenu","missing tile: "+b)});if(0<l){G&&(c=c.reverse());var s=1;processArray(c,function(a){q=r(a);null!==q&&A(q)&&(a=!0,0<f&&!J&&(a=!1,p>=1*m+U&&(a=!0)),a&&(I(k,s,b,q,""),n=q.id,a=e.element(g,"."+q.id).css("width"),a=str_replace(a,"px",""),null===a&&(a="0"),q.renderwidth=parseInt(a,10),q.renderwidth>m&&(m=q.renderwidth),p-=q.renderwidth,0>p&&(p=0),k++,s++))});G&&(c=c.reverse());b++}});H(b);J||(b--,
ea(c,b,n));P=!1}}function ea(c,f,a){var b,k,q,n,m=1,p;k='<div class="ge-more-button btn-group"><span class="btn btn-primary dropdown-toggle" data-toggle="dropdown">More...&nbsp;<span class="caret"></span></span>';k+='<ul class="ge-more-menu gs-button-panel-dropdown-menu dropdown-menu">';k+="</ul>";k+="</div>";$("#"+t).append(k);var v=!1,l=!1,s=!1,h;processArray(c,function(k){m==f&&(v=!0);v&&processArray(k,function(k){b=r(k);q=k;if(l)if(null!==b&&A(b)){h="";void 0==b.tempclasses||(b.tempclasses.length=
0)?(h=$.isFunction(b.classes)?b.classes():b.classes,b.tempclasses=h):h=b.tempclasses;if(""===h||void 0===h)h="btn-primary";0<=h.indexOf("gs-green-background-colour")&&(h=h.replace("gs-green-background-colour","btn-success"));0<=h.indexOf("gs-red-background-colour")&&(h=h.replace("gs-red-background-colour","btn-danger"));0<=h.indexOf("gb-cell-disabled-xxx")&&(h=h.replace("gb-cell-disabled-xxx","btn-disabled"));0<=h.indexOf("gb-cell-disabled")&&(h=h.replace("gb-cell-disabled","btn-disabled"));-1===
h.indexOf("btn-default")&&(-1===h.indexOf("btn-primary")&&-1===h.indexOf("btn-success")&&-1===h.indexOf("btn-danger")&&-1===h.indexOf("btn-disabled"))&&(h+=" btn-primary");p=b.caption;n="";"toolbardevicebutton"===b.type?(n+='<li onclick="event.stopPropagation()">',n+='<div class="btn-group" style="display:block;">',n+='<span class="ge-toolbardevicebutton-more-menu gs-dropdown-tile btn '+h+' gb-dropdown-tile" data-toggle="dropdown" style="display:block;width:100%;padding-left:20px">',n+=p+'&nbsp;<span class="caret"></span>',
n+="</span>",n+='<ul class="gs-button-panel-dropdown-menu dropdown-menu" style="left:100%">',processArray(b.actionDataList,function(b){n+='<li><a class="gs-dropdown-tile btn btn-primary gb-dropdown-tile '+b.id+'">'+b.caption+"</a></li>"}),n+="</ul>",n+="</div>"):(n="<li>",n+='<a class="'+q+" gs-dropdown-tile btn "+h+' gb-dropdown-tile">'+p+"</a>");n+="</li>";e.element("#"+t,".ge-more-menu").append(n);($.isFunction(b.action)||0<b.action.length)&&e.unbindEvents("#"+t,q);e.bindEvent(w,"#"+t,"."+q,"Tile",
"onClick",b);e.bindEvent(w,"#"+t,"."+q,"Tile","onEnterKey",b);"toolbardevicebutton"===b.type&&processArray(b.actionDataList,function(b){e.unbindEvents("#"+t,b.id);e.bindEvent(w,"#"+t,"."+b.id,"Tile","onClick",b)});b.tempclasses=e.element(g,"."+b.id).attr("class");s=!0}else doException("renderVerticalMenu","missing tile: "+k);else if(b.id==a||0===a.length)l=!0});m++});$(".ge-toolbardevicebutton-more-menu").click(function(){var b=$(this);b.parent(".btn-group").hasClass("open")?b.parent(".btn-group").removeClass("open"):
b.parent(".btn-group").addClass("open")});s||e.element("#"+t,".ge-more-button").remove()}function fa(c){var f=1,a=1,b,k,e="",g=null;processArray(c,function(c){var m=0;processArray(c,function(a){b=r(a);null!==b?(k=b.significant,void 0===k&&(k=!0),k&&A(b)&&m++):doException("renderVerticalMenu","missing tile: "+a)});if(0<m){var t=1;processArray(c,function(k){b=r(k);null!==b?(1==t?"-"===b.id?Q&&(I(a,1,f,b,e),a++):A(b)&&0<b.caption.length&&(null!==g&&"--"===g.id&&g.id===b.id?doNothing():(e=b.id,I(a,1,
f,b,e),g=b,a++)):A(b)&&0<b.caption.length&&(null!==g&&"--"===g.id&&g.id===b.id?doNothing():(I(a,1,f,b,e),g=b,a++)),f++,t++):doException("renderVerticalMenu","missing tile: "+k)})}});H(f)}function ga(c,f){var a=c.split(","),b;processArray(a,function(a){var c=r(a);null!==c&&A(c)?(a=f.split(" "),b=c.id,processArray(a,function(a){e.element(g,"."+b).hasClass("gs-darkblue-background-colour")&&e.element(g,"."+b).removeClass("btn-primary");e.element(g,"."+b).hasClass("gs-red-background-colour")&&e.element(g,
"."+b).removeClass("btn-danger");e.element(g,"."+b).removeClass(a)}),e.element(g,"."+b).addClass("btn-disabled disabled")):doException("disableDropdownButtons","missing tile: "+a)})}function ha(c,f){var a=c.split(","),b;processArray(a,function(a){var c=r(a);null!==c&&A(c)?(a=f.split(" "),b=c.id,processArray(a,function(a){e.element(g,"."+b).hasClass("gs-red-background-colour")?e.element(g,"."+b).addClass("btn-danger"):e.element(g,"."+b).hasClass("gs-darkblue-background-colour")?e.element(g,"."+b).addClass("btn-primary"):
e.element(g,"."+b).addClass(a)}),e.element(g,"."+b).removeClass("disabled gb-cell-disabled btn-disabled")):doException("enableDropdownButtons","missing tile: "+a)})}function V(c,f){w.setLocation(c,f);var a=$("#"+t).css("height"),a=str_replace(a,"px","");0===a.length&&(a="0");W=parseInt(a,10);a=$("#"+t).css("width");a=str_replace(a,"px","");0===a.length&&(a="0");X=parseInt(a,10)}var U=82,e=Y,w=this,P=!1,W=0,X=0,t="",N="",g="",C="",E=[],K=z.addtorecent;void 0===K&&(K=!0);var G=z.alignright;void 0===
G&&(G=!1);var T=z.cbOnRender,v="",ca=z.map,x=z.mode;void 0==x&&(x="buttongrid");var m=z.recent;void 0===m&&(m=[]);var S=!1,Q=z.renderblanks;void 0===Q&&(Q=!0);var O=z.tiles;void 0===O&&(O=[]);var L=z.closeonselect;void 0===L&&(L=!1);var J=z.alwayshidemorebutton;void 0===J&&(J=!1);this.Dock_onResize=function(){V(C,0);V(C,X)};this.disableButtons=function(c,f){var a=c.split(",");processArray(a,function(b){var a=r(b);null!==a&&A(a)?(b=f.split(" "),processArray(b,function(b){"toolbarbutton"===a.type&&
(e.element(g,"."+a.id).hasClass("gs-darkblue-background-colour")&&e.element(g,"."+a.id).removeClass("btn-primary"),e.element(g,"."+a.id).hasClass("gs-red-background-colour")&&e.element(g,"."+a.id).removeClass("btn-danger"));a.classes=a.classes.replace(b,"");e.element(g,"."+a.id).removeClass(b)}),"toolbarbutton"===a.type?-1===a.classes.indexOf("disabled")&&e.element(g,"."+a.id).addClass("btn-disabled disabled"):-1===a.classes.indexOf("gb-cell-disabled-xxx")&&(a.classes+=" gb-cell-disabled-xxx",e.element(g,
"."+a.id).addClass("gb-cell-disabled-xxx")),a.classes=a.classes.replace("  "," "),a.classes=$.trim(a.classes),e.element(g,"."+a.id).qtip("hide",!0),e.element(g,"."+a.id).qtip("disable",!0),a.tempclasses=e.element(g,"."+a.id).attr("class")):doException("disableButtons","missing tile: "+b)});ga(c,f)};this.enableButtons=function(c,f){var a=c.split(",");processArray(a,function(a){var c=r(a);null!==c&&A(c)?(a=f.split(" "),processArray(a,function(a){"toolbarbutton"===c.type?e.element(g,"."+c.id).hasClass("gs-red-background-colour")?
e.element(g,"."+c.id).addClass("btn-danger"):e.element(g,"."+c.id).hasClass("gs-darkblue-background-colour")?e.element(g,"."+c.id).addClass("btn-primary"):e.element(g,"."+c.id).addClass(a):-1===c.classes.indexOf(a)&&(c.classes=c.classes+" "+a,e.element(g,"."+c.id).addClass(a))}),"toolbarbutton"===c.type?e.element(g,"."+c.id).removeClass("disabled gb-cell-disabled btn-disabled"):(c.classes=c.classes.replace("gb-cell-disabled-xxx",""),c.classes=c.classes.replace("  "," "),c.classes=$.trim(c.classes),
e.element(g,"."+c.id).removeClass("gb-cell-disabled-xxx")),e.element(g,"."+c.id).qtip("disable",!1),c.tempclasses=e.element(g,"."+c.id).attr("class")):doException("enableButtons","missing tile: "+a)});ha(c,f)};this.getHeight=function(){return W};this.render=function(c,f,a){void 0===a&&(a="root");g=c;N=f;t="jdock-"+getGUID();$(N,c).attr("id",t);C=a;"verticalmenu"===x?doNothing():e.bindEvent(w,g,".gb-form","Dock","onResize");w.Dock_onResize()};this.getLocation=function(){return C};this.setLocation=
function(c,f){C=c;v="";aa();var a=ba(C);doNothing();"verticalmenu"===x?fa(a.layout):da(a.layout,f)};this.Tile_onClick=function(c,f,a,b,k){a.shiftKey?(a=f=c=null,$.isFunction(k.actionShifted)?(b=M(),D(k,b),K&&R(k),L&&e.toggleMenu(),c=b.actionDataShifted,$.isFunction(b.actionDataShifted)&&(c=b.actionDataShifted()),f=b.actionDataShifted2,$.isFunction(b.actionDataShifted2)&&(f=b.actionDataShifted2()),a=b.actionDataShifted3,$.isFunction(b.actionDataShifted3)&&(a=b.actionDataShifted3()),b.actionShifted(c,
f,a)):"navigate"===k.actionShifted&&k.actionDataShifted!=C?w.setLocation(k.actionDataShifted):(e.element(g,".gb-collapsable").hide(),v==k.id?v="":(v=k.id,e.element(g,"."+v+"ROWHEAD").removeClass("hidden"),e.element(g,"."+v+"ROWHEAD").show()),H(0))):(a=f=c=null,$.isFunction(k.action)?(b=M(),D(k,b),K&&R(k),L&&e.toggleMenu(),c=b.actionData,$.isFunction(b.actionData)&&(c=b.actionData()),f=b.actionData2,$.isFunction(b.actionData2)&&(f=b.actionData2()),a=b.actionData3,$.isFunction(b.actionData3)&&(a=b.actionData3()),
b.action(c,f,a)):"navigate"===k.action&&k.actionData!=C?w.setLocation(k.actionData):(e.element(g,".gb-collapsable").hide(),v==k.id?v="":(v=k.id,e.element(g,"."+v+"ROWHEAD").removeClass("hidden"),e.element(g,"."+v+"ROWHEAD").show()),H(0)))};this.Tile_onEnterKey=function(c,f,a,b,e){w.Tile_onClick(c,f,a,b,e)}};
