// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function osEntry(ma,aa){var k=ma,c=this,na=!1;void 0===k.background&&(k.background="");void 0===k.child&&(k.child=!1);void 0===k.container&&(k.container="");void 0===k.dependencies&&(k.dependencies="");void 0===k.orientation&&(k.orientation="");void 0===k.keepalive&&(k.keepalive=!1);void 0===k.unloadprompt&&(k.unloadprompt=!0);var Wa=1366,Xa=768,Ya=!1,ba=608,ca=1E3,Za=28,O=30,$a=10,ab=500,bb=15,cb=10,da=1E3,z=250,db=500,Ca=10,eb=1,fb=5,P=20,Da=[],Q="",Ea=[],Fa=[],Ga=[],C=0,y="";getGUID();var F=null,
Ha="",oa=null,pa="",ea=!1,G=!1,t="",Ia,Ja,D="",fa="",R=10,S,H="",ha="",Ka=!0,p=0,gb=10,I=0,qa=[],ia=[],J=[],ra=[],T=[],A,n={OS:"unknown",name:"unknown",version:"unknown",major:-1,capabilities:"",incapabilities:"",support:"unavailable"},B=0,K=0,La=1,U=0,ja=0,sa=0,ta=!1,Ma="",ua=navigator.userAgent,Na=!1,va,L=[],wa=[{name:"SYSTEMFORM",timeframe:5},{name:"xLVBARCODETYPE",timeframe:5},{name:"xLVBOOKINGSTATUS",timeframe:5},{name:"xLVBOOKINGTYPE",timeframe:5},{name:"xLVCASENOTECATEGORY",timeframe:5},{name:"xLVCASENOTESTATUS",
timeframe:5},{name:"xLVPERSONSTATUS",timeframe:5},{name:"xLVPHONENUMBERASSOC",timeframe:5}];(function(){var c=0;try{var k=(new UAParser(ua)).getResult();n.OS=k.os.name;n.name=k.browser.name;c=n.version=k.browser.major;n.major=c}catch(p){doException("detectBrowserInfo",p)}k=FULLBROWSERCAPABILITY;processArray(g_objBrowsers,function(k){var p=RegExp(k.browserid);if(n.OS.match(RegExp(k.osid))&&n.name.match(p)&&c>=k.major)return n.name=k.name,n.capabilities=k.capabilities,n.support=k.supportlevel,!0});
"unavailable"===n.support&&"TRUE"===BYPASSBROWSERCHECK&&(n.support="minimal",n.capabilities="");n.incapabilities=diffString(str_replace(k,","," "),str_replace(n.capabilities,","," "))})();0<k.background.length&&$("html").addClass(k.background);os=osEntry=function(){function Oa(a){var b=a.showform,d=a.url,e=a.parameters;a.newtab?window.open(d,"_blank"):b?c.showForm(d,e):c.gotoURL(d,e,"Server")}function hb(a,b,d){d?(c.resizeDockedForm("#"+a),c.formobject=!0):c.element("#"+a,".gb-form").draggable({handle:".gb-form-handle"});
b&&!d&&c.element("#"+a,".gb-form").resizable({minHeight:200,minWidth:db,resize:function(b,d){W(a)}});W(a);c.broadcast("system","viewport","change");I++;logDebug("ViewPortChangeCount2:"+I);c.showMDIClose("#"+a)}function V(){var a=!1;0<t.length&&(a=p,a=c.getViewPort().height-a-R+fb,c.element("#"+t,".gb-form").css("height",a+"px"),a=!0);return a}function aa(a,b,d,e,f,g){var h=c.str_right(f,f.length-2),q=c.element(b,d);q.bind(h.toLowerCase(),function(b,d){X(a,this,q,e,f,b,d,g)})}function ma(a,b,d,e,f){var g=
c.element(b,d);g.bind("keypress",function(b,d){13===b.which&&X(a,this,g,e,"onEnterKey",b,d,f)})}function X(a,b,d,c,f,g,h,q){var k;try{k=a[c+"_"+f](b,d,g,h,q)}catch(m){try{k=a[f](c,b,d,g,h,q)}catch(w){doException("raiseEvent",w)}}return k}function Pa(a,b){$.isFunction($(a).block)&&(b?$(a).block({message:null,overlayCSS:{opacity:0.1}}):$(a).block({message:null,overlayCSS:{opacity:0}}))}function xa(a){$.isFunction($(a).unblock)&&$(a).unblock()}function Ba(a,b){try{logDebug(b),Ia.Form_onMicrophone(a)}catch(d){doNothing()}}
function ib(a,b,d,c){logDebug("========== START BROADCAST TO FORM");l(function(f){if("#"+f.id==a){try{logDebug("broadcast "+b+"."+d+" ("+JSON.stringify(c)+") to: "+f.id),f.formobject.Form_onBroadcast(b,d,c)}catch(g){doException("broadcastToForm",g)}return!0}});logDebug("========== END BROADCAST TO FORM")}function Qa(a,b){var d=!1;if(!0===b)d=!0;else{var c=!1;l(function(b){if(b.name==a)return c=!0});d=!1===c}return d}function la(a,b){jb(a);c.element(a).replaceWith("");var d=null,e=Da.pop();$.isFunction(e.FormResult)&&
(d=e.FormResult());var e=Fa.pop(),f=Ga.pop();c.setFormFocus(e,f,!0);e=Ea.pop();$.isFunction(e)&&e(d,b);Q="";$("#ge-modal-layer").addClass("gb-hidden")}function Ra(a){var b="";l(function(d){if(d.name==a)return b=d.id,!0});return b}function kb(a){var b=str_replace(a,"#","");l(function(a){a.id===b?a.tag=a.visible:(a.tag=a.visible,a.visible=!1,c.element("#"+a.id).hide())})}function Sa(a){var b=str_replace(a,"#","");l(function(d){if(d.id==b)return d.visible=!1,c.element("#"+a).hide(),!0});ya()}function za(a){var b=
str_replace(a,"#","");l(function(d){if(d.id==b)return d.visible=!0,c.element("#"+a).show(),!0});ya()}function lb(){l(function(a){a.visible=a.tag;a.visible&&c.element("#"+a.id).show()})}function Y(){logDebug("========== START FORMS");mb(function(a){"#"+a.id==H?logDebug("id: "+a.id+", name: "+a.name+" (focus), top: "+a.top+", left: "+a.left):logDebug("id: "+a.id+", name: "+a.name+", top: "+a.top+", left: "+a.left)});logDebug("========== END FORMS")}function W(a){var b=!1,d=null,e=0,f=0;l(function(b){"#"+
b.id=="#"+a&&(d=b.formobject)});try{if(null!==d){e=c.element("#"+a,".gb-form").height();if(d.fullwidth){var g=0;G&&(g=z);f=c.getViewPort().width-g-P}else f=c.element("#"+a,".gb-form").width();b=!0;$.isFunction(d.Form_onResize)&&d.Form_onResize(f,e)}}catch(h){doException(h)}b&&(c.element("#"+a,".gb-formclose-panel").css("left",f-Za+"px"),c.element("#"+a,".gb-formtitle-panel").css("width",f-O+"px"),c.element("#"+a,".gb-formtitle-inner-panel").css("width",f-O+"px"))}function M(a,b){var d=!1,e=b;void 0===
e&&(e=500);processArray(T,function(b){b.id==a&&b.active&&(d=!0)});d||(d=!1,processArray(T,function(b){b.id==a&&!b.active&&(d=!0,b.active=!0)}),d||T.push({id:a,active:!0}),c.after(e,function(){c.resizeDockedForm("#"+a)&&W(a);V()&&W(t);processArray(T,function(a){if(a.active)return c.broadcast("system","viewport","change"),I++,logDebug("ViewPortChangeCount:"+I),!0});processArray(T,function(a){a.active&&(a.active=!1)})}))}function Ta(a,b,d){logDebug("tab broadcast received: "+a+"."+b+" ("+JSON.stringify(d)+
")");"system"===a&&"ping"===b?doNothing():c.broadcast("system",a,b,d,!0)}function mb(a){processArray(ia,function(b){$.isFunction(a)&&a(b)})}function l(a){processArray(ia,function(b){if("unregistered"!==b.id&&$.isFunction(a)&&a(b))return!0})}function Ua(a,b,d,c,f,g,h,q,k){a=str_replace(a,"#","");b={canvasbottom:gb,canvastop:p,dockable:q,footer:g,formified:k,formobject:d,id:a,landing:c,left:0,left_store:0,menu:!1,name:b,resizable:h,tag:null,taskbar:f,top:0,top_store:0,visible:!0};c=null;try{c=X(d,d,
d,"Form","getVue"),null!==c&&void 0!==c&&(c.el="#"+a,d.vue=new Vue(c))}catch(m){doException("registerFormInstance",m)}ia.push(b);Y()}function nb(a){processArray(a,function(a){try{$(a).hasClass("gb-preservetab")?$(a).attr("tabindex","99"):$(a).removeAttr("tabindex")}catch(d){doException("removeTabs",d)}})}function jb(a){var b=str_replace(a,"#","");l(function(a){if(a.id==b)return a.footer=!1,a.formobject=!1,a.fullwidth=!1,a.id="unregistered",a.landing=!1,a.menu=!1,a.name="unregistered",a.taskbar=!1,
a.visible=!1,a.tag=null,!0});Y()}function ob(){var a=[];$(".gb-forminstance","#ge-form-container").each(function(){var b=parseInt($(this).children(".gb-form").css("z-index"),10);b||(b=0);b<da&&(b={formid:$(this).attr("id"),zorder:b},a.push(b))});a.sort(function(a,b){return a.zorder>b.zorder});var b=Ca;processArray(a,function(a){c.element("#"+a.formid,".gb-form").css("z-index",b);b++});b=Ca+da;$("#ge-busyindicator").css("z-index",b)}function ya(){Ya&&l(function(a){var b=c.element("#"+a.id,".gb-form").css("z-index");
c.element("#"+a.id,".zorderdebug").remove();c.element("#"+a.id,".gb-form").append('<font class="zorderdebug" style="color:red;"><b>'+b+"</b></font>")})}function N(a,b){var d=b;void 0===d&&(d=!1);var e=0,f=null;Q==a&&(d=!0);ob();$("div.gb-form").each(function(){var a=parseInt($(this).css("z-index"),10);a>e&&a<da&&(e=a)});$("div.gb-page").each(function(){var a=parseInt($(this).css("z-index"),10);a>e&&a<da&&(e=a)});e++;d?($("#ge-modal-layer").css("z-index",e),$("#ge-modal-layer").removeClass("gb-hidden"),
e++):$("#ge-modal-layer").hasClass("gb-hidden")?doNothing():$("#ge-modal-layer").addClass("gb-hidden");c.element(a,".gb-form").css("z-index",e);l(function(b){if("#"+b.id==a)return f=b.formobject,!0});if(null!==f)try{f.Form_onBringToFront()}catch(g){doNothing()}d=c.element(a,".gb-form").css("top");void 0!=d&&(d=d.replace("px",""),0>parseInt(d,10)&&c.element(a,".gb-form").css("top",p+"px"));ya()}function pb(a,b,d,e,f,g,h){b=void 0===b?{}:"string"===typeof b?c.urlToJSON(b):b;a=this.ajaxRequestCreate("core_showform_device",
[{name:"formname",value:a},{name:"params",value:b},{name:"center",value:d},{name:"formoffsetx",value:e},{name:"formoffsety",value:f},{name:"bypassdirtycheck",value:g}]);this.ajaxCall(URL_WEBSERVICE,a,function(a){a.result&&$.isFunction(h)&&h()},doNothing)}function qb(a){var b,d,c,f;b=a+"=";d=b.length;c=document.cookie.length;for(f=0;f<c;){a=f+d;if(document.cookie.substring(f,a)==b)return b=document.cookie.indexOf(";",a),-1==b&&(b=document.cookie.length),unescape(document.cookie.substring(a,b));f=document.cookie.indexOf(" ",
f)+1;if(0===f)break}return null}function Aa(a,b){var d,c,f,g,h;c=Aa.arguments;d=Aa.arguments.length;g=2<d?c[2]:null;h=3<d?c[3]:null;f=4<d?c[4]:null;d=5<d?c[5]:!1;f=a+"="+escape(b)+(null===g?"":"; expires="+g.toGMTString())+(null===h?"":"; path="+h)+(null===f?"":"; domain="+f)+(!0===d?"; secure":"");document.cookie=f}function Z(a,b,d,e,f,g,h,q,k,m,w,x){var r="";c.lazyLoadForm(a,function(){r=rb(a,b,d,e,f,g,h,q,k,m,w);$.isFunction(x)&&x(r)});return r}function rb(a,b,d,e,f,g,h,q,k,m,w){c.showBusyIndicator();
void 0===m&&(m=!1);void 0===w&&(w=!1);var x=!1,r=null,n;n=void 0===b?{}:"string"===typeof b?c.urlToJSON(b):b;a=str_replace(a,"-",".").split(".");a=a[0]+"_"+a[1];try{var v="form_"+getGUID(),s="",r=new window[a](c,"#"+v,n),u=!0;Fa.push(S);Ga.push(H);Ea.push(d);Da.push(r);f&&0===Q.length&&(Q="#"+v,x=!0);var y=0<c.element("#"+a+"Template",".gb-form").find(".gb-formtitle-inner-panel").length,E=c.element("#"+a+"Template",".gb-form").hasClass("gb-dockable");c.element("#"+a+"Template",".gb-form").hasClass("gb-alwaysdocked")||
(E=E&&!c.isMDI());try{u=r.Form_allowMultipleInstances()}catch(A){u=!0}d="";try{d=r.Form_getDesktopRegion()}catch(B){doNothing()}0===d.length&&(d="CAS",E&&!c.isMDI()&&(d="FS"));f=!0;var V=!1;E&&!w&&(s=c.getDirtyDockableOpenForms(),0<s.length?(f=!1,V=!0,c.hideBusyIndicator(),c.dialogAlert("You are currently editing a form, please save or cancel your changes first.",doNothing)):f=!0);if(f&&(f=f&&Qa(a,u),!0===f))if(r.Form_onPermissionCheck()){var z=c.element("#"+a+"Template",".gb-form").hasClass("gb-resizable");
sb("#"+a+"Template",v,a,e,x,g,y,q,k,z,m,d,b);Ua(v,a,r,!1,g,h,z,E,m);X(r,r,r,"Form","onLoad");hb(v,z,E);E&&c.element("#"+v,".gb-form").addClass("gb-docked")}else doNothing();V||(f||(v=0<s.length?s:Ra(a),l(function(a){if("#"+a.id=="#"+v)return r=a.formobject,!0}),N("#"+v,!1)),v==t?Sa(v):(za(v),g&&(p=parseInt(c.element(D,".gb-form").css("height"),10)-eb)),c.setFormFocus(r,"#"+v,!0,n),N("#"+v,!1),ga("send","pageview","#"+a))}catch(C){doException("createForm2",C)}c.hideBusyIndicator();return v}function sb(a,
b,d,e,f,g,h,q,ka,m,w,x,r){var l=k.container,n=!1;void 0==w&&(w=!1);d=!1;0===q&&0===ka&&(d=!0,window.scrollTo(0,0));var s="";void 0==q&&(q=c.isMDI()?bb:0);void 0==ka&&(ka=cb);s=c.element(a,".gb-form").hasClass("gb-invisible");void 0!==r&&(void 0!==r.containerid&&0<r.containerid.length)&&(l=r.containerid,n=!0,console.log("container id is : "+l));!0===s?s='<div id="'+b+'" class="gb-invisible">'+c.element(a).html()+"</div>":(r="",w?(r=c.element(a,".wr-body").html(),void 0==r?(r=c.element(a).html(),s=
'<div id="'+b+'" class="gb-forminstance">'+r+"</div>"):(s='<div id="'+b+'" class="gb-forminstance ">'+('<div class="gb-form gi-background-form gs-form-standard gs-shadow" style="width:'+ca+"px; height:"+ba+'px;">'),s+=r,s+="</div>",s+="</div>")):(r=c.element(a).html(),s='<div id="'+b+'" class="gb-forminstance">'+r+"</div>"));n?c.element("#"+l,".ge-container-panel-content").append('<div style="position:relative">'+s+"</div>"):c.element("#"+l).append(s);w?(c.element("#"+b,".gb-notformifiedonly").remove(),
c.element("#"+b,".gb-panel-resize").css("overflow-x","hidden"),c.element("#"+b,".gb-panel-resize").css("overflow-y","auto")):c.element("#"+b,".gb-formifiedonly").remove();h&&c.element("#"+b,".gb-form").prepend('<div class="gs-to768"><div style="height:50px;"></div></div><div class="gs-from768"><div style="height:50px;"></div></div>');tb(b);void 0===e&&(e=!1);a=0;h=p;g?doNothing():e&&c.hasCapability("viewport")?(a=0.5*c.getViewPort().width-0.5*c.element("#"+b,".gb-form").width(),h=p):d?h=a=0:(c.isMDI()&&
0===B&&(B=z),B+=q,c.isMDI()?(B>z+ab&&(B=z),K+=ka,K>$a*c.getViewPort().height/100&&(K=0)):K=B=0,a=B+$(document).scrollLeft(),h=p+K+$(document).scrollTop());!0===c.element("#"+b).hasClass("gb-invisible")?(c.element("#"+b).css("position","absolute").css("top",0).css("left",0).css("width",0).css("height",0),c.element("#"+b,".gb-form").css("position","absolute")):(!0===c.element("#"+b).hasClass("gs-form-standard")?(c.element("#"+b).css("position","absolute").css("top",0).css("left",0).css("width",0).css("height",
0),m&&c.element("#"+b,".gs-form-standard").css("position","absolute").css("width",ca+"px").css("height",ba+"px")):!0===c.element("#"+b).hasClass("gs-form-headerless")?(c.element("#"+b).css("position","absolute").css("top",0).css("left",0).css("width",0).css("height",0),m&&c.element("#"+b,".gs-form-standard").css("position","absolute").css("width",ca+"px").css("height",ba+"px")):(c.element("#"+b).css("position","absolute").css("top",0).css("left",0).css("width","100%").css("height",0),c.element("#"+
b,".gb-form").css("position","absolute").css("top",h).css("left",a),m&&(g=e=0,e=x,c.getViewPort().width>=Wa||(e=str_replace(e,"L",""),e=str_replace(e,"R","")),c.getViewPort().height>=Xa||(e=str_replace(e,"T",""),e=str_replace(e,"B","")),0===e.length&&0<x.length&&(e="FS"),"TL"==e?(h=c.getCanvasTop(),a=c.getCanvasLeft(),e=0.5*c.getCanvasWidth(),g=0.5*c.getCanvasHeight()):"TR"==e?(h=c.getCanvasTop(),a=c.getCanvasLeft()+0.5*c.getCanvasWidth(),e=0.5*c.getCanvasWidth(),g=0.5*c.getCanvasHeight()):"BL"==
e?(h=c.getCanvasTop()+0.5*c.getCanvasHeight(),a=c.getCanvasLeft(),e=0.5*c.getCanvasWidth(),g=0.5*c.getCanvasHeight()):"BR"==e?(h=c.getCanvasTop()+0.5*c.getCanvasHeight(),a=c.getCanvasLeft()+0.5*c.getCanvasWidth(),e=0.5*c.getCanvasWidth(),g=0.5*c.getCanvasHeight()):"T"==e?(h=c.getCanvasTop(),a=c.getCanvasLeft(),e=c.getCanvasWidth(),g=0.5*c.getCanvasHeight()):"B"==e?(h=c.getCanvasTop()+0.5*c.getCanvasHeight(),a=c.getCanvasLeft(),e=c.getCanvasWidth(),g=0.5*c.getCanvasHeight()):"L"==e?(h=c.getCanvasTop(),
a=c.getCanvasLeft(),e=0.5*c.getCanvasWidth(),g=c.getCanvasHeight()):"R"==e?(h=c.getCanvasTop(),a=c.getCanvasLeft()+0.5*c.getCanvasWidth(),e=0.5*c.getCanvasWidth(),g=c.getCanvasHeight()):"FS"==e?(h=c.getCanvasTop(),a=c.getCanvasLeft(),e=c.getCanvasWidth(),g=c.getCanvasHeight()):"C"==e?(h=0.1*c.getViewPort().height,a=0.1*c.getViewPort().width,e=0.8*c.getViewPort().width,g=0.8*c.getViewPort().height):(e=ca,g=ba),c.element("#"+b,".gs-form-standard").css("position","absolute").css("top",h).css("left",
a).css("width",e+"px").css("height",g+"px"))),N("#"+b,f))}function tb(a){c.element("#"+a,"img").each(function(a,d){try{var c=$(d).attr("dynamicsrc");0<c.length&&(c=str_replace(c,"%DYNAMIC_BRANDING%",DYNAMIC_BRANDING),c=str_replace(c,"%DYNAMIC_APP_DIR_URL%",DYNAMIC_APP_DIR_URL),$(d).attr("src",c))}catch(f){doNothing()}})}function ub(a,b){var d=[],c=0;processArray(a,function(a){a.moduleid==b&&!1===a.loaded&&(d[c]=a,c++)});return d}function u(a,b,d,e){function f(){c.transmissionIndicator(!1);$.isFunction(e)&&
e(!1)}function g(){c.transmissionIndicator(!1);$.isFunction(e)&&e(!0)}c.transmissionIndicator(!0);if("js"===d)$.ajax({url:b,dataType:"script",cache:!0,success:g,error:f});else if("html"===d){d="lazy_"+a;var h=$("#"+d).html();void 0===h||0===h.length?($("#ge-lazyload-container").append('<div id="'+d+'" class="gb-hidden"></div>'),$("#"+d).load(b,function(){logDebug("Lazy Load Success: "+a);g()})):g()}}function vb(a){var b;c.processArray(qa,function(d){d.key==a&&(b=d)});return b}function wb(a){var b=
"";processArray(J,function(d){if(d.eventqueue==a)return b=d.broadcastformid,!0});return b}function xb(a){var b={};processArray(a,function(a){var e=wb(a.eventqueue);if(0<e.length){b={};if(0<a.eventdata.length)try{b=JSON.parse(a.eventdata)}catch(f){doNothing()}"system"==e?"formqueue"===a.eventqueue&&"showform"===a.eventname&&c.showForm(b.formname,b.params,b.center,b.formoffsetx,b.formoffsety,b.bypassdirtycheck):ib(e,a.eventqueue,a.eventname,b)}else b=JSON.parse(a.eventdata),c.broadcast("system",a.eventqueue,
a.eventname,b)})}function Va(a){processArray(ra,function(b){$.isFunction(a)&&a(b)})}function yb(a,b){var d={id:str_replace(a,"#",""),timerobject:b};ra.push(d);logDebug("timer registered: "+d.id)}function zb(a){var b=str_replace(a,"#","");Va(function(a){a.id==b&&(a.timerobject.stop(),logDebug("timer unregistered: "+a.id),a.id="unregistered",a.timerobject=null)});Y()}function Ab(a){var b=[];processArray(a,function(a){var c=a.element,f=a.help;a=a.position;var g={};void 0===c?(g={intro:f},b.push(g)):
c.is(":visible")&&(g={element:c[0],intro:f,position:a},b.push(g))});return b}c.initialise=function(){na=os().getArgs().child;var a=os().getArgs().tabID;c.element("#ge-browsers").remove();c.shortcutAdd(g_objShortcuts.keycloseform,function(){c.closeFormFocus()});processArray(g_objShortcutsOverride,function(a){c.shortcutAdd(a.keys,doNothing)});$(document).unbind("keydown").bind("keydown",function(a){var b=!1;8===a.keyCode&&(b=a.srcElement||a.target,b="INPUT"===b.tagName.toUpperCase()&&("TEXT"===b.type.toUpperCase()||
"PASSWORD"===b.type.toUpperCase())||"TEXTAREA"===b.tagName.toUpperCase()?b.readOnly||b.disabled:!0);b&&a.preventDefault()});$(window).bind("beforeunload",function(){if(k.unloadprompt)return APP_NAME+"\n\nPlease be sure you have saved your data before continuing."});c.hasCapability("multimon")&&(na?(A=new childTabHandler({id:a,cbOnBroadcast:Ta,window:window}),c.createTimer(A.ping,1E4,!0)):A=new parentTabHandler({cbOnBroadcast:Ta,window:window}));0<DEVICEIDCOOKIE.length?y=DEVICEIDCOOKIE:(y=qb(COOKIE_DEVICENAME),
null===y&&(y=""),0===y.length&&(a=new Date,a.setYear(parseInt(a.getFullYear(),10)+COOKIE_EXPIRY),y=getGUID(),Aa(COOKIE_DEVICENAME,y,a)));try{c.element("#ge-zoom2-container").get(0).style.left=c.element("#ge-zoom1-container").get(0).offsetLeft+"px",sa=c.element("#ge-zoom1-container").get(0).offsetLeft}catch(b){doException("initialise",b)}$.isFunction(k.orientation)&&(a=function(){var a=c.getOrientation();a!==g_intPreviousOrientation&&(g_intPreviousOrientation=a,k.orientation(a),c.broadcast("system",
"orientation","change"))},window.addEventListener("resize",a,!1),window.addEventListener("resize",function(a){l(function(a){a.resizable&&M(a.id)});M(t);c.menuToFront()},!1),window.addEventListener("orientationchange",a,!1),setInterval(a,2E3));k.keepalive&&c.hasCapability("timers")&&c.registerServerEvent("keepalive")};c=this;this.addUniqueID=function(a){var b="elementid-"+getGUID();a.attr("id",b);return b};this.getArgs=function(){return k};this.getForms=function(){return ia};this.getTabs=function(){var a=
[];c.hasCapability("multimon")&&(a=A.getTabs());return a};this.getTimers=function(){return ra};this.getVersion=function(){return"AWAFOS v20241106.0"};this.logout=function(a,b){c.setUnloadPrompt(!1);c.hasCapability("timers")&&c.deleteTimersAll();c.after(500,function(){c.gotoURL(APP_LOGOUT,a,b)})};this.clientReturn=function(a,b){c.setUnloadPrompt(!1);c.hasCapability("timers")&&c.deleteTimersAll();c.after(500,function(){c.gotoURL(APP_RETURN,a,b)})};this.reboot=function(a,b){c.setUnloadPrompt(!1);c.hasCapability("timers")&&
c.deleteTimersAll();c.after(500,function(){c.gotoURL(APP_HOME,a,b)})};this.isChild=function(){return na};this.gotoURL=function(a,b,d){void 0===d&&(d="");0<d.length&&logDebug("URL redirect from:"+d+" to: "+a);a=c.makeURL(a,b);d!=a&&(location=a)};this.isModuleLoaded=function(a){return 0<=(","+CLIENTMODULES+",").indexOf(","+a+",")};this.makeURL=function(a,b){var d=a;if(void 0!==b&&0<b.length)for(var c=b.split("&"),f=0;f<c.length;f++){var g=c[f].split("="),h=g[0],g=g[1],q="?",k="",m=0;0===d.indexOf("#")&&
(q="&");m=d.indexOf("?");-1!=m&&(q="&");if(0<k.length){for(var k=k.split("&"),l="",m=0;m<k.length;m++){var x=k[m].split("=");x[0]!=h&&(0<l.length&&(l+="&"),l+=x[0]+"="+x[1])}k=l+"&"+h+"="+g}else k=h+"="+g;d=d+q+k}return d};this.isApp=function(a){var b=!1;processArray(a,function(a){if(a.toUpperCase()==APP_CODE.toUpperCase())return b=!0});return b};this.setBackground=function(a){$("html").addClass(a)};this.setFocus=function(){window.focus()};this.entityDataCache=new function(){function a(a,b){L=L.filter(function(a,
d){return d!==b});logDebug("%c"+a+" cached purged","color:red;")}function b(a){var b="";processArray(a,function(a){"formentitycode"===a.name&&(b=a.value)});return b}function d(a){var b;processArray(wa,function(d){d.name===a&&(b=d)});return b}var c=this;this.addToCache=function(a,d){var h=c.findCachedData(a),k=a.AWAFOS.parameters,l=JSON.stringify(k),m=a.AWAFOS["function"],k=b(k);-1===h&&0<k.length&&(L.push({"function":m,entity:k,request:l,response:d,time:new Date}),logDebug("%c"+k+" data cached","color:green;"))};
this.findCachedData=function(a){var d=-1,h=a.AWAFOS.parameters,k=JSON.stringify(h),l=a.AWAFOS["function"],m=b(h);c.isCachable(a)&&0<L.length&&processArray(L,function(a,b,c){if(0<m.length&&a.entity===m&&a["function"]===l&&a.request===k)return d=c,!0});return d};this.isCachable=function(a){var d=!1,c=b(a.AWAFOS.parameters);0<c.length&&0<wa.length&&processArray(wa,function(a){if(a.name===c)return d=!0});return d};this.readCache=function(f){var g,h=f.AWAFOS.parameters;f=c.findCachedData(f);h=b(h);if(0<=
f){var k=d(h),l=L[f];(new Date-l.time)/1E3>k.timeframe?a(h,f):g=l.response}return g}};this.ajaxCall=function(a,b,d,e,f,g){function h(a,g){function h(){try{$.isFunction(d)&&d(a.AWAFOS.response),!n&&c.entityDataCache.isCachable(b)&&c.entityDataCache.addToCache(b,a)}catch(e){doException("ajaxSuccessContinue",e)}}function q(a){try{$.isFunction(e)&&e(f,a)}catch(b){doException("ajaxErrorContinue",b)}}var n=g;void 0!==n&&(n=!1);c.transmissionIndicator(!1);0!==ja&&(ja=0,c.connectionIndicator(!0));if(!1===
l)if(!1===m&&($("body").css("cursor","auto"),xa("#"+k.container)),void 0===a||null===a)q("Undefined or Null Response");else{logDebug("response:"+JSON.stringify(a));logDebug("========== END REQUEST");try{switch(parseInt(a.AWAFOS.responsecode,10)){case 0:c.dialogAlert(a.AWAFOS.message,doNothing);h();break;case 1:c.dialogAlert(a.AWAFOS.message,doNothing);h();break;case 2:l=!0;q(a.AWAFOS.message);break;case 3:c.deleteTimersAll();k.unloadprompt=!1;c.dialogAlert(a.AWAFOS.message,doNothing);location=APP_LOGOUT;
l=!0;break;case 4:var p=a.AWAFOS.response.download;void 0===p&&(p=!0);c.viewDocument(a.AWAFOS.response.document_id,p);h();break;case 5:0<a.AWAFOS.message.length?c.dialogAlert(a.AWAFOS.message,function(){k.unloadprompt=!1;Oa(a.AWAFOS.response)}):(k.unloadprompt=!1,Oa(a.AWAFOS.response));break;case 6:c.reboot("","Server");break;case 7:c.broadcast("system","printer",ENTITY_PRINTJOB);c.dialogAlert(a.AWAFOS.message,doNothing);h();break;default:l=!0,q("Undefined Error")}}catch(w){q("System Error")}}}function q(){logDebug("========== END REQUEST DUE TO ERROR");
ja++;ja>=ERROR_INDICATOR_FAILURECOUNT&&c.connectionIndicator(!1);c.transmissionIndicator(!1);!1===m&&($("body").css("cursor","auto"),xa("#"+k.container));l=!0;try{$.isFunction(e)&&e(f)}catch(a){doException("ajaxRaiseError",a)}}var l=!1,m=g;void 0===m&&(m=!1);c.transmissionIndicator(!0);g=c.entityDataCache.readCache(b);c.viewDocument=function(a,b){var d=c.getFileDownloadURL(encodeURIComponent(a)),d=b?d+"&download=true":d+"&download=false";0<d.length&&(c.setUnloadPrompt(!1),window.open(d),c.after(3E3,
function(){c.setUnloadPrompt(!0)}))};if(void 0!==g){logDebug("%ccache hit","color:green;");logDebug("========== START CACHE FETCH");logDebug("request:"+JSON.stringify(b));g.AWAFOS.dataid=b.AWAFOS.dataid;try{$.isFunction(d)&&h(g,!0)}catch(n){}}else USEJSONP?(logDebug("%ccache miss","color:red;"),logDebug("========== START AJAX JSONP"),logDebug("request:"+JSON.stringify(b)),!1===m&&(Pa("#"+k.container,!1),$("body").css("cursor","wait")),$.ajax({type:"GET",async:!0,url:a+"?json="+encodeURIComponent(JSON.stringify(b))+
"&callback=?",data:JSON.stringify(b),contentType:"application/x-www-form-urlencoded; charset=utf-8",dataType:"jsonp",success:h,error:q})):(logDebug("%ccache miss","color:red;"),logDebug("========== START AJAX JSON"),logDebug("request:"+JSON.stringify(b)),!1===m&&(Pa("#"+k.container,!1),$("body").css("cursor","wait")),$.ajax({type:"POST",async:!0,url:a,data:JSON.stringify(b),contentType:"application/x-www-form-urlencoded; charset=utf-8",dataType:"json",success:h,error:q}))};this.ajaxError=function(a,
b){var d=b;void 0===d&&(d="Connection Error");$("body").css("cursor","auto");xa("#"+k.container);c.hideBusyIndicator();c.dialogAlert("Attention: "+d,doNothing);$.isFunction(a)&&a()};this.ajaxRequestCreate=function(a,b,d){void 0===d&&(d="sys"+La,La++);return{AWAFOS:{securitytoken:SECURITY_TOKEN,clientversion:CLIENT_VERSION,deviceidcookie:y,payload:PAYLOAD,callerid:CALLERID_PUBLIC,dataid:d,"function":a,parameters:b}}};this.fileDownload=function(a){a=c.getFileDownloadURL(a);$.fileDownload(a).done(doNothing).fail(function(){c.ajaxError("File not found.")})};
this.getFileDownloadURL=function(a){return"ws/server.php?token="+SECURITY_TOKEN+"&document="+a};this.initialiseScrollbars=function(a){c.isMDI()||a?($("body").css("overflow","auto"),P=20):($("body").css("overflow-x","hidden"),$("body").css("overflow-y","hidden"),P=0)};this.repositionForm=function(a,b,d){c.element(a,".gb-form").css("top",b+"px");c.element(a,".gb-form").css("left",d+"px")};this.resizeDockedForm=function(a){var b=!1;if(c.isDockable(a)){var b=p,d=0;G&&(d=z);var e=c.getViewPort().height-
b-R+1,f=c.getViewPort().width-d-P,g="TRUE"==TESTSCROLL&&!c.hasCapability("regionscroll")&&c.hasCapability("mobile");c.element(a,".gb-form").removeClass("gs-shadow");c.element(a,".gb-form").removeClass("gs-form-standard");c.element(a,".gb-form").css("top",b+"px");c.element(a,".gb-form").css("left",d+"px");g?c.element(a,".gb-form").css("width","100%"):c.element(a,".gb-form").css("width",f+"px");c.element(a,".gb-form").css("height",e+"px");c.element(a,".gb-formtitle-panel").css("width",f-O+"px");b=!0}return b};
this.resizeForm=function(a,b,d){c.element(a,".gb-form").css("height",b+"px");c.element(a,".gb-form").css("width",d+"px");c.element(a,".gb-formtitle-panel").css("width",d-O+"px")};this.resizeAndRepositionForm=function(a,b,d,e,f){c.element(a,".gb-form").css("top",b+"px");c.element(a,".gb-form").css("left",d+"px");c.element(a,".gb-form").css("height",e+"px");c.element(a,".gb-form").css("width",f+"px");c.element(a,".gb-formtitle-panel").css("width",f-O+"px")};this.getAgent=function(){return ua};this.getBrowser=
function(){return n};this.getBrowserCapabilities=function(){var a=c.getBrowser().incapabilities.split(" "),b=2,d="";void 0===va&&(processArray(a,function(a){a=a.replace("</del>","");a=a.replace("<del>","-");0<$.trim(a).length&&(d=0===b%20?$.trim(d+" "+a)+"\r\n":d+" "+a,b++)}),va=d);return va};this.getBrowserCapabilityInfo=function(a){var b;processArray(g_objCapabilities,function(d){if(d.code==a&&"hidden"!==d.description)return b=d,!0});return b};this.getBrowserRecommendation=function(){var a="";"passable"===
n.support?a="A browser upgrade is recommended.":"unsupported"===n.support&&(a="A browser upgrade is recommended.");return a};this.getBrowserVersion=function(){return n.version};this.getDeviceIDCookie=function(){return y};this.getHealth=function(){c.getAgent();var a=c.getMapProvider();0===a.length&&(a="none");var b=c.getPrinterProvider();0===b.length&&(b="none");var d=c.getSpeechProvider();0===d.length&&(d="none");var e='<table style="width:80%; margin:auto;" border="1"><thead style="background-color:yellow"><tr><td style="text-align:left;"><b>&nbsp;Feature</b></td><td style="text-align:center;"><b>&nbsp;Enabled&nbsp;</b></td><td style="text-align:center;"><b>&nbsp;Disabled&nbsp;</b></td><td style="text-align:center;"><b>&nbsp;Notes</b></td></tr></thead><tbody>',
f=c.getBrowser().incapabilities.split(" ");processArray(f,function(f){var h=f;f=0>h.indexOf("<del>");var k="",h=h.replace("</del>",""),h=h.replace("<del>",""),h=$.trim(h);0<h.length&&(h=c.getBrowserCapabilityInfo(h),void 0!==h&&("maps"===h.code?"none"===a&&(k='<b><font color="red"><br><br>Mapping is unavailable. A map provider is not configured.</font></b><hr>',f=!1):"speech"===h.code&&"none"===d&&(k='<b><font color="red"><br><br>Speech recognition is unavailable. A map speech recognition is not configured.</font></b><hr>',
f=!1),"java"===h.code&&(Na?f=!0:(k='<b><font color="red"><br><br>For certain features to be available, please ensure that Java is correctly installed on this device <a href="'+URL_VERIFY_JAVA+'" target="_blank">verify your Java version</a>.</font></b><hr>',f=!1)),"printer"===h.code&&"none"===b&&(k='<b><font color="red"><br><br>Printing is unavailable. Please be sure that the Java Printing Utility is installed. Refer to your software vendor for information.</font></b><hr>',f=!1),e+="<tr>",e=e+'<td style="vertical-align:top; text-align:left; width:200px;">&nbsp;'+
h.description+"</td>",e=f?e+'<td style="vertical-align:top; text-align:center;"><i class="fa fa-check" aria-hidden="true"></i></td><td>&nbsp;</td>':e+'<td>&nbsp;</td><td style="vertical-align:top; text-align:center;"><b>X</b></td>',e=e+'<td style="text-align:left;">&nbsp;'+h.notes+" "+k+"</td>",e+="</tr>"))});return e+="</tbody></table>"};this.getOrientation=function(){var a=0;try{a=void 0===window.orientation?0:parseInt(window.orientation,10)}catch(b){doNothing()}return a};this.getOS=function(){return n.OS};
this.getViewPort=function(){var a=0,b=0,b=window,d="inner";"innerWidth"in window||(d="client",b=document.documentElement||document.body);a=b[d+"Height"];b=b[d+"Width"];return{width:b,height:a}};this.hasCapability=function(a){var b=","+n.capabilities+",",d=!1;"geolocation"===a?navigator.geolocation&&(d=!0):d=0<=b.indexOf(","+a+",");return d};this.initialiseViewPort=function(){var a="";"device-width"===DEVICE_WIDTH&&(a="1.0");for(var b=document.getElementsByTagName("meta"),d=0;d<b.length;d++)"viewport"==
b[d].name&&(b[d].content="width="+DEVICE_WIDTH+", initial-scale="+a+", minimum-scale="+a+", maximum-scale=3.0",c.after(500,function(){c.broadcast("system","viewport","change");I++;logDebug("ViewPortChangeCount3:"+I)}))};this.getCanvasHeight=function(){return c.getViewPort().height-p-R+1};this.getCanvasLeft=function(){var a=0;G&&(a=z);return a};this.getCanvasTop=function(){return p};this.getCanvasWidth=function(){var a=c.getCanvasLeft();return c.getViewPort().width-a-P};this.getFormHeight=function(a){return parseInt(c.element(a,
".gb-form").height(),10)};this.getFormCanvasHeight=function(a){var b=0<c.element(a,".gb-form").find(".gb-formtitle-inner-panel").length,d=c.getFormHeight(a);b&&(a=parseInt(c.element(a,".gb-form").find(".gb-formtitle-inner-panel").height(),10),d-=a);return d};this.isMDI=function(){var a=c.toBoolean(c.getProperty("ismdi")),b=c.hasCapability("mobile");return a&&!b};this.resetViewPort=function(){if(c.hasCapability("viewport"))for(var a=document.getElementsByTagName("meta"),b=0;b<a.length;b++)"viewport"==
a[b].name&&(a[b].content=VIEWPORTINITIALSTATE)};this.bindDatePicker=function(a,b,d){c.element(a,b).removeClass("hasDatepicker");c.element(a,b).datepicker(d);var e=parseInt(c.element(a,b).closest(".gb-form").css("z-index"),10);c.element(a,b).css("z-index",e);c.element(a,b).bind("click",function(a,b){var d=parseInt($(this).css("top"),10);e=parseInt($(this).closest(".gb-form").css("z-index"),10);c.$(a.srcElement).css("z-index",e);c.$(a.srcElement).css("top",d);c.$(a.srcElement).datepicker("show")})};
this.bindTimePicker=function(a,b,d){var e=document.createElement("input");e.setAttribute("type","date");e.setAttribute("value","not-a-time");"not-a-time"===e.value?(d=$.isFunction(d.onSelect)?d.onSelect:doNothing,c.element(a,b).wrap('<div style="position:relative"></div>'),c.element(a,b).timeEntry({spinnerIncDecOnly:!0,onChange:d})):doNothing()};this.bindEvent=function(a,b,d,c,f,g){"onenterkey"===f.toLowerCase()?ma(a,b,d,c,g):aa(a,b,d,c,f,g)};this.onDirty=function(a,b,d){$.isFunction(d)&&(b=b.split(","),
processArray(b,function(b){try{c.element(a,"."+b).change(function(a){!0!==this.readOnly&&9!==a.which&&d()}),c.element(a,"."+b).keydown(function(a){!0!==this.readOnly&&9!==a.which&&d()}),c.element(a,"."+b).keyup(function(a){!0!==this.readOnly&&9!==a.which&&d()})}catch(f){logDebug("setting onDirty on field "+a+"."+b+" failed.")}}))};this.unbindEvents=function(a,b){if(0<b.length){var d=b.split(",");processArray(d,function(b){try{c.element(a).find("."+b).unbind()}catch(d){doException("raiseEvent",d)}})}};
this.getMapProvider=function(){return $("#ge-mapprovider-container").html()};this.getDefaultPrinter=function(){var a="";c.isPrinterRegistered()&&(a=F.getDefaultPrinter());return a};this.getPrinterProvider=function(){return Ha};this.getPrinters=function(){var a=[];c.isPrinterRegistered()&&(a=F.getPrinters());return a};this.getPrinterVersion=function(){var a="";c.isPrinterRegistered()&&(a=F.getVersion());return a};this.isPrinterRegistered=function(){var a=!1;null!==F&&(a=!0);return a};this.registerPrinter=
function(a,b){Ha=a;F=b;Na=!0};this.setPrinter=function(a){c.isPrinterRegistered()&&F.setPrinter(a)};this.copyToClipboard=function(a){navigator.clipboard.writeText(a).then(function(){document.execCommand("paste");c.dialogAlert('Copied to clipboard: "'+a+'"',doNothing)},doNothing)};this.getSpeechProvider=function(){return pa};this.isSpeechRegistered=function(){return 0<pa.length};this.processSpeech=function(a,b){var d=!1,e="",f="..."+c.str_right(a,50);Ba(f,a);f=" "+a+" ";processArray(g_objVocab,function(a){0<=
f.indexOf(" "+a.phrase+" ")&&(e=a.action,b?"speech dictate off"===e?f="":e="":f="")});0<e.length&&(c.broadcast("system","speech",e),d=!0);"speech window close"===e&&c.closeFormFocus();return d};this.registerMicrophoneStatus=function(a,b){Ia=a;Ja=b;0<D.length&&c.element(Ja,".gb-indicator-connection")};this.registerSpeech=function(a,b){oa=a;pa=b};this.speechOn=function(){if(c.isSpeechRegistered())try{oa.Form_onBroadcast("speech","speech system on")}catch(a){doNothing()}};this.speechOff=function(){if(c.isSpeechRegistered())try{oa.Form_onBroadcast("speech",
"speech system off")}catch(a){doNothing()}};this.speak=function(a,b){c.broadcast(a,"speak",b)};this.isFormified=function(a){var b=!1;l(function(d){if("#"+d.id==a)return b=d.formified,!0});return b};this.hideForm=function(a){l(function(b){if("#"+b.id===a)return b.tag=b.visible,b.visible=!1,c.element("#"+b.id).hide(),!0})};this.reshowForm=function(a){l(function(b){if("#"+b.id===a)return b.tag=b.visible,b.visible=!0,c.element("#"+b.id).show(),!0})};this.closeFormFocus=function(){var a=!0,b=null;l(function(a){if("#"+
a.id==H)return b=a.formobject,!0});try{null!==b&&(a=b.Form_canClose())}catch(d){a=!0}a&&c.closeForm(H)};this.bindLandingForm=function(a,b,d){var e=null,f={},f=void 0===d?{}:"string"===typeof d?c.urlToJSON(d):d;b=str_replace(b,"-",".");d=b.split(".");var g=d[0]+"_"+d[1],h=a;try{c.lazyLoadDependencies(g_arrDependencies,b,function(a){e=new window[g](c,"#"+h,f);a=!0;try{a=e.Form_allowMultipleInstances()}catch(b){a=!0}!0===Qa(g,a)?(Ua(h,g,e,!0,!1,!1,!1,!1,!1),X(e,e,e,"Form","onLoad")):h=Ra(g);za(h);c.setFormFocus(e,
"#"+h,!0,f);ga("send","pageview","#"+g)})}catch(k){doException("bindLandingForm",k)}};this.broadcast=function(a,b,d,e,f){void 0==b&&doNothing();var g=e;void 0===g&&(g={});e=f;void 0===e&&(e=!1);logDebug("========== START BROADCAST");l(function(c){if("#"+c.id!=a)try{logDebug("broadcast "+b+"."+d+" ("+JSON.stringify(g)+") to: "+c.id),c.formobject.Form_onBroadcast(b,d,g)}catch(e){doException("broadcast",e)}});!1===e&&c.hasCapability("multimon")&&(logDebug("broadcast "+b+"."+d+" ("+JSON.stringify(g)+
") to other tabs"),A.broadcast(b,d,g));logDebug("========== END BROADCAST")};this.canOpenTab=function(){var a=!1;c.hasCapability("multimon")&&(a=A.canCreateTab());return a};this.closeAllForms=function(a){l(function(a){la(a.id,!1)});$.isFunction(a)&&a();Y()};this.closeDockableFormsExcept=function(a,b){l(function(b){b.dockable&&b.id!==a&&la(b.id,!1)});$.isFunction(b)&&b();Y()};this.closeForm=function(a,b){var d=null,e=b;void 0===e&&(e=!1);l(function(b){if("#"+b.id==a)return d=b.formobject,!0});if(null!==
d){var f=!0;try{f=d.Form_canClose()}catch(g){doNothing()}var h=!1;try{h=d.Form_isDirty()}catch(k){doNothing()}f&&(h?c.dialogConfirm("<b>Are you sure you want to close this form?</b><br><br>You have unsaved changes.<br>To stay on this page and save your changes, click <b>Cancel</b>.",function(){la(a,e)}):la(a,e))}};this.closeTab=function(){window.close()};this.dialogAlert=function(a,b,d){var c=BootstrapDialog.SIZE_NORMAL;void 0===d&&(d=!1);d&&(c=BootstrapDialog.SIZE_WIDE);0<a.length&&(void 0===b?alert(a):
BootstrapDialog.show({size:c,title:APP_NAME+" Attention",message:a,buttons:[{label:"Close",action:function(a){$.isFunction(b)&&(a.close(),b())}}]}))};this.dialogAlertScroll=function(a,b){c.dialogAlert(a,b)};this.dialogConfirm=function(a,b,d){void 0===d&&(d=APP_NAME+" Confirmation");void 0===b?doNothing():BootstrapDialog.show({title:d,message:a,buttons:[{label:"OK",action:function(a){$.isFunction(b)&&(a.close(),b())}},{label:"Cancel",action:function(a){a.close()}}]})};this.element=function(a,b){var d=
null;return d=void 0===b?$(a):$(b,a)};this.formToFront=function(a,b){c.isDockable(a)||N(a,b)};this.getDirtyDockableOpenForms=function(){var a="";l(function(b){var d=!1;if(b.dockable){var c=b.formobject;try{d=c.Form_isDirty()}catch(f){doNothing()}}if(d)return a=b.id,!0});return a};this.getFormFromHash=function(a){a=a.replace(/^#/,"");"!"===a.substring(0,1)&&(a=c.str_right(a,a.length-1));if(void 0===a||0===a.length)a="";return a=c.getStrippedAnchor(a)};this.getMenu=function(){return"#"+t};this.getTaskbar=
function(){return D};this.hashChange=function(a){var b=a.replace(/^#/,"");"!"===b.substring(0,1)&&(b=c.str_right(b,b.length-1));if(void 0===b||0===b.length)b="";var d=c.getAncorParameters(b),e=c.urlToJSON(d),b=c.getStrippedAnchor(b);c.showForm(b,d,!1,0,0);c.broadcast("system","hash","change",{old:Ma,"new":a});Ma=a;return e};this.hideLanding=function(a){$("#"+a).hide()};this.hideMDIClose=function(a){c.element(a,".gb-form-close").hide()};this.isButtonEnabled=function(a,b){return!c.element(a,"."+b).hasClass("gb-cell-disabled-xxx")};
this.isDockable=function(a){var b=!1,d=str_replace(a,"#","");l(function(a){if(a.id==d)return b=a.dockable,!0});return b};this.isFormVisible=function(a){var b=!1,d=str_replace(a,"#","");l(function(a){if(a.id==d)return b=a.visible,!0});return b};this.limitInput=function(a,b,d,e){void 0===e&&(e=!1);e?c.element(a,b).inputlimiter({limit:d,remText:"",remFullText:"",limitText:"",boxAttach:!1,boxId:"ge-temp-container"}):c.element(a,b).inputlimiter({limit:d,remText:"%n character%s remaining...",remFullText:"No characters remaining.",
limitText:""})};this.openTab=function(a,b){c.hasCapability("multimon")&&A.canCreateTab()&&A.createTab(EXTEND_PAGE,a,b)};this.populateCombo=function(a,b,d,e,f,g){void 0===e&&(e=!1);void 0===f&&(f=!1);var h="";!1===f&&(h='<option value=""></option>');c.element(a,"."+b).find("option").remove().end();null!==d&&(e&&d.sort(function(a,b){return a.description>b.description}),processArray(d,function(a){var b=a.id,d=a.description;if(void 0===d||null===d||0===d.length)d=a.fieldname;var c=!0;$.isFunction(g)&&
(c=g(a));c&&(h="["===b?h+('<optgroup label="'+htmlEncode(d)+'">'):"]"===b?h+"</optgroup>":h+('<option value="'+htmlEncode(b)+'">'+htmlEncode(d)+"</option>"))}));c.element(a,"."+b).append(h)};this.populateList=function(a,b,d,e,f,g){void 0===e&&(e=!1);void 0===f&&(f=!1);var h="";!1===f&&doNothing();c.element(a,"."+b).find("li").remove().end();null!==d&&(e&&d.sort(function(a,b){return a.description>b.description}),processArray(d,function(a){var d=a.id,c=a.description,e=!0;$.isFunction(g)&&(e=g(a));e&&
(h+='<li><a class="'+b+'-option gb-button" value="'+htmlEncode(d)+'">'+htmlEncode(c)+"</a></li>")}));c.element(a,"."+b).append(h)};this.registerMenu=function(a,b){t=str_replace(b,"#","");c.element("#"+t,".gb-form").css("top",p+"px");c.element("#"+t,".gb-form").css("left","0px");l(function(a){if("#"+a.id==b)return a.menu=!0,a.fullwidth=!1,V(),W(t),!0})};this.registerAndUpdateFooter=function(a,b){fa=b;R=parseInt(c.element(fa,".gb-form").css("height").replace("px",""),10);var d=c.getViewPort().height-
R;c.element(fa,".gb-form").css("left","0px");c.element(fa,".gb-form").css("top",d+"px")};this.registerTaskbar=function(a,b){D=b;c.element(D,".gb-form").css("top","0px")};this.setFormFocus=function(a,b,d,e){void 0===d&&(d=!1);d&&(ha=b);if(0<ha.length&&ha!=b)logDebug("focus bounced: "+b),ha="";else{if(0<H.length)if(void 0===S)doNothing();else try{S.Form_onFocusLost()}catch(f){doException("setFormFocus",f)}S=a;H=b;l(function(a){var d=c.element("#"+a.id,".gb-formtitle-inner-panel");void 0!==d&&("#"+a.id==
b?(d.removeClass("gs-black-background-colour"),d.addClass("gs-navyblue-background-colour"),logDebug("focus: "+a.id+", name: "+a.name)):(d.removeClass("gs-navyblue-background-colour"),d.addClass("gs-black-background-colour")))});try{S.Form_onFocus(e)}catch(g){doException("setFormFocus",g)}}};this.removeStyle=function(a,b,d){var e=c.element(a,b).attr("style"),f=e,g=e.indexOf(d+" ");-1===g&&(g=e.indexOf(d+":"));0<=g&&(d=e.indexOf(";",g),0<=d&&(f=$.trim(e.substring(0,g))+" "+$.trim(e.substring(d+1,e.length))));
c.element(a,b).attr("style",f)};this.addStyle=function(a,b,d,e){c.removeStyle(a,b,d);var f=c.element(a,b).attr("style");c.element(a,b).attr("style",f+(" "+d+":"+e+";"))};this.setFormHeight=function(a,b,d){var e=c.getViewPort().height,f=c.element(a,".gb-spacer").height();if(void 0!==d){if(d<e){f=parseInt((e-d)/f,10);d=e;for(var e="&nbsp;<br>",g=0;g<f;g++)e+="&nbsp;<br>";c.element(a,".gb-spacer").html(e)}c.addStyle(a,b,"height",d+"px")}};this.setTabOrder=function(a,b){nb(c.element("html","*"));var d=
b.split(","),e=null,f=1;processArray(d,function(b){b=$.trim(b);if(0<b.length&&!1===c.element(a,"."+b).hasClass("gb-readonly"))try{e=c.element(a,"."+b),e.attr("tabindex",f.toString()),f++}catch(d){}else doNothing()});e.attr("tabindex","0")};this.isDocked=function(a){return c.element(a,".gb-form").hasClass("gb-docked")};this.hideBusyIndicator=function(){0<C&&(C--,0===C&&$("#ge-busyindicator").hide())};this.showBusyIndicator=function(a){0===C&&c.after(250,function(){0<C&&$("#ge-busyindicator").show()});
C++};this.showElement=function(a,b,d){d?(c.element(a,b).removeClass("gb-hidden"),c.element(a,b).show()):(c.element(a,b).addClass("gb-hidden"),c.element(a,b).hide())};this.showLanding=function(a){$("#"+a).show()};this.destroyMenu=function(a){c.element(a,".ge-burgermenu").addClass("hidden");ea=!1};this.createMenu=function(a){c.element(a,".ge-burgermenu").removeClass("hidden");ea=!0};this.hideMenu=function(){Sa(t);G=!1;l(function(a){a.resizable&&M(a.id,100)});M(t,100)};this.showMenu=function(){ea&&(za(t),
G=!0,l(function(a){a.resizable&&M(a.id,100)}),M(t,100),N("#"+t,!1))};this.menuToFront=function(){N("#"+t,!1)};this.toggleMenu=function(){ea?G?c.hideMenu():c.showMenu():c.hideMenu()};this.makeForm=function(a,b,d,e,f,g,h){c.dialogAlert("os.makeForm is now deprecated",doNothing)};this.showForm=function(a,b,d,e,f,g,h){0<a.length&&(c.toBoolean(ENABLE_XDEVICE)?pb(a,b,d,e,f,g,function(){Z(a,b,null,d,!1,!1,!1,e,f,!1,g,h)}):Z(a,b,null,d,!1,!1,!1,e,f,!1,g,h))};this.showFormLocal=function(a,b,d,c,f,g,h,k){0<
a.length&&Z(a,b,d,c,!1,!1,!1,f,g,!1,h,k)};this.showFormPopup=function(a,b,d,e,f,g){0===Q.length?Z(a,b,d,!0,!0,!1,!1,0,0,!1,f,g):c.dialogAlert("A modal dialog is already open.",doNothing)};this.showMDIClose=function(a){c.element(a,".gb-form-close").show()};this.closeExclusive=function(a){var b=a;void 0===b&&(b="");b=str_replace(b,"#","");l(function(a){if(c.element("#"+a.id,".gb-form").hasClass("gb-nonexclusive")){if(a.id===b||a.visible&&!a.taskbar){var e="",e=str_replace(c.element(b,".gb-form").css("top"),
"px",""),e=parseInt(e,10);a.id===b&&(a.visible=!0,$("#"+a.id).show());e<p&&c.element("#"+a.id,".gb-form").css("top",p+"px")}}else a.id===b?(a.visible=!0,$("#"+a.id).show(),c.element("#"+a.id,".gb-form").css("top",p+"px")):(a.visible=!1,$("#"+a.id).hide())});c.menuToFront()};this.showTaskbar=function(a,b,d,c){str_replace(a,".","-");Z(a,b,null,!1,!1,!0,!1,0,0,!1,d,c)};this.setUnloadPrompt=function(a){k.unloadprompt=a};this.fullZoom=function(a){var b=c.getViewPort(),d=b.width,e=c.element(a,".gb-form").width(),
d=d/e,e=b.height,f=c.element(a,".gb-form").height(),d=Math.min(d,e/f)-0.01;c.element(a,".gb-form").css("margin-left","0px");c.element(a,".gb-form").css("zoom",d);c.element(a,".gb-form").css("-moz-transform","scale("+d+","+d+")");c.element(a,".gb-form").css("-moz-transform-origin","left top");d=parseInt(10*(d+0.05)+"",10)/10;d*=c.element(a,".gb-form").width();b=parseInt(0.5*b.width-0.5*d+"",10);c.element(a,".gb-form").css("margin-left",b+"px")};this.getZoom=function(){var a=100;try{a=c.element("#ge-zoom2-container").get(0).offsetLeft/
c.element("#ge-zoom1-container").get(0).offsetLeft,a=Math.floor(100*(Math.floor(0.01*sa*Math.floor(100*a))/sa))}catch(b){doException("getZoom",b)}return a};this.zoomFormInOut=function(a){c.element(a,".gb-form").hasClass("gb-zoomedout")&&(c.zoomInOut(),$("html, body").animate({scrollTop:c.element(a,".gb-form").offset().top,scrollLeft:c.element(a,".gb-form").offset().left},0))};this.zoomInOut=function(){l(function(a){var b="#"+a.id;if(c.element(b,".gb-form").hasClass("gb-nozoom"))doNothing();else{var d=
1,e="",e=str_replace(c.element(b,".gb-form").css("top"),"px","");a.top=parseInt(e,10);e=str_replace(c.element(b,".gb-form").css("left"),"px","");a.left=parseInt(e,10);ta?c.element(b,".gb-form").hasClass("gb-nozoomxy")?d=4:c.element(b,".gb-form").hasClass("gb-zoomedout")&&(c.element(b,".gb-form").removeClass("gb-zoomedout"),d=4):c.element(b,".gb-form").hasClass("gb-nozoomxy")?d=0.25:!1===c.element(b,".gb-form").hasClass("gb-zoomedout")&&(c.element(b,".gb-form").addClass("gb-zoomedout"),d=0.25);c.element(b,
".gb-form").css("top",(a.top-p)*d+p+"px");c.element(b,".gb-form").css("left",a.left*d+"px");0>a.top*d&&c.element(b,".gb-form").css("top",p+"px");0>a.left*d&&c.element(b,".gb-form").css("left",p+"px")}});ta=ta?!1:!0};this.connectionIndicator=function(a){if(0<D.length){var b=c.element(D,".gb-indicator-connection");b.removeClass("gi-connectionamber");b.removeClass("gi-connectiongreen");b.removeClass("gi-connectionred");a?b.addClass("gi-connectiongreen"):b.addClass("gi-connectionred")}};this.transmissionIndicator=
function(a){if(0<D.length){var b=c.element(".gb-form",".gb-indicator-transmission");a?(0===U&&(b.removeClass("gi-xmitgrey"),b.removeClass("gi-xmitgreen"),b.removeClass("gi-xmitred"),b.addClass("gi-xmitgreen")),U++):(U--,0>=U&&(b.removeClass("gi-xmitgrey"),b.removeClass("gi-xmitgreen"),b.removeClass("gi-xmitred"),b.addClass("gi-xmitgrey"),U=0))}};this.shortcutAdd=function(a,b){var d=a.split(",");processArray(d,function(a){shortcut.add(a,b)})};this.shortcutRemove=function(a){a=a.split(",");processArray(a,
function(a){shortcut.remove(a)})};this.shortcuts=function(){return g_objShortcuts};this.lazyLoadDependencies=function(a,b,d){var e=ub(a,b),f=0,g=e.length,h=0,l=0;if(0===e.length)d(!0);else{var n=function(a,b){var d=a.dependency,c=a.debug;void 0===c&&(c="");"TRUE"===DEBUG_SOURCE&&0<c.length&&(d=c);u("",d,a.type,function(c){c?a.loaded=!0:(alert("lazy load failed: "+d),doException("lazyLoadDependencies","failed to load "+d));b()})},m=k.progresscolour;void 0===m&&(m="white");var p=function(){if(0<e.length){l=
parseInt(100*(f/g),10);f++;void 0!=k.percentage&&$("#"+k.percentage).html(l+"%");void 0!=k.progress&&(h=c.getViewPort().width/100*l,$("#"+k.progress).css({width:h}),$("#"+k.progress).css({"background-color":m}),$("#"+k.percentage).css({color:m}));var a=e.shift();n(a,p)}else void 0!=k.percentage&&$("#"+k.percentage).html("100%"),void 0!=k.progress&&(h=c.getViewPort().width,$("#"+k.progress).css({width:h}),$("#"+k.progress).css({"background-color":m}),$("#"+k.percentage).css({color:m})),d(!0)};p()}};
this.lazyLoadApp=function(a,b){var d=a,d=str_replace(d,".js","");u("",d+".z.js","js",function(a){a?doNothing():u("",d+".js","js",function(a){doNothing()})})};this.lazyLoadForm=function(a,b){var d=str_replace(a,"-","."),e=d.split("."),f=e[0],g=e[1],h=DYNAMIC_APP_DIR_URL+"modules/",k=str_replace(d,".","_");c.lazyLoadDependencies(g_arrDependencies,d,function(a){"TRUE"===DEBUG_SOURCE?u(k,h+f+"/"+g+".js","js",function(a){u(k,h+f+"/"+g+".htm","html",b)}):u(k,h+f+"/"+g+".z.js","js",function(a){a?u(k,h+f+
"/"+g+".z.htm","html",b):u(k,h+f+"/"+g+".js","js",function(a){u(k,h+f+"/"+g+".htm","html",b)})})})};this.lazyLoadLogic=function(a,b){var d=a.toLowerCase(),c=DYNAMIC_APP_DIR_URL+"modules/";"TRUE"===DEBUG_SOURCE?u("",c+"entitylogic/"+d+".js","js",b):u("",c+"entitylogic/"+d+".z.js","js",function(a){a?b(!1):u("",c+"entitylogic/"+d+".js","js",b)})};this.massageClassName=function(a,b){var d=$.trim(a+"_"+b),d=str_replace(d," ",""),d=str_replace(d,"<",""),d=str_replace(d,">",""),d=str_replace(d,"/",""),d=
str_replace(d,"-",""),d=str_replace(d,"&",""),d=str_replace(d,"'","");return d=str_replace(d,'"',"")};this.getProperty=function(a){var b;c.processArray(qa,function(d){d.key==a&&(b=d.value)});return b};this.setProperty=function(a,b){var d=vb(a);void 0===d?(d={key:a,value:b},qa.push(d),logDebug("property added: "+d.key)):(d.value=b,logDebug("property changed: "+d.key))};this.checkServerEvents=function(){var a="";processArray(J,function(b){!0===b.enabled&&(a+=b.eventqueue+" ")});a=$.trim(a);if(0<a.length){var b=
c.ajaxRequestCreate("core_servereventscheck",[{name:"eventqueuelist",value:a}]);c.ajaxCall(URL_WEBSERVICE,b,xb,function(){doNothing()},function(){doNothing()},!0)}};this.disableServerEventQueue=function(a){processArray(J,function(b){b.eventqueue==a&&(b.enabled=!1,logDebug("server event disabled: "+b.eventqueue))})};this.enableServerEventQueue=function(a){processArray(J,function(b){b.eventqueue==a&&(b.enabled=!0,logDebug("server event enabled: "+b.eventqueue))})};this.registerServerEvent=function(a,
b){var d=b;void 0===d&&(d="");var c=!1;processArray(J,function(b){if(b.eventqueue==a)return c=!0});c||(d={eventqueue:a,enabled:!0,broadcastformid:d},J.push(d),logDebug("server event registered: "+d.eventqueue))};this.after=function(a,b){if($.isFunction(b))var d=window.setInterval(function(){try{b()}catch(a){doNothing()}d=window.clearInterval(d)},a)};this.createTimer=function(a,b,d){function e(){$.isFunction(a)&&0<b&&(g.pause(),a(),g.play())}var f="timer_"+getGUID();c.element("#ge-timer-container").append('<div id="'+
f+'" class="gb-hidden"></div>');var g=null;try{g=$.timer(e,b,d),yb(f,g)}catch(h){c.dialogAlert("Timer Error: "+h,doNothing)}return f};this.deleteTimersAll=function(){Va(function(a){"unregistered"!=a.id&&(a=a.id,zb(a),c.element("#ge-timer-container").find("#"+a).remove())})};this.showHelp=function(a,b,d){if(c.hasCapability("help")){var e=function(){lb();$.isFunction(d)&&d();c.setUnloadPrompt(!0)};kb(a);a=Ab(b);c.setUnloadPrompt(!1);b=introJs();b.setOptions({skipLabel:"Close",steps:a});b.oncomplete(e);
b.onexit(e);b.start()}};this.enableTips=function(a){Ka=a};this.showTip=function(a,b,d,e,f,g,h,k){void 0===h&&(h=!1);void 0===k&&(k=!1);a=c.element(a,b);if(c.hasCapability("tips")&&(b="qtip-green qtip-shadow qtip-rounded",1===f?b="qtip-red qtip-shadow qtip-rounded":2===f&&(b="qtip-blue qtip-shadow qtip-rounded"),!0===Ka||3===f))if(h){d={content:{text:g},hide:{fixed:!0,leave:!1,event:!1,inactive:2E3},position:{my:d,at:e,target:a},show:{when:!1,ready:!0},style:{classes:b}};try{a.qtip(d)}catch(l){doNothing()}}else{d=
{content:{text:g},hide:{fixed:!0,leave:!1,xevent:!1,event:"mouseleave click",xinactive:2E3},position:{my:d,at:e,target:a},show:{when:!1,ready:k,event:"mouseover"},style:{classes:b}};try{a.qtip(d)}catch(m){doNothing()}}};this.getStrippedAnchor=function(a){var b=0,b=a.indexOf("&");-1!=b&&(a=a.substring(0,b));return a};this.getAncorParameters=function(a){var b="",d=0,d=a.indexOf("&");-1!=d&&(b=a.substring(d+1));return b};this.jsonToNameValueArray=function(a){var b=[],d;for(d in a)b.push({name:d,value:a[d]});
return b};this.jsonToURL=function(a,b){var d="",c;for(c in a){if(0<d.length||b)d+="&";d+=encodeURIComponent(c)+"="+encodeURIComponent(a[c])}return d};this.urlToJSON=function(a){var b={};0<a.length&&(b=a.split("&").reduce(function(a,b,c,g){b=b.split("=");a[decodeURIComponent(b[0])]=decodeURIComponent(b[1]);return a},{}));return b};this.str_left=function(a,b,d){var c="";void 0===d&&(d="");0<b&&(c=b>a.length?a+d:a.substring(0,b)+d);return c};this.str_right=function(a,b){var d="";0<b&&(d=b>a.length?a:
a.substring(a.length-b,a.length));return d};this.str_quotes=function(a){var b=0,b=a.length;if(1<=b&&("'"===c.str_left(a,1)||'"'===c.str_left(a,1)))a=c.str_right(a,b-1);b=a.length;if(1<=b&&("'"===c.str_right(a,1)||'"'===c.str_right(a,1)))a=c.str_left(a,b-1);return a};this.toBoolean=function(a){a=(a+"").toUpperCase();return"1"===a||"Y"===a||"YES"===a||"T"===a||"TRUE"===a};this.convertDateToISO=function(a,b,d){var c="",f=str_replace(b,"/","-").split("-");3===f.length&&(2===f[0].length&&2===f[1].length&&
4===f[2].length?(c=new Date,c.setMonth(parseInt(f[1],10)-1),c.setDate(parseInt(f[0],10)),c.setFullYear(parseInt(f[2],10)),c=$.datepicker.formatDate("yy-mm-dd",c)):4===f[0].length&&2===f[1].length&&2===f[2].length?c=b:doNothing());b!==c&&$.isFunction(d)&&d(a,b,c);return c};this.convertISOToDate=function(a){var b=new Date;a=str_replace(a,"/","-").split("-");3===a.length&&(4===a[0].length&&2===a[1].length&&2===a[2].length?(b.setMonth(parseInt(a[1],10)-1),b.setDate(parseInt(a[2],10)),b.setFullYear(parseInt(a[0],
10)),b.setHours(0,0,0)):doNothing());return b};this.copyArray=function(a){return JSON.parse(JSON.stringify(a))};this.dateFromISO=function(a,b){var d=a.toLowerCase(),c="",f="",c=0<b.length?b:$.datepicker.formatDate("yy-mm-dd",new Date);if("dd/mm/yy"===d||"dd/mm/yyyy"===d)f=c.substr(8,2)+"/"+c.substr(5,2)+"/"+c.substr(0,4);else if("dd-mm-yy"===d||"dd-mm-yyyy"===d)f=c.substr(8,2)+"-"+c.substr(5,2)+"-"+c.substr(0,4);else if("mm/dd/yy"===d||"mm/dd/yyyy"===d)f=c.substr(5,2)+"/"+c.substr(8,2)+"/"+c.substr(0,
4);else if("mm-dd-yy"===d||"mm-dd-yyyy"===d)f=c.substr(5,2)+"-"+c.substr(8,2)+"-"+c.substr(0,4);else if("yy/mm/dd"===d||"yyyy/mm/dd"===d)f=c.substr(0,4)+"/"+c.substr(5,2)+"/"+c.substr(8,2);else if("yy-mm-dd"===d||"yyyy-mm-dd"===d)f=c.substr(0,4)+"-"+c.substr(5,2)+"-"+c.substr(8,2);return f};this.dateToISO=function(a,b){var c="1900-00-00";if("dd/mm/yy"===a||"dd-mm-yy"===a)c=b.substr(6,4)+"-"+b.substr(3,2)+"-"+b.substr(0,2);else if("mm/dd/yy"===a||"mm-dd-yy"===a)c=b.substr(6,4)+"-"+b.substr(0,2)+"-"+
b.substr(3,2);else if("yy/mm/dd"===a||"yy-mm-dd"===a)c=b.substr(0,4)+"-"+b.substr(5,2)+"-"+b.substr(8,2);return c};this.isInt=function(a){var b=!1;isNaN(parseInt(a,10))||parseInt(a,10)==parseFloat(a)&&(b=!0);return b};this.isIntRange=function(a,b,d){var e=!1;c.isInt(a)&&(a=parseInt(a,10),a>=b&&a<=d&&(e=!0));return e};this.isFloat=function(a){var b=!1;isNaN(parseFloat(a,10))||(b=!0);return b};this.isFloatRange=function(a,b,d){var e=!1;c.isFloat(a)&&(a=parseFloat(a,10),a>=b&&a<=d&&(e=!0));return e};
this.isEmailAddress=function(a){return/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(a)};this.formatMoney=function(a,b,d){var e=!0,f="";a=parseFloat(a);a=a.toFixed(2);void 0!==d&&(e=d);f=e?0<(a%1).toFixed(2)?c.roundFloat(a,2):c.roundFloat(a,0):c.roundFloat(a,0);b&&(f="$"+f);return f};this.roundInt=function(a){var b="";c.isInt(a)&&(b=parseInt(a,10)+"");return b};this.roundFloat=function(a,
b){var d="";if(c.isFloat(a))var d=parseFloat(a),e=Math.pow(10,b),d=parseInt(d*e,10),d=d/e,d=d.toFixed(b)+"";return d};this.rowStateGet=function(a,b){var c=a;"RETRIEVED"==a?"ADDED"==b?doNothing():"DELETED"==b?c="DELETED":"UPDATED"==b&&(c="UPDATED"):"DELETED"==a?"ADDED"==b?c="UPDATED":"DELETED"==b?doNothing():"UPDATED"==b&&(c="UPDATED"):"UPDATED"==a?"ADDED"==b?doNothing():"DELETED"==b?c="DELETED":"UPDATED"==b&&doNothing():"ADDED"==a&&("ADDED"==b?doNothing():"DELETED"==b?doNothing():"UPDATED"==b&&doNothing());
return c};this.nowAU=function(){var a=new Date,b=a.getFullYear().toString(),c=(a.getMonth()+1).toString();1===c.length&&(c="0"+c);var e=a.getDate().toString();1===e.length&&(e="0"+e);var f=a.getHours().toString();1===f.length&&(f="0"+f);var g=a.getMinutes().toString();1===g.length&&(g="0"+g);a=a.getSeconds().toString();1===a.length&&(a="0"+a);return e+"/"+c+"/"+b+" "+f+":"+g+":"+a};this.nowISO=function(){var a=new Date,b=a.getFullYear().toString(),c=(a.getMonth()+1).toString();1===c.length&&(c="0"+
c);var e=a.getDate().toString();1===e.length&&(e="0"+e);var f=a.getHours().toString();1===f.length&&(f="0"+f);var g=a.getMinutes().toString();1===g.length&&(g="0"+g);a=a.getSeconds().toString();1===a.length&&(a="0"+a);return b+"-"+c+"-"+e+" "+f+":"+g+":"+a};this.timeISO=function(){var a=new Date;a.getFullYear();a.getMonth();a.getDate();var b=a.getHours().toString();1===b.length&&(b="0"+b);var c=a.getMinutes().toString();1===c.length&&(c="0"+c);a=a.getSeconds().toString();1===a.length&&(a="0"+a);return b+
":"+c+":"+a};this.todayISO=function(){var a=new Date,b=a.getFullYear().toString(),c=(a.getMonth()+1).toString();1===c.length&&(c="0"+c);a=a.getDate().toString();1===a.length&&(a="0"+a);return b+"-"+c+"-"+a};return this};try{void 0!=k.progress&&$("#"+k.progress).show();void 0!=k.percentage&&$("#"+k.percentage).show();var Ba=os().getArgs().dependencies;os().lazyLoadDependencies(g_arrDependencies,Ba,function(c){os().after(500,function(){void 0!=k.progress&&($("#"+k.progress).hide(),k.progress=void 0);
void 0!=k.percentage&&($("#"+k.percentage).hide(),k.percentage=void 0);var c=!0;if("unavailable"===n.support){var c=!1,p='<font color="red"><b>Support for this browser is currently '+n.support+".</b></font><br><br>",p=p+('<font color="red"><b>Your browser is identified as '+n.name+" version "+n.version+" on "+n.OS+"</b></font><br><br>"),p=p+('<font color="red"><b>User Agent "'+ua+'"</b></font><br><br>');document.getElementById("ge-browser-message").innerHTML=p;document.getElementById("ge-browsers").style.visibility=
"visible";document.bgColor="white"}c&&(os().initialise(),$.isFunction(aa)&&(os().initialiseViewPort(),aa(),$(document).trigger("osready")))})})}catch(Bb){location=APP_LOGIN}}var os=osEntry;
