// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function jEditor(f,s,t,a){function q(){u.after(500,function(){0<r.length&&d.setContent(r)})}var u=f,d=this,e="editor-"+getGUID(),c=!1,r=a.defaultContent,g,b,n,h,k,l,p,m;f="run | load | save | reset | clear | searchreplace | undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | fullscreen";void 0!==a.toolbar&&(f=a.toolbar);void 0!==a.cbOnClear&&(g=a.cbOnClear);void 0!==a.cbOnDirty&&(b=a.cbOnDirty);void 0!==a.cbOnFileBrowse&&(n=a.cbOnFileBrowse);
void 0!==a.cbOnLoad&&(h=a.cbOnLoad);void 0!==a.cbOnReset&&(k=a.cbOnReset);void 0!==a.cbOnRun&&(l=a.cbOnRun);void 0!==a.cbOnSave&&(p=a.cbOnSave);void 0!==a.cbOnImagePicker&&(m=a.cbOnImagePicker);$(t,s).attr("id",e);$("#"+e).tinymce({setup:function(a){a.on("change",function(a){c=!0;$.isFunction(b)&&b(c)});a.on("ExecCommand",function(a){"mceNewDocument"==a.command&&q()});a.on("keyup",function(a){c=!0;$.isFunction(b)&&b(c)});void 0!==h&&a.addButton("load",{title:"Load",text:"Load",onclick:function(){$.isFunction(h)&&
h(d.getContent(!0),d.getContent(!1))&&(c=!1,$.isFunction(b)&&b(c))}});void 0!==k&&a.addButton("reset",{title:"Reset",text:"Reset",onclick:function(){$.isFunction(k)&&k(d.getContent(!0),d.getContent(!1))&&(c=!1,$.isFunction(b)&&b(c))}});void 0!==g&&a.addButton("clear",{title:"Clear",text:"Clear",onclick:function(){$.isFunction(g)&&g(d.getContent(!0),d.getContent(!1))&&(c=!1,$.isFunction(b)&&b(c))}});void 0!==l&&a.addButton("run",{title:"Run",text:"Run",onclick:function(){$.isFunction(l)&&l(d.getContent())}});
void 0!==m&&a.addButton("imagepicker",{title:"Image Picker",text:"Image Picker",onclick:function(){$.isFunction(m)&&m(a)}});q()},force_br_newlines:!0,force_p_newlines:!1,forced_root_block:"",menu:{file:{title:"File",items:"newdocument | print preview"},edit:{title:"Edit",items:"undo redo | cut copy paste pastetext | selectall | searchreplace"},insert:{title:"Insert",items:"image media link | charmap hr anchor pagebreak insertdatetime nonbreaking"},view:{title:"View",items:"visualchars visualblocks visualaid | fullscreen"},
format:{title:"Format",items:"bold italic underline strikethrough superscript subscript | formats | removeformat"},table:{title:"Table",items:"inserttable tableprops deletetable cell row column"},tools:{title:"Tools",items:"code"}},nonbreaking_force_tab:!0,plugins:["advlist autolink lists link image charmap hr anchor pagebreak","searchreplace wordcount visualblocks visualchars code fullscreen","insertdatetime media nonbreaking table contextmenu directionality","paste print preview save textcolor"],
resize:!1,toolbar:f,file_browser_callback:function(a,c,b,d){$.isFunction(n)&&n(d,a,b)},save_onsavecallback:function(){$.isFunction(p)&&p(d.getContent(!0),d.getContent(!1))&&(c=!1,$.isFunction(b)&&b(c))}});this.getContent=function(a){var b="";try{b=a?tinymce.EditorManager.get(e).getContent({format:"html"}).toString():tinymce.EditorManager.get(e).getContent({format:"text"}).toString()}catch(c){b=""}return b};this.isDirty=function(){return c};this.setContent=function(a){try{tinymce.EditorManager.get(e).setContent(a),
c=!1,$.isFunction(b)&&b(c)}catch(d){doNothing()}}};
