// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function jGrid(S,b){function w(b,c){var d=null,a=d="",e=c;void 0===e&&(e=N);for(var h=0;h<e.length;h++)d='"'+e[h]+'": "'+b[e[h]]+'"',0<h&&(a+=","),a+=d;return d=JSON.parse("{"+a+"}")}function O(){x&&q&&(g=[],p={});y.render(B,n);$.isFunction(m)&&m([])}function z(){a.invalidate();a.render();k.editable&&a.commitEditAndSetFocus()}function P(a){0<a.length&&processArray(g,function(c,b){c[a]=b})}function Q(){e.onRowCountChanged.subscribe(function(b,c){a.updateRowCount();a.render()});e.onRowsChanged.subscribe(function(b,
c){a.invalidateRows(c.rows);a.render()})}function T(){$.isFunction(E)&&a.onActiveCellChanged.subscribe(function(b,c){var d=a.getColumns()[c.cell];g[c.row]!==l&&(E(g[c.row],d.field),l=c.row)});$.isFunction(F)&&a.onAddNewRow.subscribe(function(b,c){var a=null,a=F();$.extend(a,c.item);e.addItem(a)});$.isFunction(G)&&(a.onCellChange.subscribe(function(b,c){var d=a.getColumns()[c.cell];G(g[c.row],d.field);a.invalidateRow(c.row);a.render()}),a.onActiveCellChanged.subscribe(function(a,c){G(null,null)}));
$.isFunction(H)&&a.onCellChange.subscribe(function(a,c){H()});$.isFunction(I)&&a.onDeleteRow.subscribe(function(b,c){var d=e.getItem(c.row),f=d.id;try{e.deleteItem(f)}catch(g){doNothing()}I(d);y.refreshRow(d);a.focus()});$.isFunction(m)&&a.onClick.subscribe(function(b,c){b.stopPropagation();var d=a.getCellFromEvent(b).row,d=e.getItem(d),f=[];f[0]=w(d);m(f)});$.isFunction(J)&&a.onDblClick.subscribe(function(b,c){b.stopPropagation();var d=a.getCellFromEvent(b).row,d=e.getItem(d),f=[];f[0]=w(d);J(f)});
a.onHeaderRowCellRendered.subscribe(function(b,a){$(a.node).empty();"rownum"===a.column.id?($("<img id='"+t+"-clearfilter' class='gb-button' src='"+DYNAMIC_APP_DIR_URL+"images/themes/default/framework/icon_clearfilter.png'>").data("columnId",a.column.id).val(p[a.column.id]).appendTo(a.node),$("#"+t+"-clearfilter").bind("click",O)):$("<input type='text' class='gs-grid-headcell-xxx'>").data("columnId",a.column.id).val(p[a.column.id]).appendTo(a.node)});a.onSort.subscribe(function(a,b){var d=b.sortCols;
A=[];processArray(d,function(a,b){A[b-1]={field:a.sortCol.field,ascending:a.sortAsc}});C()})}function U(){$(a.getHeaderRow()).delegate(":input","change keyup",function(a){var b=$(this).data("columnId");"rownum"!==b&&null!==b&&(p[b]=$.trim($(this).val()),13===a.which&&C())})}function R(a){$("body").css("cursor","auto");g=a;e.beginUpdate();e.setItems(g);e.endUpdate();z();$.isFunction(D)&&D(g)}function C(){if(x){if(q){var a=u.ajaxRequestCreate(K,$.merge([{name:"filter",value:y.getFilter()},{name:"order",
value:A}],k.extraParameters));u.ajaxCall(URL_WEBSERVICE,a,R,u.ajaxError)}else R(g);$.isFunction(m)&&m([])}}var u=S,y=this,k={autoEdit:!0,autoHeight:!0,editable:!1,enableAddRow:!1,enableColumnReorder:!1,explicitInitialization:!0,extraParameters:[],fixedFilter:[],xforceFitColumns:!0,autosizeColsMode:!0,fullWidthRows:!0,gridName:"",headerRowHeight:25,multiColumnSort:!0,multiSelect:!1,showHeaderRow:!1,enableCellNavigation:!0,createPreHeaderPanel:!1},e=null,a=null,l=null,q=!0,v="",B="",t="",n="",g=[],
p={},L=[],x=!1;0<b.webServiceFunction.length&&(x=!0);var N=b.returnFields,r=b.columns,E=b.cbOnActiveRowChange,F=b.cbOnAddNew,G=b.cbOnCalculate,H=b.cbOnCellChange,I=b.cbOnDeleteRow,D=b.cbOnFetchData,J=b.cbOnSelection,m=b.cbOnSelectionChange,K=b.webServiceFunction,A=null;void 0!==b.autoHeight&&(k.autoHeight=b.autoHeight);void 0!==b.containerClass&&(v=b.containerClass);void 0!==b.editable&&(k.editable=b.editable);void 0!==b.enableAddRow&&(k.enableAddRow=b.enableAddRow);void 0!==b.extraParameters&&(k.extraParameters=
b.extraParameters);void 0!==b.fixedFilter&&(k.fixedFilter=b.fixedFilter);void 0!==b.autosizeColsMode&&(k.autosizeColsMode=b.autosizeColsMode);void 0!==b.gridName&&(k.gridName=b.gridName);void 0!==b.multiSelect&&(k.multiSelect=b.multiSelect);void 0!==b.rowHeight&&(k.rowHeight=b.rowHeight);void 0!==b.showHeaderRow&&(k.showHeaderRow=b.showHeaderRow);this.append=function(a,b){void 0===b&&(b="");var d=u.copyArray(a),f=g.length;processArray(d,function(a){g[f]=a;f++});P(b);e.beginUpdate();e.setItems(g);
e.endUpdate();z()};this.commit=function(){a.commitEditAndSetFocus()};this.getData=function(){return g};this.getDataView=function(){return e};this.getFilter=function(){var b=[],c=0,d;for(d in p)if(void 0!==d&&""!==p[d]){var f=a.getColumns()[a.getColumnIndex(d)];b[c]={field:f.field,value:p[d]};c++}try{processArray(k.fixedFilter,function(a){b[c]={field:a.field,value:a.value,wildcards:!1};c++})}catch(e){doNothing()}try{processArray(L,function(a){b[c]={field:a.field,value:a.value,wildcards:!1};c++})}catch(h){doNothing()}return b};
this.getSelection=function(b){var c=[],d=a.getSelectedRows();d.sort(function(a,b){return a>b});processArray(d,function(a,d){var h=e.getItem(a);c[d-1]=w(h,b)});return c};this.moveTo=function(a,b,d,e){try{a.append(b,e),y.remove(b,d,e)}catch(g){doNothing()}};this.setFocus=function(){a.commitEditAndSetFocus();a.navigateTop();a.navigateRowStart()};this.refresh=function(a){q=a;void 0===q&&(q=!0);try{x?O():(e.beginUpdate(),e.setItems(g),e.endUpdate(),z())}catch(b){doNothing()}q=!0};this.refreshRow=function(b){a.invalidateRow(b);
a.render()};this.remove=function(a,b,d){void 0===d&&(d="");a=u.copyArray(a);processArray(a,function(a){var d=a[b];processArray(g,function(a,s,e){a[b]==d&&g.splice(e,1)})});P(d);e.beginUpdate();e.setItems(g);e.endUpdate();z()};this.render=function(b,c){B=b;n=c;t="grid-"+getGUID();$(n,b).attr("id",t);0<v.length&&!1===k.autoHeight&&$(n,b).addClass(v);e=new Slick.Data.DataView;a=new Slick.Grid("#"+t,e,r,k);a.setSelectionModel(new Slick.RowSelectionModel);Q();T();U();C();a.init();e.beginUpdate();e.setItems(g);
e.endUpdate();a.onContextMenu.subscribe(function(a){a.preventDefault()});new Slick.Controls.ColumnPicker(r,a,k);z()};this.setData=function(a){g=a};this.setVariableFilter=function(a){L=a}}
function jDatatableRenderer(S,b){function w(a){a=V+"-"+a;for(var b=0;15>b;b++)a=str_replace(a," +:._<>=&;\"()/'"[b],"-");return a}function O(){c="ge-DT-"+getGUID();var b="",b='<table  class="table table-hover display nowrap '+c+'" cellspacing="0" width="100%">',b=b+"<thead>",b=b+"<tr>";processArray(n,function(a){b+="<th>";b+=a.name;b+="</th>"});b+="</tr>";b+="</thead>";b+="<tbody>";b+="</tbody>";b+="</table>";a.element(l,q).html(b)}function z(){var b=[],s=0;processArray(n,function(d,e,c){e=!1;a.toBoolean(d.sortable)&&
(e=!0,0===s&&(s=c));b.push({data:d.id,orderable:e,defaultContent:""})});var e="Showing _START_ to _END_ of _TOTAL_ records",f="No Records";a.hasCapability("mobile")&&(f=e="");e={ajax:function(b,e,h){var s=this.api(),c=g,f="";void 0!==c&&0<c.length?(processArray(c,function(a,d,h){if("offset"===a.name)return c[h].value=b.start,!0}),processArray(c,function(b,a,h){if("filter"===b.name)return"normal"!==m&&(f=U(s),c[h].value=f),!0}),processArray(c,function(b,a,h){if("order"===b.name)return c[h].value=R(s),
!0}),processArray(c,function(b,a,h){if("limit"===b.name)return c[h].value=Q(),!0})):g=c=[{name:"order",value:""},{name:"filter",value:""},{name:"offset",value:0},{name:"limit",value:Q()}];h=a.ajaxRequestCreate(G,c);a.ajaxCall(URL_WEBSERVICE,h,function(a){var h=0,c=0,s=[];0<a.length&&(c=h=a[0].recordcount,s=$.isFunction(p)?p(a):T(a),d.page.len(a[0].limited));e({recordsTotal:c,recordsFiltered:h,data:s,draw:b.draw})},a.ajaxError)},processing:!1,colReorder:!0,columns:b,drawCallback:function(){u()},createdRow:function(b,
a,h){$.isFunction(I)&&I(b,a,h)},order:[],searching:!1,serverSide:!0,scrollX:300,responsive:!0,scrollCollapse:!0,rowId:function(b){return w(b.id)},bLengthChange:!1,language:{emptyTable:"&nbsp;",info:e,infoEmpty:f,xinfoFiltered:"(filtered)"}};B&&(e.dom='lfrt<"ge-customfooter-wrapper-xxx"<"ge-selectionclear-xxx">ip>');e.rowReorder=!1;K&&0<A.length&&(e.rowReorder={dataSrc:A,xselector:"tr"});d=a.element(l,"."+c).DataTable(e);B&&(a.element(l,"div.ge-selectionclear-xxx").html('<input class="btn btn-default gb-button ge-DT-clearselection" type="button" value="Clear Selection">'),
a.element(l,".ge-DT-clearselection").click(y))}function P(){$.isFunction(L)&&L();a.element(l,"."+c+" tbody").on("click","td",function(b){b.stopPropagation();var a=$(this),c=a.closest("tr")[0],a=a.index(),d;0<=a&&a<n.length&&(d=n[a]);a=c.id;void 0!==a&&0<a.length&&(C(c),d.events&&0<d.events.length&&processArray(d.events,function(a){var c=$(b.target).closest("."+a.bind),e=a.command;a=a.parameters;0<c.length&&$.isFunction(x)&&x(d,f,c,e,a)}))});a.element(l,"."+c+" tbody").on("dblclick","tr",function(){D&&
(clearTimeout(D),D=null);J=!0;var a=this.id;void 0!==a&&0<a.length&&(f=[],C(this),$.isFunction(N)&&N(f))});if(K){if($.isFunction(F))d.on("pre-row-reorder",F);if($.isFunction(E))d.on("row-reorder",E)}}function Q(){var b=a.element(l,".gb-form").height(),c=a.element(l,".ge-button-panel").height(),b=b-230;40<c&&(b-=c-50);return Math.floor(b/33)}function T(a){var b=[];0<a.length&&processArray(a,function(a,c,d){var e={};$.each(a,function(a,b){var c=b;if($.isArray(c)){var d="<ul>";processArray(c,function(a){d+=
"<li>"+a+"</li>"});c=d+="</ul>"}e[a]=c});b.push(e)});return b}function U(b){var c="";if("string"===m)c=M;else if("all"===m)c=[{field:"all",value:M}];else if("array"===m){var c=[],d;processArray(n,function(b){a.toBoolean(b.sortable)&&(d={field:b.field,value:M},c.push(d))})}return c}function R(a){a=a.order();var b=[],c,d,e,f;0<a.length&&processArray(a,function(a){c=a[0];d=a[1];f=n[c];e="asc"===d?!0:!1;b.push({field:f.field,ascending:e})});return b}function C(a){var b=d.rows("#"+a.id).data()[0];a=$(a);
var c=b.id;(!v||J)&&a.parents("tbody").find("tr.selected").removeClass("selected");a.toggleClass("selected");if(a.hasClass("selected"))v?f.push(b):f=[b];else if(v){var e=[];processArray(f,function(a){c!==a.id&&e.push(a)});f=e}else f=[];$.isFunction(r)&&r(f)}function u(){processArray(f,function(b){b=b.id;var c=d.rows("#"+w(b)).data()[0];void 0!=c&&c.id==b&&a.element("#"+w(b)).toggleClass("selected")})}function y(){f=[];e(!1);a.element(l,"."+c+" tbody").find("tr.selected").removeClass("selected");$.isFunction(r)&&
r(f);$.isFunction(H)&&H()}function k(a){var b=!1,c=-1;processArray(a,function(a){b=!1;c=-1;processArray(g,function(d,e,f){d.name===a.name&&(b=!0,c=f)});b?g[c].value=a.value:g.push(a)})}function e(a,b){var c=a;void 0===c&&(c=!0);void 0===b&&(b=!1);d.draw(b);c||(f=[],$.isFunction(r)&&r(f));0<f.length&&u()}var a=S,l="",q="",v=!1,B=!1,t=b.returnFields,n=b.columns,g=b.parameters,p=b.cbDataFormatter,L=b.cbPopulateAfter,x=b.cbOnClickEvent,N=b.cbOnSelection,r=b.cbOnSelectionChange,E=b.cbOnRowReorder,F=b.cbOnPreRowReorder,
G=b.webServiceFunction,H=b.cbClearSelection,I=b.cbRowFormatter,D,J=!1,m="all";void 0!==b.filterType&&(m=b.filterType);void 0!==b.multiSelect&&(v=b.multiSelect);void 0!==b.clearSelectionEnabled&&(B=b.clearSelectionEnabled);var K=!1;void 0!==b.rowReorder&&(K=b.rowReorder);var A="id";void 0!==b.rowReorderSortorderfield&&(A=b.rowReorderSortorderfield);var V="ge-DT-"+getGUID(),c="",d="",f=[],M="";return{clearSelection:y,getSelection:function(a){var b=[],c=[];void 0!==a?c=a:void 0!==t&&(c=t);processArray(f,
function(a){var d={};0===c.length?b.push(a):processArray(c,function(b){void 0!==a[b]&&(d[b]=a[b])});b.push(d)});return b},getDatatable:function(){return d},refresh:e,search:function(a,b){M=a;void 0!==b&&0<b.length&&k(b);e(!0,!0)},resize:function(){d.draw(!1)},render:function(a,b){l=a;q=b;O();z();P()}}};
