// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function jCanvas(n,b){function k(a,d){var b={x:0,y:0};if(d)b.x=a.touches[0].pageX-c.touchoffsetX,b.y=a.touches[0].pageY-c.touchoffsetY;else if(a.layerX||0===a.layerX)b.x=a.layerX*l,b.y=a.layerY*l;else if(a.offsetX||0===a.offsetX)b.x=a.offsetX*l,b.y=a.offsetY*l;return b}var f=this,e,d,g=!1,h=!1,l=1,c={cbOnDirty:"",backgroundColour:"black",height:0,penColour:"white",touchoffsetX:0,touchoffsetY:0,width:0};void 0!==b.cbOnDirty&&(c.cbOnDirty=b.cbOnDirty);void 0!==b.penColour&&(c.penColour=b.penColour);
void 0!==b.backgroundColour&&(c.backgroundColour=b.backgroundColour);void 0!==b.touchoffsetX&&(c.touchoffsetX=b.touchoffsetX);void 0!==b.touchoffsetY&&(c.touchoffsetY=b.touchoffsetY);void 0!==b.width&&(c.width=b.width);void 0!==b.height&&(c.height=b.height);var m="";this.onDraw=function(a){if(h){var b=k(a,!1);d.lineTo(b.x,b.y);d.strokeStyle=c.penColour;d.stroke();a.preventDefault();$.isFunction(c.cbOnDirty)&&c.cbOnDirty()}};this.onDrawEnd=function(a){h&&(f.onDraw(a),a.preventDefault(),h=!1)};this.onDrawStart=
function(a){var b=k(a,!1);d.beginPath();d.moveTo(b.x,b.y);a.preventDefault();h=!0;g=!1};this.onTouchEnd=function(a){g&&(f.onTouchMove(a),a.preventDefault(),g=!1)};this.onTouchMove=function(a){if(g){var b=k(a,!0);d.lineTo(b.x,b.y);d.strokeStyle=c.penColour;d.stroke();a.preventDefault()}};this.onTouchStart=function(a){var b=k(a,!0);d.beginPath();d.moveTo(b.x,b.y);a.preventDefault();g=!0;h=!1};this.clear=function(){d.clearRect(0,0,c.width,c.height);d.fillStyle=c.backgroundColour;d.fillRect(0,0,c.width,
c.height)};this.getBlob=function(){var a;e.toBlob(function(b){a=b},"image/jpeg");return a};this.getJPEG=function(){var a=(new JPEGEncoder).encode(d.getImageData(0,0,c.width,c.height),100);return a=a.substr(a.indexOf(",")+1).toString()};this.getPNG=function(){var a=e.toDataURL("image/png");return a=a.substr(a.indexOf(",")+1).toString()};this.render=function(a){m=a;e=$("#"+m)[0];d=e.getContext("2d");d.fillStyle=c.backgroundColour;d.fillRect(0,0,c.width,c.height);g=h=!1;n.hasCapability("touch")&&(e.addEventListener("touchstart",
f.onTouchStart),e.addEventListener("touchmove",f.onTouchMove),e.addEventListener("touchend",f.onTouchEnd));e.addEventListener("mousedown",f.onDrawStart,!1);e.addEventListener("mousemove",f.onDraw,!1);e.addEventListener("mouseup",f.onDrawEnd,!1)}};
