// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function jFormRenderer(pa,B,ba){function qa(b){var d="";processArray(y,function(c){"FORMHEADER"===c.sectiontype.toUpperCase()&&processArray(c.fields,function(g){var e=G(c.sectiontype,g.p_name),a=G("FORMHEADER",b);if(e.toUpperCase()===a.toUpperCase())return d=g.p_value,!0})});return d}function W(b){b=str_replace(b,"'","");return b=str_replace(b,'"',"")}function G(b,d){var c=$.trim(b+"_"+d),c=str_replace(c," ",""),c=str_replace(c,"<",""),c=str_replace(c,">",""),c=str_replace(c,"/",""),c=str_replace(c,
"-",""),c=str_replace(c,"&",""),c=str_replace(c,"'","");return c=str_replace(c,'"',"")}function ra(){processArray(X,function(b){(new abnFinder(c,e,htmlEncode(b.fieldname)+"_ABN",htmlEncode(b.fieldname)+"_COMPANYNAME","BusinessName",!0,htmlEncode(b.fieldname)+"-ge-abnsearch-button")).bind()})}function sa(){processArray(Y,function(b){b.finder=new predictiveTextFinder(c,e,l,b.sourceid);b.finder.bind()})}function ta(){processArray(w,function(b){var d=[],k="",g=["description"];0<b.source.length&&(d=b.source.split("|"));
0<d.length&&(k=d[0]);1<d.length&&(d=d[1],d=str_replace(d,"'",'"'),g=JSON.parse(d));var h="",a=c.element(e,"."+b.sourceid+"cb").attr("name"),Q=b.selected;null===Q&&(Q=[]);processArray(b.data,function(b){var d="";0<Q.length&&processArray(Q,function(a){"SYSTEMPRINTERS"===k?htmlEncode(a)===htmlEncode(b.description)&&(d='checked="checked"'):htmlEncode(a)===htmlEncode(b.id)&&(d='checked="checked"')});var c="";processArray(g,function(a){0<c.length&&(c+=" | ");c+=htmlEncode(b[a])});h+='<label><input type="checkbox" class=" '+
htmlEncode(a)+'" value="'+htmlEncode(b.id)+'" checkboxlabel="'+c+'" name="'+htmlEncode(a)+'" '+d+'><span style="margin-right:10px;"> '+htmlEncode(b.description)+"</span></label>"});c.element(e,"."+b.sourceid+"cb").html(h)})}function ua(){processArray(w,function(b){var d=[],k="",g=["description"];0<b.source.length&&(d=b.source.split("|"));0<d.length&&(k=d[0]);1<d.length&&(d=d[1],d=str_replace(d,"'",'"'),g=JSON.parse(d));var h='<option value=" "></option>',d=c.element(e,"."+b.sourceid+"dd"),a=d.val();
processArray(b.data,function(d){var c="";if("SYSTEMPRINTERS"===k)if(ca){if(htmlEncode(b.selected)===htmlEncode(d.description)||a===d.description)c="selected"}else doNothing();else if(htmlEncode(b.selected)===htmlEncode(d.id)||a===d.id)c="selected";var e="";processArray(g,function(a){0<e.length&&(e+=" | ");e+=htmlEncode(d[a])});h+='<option value="'+htmlEncode(d.id)+'" '+c+">"+e+"</option>"});d.html(h)})}function va(){processArray(w,function(b){var d=[],k="",g=["description"];0<b.source.length&&(d=
b.source.split("|"));0<d.length&&(k=d[0]);1<d.length&&(d=d[1],d=str_replace(d,"'",'"'),g=JSON.parse(d));var h=b.selected,a='<option value=" "></option>';null===h&&(h=[]);processArray(b.data,function(b){var d="";0<h.length&&processArray(h,function(a){"SYSTEMPRINTERS"===k?htmlEncode(a)===htmlEncode(b.description)&&(d="selected"):htmlEncode(a)===htmlEncode(b.id)&&(d="selected")});var c="";processArray(g,function(a){0<c.length&&(c+=" | ");c+=htmlEncode(b[a])});a+='<option value="'+htmlEncode(b.id)+'" '+
d+">"+c+"</option>"});c.element(e,"."+b.sourceid+"md").html(a)})}function wa(){processArray(w,function(b){var d=[],k="",g=["description"];0<b.source.length&&(d=b.source.split("|"));0<d.length&&(k=d[0]);1<d.length&&(d=d[1],d=str_replace(d,"'",'"'),g=JSON.parse(d));var h="",a=c.element(e,"."+b.sourceid+"rb").attr("name");processArray(b.data,function(d){var c="";"SYSTEMPRINTERS"===k?htmlEncode(b.selected)===htmlEncode(d.description)&&(c="checked"):htmlEncode(b.selected)===htmlEncode(d.id)&&(c="checked");
var e="";processArray(g,function(a){0<e.length&&(e+=" | ");e+=htmlEncode(d[a])});h+='<label><input type="radio" class=" '+htmlEncode(a)+'" value="'+htmlEncode(d.id)+'" radiolabel="'+e+'" name="'+htmlEncode(a)+'" '+c+'><span style="margin-right:10px;"> '+htmlEncode(d.description)+"</span></label>"});c.element(e,"."+b.sourceid+"rb").html(h)})}function xa(b){c.showFormPopup("entity.frmEntityChooser",{type:"form",entity:"systemform",formentity:"document",mode:"select",title:"Document Selection",fixedfilter:[],
resultfields:["id","description","tagtype","tag","result"]},function(d){if(0<d.length){var c=!1,g;processArray(d,function(d){void 0!==d.id&&(g={documentid:d.id,filename:W(d.description)},da(b,g),c=!0)});c&&(l.raiseRendererEvent("Document",e,"."+b,"onChange"),q(),L(b,!1))}},!1,!0)}function q(){!D&&!C.readonly&&(D=!0,$.isFunction(ea)&&ea(!0))}function da(b,d){var k=c.element(e,"."+htmlEncode(b)),g=k.val(),h=[];0<g.length&&(h=JSON.parse(g));h.push(d);k.val(JSON.stringify(h));l.raiseRendererEvent("Document",
e,"."+htmlEncode(b),"onChange");q()}function fa(b,d,c,g,e){void 0===e&&(e=!1);var a='<button class="form-control fb-view-button document-'+htmlEncode(b)+'" documentid="'+htmlEncode(d)+'" >',a=a+("<span>"+c+"</span>");e||(a+='&nbsp;<span title="Download" style="cursor: pointer; color:#069;" class="fb-download-button" documentid="'+htmlEncode(d)+'" ><i class="glyphicon glyphicon glyphicon-circle-arrow-down"></i></span>');a+="</button>";!e&&!g&&(a=a+"&nbsp;&nbsp;"+('<a><span title="Remove" style="cursor: pointer; color:red;" class="ge-d_document-remove-button" document="'+
htmlEncode(b)+'" documentid="'+htmlEncode(d)+'"><i class="glyphicon glyphicon-remove"></i></span></a>'));return a}function L(b,d){var k=c.element(e,"."+htmlEncode(b)).val();if(0<k.length){var k=JSON.parse(k),g=[],h,a;processArray(k,function(c){h=c.documentid;a=c.filename;g.push(fa(b,h,a,!1,d))});c.element(e,".documentDL-"+htmlEncode(b)).html(g.join("&nbsp;&nbsp;"))}else c.element(e,".documentDL-"+htmlEncode(b)).html("");ga()}function ya(b){void 0===b&&(b="");if("string"===typeof b){var d=c.getProperty("client");
void 0===d&&(d="none");var e=c.getProperty("login");void 0===e&&(e="none");var g=c.getMapProvider();0===g.length&&(g="none");var h=c.getSpeechProvider();0===h.length&&(h="none");var a=c.getPrinterVersion();0===a.length&&(a="none");b=str_replace(b,"[AWAF_AGENT]",c.getAgent());b=str_replace(b,"[AWAF_APPNAME]",APP_SHORT_NAME);b=str_replace(b,"[AWAF_APPVERSION]",APP_VERSION);b=str_replace(b,"[AWAF_BROWSERCAPABILITIES]",c.getBrowserCapabilities());b=str_replace(b,"[AWAF_BROWSERRECOMMENDATION]",c.getBrowserRecommendation());
b=str_replace(b,"[AWAF_BROWSERSUPPORTLEVEL]",c.getBrowser().support);b=str_replace(b,"[AWAF_BROWSERVERSION]",c.getBrowserVersion()+" ("+c.getBrowser().major+")");b=str_replace(b,"[AWAF_CLIENTBROWSER]",c.getBrowser().name);b=str_replace(b,"[AWAF_CLIENTOS]",c.getOS());b=str_replace(b,"[AWAF_CLIENT]",d);b=str_replace(b,"[AWAF_HEALTH]",c.getHealth());b=str_replace(b,"[AWAF_LOGIN]",e);b=str_replace(b,"[AWAF_MAPSPROVIDER]",g);b=str_replace(b,"[AWAF_PRINTERPROVIDER]",a);b=str_replace(b,"[AWAF_RESOLUTION]",
screen.width+"x"+screen.height);b=str_replace(b,"[AWAF_SPEECHPROVIDER]",h);b=str_replace(b,"[AWAF_VIEWPORT]",c.getViewPort().width+"x"+c.getViewPort().height)}return b}function za(b,d,k){b=c.element(e,"."+htmlEncode(d));var g=b.val();if(0<g.length){var g=JSON.parse(g),h=-1;processArray(g,function(a,b,d){a.documentid===k&&(h=d)});-1<h&&(g.splice(h,1),0<g.length?b.val(JSON.stringify(g)):b.val(""));l.raiseRendererEvent("Document",e,"."+htmlEncode(d),"onClear");l.raiseRendererEvent("Document",e,"."+htmlEncode(d),
"onChange");q()}}function ha(b,d){var k="",k=""!==b?"fetch.php?token="+encodeURIComponent(SECURITY_TOKEN)+"&image="+encodeURIComponent(b):"images/noimage.png";c.element(e,"."+htmlEncode(d)).attr("src",k);c.element(e,"."+htmlEncode(d)).attr("documentid",htmlEncode(b));c.element(e,"."+htmlEncode(d)).val(htmlEncode(b))}function N(){processArray(y,function(b){"FORMHEADER"===b.sectiontype.toUpperCase()||"DATAHEADER"===b.sectiontype.toUpperCase()?doNothing():"DATA"===b.sectiontype.toUpperCase()||"INTERNALUSEFORMHEADER"===
b.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])||"INTERNALUSEONLY"===b.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])?processArray(b.fields,function(d){var k=c.toBoolean(d.p_readonly),g=G(b.sectioncode,d.p_name),h=d.p_datatype,a=d.p_label,l=d.p_style;try{var q=!1;isNullOrUndefined(l)&&(l="");0<=(" "+l+" ").indexOf(" gb-hidden ")&&(q=!0)}catch(s){doException("updateJSONwithElementValues",s)}if(!q&&!k)if(k=d.p_source,void 0===k&&(k=""),d.p_valuedescription="","d_abnlookup"===
h)a=c.element(e,"."+htmlEncode(g)+"_ABN").val(),g={companyvalue:c.element(e,"."+htmlEncode(g)+"_COMPANYNAME").val(),abnvalue:a},d.p_value=g;else if("d_date"===h)g=c.element(e,"."+htmlEncode(g)).val(),10<g.length&&(g=c.str_left(g,10)),g=c.convertDateToISO(a,g,doNothing),d.p_value=g;else if("d_representation"===h)0<=d.p_classes.indexOf("d_singleradio")||"d_singleradio"===d.p_style?(d.p_value=c.element(e,"."+htmlEncode(g)+":checked").val(),d.p_valuedescription=c.element(e,"."+htmlEncode(g)+":checked").attr("radiolabel")):
0<=d.p_classes.indexOf("d_singledropdown")||"d_singledropdown"===d.p_style?(d.p_value=c.element(e,"."+htmlEncode(g)).val(),d.p_valuedescription=c.element(e,"."+htmlEncode(g)+" option:selected").text()):(d.p_value=c.element(e,"."+htmlEncode(g+"epv")).val(),d.p_valuedescription=c.element(e,"."+htmlEncode(g+"epd")).val());else if("d_list"===h)0<=d.p_classes.indexOf("d_singleradio")||"d_singleradio"===d.p_style?(d.p_value=c.element(e,"."+htmlEncode(g)+":checked").val(),d.p_valuedescription=c.element(e,
"."+htmlEncode(g)+":checked").attr("radiolabel")):0<=d.p_classes.indexOf("d_singledropdown")||"d_singledropdown"===d.p_style?(d.p_value=c.element(e,"."+htmlEncode(g)).val(),d.p_valuedescription=c.element(e,"."+htmlEncode(g)+" option:selected").text(),0===d.p_valuedescription.length&&(d.p_valuedescription=d.p_value)):(d.p_value=c.element(e,"."+htmlEncode(g+"epv")).val(),d.p_valuedescription=c.element(e,"."+htmlEncode(g+"epd")).val());else if("d_multilist"===h){var u=[],t=[];0<=d.p_classes.indexOf("d_multicheckbox")||
"d_multicheckbox"===d.p_style?(c.element(e,"."+htmlEncode(g)+" :checkbox").each(function(){this.checked&&(u.push($(this).val()),t.push($(this).attr("checkboxlabel")))}),d.p_value=u,d.p_valuedescription=t):(u=c.element(e,"."+htmlEncode(g)).val(),c.element(e,"."+htmlEncode(g)+" option:selected").each(function(){t.push($(this).text())}),d.p_value=null===u?[]:u,d.p_valuedescription=null===t?[]:t)}else"d_html"===h?d.p_value=Aa(g):"d_codeeditor"===h?d.p_value=Ba(g):"d_multilinetext"===h?d.p_value=c.element(e,
"."+htmlEncode(g)).val():"d_yesno"===h?!0===c.element(e,"."+htmlEncode(g)).is(":checked")?d.p_value="Y":d.p_value="N":"d_document"===h?(g=c.element(e,"."+htmlEncode(g)).val(),a=[],0<g.length&&(a=JSON.parse(g)),d.p_value=a):d.p_value=c.element(e,"."+htmlEncode(g)).val()}):doNothing()})}function Ca(b){c.showFormPopup("core.frmUpload","mode=generic&flags=select%20nobatch&autoclose=true",function(d){if(!1===C.readonly&&0<d.length){var c=!1,g;processArray(d,function(d){"COMPLETED"===d.result&&"documentid"===
d.tagtype&&(g={documentid:d.tag,filename:W(d.description)},da(b,g),c=!0)});c&&(l.raiseRendererEvent("Document",e,"."+htmlEncode(b),"onChange"),q(),L(b,!1))}},!1,!0)}function Da(b,d,e,g){try{var h=!1,a="",l=R,q=d.p_datatype;isNullOrUndefined(d.p_datatype)&&(q="");var s=!1,u="",t="";c.toBoolean(d.p_readonly)&&(u="readonly",t='readonly onclick="return false;"',s=!0);if(C.readonly||e)u="readonly",t='readonly onclick="return false;"',s=!0;var r="",z="";!s&&c.toBoolean(d.p_required)&&(r="required",z='<span class="required-asterisk" style="display:inline"> *</span>');
var F=d.p_length;isNullOrUndefined(d.p_length)&&(F="");var v=d.p_label;isNullOrUndefined(v)&&(v="");var y=d.p_style;isNullOrUndefined(y)&&(y="");var n=d.p_classes;isNullOrUndefined(n)&&(n="");n+=" "+y;switch(q){case "d_abnlookup":case "d_button":case "d_chart":case "d_predictivetext":case "d_date":case "d_document":case "d_gps":case "d_password":case "d_text":case "d_barcode":case "d_number":case "d_time":case "d_yesno":case "d_url":case "d_representation":case "d_list":case "d_multilinetext":case "d_multilist":h=
!0,g&&0<l.length&&(n=n+" "+l)}var p=d.p_colour;if(isNullOrUndefined(p))p="";else{var E=p.split("|");isNullOrUndefined(E[2])||(p="background-color:"+E[2]+"; ");isNullOrUndefined(E[3])||(p+="color:"+E[3]+"; background-image:none;")}var f=G(b.sectioncode,d.p_name);isNullOrUndefined(f)&&(f="");0<I.length&&(I+=",");I+=f;var B=d.p_lines;isNullOrUndefined(B)&&(B="1");var m=d.p_value;isNullOrUndefined(m)&&(m="");var H=d.p_valuedescription;isNullOrUndefined(H)&&(H="");0===m.length&&(m=H);var x=d.p_source;
isNullOrUndefined(x)&&(x="");var D=d.p_selection;void 0===D&&(D=[]);y=!0;C.htmlmode&&(y=!1,"d_html"===q&&(y=!0));s&&(l="");E=b="";hasFlag(C.flags,"noplaceholdersubstitution")?doNothing():m=ya(m);"d_html"===q&&(m=str_replace(m,"clickevent","onclick"));if(y){switch(q){case "d_abnlookup":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";
a+='<div class="col-md-9 small"><div style="width:100%;" class="row">';a+='<div class="col-md-10 small">';a+='<input type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'_COMPANYNAME" name="'+htmlEncode(f)+'_COMPANYNAME"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m.companyvalue)+'" placeholder="Business Name" type="text" autocorrect="off" autocapitalize="none" >';a+="</div>";a+='<div class="col-md-2 small">';a+='<button class="form-control '+htmlEncode(f)+'-ge-abnsearch-button" btnid="'+
htmlEncode(f)+'">Search</button>';a+="</div>";a+="</div>";a+='<div class="row" style="margin-top:10px">';a+='<div class="col-md-10 small">';a+='<input type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'_ABN" name="'+htmlEncode(f)+'_ABN"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m.abnvalue)+'" placeholder="ABN" type="text" autocorrect="off" autocapitalize="none">';a+="</div>";a+="</div>";a+="</div></div>";X.push({fieldname:htmlEncode(f)});ia++;O+=","+htmlEncode(f)+
"_ABN,"+htmlEncode(f)+"_COMPANYNAME,"+htmlEncode(f)+"-ge-abnsearch-button";break;case "d_button":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+"</label></div>";e?doNothing():(a+='<div class="col-md-7 small" style="text-align:left;">',a+='<div class="form-control gb-button" style="vertical-align:top; text-align:left;"><div class="'+htmlEncode(n)+
" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">'+htmlEncode(m)+"</div></div>",a+="</div>");a+="</div>";break;case "d_chart":E="reports/report/?chart_only=true&content_only=true&report=~CHARTGUID~.report".replace("~CHARTGUID~",d.p_source);a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";a+='<iframe src="'+E+'" style="width:100%;height:230px"></iframe>';
a+="</div>";break;case "d_date":t="";0<m.length&&(10<m.length&&(m=c.str_left(m,10)),m=c.convertDateToISO(v,m,function(a){S=!0;0<J.length&&(J+=", ");J+=a}),0<m.length&&(t=c.dateFromISO(DATE_OUTPUTFORMAT,m)));a+='<div class="form-group" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="date">'+htmlEncode(v)+z+"</label></div>";s?a+='<div class="col-md-3 small"><input type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+
'" name="'+htmlEncode(f)+'"  '+r+" "+u+' value="'+htmlEncode(t)+'" ></div>':(a+='<div class="col-md-9 small">',a+='<div class="input-group">',a+='   <input type="text" class="form-control ge-btdatepicker '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  '+r+" "+u+' value="'+htmlEncode(t)+'" placeholder="'+DATE_OUTPUTFORMATDESC+'" >',a+='   <div class="input-group-btn">',a+='      <button class="btn btn-default todaysdate-button" btnid="'+htmlEncode(f)+'">Today</button>&nbsp;',a+='      <button class="btn btn-default cleardate-button" btnid="'+
htmlEncode(f)+'">Clear</button>',a+="    </div>",a+="</div>",a+="</div>");a+="</div>";break;case "d_document":t=[];0<m.length&&(t=m,processArray(t,function(a){a.filename=W(a.filename)}));a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";a+='<div class="col-md-9 small">';a+='<input type="hidden" class="form-control '+htmlEncode(n)+
" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" value='"+JSON.stringify(t)+"'>";a+='<div class="text-left documentDL-'+htmlEncode(f)+'" >';if(0<t.length){var K=[],L="";processArray(t,function(a){L=fa(f,a.documentid,a.filename,s,e);K.push(L)});a+=K.join("&nbsp;&nbsp;")}a+="</div>";s?doNothing():(a+='<div class="text-left" style="margin-top:5px">',a+='<button class="form-control ge-uploaddocument-button" btnid="'+htmlEncode(f)+'">Upload</button>',a+='&nbsp;<button class="form-control ge-selectdocument-button" btnid="'+
htmlEncode(f)+'">Select</button>',a+="</div>");a+="</div>";a+="</div>";break;case "d_gps":a+='<div class="form-group" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";a+='<div class="col-md-9 small">';e?a+='<a class="form-control fb-map-link" style="display: none;" href="'+htmlEncode(m.replace(" ",""))+'">Map</a>':(a+='<div class="input-group">',a+='<input type="text" class="form-control '+
htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m)+'">',a+='<div class="input-group-btn">',c.hasCapability("geolocation")&&(a+='<button class="btn btn-default fb-here-btn" btnid="'+htmlEncode(f)+'">Here</button>&nbsp;'),c.hasCapability("maps")&&(a+='<button class="btn btn-default fb-map-btn" btnid="'+htmlEncode(f)+'">Map</button>&nbsp;'),a+="</div>",a+="</div>");a+="</div>";a+="</div>";break;case "d_image":a+='<div class="form-group form-inline '+
htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small">';a+='<label for="text" style="width:100%;" >'+htmlEncode(v)+z+"</label>";a+="</div>";a+='<div class="col-md-4 small move-left">';s?doNothing():(a+='<button class="form-control fb-imagepicker-btn" btnid="'+htmlEncode(f)+'">Upload</button>',a+="&nbsp;&nbsp;",a+='<button class="form-control fb-imagegallery-btn" btnid="'+htmlEncode(f)+'">Select</button>',a+="&nbsp;&nbsp;",a+='<button class="form-control fb-imagedelete-btn" btnid="'+
htmlEncode(f)+'">Delete</button>');a+="</div>";a+='<div class="col-md-5 small">';a+='<input type="hidden" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m)+'">';E="images/noimage.png";0<m.length&&(E="fetch.php?token="+encodeURIComponent(SECURITY_TOKEN)+"&image="+encodeURIComponent(m));e?0<m.length&&(a+='<div class="ge-form-banner" style="width:100%; color:white; background-color:red;"></div><div style="height:238px; width:238px;"><img style="height:100%;max-width:238px" class="ge-image-field '+
htmlEncode(f)+'" src="'+E+'"><br></div>'):a+='<div class="ge-form-banner" style="width:100%; color:white; background-color:red;"></div><div style="height:238px; width:238px;"><a class="gb-button fb-view-button '+htmlEncode(f)+'" documentid="'+htmlEncode(m)+'"><img class="ge-image-field '+htmlEncode(f)+'" src="'+E+'"></a><br></div>';a+="</div>";a+="</div>";break;case "d_password":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+=
'<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";a+='<div class="col-md-9 small"><input style="width:100%;" type="password" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m)+'"></div>';a+="</div>";break;case "d_metadata":m=Ea("logic",m);if(0<m.length){var N=m.split(",");processArray(N,function(a){var b=!1;processArray(T,function(d){if(d==a)return b=
!0});b||T.push(a)})}break;case "d_text":case "d_barcode":case "d_number":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";a+='<div class="col-md-9 small"><input style="width:100%;" type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+
htmlEncode(m)+'" ></div>';a+="</div>";break;case "d_time":a+='<div class="form-group" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="time">'+htmlEncode(v)+z+"</label></div>";s?a+='<div class="col-md-9 small"><input type="time" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m)+'" ></div>':(a+='<div class="col-md-9 small">',a+='<div class="input-group">',
a+='<input type="time" class="form-control ge-bttimepicker '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m)+'" >',a+='<div class="input-group-btn">',a+='<button class="btn btn-default currenttime-button" btnid="'+htmlEncode(f)+'">Now</button>',a+='<button class="btn btn-default cleartime-button" btnid="'+htmlEncode(f)+'">Clear</button>',a+="</div>",a+="</div>",a+="</div>");a+="</div>";break;case "d_yesno":r="";c.toBoolean(m)&&
(r="checked");a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small">';a+='<label class="" style="width:100%;'+p+'" for="label">'+htmlEncode(v)+'</label></div><div class="col-md-1 text-left" style="text-align:left;"><input class="move-left '+htmlEncode(n)+" "+htmlEncode(f)+'" type="checkbox" name="'+htmlEncode(f)+'"  '+t+" "+r+" >";a+="</div>";a+="</div>";break;case "d_url":E=m;a+='<div class="form-group form-inline '+
htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";"http://"!==c.str_left(E,7).toLowerCase()&&"https://"!==c.str_left(E,8).toLowerCase()&&(E="http://"+E);e?a+=htmlEncode(E):s?0<m.length&&(a+='<div class="col-md-7 small" style="text-align:left;">',a+='<div class="form-control gb-button" style="vertical-align:top; text-align:left;"><a class="'+htmlEncode(n)+" "+htmlEncode(f)+
'" name="'+htmlEncode(f)+'" href="'+htmlEncode(E)+'" target="_blank" >'+htmlEncode(E)+'&nbsp;<i class="glyphicon glyphicon-circle-arrow-up gb-button"></i></a></div>',a+="</div>"):(a+='<div class="col-md-7 small" style="text-align:left;">',a+='<input type="text" style="width:95%;" class="form-control fb-url-field '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(m)+'">&nbsp;&nbsp;&nbsp;',a+="</div>",a+='<div class="col-md-2 '+
htmlEncode(n)+" "+htmlEncode(f)+'" style="vertical-align:top; text-align:left; margin-top:5px;"><a href="'+htmlEncode(E)+'" target="_blank"><i class="glyphicon glyphicon-circle-arrow-up gb-button"></i></a></div>');a+="</div>";break;case "d_heading":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-12 small"><h3 style="width:100%; text-align:left; font-weight:bold;" name="'+htmlEncode(f)+'" class="'+htmlEncode(n)+
" "+htmlEncode(f)+'" >'+htmlEncode(v)+"</h3></div>";a+="</div>";break;case "d_representation":s?(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><input style="width:100%;" type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+
'"  '+r+" "+u+' value="'+htmlEncode(H)+'"></div>'):(b="",a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+" "+htmlEncode(f)+'_fg" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>",0<=n.indexOf("d_singleradio")?(0<x.length?(b="datasource-"+A,a+='<div class="col-md-9 small"><div class="clear"></div><fieldset style="width:100%; border:0; box-shadow: none; text-align:left; padding:0;" class="form-control '+
htmlEncode(n)+" "+htmlEncode(b+"rb")+" "+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'" >',w.push({fetched:!1,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++):(a+='<div class="col-md-9 small"><fieldset style="width:100%; border:none; background:none; text-align:left; padding:0;" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">',processArray(D,function(b){var d="";m===b.p_code&&(d='checked="checked"');a+='<label><input type="radio" class=" '+
htmlEncode(f)+'" value="'+htmlEncode(b.p_code)+'" radiolabel="'+htmlEncode(b.p_value)+'" name="'+htmlEncode(f)+'" '+d+'><span style="margin-right:10px;"> '+htmlEncode(b.p_value)+"</span></label>"})),a+="</fieldset></div>"):0<=n.indexOf("d_singledropdown")?(0<x.length?(b="datasource-"+A,a+='<div class="col-md-7 small" style="text-align:left;"><select style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"dd")+" "+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+
'"  '+r+" "+t+" >",w.push({fetched:!1,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++):(a+='<div class="col-md-7 small" style="text-align:left;"><select style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+" >",processArray(D,function(b){var d="";m===b.p_code&&(d="selected");a+='<option value="'+htmlEncode(b.p_code)+'" '+d+">"+htmlEncode(b.p_value)+"</option>"})),a=0===x.length?a+"</select></div>":a+('</select></div><div class="col-md-2" style="vertical-align:top; text-align:left; margin-top:5px;"><i class="glyphicon glyphicon-search gb-button ge-d_representation-search" targetdatasourceid="'+
htmlEncode(b)+'" targettitle="'+htmlEncode(v)+'"></i></div>')):(0<=n.indexOf("d_predictivetext")?(0<x.length&&(b="datasource-"+A,a+='<div class="col-md-7 small" style="text-align:left;">',a+='<input type="text" style="width:0%; display:none;" readonly="readonly" class="'+htmlEncode(n)+" "+htmlEncode(b+"epv")+" "+htmlEncode(f)+" "+htmlEncode(f+"epv")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(m)+'">',a+='<input type="text" style="width:0%; display:none;" readonly="readonly" class="'+
htmlEncode(n)+" "+htmlEncode(b+"epd")+" "+htmlEncode(f)+" "+htmlEncode(f+"epd")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(H)+'">',a+='<input type="text" style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"tds")+" "+htmlEncode(f)+" "+htmlEncode(f+"tds")+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(H)+'">',w.push({fetched:!0,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),Y.push({fieldname:htmlEncode(f),
sourceid:b,source:x}),A++,ja++),0!==x.length&&(a+="</div>",a+='<div class="col-md-2 small" style="vertical-align:top; text-align:left; margin-top:5px;">',a+='<i class="glyphicon glyphicon-remove-circle gb-button ENTITYPICKERCLEAR '+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"></i>&nbsp;&nbsp;',a+='<i class="glyphicon glyphicon-search gb-button ENTITYPICKER '+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'" targettitle="'+htmlEncode(v)+
'"></i>&nbsp;')):(0<x.length&&(b="datasource-"+A,a+='<div class="col-md-8 small" style="text-align:left;">',a+='<input type="text" style="width:98%; display:none;" readonly="readonly" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"epv")+" "+htmlEncode(f)+" "+htmlEncode(f+"epv")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(m)+'">',a+='<input type="text" style="width:98%;" readonly="readonly" class="form-control ENTITYPICKER '+htmlEncode(n)+" "+htmlEncode(b+"epd")+" "+htmlEncode(f)+
" "+htmlEncode(f+"epd")+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(H)+'">',w.push({fetched:!0,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++),0!==x.length&&(a+="</div>",a+='<div style="vertical-align:top; text-align:left; margin-top:5px;">',a+='<i class="glyphicon glyphicon-remove-circle gb-button ENTITYPICKERCLEAR '+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"></i>&nbsp;&nbsp;',a+='<i class="glyphicon glyphicon-search gb-button ENTITYPICKER '+
htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'" targettitle="'+htmlEncode(v)+'"></i>&nbsp;')),a+="</div>"));a+="</div>";break;case "d_list":s?(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>",a+='<input type="text" style="width:98%; display:none;" readonly="readonly" class="form-control '+htmlEncode(n)+
" "+htmlEncode(b+"epv")+" "+htmlEncode(f)+" "+htmlEncode(f+"epv")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(m)+'">',a+='<div class="col-md-9 small"><input style="width:100%;" type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' value="'+htmlEncode(H)+'"></div>',a+="</div>"):"SYSTEMPRINTERS"===x?(ca?(b="",a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+" "+htmlEncode(f)+'_fg" style="margin:0px; padding:1px 1px 1px 1px;'+
p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>",b="datasource-"+A,a+='<div class="col-md-9 small" style="text-align:left;"><select style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"dd")+" "+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+" >",a+="</select></div>"):(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+
p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+"</label></div>",a+='<div class="col-md-9 small"><input style="width:100%;" type="text" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"dd")+" "+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  value="'+htmlEncode(m)+'"></div>'),a+="</div>",w.push({fetched:!1,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++):(b="",a+='<div class="form-group form-inline '+
htmlEncode(f+"fld")+" "+htmlEncode(f)+'_fg" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>",0<=n.indexOf("d_singleradio")?(0<x.length?(b="datasource-"+A,a+='<div class="col-md-9 small"><div class="clear"></div><fieldset style="width:100%; border:0; box-shadow: none; text-align:left; padding:0;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"rb")+" "+htmlEncode(f)+'" targetdatasourceid="'+
htmlEncode(b)+'" name="'+htmlEncode(f)+'" >',w.push({fetched:!1,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++):(a+='<div class="col-md-9 small"><fieldset style="width:100%; border:none; background:none; text-align:left; padding:0;" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">',processArray(D,function(b){var d="";m===b.p_code&&(d='checked="checked"');a+='<label><input type="radio" class=" '+htmlEncode(f)+'" value="'+htmlEncode(b.p_code)+'" radiolabel="'+
htmlEncode(b.p_value)+'" name="'+htmlEncode(f)+'" '+d+'><span style="margin-right:10px;"> '+htmlEncode(b.p_value)+"</span></label>"})),a+="</fieldset></div>"):0<=n.indexOf("d_singledropdown")?(0<x.length?(b="datasource-"+A,a+='<div class="col-md-7 small" style="text-align:left;"><select style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"dd")+" "+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+" >",w.push({fetched:!1,locator:"."+f,sourceid:b,
source:x,data:null,selected:m}),A++):(a+='<div class="col-md-7 small" style="text-align:left;"><select style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+" >",processArray(D,function(b){var d="";m===b.p_code&&(d="selected");a+='<option value="'+htmlEncode(b.p_code)+'" '+d+">"+htmlEncode(b.p_value)+"</option>"})),a=0===x.length?a+"</select></div>":a+('</select></div><div class="col-md-2" style="vertical-align:top; text-align:left; margin-top:5px;"><i class="glyphicon glyphicon-search gb-button ge-d_list-search" targetdatasourceid="'+
htmlEncode(b)+'" targettitle="'+htmlEncode(v)+'"></i></div>')):(0<=n.indexOf("d_predictivetext")?(0<x.length&&(b="datasource-"+A,a+='<div class="col-md-7 small" style="text-align:left;">',a+='<input type="text" style="width:0%; display:none;" readonly="readonly" class="'+htmlEncode(n)+" "+htmlEncode(b+"epv")+" "+htmlEncode(f)+" "+htmlEncode(f+"epv")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(m)+'">',a+='<input type="text" style="width:0%; display:none;" readonly="readonly" class="'+
htmlEncode(n)+" "+htmlEncode(b+"epd")+" "+htmlEncode(f)+" "+htmlEncode(f+"epd")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(H)+'">',a+='<input type="text" style="width:98%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"tds")+" "+htmlEncode(f)+" "+htmlEncode(f+"tds")+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(H)+'">',w.push({fetched:!0,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),Y.push({fieldname:htmlEncode(f),
sourceid:b,source:x}),A++,ja++),0!==x.length&&(a+="</div>",a+='<div class="col-md-2 small" style="vertical-align:top; text-align:left; margin-top:5px;">',a+='<i class="glyphicon glyphicon-remove-circle gb-button ENTITYPICKERCLEAR '+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"></i>&nbsp;&nbsp;',a+='<i class="glyphicon glyphicon-search gb-button ENTITYPICKER '+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'" targettitle="'+htmlEncode(v)+
'"></i>&nbsp;')):(0<x.length&&(b="datasource-"+A,a+='<div class="col-md-8 small" style="text-align:left;">',a+='<input type="text" style="width:98%; display:none;" readonly="readonly" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"epv")+" "+htmlEncode(f)+" "+htmlEncode(f+"epv")+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(m)+'">',a+='<input type="text" style="width:98%;" readonly="readonly" class="form-control ENTITYPICKER '+htmlEncode(n)+" "+htmlEncode(b+"epd")+" "+htmlEncode(f)+
" "+htmlEncode(f+"epd")+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"  '+r+" "+t+' value="'+htmlEncode(H)+'">',w.push({fetched:!0,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++),0!==x.length&&(a+="</div>",a+='<div style="vertical-align:top; text-align:left; margin-top:5px;">',a+='<i class="glyphicon glyphicon-remove-circle gb-button ENTITYPICKERCLEAR '+htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'"></i>&nbsp;&nbsp;',a+='<i class="glyphicon glyphicon-search gb-button ENTITYPICKER '+
htmlEncode(f)+'" targetdatasourceid="'+htmlEncode(b)+'" name="'+htmlEncode(f)+'" targettitle="'+htmlEncode(v)+'"></i>&nbsp;')),a+="</div>"),a+="</div>");break;case "d_spacer":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-12 small"></br></div>';a+="</div>";break;case "d_description":a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-12 small"><label style="width:100%; height:auto; font-weight:normal; border:0px;" class="'+
htmlEncode(f)+'" name="'+htmlEncode(f)+'">'+v+"</label></div><br><br>";a+="</div>";break;case "d_html":s?(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-12 small"><label style="width:100%; height:auto; font-weight:normal; border:0px;" class="'+htmlEncode(f)+'" name="'+htmlEncode(f)+'">'+m+"</label></div>",a+="</div>"):(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+
p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="textarea">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><textarea style="width:100%;" name="'+htmlEncode(f)+'" class="'+htmlEncode(n)+" "+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' rows="'+B+'" >'+htmlEncode(m)+"</textarea></div>",a+="</div>",U.push({fetched:!0,sourceid:htmlEncode(f),source:null,type:"d_html"}));break;case "d_texthtml":s?(a+='<div class="form-group form-inline '+htmlEncode(f+
"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="label">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><label style="width:100%; height:auto; word-wrap:break-word" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">'+m+"</label></div>",a+="</div>"):(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+=
'<div class="col-md-3 small"><label style="width:100%;'+p+'" for="textarea">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><textarea style="width:100%;" name="'+htmlEncode(f)+'" class="'+htmlEncode(n)+" "+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' rows="'+B+'" >'+htmlEncode(m)+"</textarea></div>",a+="</div>",U.push({fetched:!0,sourceid:htmlEncode(f),source:null,type:"d_texthtml"}));break;case "d_codeeditor":s?(a+='<div class="form-group form-inline '+htmlEncode(f+
"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%; height: 300px;'+p+'" for="label">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><label style="width:100%; height:auto; word-wrap:break-word" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">'+m+"</label></div>",a+="</div>"):(a+='<div class="form-group form-inline '+htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+
p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="codeeditor">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><div style="width:100%; height: 300px;" name="'+htmlEncode(f)+'" class="'+htmlEncode(n)+" "+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' rows="'+B+'" >'+htmlEncode(m)+"</div></div>",a+="</div>",Z.push({fetched:!0,sourceid:htmlEncode(f),source:null,type:"d_codeeditor"}));break;case "d_multilinetext":s?(a+='<div class="form-group form-inline '+
htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="label">'+htmlEncode(v)+z+"</label></div>",m=htmlEncode(m),m=str_replace(m,"\r",""),m=str_replace(m,"\n","<br />"),a+='<div class="col-md-9 small"><label style="width:100%; height:auto; word-wrap:break-word" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">'+m+"</label></div>"):(a+='<div class="form-group form-inline '+htmlEncode(f+
"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">',a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="textarea">'+htmlEncode(v)+z+"</label></div>",a+='<div class="col-md-9 small"><textarea style="width:100%;" name="'+htmlEncode(f)+'" class="'+htmlEncode(n)+" "+htmlEncode(f)+'"  maxlength="'+htmlEncode(F)+'"  '+r+" "+u+' rows="'+B+'" >'+htmlEncode(m)+"</textarea></div>");a+="</div>";break;case "d_multilist":u="";s&&(u=' onclick="return false;" ');var M="";b="";a+='<div class="form-group form-inline '+
htmlEncode(f+"fld")+'" style="margin:0px; padding:1px 1px 1px 1px;'+p+'">';a+='<div class="col-md-3 small"><label style="width:100%;'+p+'" for="text">'+htmlEncode(v)+z+"</label></div>";0<=n.indexOf("d_multicheckbox")?(a+='<div class="col-md-9 small"><div class="clear"></div>',0<x.length?(b="datasource-"+A,a+="<fieldset "+u+' style="width:100%; border:0; box-shadow: none; height:auto; text-align:left; padding:0;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"cb")+" "+htmlEncode(f)+'" name="'+
htmlEncode(f)+'" >',w.push({fetched:!1,locator:"."+f,sourceid:b,source:x,data:null,selected:m}),A++):(M=null===m?[]:m,a+="<fieldset "+u+' style="width:100%; height:auto; overflow:auto; max-height:170px; border:0; box-shadow: none; text-align:left;" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'">',processArray(D,function(b){var d="";0<M.length&&processArray(M,function(a){a===b.p_code&&(d='checked="checked"')});a+='<div style="text-align:left"><label><input type="checkbox" class=" '+
htmlEncode(f)+'" value="'+htmlEncode(b.p_code)+'" checkboxlabel="'+htmlEncode(b.p_value)+'" name="'+htmlEncode(f)+'" '+d+'><span style="margin-right:10px;"> '+htmlEncode(b.p_value)+"</span></label></div>"})),a+="</fieldset></div>"):(0<x.length?(b="datasource-"+A,a+='<div class="col-md-9 small"><select style="width:100%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(b+"md")+" "+htmlEncode(f)+'" multiple name="'+htmlEncode(f)+'"  '+r+" "+t+" ></div>",w.push({fetched:!1,locator:"."+f,sourceid:b,
source:x,data:null,selected:m}),A++):(M=null===m?[]:m,a+='<div class="col-md-9 small"><select style="width:100%;" class="form-control '+htmlEncode(n)+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'"  multiple '+r+" "+t+" >",processArray(D,function(b){var d="";0<M.length&&processArray(M,function(a){a===b.p_code&&(d="selected")});a+='<option value="'+htmlEncode(b.p_code)+'" '+d+">"+htmlEncode(b.p_value)+"</option>"})),a+="</select></div>");a+="</div>";break;case "d_relatedlinks":e||0===V.length?doNothing():
(a+='<div class="form-group">',a+='<div class="col-md-12 small"><div class="clear"></div>',b="datasource-"+A,a+='<fieldset class="'+htmlEncode(n)+" "+htmlEncode(b+"rf")+" "+htmlEncode(f)+'" name="'+htmlEncode(f)+'" >',processArray(D,function(b){if(void 0===b.p_permissions||0===b.p_permissions.length||hasPermission(JSON.parse(str_replace(b.p_permissions,"'",'"'))))a+='<label class=" fb-relatedlink-btn '+htmlEncode(f)+'" style="cursor: pointer; color:#069;" command="'+htmlEncode(b.p_command)+'" parameters="'+
htmlEncode(b.p_parameters)+'" name="'+htmlEncode(f)+'"><span style="margin-right:10px;"> '+htmlEncode(b.p_label)+"</span></label>"}),a+="</fieldset></div>");break;default:doNothing()}O+=","+n.split(" ")}h&&(g&&0<l.length&&l==R)&&(R="")}catch(P){doException("renderField:"+d.p_name,P)}return a}function ka(b,d,c){var g="",g=g+"<div>";processArray(b.fields,function(e){if(null===e)doException("renderSection","null field exception");else try{var a=e.p_style;isNullOrUndefined(a)&&(a="");0>(" "+a+" ").indexOf(" gb-hidden ")&&
(g+=Da(b,e,d,c))}catch(l){doException("renderSection",l)}});return g+="</div>"}function la(b,d){var c="",e=getGUID();X=[];w=[];A=ia=0;R="ge-focusfield";if(C.htmlmode)c+="<div>",processArray(b,function(a){var b=a.sectioncolour;isNullOrUndefined(b)||(b=b.split("|"),isNullOrUndefined(b[2]),isNullOrUndefined(b[3]));"DATA"===a.sectiontype.toUpperCase()?(c+="<div>",c+=ka(a,d),c+="</div>"):doNothing()});else{var h=0;processArray(b,function(a){"FORMHEADER"===a.sectiontype.toUpperCase()||"DATAHEADER"===a.sectiontype.toUpperCase()?
doNothing():("DATA"===a.sectiontype.toUpperCase()||"INTERNALUSEFORMHEADER"===a.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])||"INTERNALUSEONLY"===a.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"]))&&h++});c=C.showaccordion||1<h?c+('<div class="panel-group ge-formsection-group" id="'+e+'" role="tablist" aria-multiselectable="true">'):c+"<div>";processArray(b,function(a){c+=ma(a,C.showaccordion||1<h,d,e)})}return c+="</div>"}function ma(b,d,c,e){var h=!1,a="",l="",q=getGUID(),
s=getGUID(),u=b.sectioncolour;void 0!==e&&0<e.length&&(q=e);isNullOrUndefined(u)?u="":(e=u.split("|"),isNullOrUndefined(e[2])||(u="background-color:"+e[2]+"; "),isNullOrUndefined(e[3])||(u+="color:"+e[3]+"; background-image:none;"));"FORMHEADER"===b.sectiontype.toUpperCase()||"DATAHEADER"===b.sectiontype.toUpperCase()?doNothing():"DATA"===b.sectiontype.toUpperCase()||"INTERNALUSEFORMHEADER"===b.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])||"INTERNALUSEONLY"===b.sectiontype.toUpperCase()&&
hasPermission(["IUSE_DATAFORM"])?("DATA"===b.sectiontype.toUpperCase()?(l="in",h=!0):l="",a+='<div class="panel panel-default gs-panel-default ge-formsection">',d&&(a=a+('<div class="panel-heading gs-panel-heading-relative" style="'+u+'" role="tab" >')+'<h4 class="panel-title">',a+='<a style="display: block; width: 100%;" role="button" data-toggle="collapse" data-parent="#'+q+'" href="#'+s+'" aria-expanded="true" aria-controls="'+s+'">',a+=htmlEncode(b.sectiontitle),a+="</a>",a+="</h4>",a+='<div class="gs-headingsection-controls">',
void 0!==b.sectionquantity&&"1+"===b.sectionquantity&&(a+='<a data-sectioncode="'+b.sectioncode+'" class="gs-headingsection-control ge-control-addcurrentsection">+</a>'),void 0!==b.sectionref&&0<b.sectionref.length&&(a+='<a style="margin-left:5px" data-sectioncode="'+b.sectioncode+'" class="gs-headingsection-control ge-control-removecurrentsection">-</a>'),a+="</div>",a+="</div>",a+='<div id="'+s+'" class="panel-collapse collapse '+l+'" role="tabpanel" >',a+='<div id="fb-render-'+s+'" class="panel-body fb-render-'+
s+'">'),a+=ka(b,c,h),d&&(a+="</div>",a+="</div>"),a+="</div>"):doNothing();return a}function Ea(b,d){for(var c=d.split("|"),e=[],h=0;h<=c.length-1;h++){var a=c[h],l=a.split("[")[0],a=a.split("[")[1].replace("]","");if(l==b){l=a.split(",");for(a=0;a<=l.length-1;a++)e[l[a]]=""}}e=Object.keys(e);return d=e.join(",")}function Fa(){processArray(w,function(b){c.unbindEvents(e,b.sourceid+"cb");c.onDirty(e,b.sourceid+"cb",function(){l.raiseRendererEvent("Checkbox",e,b.locator,"onChange");q()})})}function Ga(){processArray(w,
function(b){c.unbindEvents(e,b.sourceid+"dd");c.onDirty(e,b.sourceid+"dd",function(){l.raiseRendererEvent("Dropdown",e,b.locator,"onChange");q()})})}function Ha(){processArray(w,function(b){c.unbindEvents(e,b.sourceid+"md");c.onDirty(e,b.sourceid+"md",function(){l.raiseRendererEvent("DropdownMulti",e,b.locator,"onChange");q()})})}function Ia(){processArray(Z,function(b){try{b.source=new jCodeEditor(c,e,"."+b.sourceid,{defaultContent:"",element:"fldCode-"+b.sourceid})}catch(d){doException("bindCodeEditors",
d)}})}function Ja(){processArray(U,function(b){b.source=new jEditor(c,e,"."+b.sourceid,{defaultContent:"",element:"fldCode-"+b.sourceid,toolbar:"run | load | reset | clear | imagepicker | searchreplace | undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | fullscreen",cbOnClear:function(d,c){b.source.setContent("");return!0},cbOnDirty:function(d){l.raiseRendererEvent("Editor",e,"."+b.sourceid,"onChange");q(d)},cbOnFileBrowse:function(b,
c,e){b.document.getElementById(c).value=e},cbOnReset:function(d,c){b.source.setContent("");return!0},cbOnSave:function(b,e){c.dialogAlert("Save failed: "+c.encodeHTML(e),doNothing);return!1}})})}function Ka(){processArray(w,function(b){c.unbindEvents(e,b.sourceid+"rb");c.onDirty(e,b.sourceid+"rb",function(){l.raiseRendererEvent("Radiobutton",e,b.locator,"onChange");q()})})}function ga(){c.unbindEvents(e,O+",fb-relatedlink-btn,fb-imagepicker-btn,fb-imagegallery-btn,fb-imagedelete-btn,fb-choose-btn,fb-download-button,fb-map-btn,ge-d_document-remove-button,ge-d_representation-search,ge-d_list-search,ENTITYPICKER,ge-uploaddocument-button,fb-url-field,ge-selectdocument-button,ge-image-field,ge-control-addcurrentsection,ge-control-removecurrentsection");
c.bindEvent(l,e,".fb-imagedelete-btn","ImageDeleteButton","onClick");c.bindEvent(l,e,".fb-imagepicker-btn","ImagePickerButton","onClick");c.bindEvent(l,e,".fb-imagegallery-btn","ImageGalleryButton","onClick");c.bindEvent(l,e,".fb-choose-btn","ChooseButton","onClick");c.bindEvent(l,e,".fb-download-button","DownloadButton","onClick");c.bindEvent(l,e,".fb-here-btn","HereButton","onClick");c.bindEvent(l,e,".fb-map-btn","MapButton","onClick");c.bindEvent(l,e,".fb-view-button","ViewButton","onClick");c.bindEvent(l,
e,".ge-d_document-remove-button","DocumentRemoveButton","onClick");c.bindEvent(l,e,".ge-uploaddocument-button","UploadButton","onClick");c.bindEvent(l,e,".ge-selectdocument-button","SelectButton","onClick");c.bindEvent(l,e,".fb-url-field","UrlField","onChange");c.bindEvent(l,e,".fb-relatedlink-btn","RelatedLinkButton","onClick");c.bindEvent(l,e,".ge-d_representation-search","DropdownSearch","onClick");c.bindEvent(l,e,".ge-d_list-search","DropdownSearch","onClick");c.bindEvent(l,e,".ENTITYPICKER",
"EntityPicker","onClick");c.bindEvent(l,e,".ENTITYPICKERCLEAR","EntityPickerClear","onClick");c.bindEvent(l,e,".ge-image-field","ImageField","onLoad");c.bindEvent(l,e,".ge-control-addcurrentsection","SectionAddCurrent","onClick");c.bindEvent(l,e,".ge-control-removecurrentsection","SectionRemoveCurrent","onClick");var b=I.split(",");processArray(b,function(b){c.onDirty(e,b,function(){l.raiseRendererEvent("Field",e,"."+htmlEncode(b),"onChange");q()})})}function na(b,d){La();ra();ga();Fa();Ga();Ha();
Ma();Ka();Na();Ja();Ia();Oa(b,d);sa();0<T.length&&$.ajax({url:"fetch.php?token="+encodeURIComponent(SECURITY_TOKEN)+"&metadata="+T.join(","),dataType:"script",success:doNothing})}function Na(){c.unbindEvents(e,"todaysdate-button,cleardate-button");c.bindEvent(l,e,".todaysdate-button","TodaysButton","onClick");c.bindEvent(l,e,".cleardate-button","ClearDateButton","onClick");c.bindDatePicker(e,".ge-btdatepicker",{dateFormat:DATE_OUTPUTFORMAT,showOtherMonths:!0,changeMonth:!0,changeYear:!0,yearRange:"c-75:c+5",
onSelect:function(b,d){l.raiseRendererEvent("Date",e,".ge-btdatepicker","onChange");q(!0)},onChangeMonthYear:function(b,d,k){k=new Date(c.element(this).datepicker("getDate"));k.setMonth(d-1);k.setYear(b);c.element(this).datepicker("setDate",k);l.raiseRendererEvent("Date",e,".ge-btdatepicker","onChange");q(!0)}});c.onDirty(e,".todaysdate-button",function(){l.raiseRendererEvent("Date",e,".ge-btdatepicker","onChange");q()});c.onDirty(e,".cleardate-button",function(){l.raiseRendererEvent("Date",e,".ge-btdatepicker",
"onClear");l.raiseRendererEvent("Date",e,".ge-btdatepicker","onChange");q()})}function Ma(){c.unbindEvents(e,"currenttime-button");c.bindEvent(l,e,".currenttime-button","NowButton","onClick");c.bindEvent(l,e,".cleartime-button","ClearTimeButton","onClick");c.bindTimePicker(e,".ge-bttimepicker",{onSelect:function(b){l.raiseRendererEvent("Time",e,".ge-bttimepicker","onChange");q(!0)}});c.onDirty(e,".currenttime-button",function(){l.raiseRendererEvent("Time",e,".ge-bttimepicker","onChange");q()});c.onDirty(e,
".cleartime-button",function(){l.raiseRendererEvent("Time",e,".ge-bttimepicker","onClear");l.raiseRendererEvent("Time",e,".ge-bttimepicker","onChange");q()})}function Oa(b,d){var k=c.element(b,".bs-input-limit");processArray(k,function(b){if(b.maxLength&&0<b.maxLength){var d=$.trim(b.name),a=getGUID(),k={color:"red"};k.counter="#"+a;k.maxLength=b.maxLength;k.removeMaxLengthAttr=!1;k.threshold=2;c.element(e,"."+d).after('<div class="form-inline small" style="font-size:10px; text-align:right;">&nbsp;&nbsp;<span id="'+
a+'"></span><span> : characters left</span></div>');c.element(e,"."+d).limit(k)}})}function Aa(b){var d="";processArray(U,function(c){if(c.sourceid==b)return d=c.source.getContent(!0),!0});return d}function Ba(b){var d="";processArray(Z,function(c){if(c.sourceid==b)return d=c.source.getContent(!0),!0});return d}function La(){function b(){q++;l==q&&(ta(),ua(),va(),wa(),$.isFunction(K)&&c.after(100,function(){K()}))}function d(){0===s&&c.ajaxError();s++}function e(a,d,c){processArray(w,function(b){if(b.sourceid==
a)return b.data=c,!0});b()}function g(a){var b=!1;processArray(w,function(d){if(d.sourceid==a&&d.fetched)return b=!0});return b}function h(a){processArray(w,function(b){if(b.sourceid==a)return b.fetched=!0})}function a(a,l){if(g(a))b();else if(h(a),"SYSTEMPRINTERS"===l){var r=c.getPrinters();e(a,"SYSTEMPRINTERS",r)}else{var q=l.split("|"),r="",s=[];0<q.length&&(r=q[0]);q.length>P&&(q=q[2],q=str_replace(q,"'",'"'),s=JSON.parse(q));r=c.ajaxRequestCreate("entity_entitydatalist",[{name:"entitycode",value:r},
{name:"order",value:""},{name:"fixedfilter",value:s},{name:"offset",value:0}]);c.ajaxCall(URL_WEBSERVICE,r,function(b){e(a,l,b)},d)}}var l=w.length,q=0,s=0;0<l?processArray(w,function(b){a(b.sourceid,b.source)}):$.isFunction(K)&&c.after(100,function(){K()})}var c=pa,l=this,D=!1,e="",oa="",R="",aa=null,P=2,S=!1,J="",C={flags:"",formified:!1,htmlmode:!1,printpreview:!1,readonly:!0,showaccordion:!1,style:"accordion"};void 0!==ba&&(aa=ba);void 0!==B.flags&&(C.flags=B.flags);void 0!==B.formified&&(C.formified=
B.formified);void 0!==B.htmlmode&&(C.htmlmode=B.htmlmode);void 0!==B.printpreview&&(C.printpreview=B.printpreview);void 0!==B.readonly&&(C.readonly=B.readonly);void 0!==B.showaccordion&&(C.showaccordion=B.showaccordion);void 0!==B.style&&(C.style=B.style);var ca=!C.readonly&&c.hasCapability("printer")&&c.isPrinterRegistered(),K=B.cbRenderComplete,ea=B.cbSetDirty,y=[],w=[],X=[],ia=0,Y=[],ja=0,A=0,U=[],Z=[],T=[],V="",O="formtitle",I="";this.getDataSourceByDataSourceID=function(b){var d=null;processArray(w,
function(c){if(c.sourceid==b)return d=c,!0});return d};this.raiseRendererEvent=function(b,d,c,e){if(null!==aa)try{aa.Renderer_onEvent(b,d,c,e)}catch(h){}};this.ChooseButton_onClick=function(b){};this.DownloadButton_onClick=function(b){b=c.element(b);b=htmlDecode(b.attr("documentid"));c.viewDocument(b,!0)};this.DocumentRemoveButton_onClick=function(b){var d=c.element(b),e=htmlDecode(d.attr("documentid")),g=htmlDecode(d.attr("document"));c.dialogConfirm("Are you sure you want to remove the selected document?",
function(){za(b,g,e);L(g)})};this.DropdownSearch_onClick=function(b){b=c.element(b);var d=htmlDecode(b.attr("targetdatasourceid"));b=htmlDecode(b.attr("targettitle"));var k=l.getDataSourceByDataSourceID(d),g=[],h="",a=[];0<k.source.length&&(g=k.source.split("|"));0<g.length&&(h=g[0]);if(1<g.length){var w=g[1],w=str_replace(w,"'",'"');JSON.parse(w)}g.length>P&&(g=g[2],g=str_replace(g,"'",'"'),a=JSON.parse(g));c.showFormPopup("entity.frmEntityChooser",{type:"form",entity:"systemform",formentity:h,mode:"select",
title:b+" chooser",fixedfilter:a,resultfields:["id"]},function(a){0<a.length&&(a=a[0].id,c.element(e,"."+d+"dd").val(a),l.raiseRendererEvent("Entity",e,k.locator,"onChange"),q(),c.element(e,"."+d+"dd").focus())},!1,!0)};this.EntityPicker_onClick=function(b){b=c.element(b);var d=htmlDecode(b.attr("targetdatasourceid"));b=htmlDecode(b.attr("targettitle"));var k=l.getDataSourceByDataSourceID(d),g=[],h="",a=["description"],w=[],y=[];0<k.source.length&&(g=k.source.split("|"));0<g.length&&(h=g[0]);if(1<
g.length)var s=g[1],s=str_replace(s,"'",'"'),s=s.toLowerCase(),a=JSON.parse(s),y=JSON.parse(s);g.length>P&&(g=g[2],g=str_replace(g,"'",'"'),w=JSON.parse(g));a.push("id");c.showFormPopup("entity.frmEntityChooser",{type:"form",entity:"systemform",formentity:h,mode:"select",title:b+" chooser",fixedfilter:w,resultfields:a},function(a){if(0<a.length){var b="";processArray(y,function(d){0<b.length&&(b+=" | ");b+=a[0][d]});var g=a[0].id,h=b;c.element(e,"."+d+"epv").val(g);c.element(e,"."+d+"epd").val(h);
c.element(e,"."+d+"tds").val(h);l.raiseRendererEvent("Entity",e,k.locator,"onChange");q();c.element(e,"."+d+"tds").focus()}},!1,!0)};this.EntityPickerClear_onClick=function(b){var d=c.element(b);b=htmlDecode(d.attr("targetdatasourceid"));d=htmlDecode(d.attr("name"));l.getDataSourceByDataSourceID(b);c.element(e,"."+b+"epv").val("");c.element(e,"."+b+"epd").val("");c.element(e,"."+b+"tds").val("");l.raiseRendererEvent("Entity",e,"."+d,"onClear");l.raiseRendererEvent("Entity",e,"."+d,"onChange");q();
c.element(e,"."+b+"tds").focus()};this.ImageGalleryButton_onClick=function(b){var d=c.element(b).attr("btnid");c.showFormPopup("core.frmGallery","mode=chooser&caption=Image Selector",function(b){!1===C.readonly&&0<b.length&&(ha(b[0].id,d),l.raiseRendererEvent("Image",e,"."+d,"onChange"),q())},!1,!0)};this.ImagePickerButton_onClick=function(b){var d=c.element(b).attr("btnid");singleFileUpload(c,"nobatch","import_images","",function(b){b.length&&(ha(b[0].tag,d),l.raiseRendererEvent("Image",e,"."+d,
"onChange"),q())})};this.ImageDeleteButton_onClick=function(b){try{var d=c.element(b).attr("btnid");c.dialogConfirm("Are you sure you want to remove the selected image?",function(){c.element(e," ."+htmlEncode(d)).attr("value","");c.element(e,"."+htmlEncode(d)).attr("src","images/noimage.png");l.raiseRendererEvent("Image",e,"."+d,"onClear");l.raiseRendererEvent("Image",e,"."+d,"onChange");q(!0)})}catch(k){doException("ImageDeleteButton_onClick",k)}};this.HereButton_onClick=function(b){navigator.geolocation.getCurrentPosition(function(d){d=
d.coords.latitude+", "+d.coords.longitude;var k=c.element(b),g=c.element(b).attr("name"),k=k.parent().siblings("input");k.val(d);l.raiseRendererEvent("Location",e,"."+g,"onChange");q(!0);k.focus()},function(){c.dialogAlert("Location not found.",doNothing)})};this.MapButton_onClick=function(b){b=c.element(e,b).attr("btnid");b=c.element(e,"."+b+"").val();c.isModuleLoaded("maps")?c.showForm("maps.frmMap","mode=search&search="+encodeURIComponent(b)):c.isModuleLoaded("openmaps")&&c.showForm("openmaps.frmMap",
"mode=search&search="+encodeURIComponent(b))};this.NowButton_onClick=function(b){b=c.element(b);b=htmlDecode(b.attr("btnid"));var d=new Date,k=d.getHours(),d=d.getMinutes(),g="",g=(10>k?"0"+k:""+k)+":"+(10>d?"0"+d:""+d),h=document.createElement("input");h.setAttribute("type","date");h.setAttribute("value","not-a-time");"not-a-time"===h.value&&(g=11<k?"PM":"AM",11<k&&(k-=12),g=(10>k?"0"+k:""+k)+":"+(10>d?"0"+d:""+d)+" "+g);c.element(e,"."+b).val(g);l.raiseRendererEvent("Time",e,"."+b,"onChange");q(!0);
c.element(e,"."+b).focus()};this.RelatedLinkButton_onClick=function(b){var d=c.element(e,b).attr("command");b=c.element(e,b).attr("parameters");b=str_replace(b,"|","&");b=str_replace(b,"%SELECTED%","/SELECTED/");b=c.urlToJSON(b);b.fixedfilter=str_replace(b.fixedfilter,"'",'"');b.fixedfilter=str_replace(b.fixedfilter,"/SELECTED/",V);b.relativeid=str_replace(b.relativeid,"/SELECTED/",V);c.showForm(d,b)};this.SelectButton_onClick=function(b){b=htmlDecode(c.element(e,b).attr("btnid"));xa(b)};this.UploadButton_onClick=
function(b){b=htmlDecode(c.element(e,b).attr("btnid"));Ca(b)};this.UrlField_onChange=function(b,d){var k=c.element(e,b).attr("name"),g="",g=c.element(e,b).val();"http://"!==c.str_left(g,7).toLowerCase()&&"https://"!==c.str_left(g,8).toLowerCase()&&(g="http://"+g);c.element(e,"."+htmlEncode(k)).attr("href",g)};this.ViewButton_onClick=function(b){b=c.element(b);b=htmlDecode(b.attr("documentid"));c.viewDocument(b,!1)};this.ClearDateButton_onClick=function(b){b=c.element(b);b=htmlDecode(b.attr("btnid"));
c.element(e,"."+b).val("");l.raiseRendererEvent("Date",e,"."+b,"onClear");l.raiseRendererEvent("Date",e,"."+b,"onChange");q();c.element(e,"."+b).focus()};this.ClearTimeButton_onClick=function(b){b=c.element(b);b=htmlDecode(b.attr("btnid"));c.element(e,"."+b).val("");l.raiseRendererEvent("Time",e,"."+b,"onClear");l.raiseRendererEvent("Time",e,"."+b,"onChange");q();c.element(e,"."+b).focus()};this.TodaysButton_onClick=function(b){b=c.element(b);b=htmlDecode(b.attr("btnid"));var d=new Date,k=d.getDate(),
g=d.getMonth()+1,d=d.getFullYear();1==g.toString().length&&(g="0"+g);1==k.toString().length&&(k="0"+k);k=d+"-"+g+"-"+k;g="";2<=k.length&&(g=c.dateFromISO(DATE_OUTPUTFORMAT,k.toString()));c.element(e,"."+b).val(g);l.raiseRendererEvent("Date",e,"."+b,"onChange");q();c.element(e,"."+b).focus()};this.append=function(b){processArray(b,function(b){1<=y.length&&"FORMHEADER"===b.sectiontype?doNothing():y.push(b)})};this.clear=function(){y=[];D=!1};this.clearData=function(){processArray(y,function(b){"FORMHEADER"===
b.sectiontype.toUpperCase()||"DATAHEADER"===b.sectiontype.toUpperCase()?doNothing():processArray(b.fields,function(d){G(b.sectioncode,d.p_name);d.p_value="d_yesno"===d.p_datatype?"Y":""})});D=!1};this.getData=function(){D&&(N(),D=!1);return y};this.getHTML=function(b){void 0==b&&(b=!0);S=!1;J="";D&&(N(),D=!1);I="";var d=la(y,!0),e=c.getProperty("businessname"),g=qa("DESCRIPTION"),h="";b&&(0<e.length&&(h+="<h1>"+htmlEncode(e)+"</h1>"),0<g.length&&(h+="<h1>"+htmlEncode(g)+"</h1>"));return h+d+REPORT_PRINTEDBY};
this.getSectionField=function(b,d){var c="";processArray(y,function(e){e.sectioncode.toUpperCase()===b.toUpperCase()&&processArray(e.fields,function(h){var a=G(e.sectioncode,h.p_name),l=G(b,d);if(a.toUpperCase()===l.toUpperCase())return c=h.p_value,!0})});return c};this.getSectionFieldByType=function(b,d){var c="";processArray(y,function(e){e.sectiontype.toUpperCase()===b.toUpperCase()&&processArray(e.fields,function(h){var a=G(e.sectiontype,h.p_name),l=G(b,d);if(a.toUpperCase()===l.toUpperCase())return c=
h.p_value,!0})});return c};this.getTabableFields=function(){};this.setData=function(b){processArray(b,function(b){"FORMHEADER"===b.sectiontype.toUpperCase()||"DATAHEADER"===b.sectiontype.toUpperCase()?doNothing():"DATA"===b.sectiontype.toUpperCase()||"INTERNALUSEFORMHEADER"===b.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])||"INTERNALUSEONLY"===b.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])?processArray(b.fields,function(c){l.setSectionField(b.sectioncode,c.p_name,c.p_value)}):
doNothing()})};this.render=function(b,d,k){S=!1;J="";C.readonly=k;e=b;oa=d;I="";var g=la(y,C.html);c.element(b,d).html(g);na(e);C.readonly?(c.element(e,".fb-imagepicker-btn").hide(),c.element(e,".fb-imagegallery-btn").hide(),c.element(e,".fb-imagedelete-btn").hide(),c.element(e,".ge-uploaddocument-button").hide(),c.element(e,".ge-selectdocument-button").hide()):(c.element(e,".fb-imagepicker-btn").show(),c.element(e,".fb-imagegallery-btn").show(),c.element(e,".fb-imagedelete-btn").show(),c.element(e,
".ge-uploaddocument-button").show(),c.element(e,".ge-selectdocument-button").show());hasPermission(["VW_MAPS"])?c.element(e,".fb-map-btn").show():c.element(e,".fb-map-btn").hide();S&&!k&&(c.dialogAlert("Attention: The following fields were updated to a new data format:<br><br>"+J+"<br><br>It is recommended you save this form.",doNothing),c.after(500,q));k||c.element(e,".ge-focusfield").focus()};this.setID=function(b){};this.setDataID=function(b){V=b};this.setSectionField=function(b,d,c){processArray(y,
function(e){e.sectioncode.toUpperCase()===b.toUpperCase()&&processArray(e.fields,function(h){var a=G(e.sectioncode,h.p_name),l=G(b,d);a.toUpperCase()===l.toUpperCase()&&(h.p_value=c)})})};this.validate=function(){var b="";D&&(N(),D=!1);processArray(y,function(d){"FORMHEADER"===d.sectiontype.toUpperCase()||"DATAHEADER"===d.sectiontype.toUpperCase()?doNothing():"DATA"===d.sectiontype.toUpperCase()||"INTERNALUSEFORMHEADER"===d.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])||"INTERNALUSEONLY"===
d.sectiontype.toUpperCase()&&hasPermission(["IUSE_DATAFORM"])?processArray(d.fields,function(k){var g="",h="",g=k.p_datatype,h=k.p_required,a=htmlEncode(k.p_label);"d_yesno"===g||"d_spacer"===g||"d_heading"===g||"d_description"===g?doNothing():"d_list"===g||"d_predictivetext"===g?c.toBoolean(h)&&(G(d.sectioncode,k.p_name+"epv"),h=$.trim(k.p_value),0===h.length&&(b+="<li>"+htmlEncode(a)+" is required.</li>")):c.toBoolean(h)&&(g=G(d.sectioncode,k.p_name),h=$.trim(k.p_value),c.element(e,"."+g).is(":hidden")||
0===h.length&&(b+="<li>"+htmlEncode(a)+" is required.</li>"))}):doNothing()});return b};this.ImageField_onLoad=function(b){var c=b.width/b.height;$(b).css("width","");$(b).css("height","");1<c?$(b).css("width","100%"):$(b).css("height","100%")};this.SectionAddCurrent_onClick=function(b){var d=c.element(b).data("sectioncode"),k=null,g=[];processArray(y,function(a){g.push(a);a.sectioncode===d&&(k=JSON.parse(JSON.stringify(a)),k.sectionquantity="1",k.sectioncode=getGUID(),k.sectionref=d,processArray(k.fields,
function(a){a.p_searchable=""}),g.push(k))});y=g;var h=c.element(b).parents(".ge-formsection-group").attr("id"),h=ma(k,!0,C.html,h);c.element(b).parents(".ge-formsection").after(h);na(e,oa);q()};this.SectionRemoveCurrent_onClick=function(b){var d=c.element(b).data("sectioncode"),e=[];processArray(y,function(b){b.sectioncode!==d&&e.push(b)});y=e;c.element(b).parents(".ge-formsection").remove();q()}};
