// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
var g_arrDesktopRegions=[],g_arrPermissions=[],g_arrProducts=[],FULLBROWSERCAPABILITY="canvas,console,geolocation,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",USEJSONP=!1,VIEWPORTINITIALSTATE="width="+DEVICE_WIDTH+", initial-scale=1.0, maximum-scale=3.0, minimum-scale=0.25",g_intPreviousOrientation;g_intPreviousOrientation=void 0===window.orientation?0:parseInt(window.orientation,10);
var g_arrDependencies=[{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-osutils-classes.z.js",debug:DYNAMIC_APP_DIR_URL+"inc-osutils-classes.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-osutils-jdock.z.js",debug:DYNAMIC_APP_DIR_URL+"inc-osutils-jdock.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-osutils-jeditor.z.js",debug:DYNAMIC_APP_DIR_URL+"inc-osutils-jeditor.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+
"inc-osutils-jcodeeditor.z.js",debug:DYNAMIC_APP_DIR_URL+"inc-osutils-jcodeeditor.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-osutils-jformrenderer.z.js",debug:DYNAMIC_APP_DIR_URL+"inc-osutils-jformrenderer.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-osutils-jgrids.z.js",debug:DYNAMIC_APP_DIR_URL+"inc-osutils-jgrids.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-osutils-notminified.js",loaded:!1},
{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"js/base64v1_0.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"js/qz-tray.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"js/jpeg_encoder_basic.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"js/fileupload/cors/jquery.xdr-transport.js",loaded:!1},{moduleid:"osfull",type:"js",dependency:DYNAMIC_APP_DIR_URL+"inc-hostdriver.js",loaded:!1},{moduleid:"osfull",
type:"js",dependency:DYNAMIC_APP_DIR_URL+"modules/widgetclock/clock/clock.js",loaded:!1},{moduleid:"widgetcalculator.wgtCalculator",type:"js",dependency:DYNAMIC_APP_DIR_URL+"modules/widgetcalculator/js/calculator.js",loaded:!1},{moduleid:"widgetclock.wgtClock",type:"js",dependency:DYNAMIC_APP_DIR_URL+"modules/widgetclock/clock/clock.js",loaded:!1},{moduleid:"widgettube.wgtTube",type:"js",dependency:DYNAMIC_APP_DIR_URL+"modules/widgettube/tabular/jquery.tubular.1.0.js",loaded:!1}],g_objCapabilities=
[{code:"canvas",description:"Canvas",notes:"Allows advanced drawing including sign on glass."},{code:"console",description:"hidden",notes:""},{code:"geolocation",description:"Geo Locations",notes:"The ability to locate your position using GPS coordinates or wifi hotspots."},{code:"google",description:"hidden",notes:""},{code:"help",description:"Interactive Help",notes:"Interactive help can guide new users in a friendly tutorial like manner."},{code:"html5",description:"HTML5 Support",notes:"Allows for advanced HTML5 facilities typically such as enhanced visual effects."},
{code:"java",description:"Java Support",notes:"Allows automatic importing as well as direct to printer printing including thermal printers."},{code:"jqxhr",description:"Multiple File Upload",notes:"Allows multiple files to be queued for upload in a single go."},{code:"maps",description:"Mapping",notes:"Indicates whether mapping services are available.  This facility requires a mapping provider to be configured."},{code:"mobile",description:"hidden",notes:""},{code:"multimon",description:"Multiple Monitor",
notes:"You can increase your productivity by having multiple monitors connected to your computer."},{code:"multitouch",description:"Multi-Touch",notes:"Incidates whether the divice supports multi-touch features."},{code:"printer",description:"Printing",notes:"Indicates whether printing facilities are available."},{code:"regionscroll",description:"hidden",notes:""},{code:"speech",description:"Speech Recognition",notes:"Indicates whether speech recognition services are available.  This facility requires a speech provider to be configured."},
{code:"symbols",description:"hidden",notes:""},{code:"themes",description:"Themable",notes:"Incidates whether custom themes are supported."},{code:"timers",description:"Background Processing",notes:"With advanced background processing you can often perform multiple tasks at the same time."},{code:"tips",description:"Tool Tips",notes:"Popup tool tips are a useful guide to more information if you hover over certain buttons and other features."},{code:"touch",description:"Touch Screen",notes:"If your touch screen monitor is supported."},
{code:"tube",description:"Youtube Video",notes:"Support for youtube video playback services."},{code:"video",description:"Video Support",notes:"Support for video playback."},{code:"viewport",description:"hidden",notes:""},{code:"widgets",description:"Widgets",notes:"Widgets can provide you useful tools that can be left on the screen for easy access or visual display."},{code:"zoom",description:"Zooming",notes:"On low resolution monitors the ability to zoom can give you an effective larger working area for multiple forms."}],
g_objBrowsers=[{osid:"Android",browserid:"Samsung Browser",name:"Samsung Browser for Android",capabilities:"canvas,google,html5,maps,mobile,multitouch,symbols,timers,touch",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom,viewport",supportlevel:"passable",major:0},{osid:"Android",browserid:"Android Browser",name:"Google Android Browser",capabilities:"canvas,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",
supportlevel:"passable",major:4},{osid:"Android",browserid:"Android Browser",name:"Google Android Browser",capabilities:"",uncapabilities:"canvas,console,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",supportlevel:"unavailable",major:0},{osid:"Android",browserid:"Chrome",name:"Google Chrome for Android",capabilities:"canvas,geolocation,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",
uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",supportlevel:"best",major:47},{osid:"Android",browserid:"Chrome",name:"Google Chrome for Android",capabilities:"canvas,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",supportlevel:"passable",major:0},{osid:"iOS",browserid:"Chrome",name:"Google Chrome for iOS",
capabilities:"canvas,geolocation,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",supportlevel:"best",major:47},{osid:"iOS",browserid:"Chrome",name:"Google Chrome for iOS",capabilities:"canvas,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",
supportlevel:"passable",major:0},{osid:"Android",browserid:"Edge",name:"Microsoft Edge for Android",capabilities:"canvas,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"passable",major:0},{osid:"iOS",browserid:"Edge",name:"Microsoft Edge for iOS",capabilities:"canvas,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",
supportlevel:"passable",major:0},{osid:"Android",browserid:"Firefox",name:"Mozilla Firefox for Android",capabilities:"canvas,geolocation,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"best",major:0},{osid:"iOS",browserid:"Firefox",name:"Mozilla Firefox for iOS",capabilities:"canvas,geolocation,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",
uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"best",major:0},{osid:"Android",browserid:"Opera",name:"Opera for Android",capabilities:"canvas,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"passable",major:0},{osid:"iOS",browserid:"Opera",name:"Opera for iOS",capabilities:"canvas,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",
uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"passable",major:0},{osid:"BlackBerry",browserid:"Mobile Safari",name:"Blackberry Browser",capabilities:"canvas,geolocation,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"best",major:0},{osid:"Windows Phone",browserid:"IEMobile",
name:"IEMobile for Windows Phone",capabilities:"canvas,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",supportlevel:"passable",major:10},{osid:"Windows Phone",browserid:"IEMobile",name:"IEMobile for Windows Phone",capabilities:"canvas,google,html5,jqxhr,maps,mobile,multitouch,timers,touch,viewport",uncapabilities:"console,help,java,multimon,printer,regionscroll,speech,symbols,themes,tips,tube,video,widgets,zoom",
supportlevel:"passable",major:0},{osid:"iOS",browserid:"Mobile Safari",name:"Mobile Safari",capabilities:"canvas,geolocation,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",supportlevel:"best",major:8},{osid:"iOS",browserid:"Mobile Safari",name:"Mobile Safari",capabilities:"canvas,geolocation,google,html5,maps,mobile,multitouch,symbols,timers,touch,viewport",uncapabilities:"console,help,java,jqxhr,multimon,printer,regionscroll,speech,themes,tips,tube,video,widgets,zoom",
supportlevel:"best",major:0},{osid:"Mac OS",browserid:"Chrome",name:"Google Chrome",capabilities:"canvas,console,geolocation,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",uncapabilities:"mobile",supportlevel:"best",major:45},{osid:"Windows",browserid:"Chrome",name:"Google Chrome",capabilities:"canvas,console,geolocation,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
uncapabilities:"mobile",supportlevel:"best",major:48},{osid:"Windows",browserid:"Chrome",name:"Google Chrome",capabilities:"canvas,console,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",uncapabilities:"mobile",supportlevel:"passable",major:17},{osid:"Windows",browserid:"Chrome",name:"Google Chrome",capabilities:"",uncapabilities:"canvas,console,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
supportlevel:"unavailable",major:0},{osid:"Windows",browserid:"Edge",name:"Microsoft Edge",capabilities:"canvas,geolocation,google,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",uncapabilities:"console,help,mobile,speech",supportlevel:"best",major:12},{osid:"Windows",browserid:"Edge",name:"Microsoft Edge",capabilities:"",uncapabilities:"canvas,console,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
supportlevel:"unavailable",major:0},{osid:"Windows",browserid:"Firefox",name:"Mozilla Firefox",capabilities:"canvas,geolocation,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",uncapabilities:"console,mobile,speech",supportlevel:"best",major:43},{osid:"Windows",browserid:"Firefox",name:"Mozilla Firefox",capabilities:"canvas,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
uncapabilities:"console,mobile,speech",supportlevel:"passable",major:10},{osid:"Windows",browserid:"Firefox",name:"Mozilla Firefox",capabilities:"",uncapabilities:"canvas,console,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",supportlevel:"unavailable",major:0},{osid:"Windows",browserid:"IE",name:"Microsoft Internet Explorer",capabilities:"canvas,geolocation,google,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
uncapabilities:"console,help,mobile,speech",supportlevel:"best",major:10},{osid:"Windows",browserid:"IE",name:"Microsoft Internet Explorer",capabilities:"google,html5,java,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets",uncapabilities:"canvas,console,help,jqxhr,mobile,speech,zoom",supportlevel:"passable",major:9},{osid:"Windows",browserid:"IE",name:"Microsoft Internet Explorer",capabilities:"",uncapabilities:"canvas,console,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
supportlevel:"unavailable",major:0},{osid:"Mac OS",browserid:"Safari",name:"Safari",capabilities:"canvas,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",uncapabilities:"console,mobile,speech",supportlevel:"passable",major:8},{osid:"Mac OS",browserid:"Safari",name:"Safari",capabilities:"canvas,google,help,html5,java,jqxhr,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
uncapabilities:"console,mobile,speech",supportlevel:"passable",major:6},{osid:"Mac OS",browserid:"Safari",name:"Safari",capabilities:"google,help,html5,java,maps,multimon,multitouch,printer,regionscroll,symbols,themes,timers,tips,touch,tube,video,viewport,widgets",uncapabilities:"canvas,console,jqxhr,mobile,speech,zoom",supportlevel:"passable",major:5},{osid:"Mac OS",browserid:"Safari",name:"Safari",capabilities:"",uncapabilities:"canvas,console,google,help,html5,java,jqxhr,maps,mobile,multimon,multitouch,printer,regionscroll,speech,symbols,themes,timers,tips,touch,tube,video,viewport,widgets,zoom",
supportlevel:"unavailable",major:0}],g_objShortcuts={keycloseform:"Escape",keynew:"Alt+N",keypallets:"Alt+P",keysave:"Alt+S",keyfunction1:"Ctrl+1",keyfunction2:"Ctrl+2",keyfunction3:"Ctrl+3",keyfunction4:"Ctrl+4",keyfunction5:"Ctrl+5",keyfunction6:"Ctrl+6",keyfunction7:"Ctrl+7",keyfunction8:"Ctrl+8"},g_objShortcutsOverride=[{keys:"F1"},{keys:"F2"},{keys:"F3"},{keys:"F4"},{keys:"F5"},{keys:"F6"},{keys:"F7"},{keys:"F8"},{keys:"F9"},{keys:"F10"},{keys:"F11"},{keys:"Alt+F1"},{keys:"Alt+F2"},{keys:"Alt+F3"},
{keys:"Alt+F4"},{keys:"Alt+F6"},{keys:"Alt+F7"},{keys:"Alt+F8"},{keys:"Alt+F9"},{keys:"Alt+F10"},{keys:"Alt+F11"},{keys:"Alt+F12"},{keys:"Ctrl+F1"},{keys:"Ctrl+F2"},{keys:"Ctrl+F3"},{keys:"Ctrl+F4"},{keys:"Ctrl+F6"},{keys:"Ctrl+F7"},{keys:"Ctrl+F8"},{keys:"Ctrl+F9"},{keys:"Ctrl+F10"},{keys:"Ctrl+F11"},{keys:"Ctrl+F12"},{keys:"Alt+0"},{keys:"Alt+1"},{keys:"Alt+2"},{keys:"Alt+3"},{keys:"Alt+4"},{keys:"Alt+5"},{keys:"Alt+6"},{keys:"Alt+7"},{keys:"Alt+8"},{keys:"Alt+9"},{keys:"Ctrl+0"},{keys:"Ctrl+1"},
{keys:"Ctrl+2"},{keys:"Ctrl+3"},{keys:"Ctrl+4"},{keys:"Ctrl+5"},{keys:"Ctrl+6"},{keys:"Ctrl+7"},{keys:"Ctrl+8"},{keys:"Ctrl+9"},{keys:"Alt+A"},{keys:"Alt+B"},{keys:"Alt+C"},{keys:"Alt+D"},{keys:"Alt+E"},{keys:"Alt+F"},{keys:"Alt+G"},{keys:"Alt+H"},{keys:"Alt+I"},{keys:"Alt+J"},{keys:"Alt+K"},{keys:"Alt+L"},{keys:"Alt+M"},{keys:"Ctrl+A"},{keys:"Ctrl+B"},{keys:"Ctrl+D"},{keys:"Ctrl+E"},{keys:"Ctrl+F"},{keys:"Ctrl+G"},{keys:"Ctrl+H"},{keys:"Ctrl+I"},{keys:"Ctrl+J"},{keys:"Ctrl+K"},{keys:"Ctrl+L"},{keys:"Ctrl+M"},
{keys:"Alt+N"},{keys:"Alt+O"},{keys:"Alt+P"},{keys:"Alt+Q"},{keys:"Alt+R"},{keys:"Alt+S"},{keys:"Alt+T"},{keys:"Alt+U"},{keys:"Alt+V"},{keys:"Alt+W"},{keys:"Alt+X"},{keys:"Alt+Y"},{keys:"Alt+Z"},{keys:"Ctrl+N"},{keys:"Ctrl+O"},{keys:"Ctrl+P"},{keys:"Ctrl+Q"},{keys:"Ctrl+R"},{keys:"Ctrl+S"},{keys:"Ctrl+U"},{keys:"Ctrl+W"}],g_objVocab=[{phrase:"start recording",action:"speech dictate on"},{phrase:"stop recording",action:"speech dictate off"},{phrase:"window close",action:"speech window close"},{phrase:"what is the time now",
action:"what is the time now"},{phrase:"show about",action:"speech form about"},{phrase:"log out",action:"speech log out"},{phrase:"speech system off",action:"speech system off"}];window.Prototype&&(delete Object.prototype.toJSON,delete Array.prototype.toJSON,delete Hash.prototype.toJSON,delete String.prototype.toJSON);
Array.prototype.reduce||(Array.prototype.reduce=function(a){if(null===this||void 0===this)throw new TypeError("Object is null or undefined");var b=0,c=this.length>>0,d;if("function"!==typeof a)throw new TypeError("First argument is not callable");if(2>arguments.length){if(0===c)throw new TypeError("Array length is 0 and no second argument");d=this[0];b=1}else d=arguments[1];for(;b<c;)b in this&&(d=a.call(void 0,d,this[b],b,this)),++b;return d});
String.prototype.toRegExp||(String.prototype.toRegExp=function(){var a=this.replace(/([\/\(\)\[\]\.\?])/g,"\\$1"),a=a.replace("*",".*");return RegExp(a)});function doException(a,b){var c=!1;processArray(["broadcast","raiseEvent","setFormFocus"],function(b){a==b&&(c=!0)});!1===c&&logDebug("%cException: "+b+" raised in '"+a+"'","color:red; font-weight:bold;")}function doNothing(){}
function getGUID(a){void 0==a&&(a="");return a+"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)})}function hasFlag(a,b){return 0<=(" "+a+" ").indexOf(" "+b+" ")}function getFormDesktopRegion(a){var b="";processArray(g_arrDesktopRegions,function(c){c.entitycode===a&&(b=c.formdesktopregion)});return b}
function getListerDesktopRegion(a){var b="";processArray(g_arrDesktopRegions,function(c){c.entitycode===a&&(b=c.listerdesktopregion)});return b}function getProducts(){return g_arrProducts}function hasPermission(a){for(var b=!1,c=0;c<a.length&&!1===b;){for(var d=a[c],e=0;e<g_arrPermissions.length&&!1===b;)d==g_arrPermissions[e]&&(b=!0),e++;c++}return b}
function hasProduct(a,b){for(var c=!1,d=0;d<a.length&&!1===c;){for(var e=a[d],f=getProducts(),g=0;g<f.length&&!1===c;){var k=f[g].productcode,h=f[g].productstatus;"*"===e?h==b&&(c=!0):e==k&&h==b&&(c=!0);g++}d++}return c}function htmlDecode(a){var b="";a&&(b=$("<div />").html(a).text());return b}function htmlEncode(a){var b="";a&&(b=$("<div />").text(a).html());return b}function isNullOrUndefined(a){return void 0===a||null===a}
function logDebug(a,b){if("TRUE"===DEBUG_JS)try{void 0===b?console.log(a):console.log(a,b)}catch(c){doNothing()}}function processArray(a,b){if(null!==a)for(var c=1,d=0,e=!1;!e&&d<a.length;)void 0!==a[d]&&$.isFunction(b)&&(e=b(a[d],c,d)),c++,d++}function inArray(a,b){var c=!1;processArray(b,function(b){a===b&&(c=!0)});return c}function randomRange(a,b){return Math.floor(Math.random()*(b-a+1)+a)}
function searchArray(a,b,c){var d=null;if(null!==a)for(var e=0;e<a.length;){var f=a[e];if(void 0!==f){var g;try{g=f[b]}catch(k){}g==c&&(d=f)}e++}return d}function setDesktopRegions(a){g_arrDesktopRegions=a}function setPermissions(a){g_arrPermissions=a}function setProducts(a){g_arrProducts=a}
function str_replace(a,b,c){var d=!1;b+="";c+="";a+="";void 0===b&&(b="");void 0===c&&(c="");void 0===a&&(a="");0<=c.indexOf(b)&&(c=str_replace(c,b,"__OLD__"),d=!0);for(;0<=a.indexOf(b);)a=a.replace(b,c);d&&(a=str_replace(a,"__OLD__",b));return a}function stripChars(a,b){var c=a,d=b;void 0===d&&(d=" `~!@#$%^&*()-_=+[{]}|;:'<,>.?/\"");for(var e=0;e<d.length;e++)var f=d.substr(e,1),c=str_replace(c,f,"");return c}
function renderBreadCrumbs(a,b,c,d){var e="",f=1,g=d.length;processArray(d,function(a){0<e.length&&(e+="&nbsp; /&nbsp; ");var b="",b=$.isFunction(a.caption)?a.caption():a.caption;e=f==g?e+('<span class="gs-buttontext">'+htmlEncode(b)+"</span>"):e+('<a class="gs-buttontext" href="'+a.url+'">'+htmlEncode(b)+"</a>");f++});0<e.length&&(e='<hr style="width: 100%; color: #cccccc; height: 1px; background-color:#cccccc; margin:5px; padding: 0px;" />'+e+'<hr style="width: 100%; color: #cccccc; height: 1px; background-color:#cccccc; margin:5px; padding: 0px;" />');
a.element(b,c).html(e)}
function singleFileUpload(a,b,c,d,e,f){try{$("#ge-global-uploader").trigger("reset"),$("#ge-global-uploader").unbind("click"),$("#ge-global-files-field").unbind("click"),$("#ge-global-uploader").fileupload("destroy")}catch(g){doNothing()}$("#ge-global-uploader-container").html($("#ge-global-uploader-template-container").html());$("#ge-global-flags-field").val(b);$("#ge-global-securitytoken-field").val(SECURITY_TOKEN);$("#ge-global-clientversion-field").val(CLIENT_VERSION);$("#ge-global-callerid-field").val(CALLERID_PUBLIC);$("#ge-global-function-field").val(c);
$("#ge-global-functionid-field").val(d);try{$("#ge-global-uploader").fileupload({url:"ws/upload.php",dateType:"json",autoUpload:!0,add:function(a,b){b.submit().success(doNothing).error(doNothing).complete(doNothing)},send:function(){doNothing()},done:function(b,c){var d=a.ajaxRequestCreate("import_processuploads",[]);a.ajaxCall(URL_WEBSERVICE,d,function(a){$.isFunction(e)&&e(a)},a.ajaxError)},always:function(){doNothing()}}),$("#ge-global-files-field").trigger("click")}catch(k){$.isFunction(f)&&f()}}
function isValidTime(a){return null!==a.match(/^\s*([01]?\d|2[0-3]):?([0-5]\d)\s*$/)}function isValidDate(a){return a instanceof Date&&!isNaN(a.getTime())}
function initialiseStartupItems(a,b){var c=0,d=a.ajaxRequestCreate("core_startupitemfetchactive",[]);a.ajaxCall(URL_WEBSERVICE,d,function(d){processArray(d,function(b){var d=0<=b.flags.split(" ").indexOf("centre"),e=b.command,h=b.parameters;b=b.flags+" onstartup";b=$.trim(b);b=b.replace("  "," ");b=b.replace(" ","=true&");b+="=true";0<h.length?0<b.length&&(h+="&"+b):h=b;e=e.replace("%WELCOMEFORM%",WELCOMEFORM);e=e.replace("#","");a.after(c,function(){a.showForm(e,h,d)});c+=100});$.isFunction(b)&&
b()})};
