// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function dash_frmSecurity(p,q,r){function s(e){d=e;f++;g===f&&(h=new dash_wgtChart(a,b,{chart:d.logins_past4weeks}),k=new dash_wgtChart(a,b,{chart:d.login_failed_past2weeks}),l=new dash_wgtChart(a,b,{chart:d.registrations_all}),m=new dash_wgtChart(a,b,{chart:d.registrations_past4weeks}),h.render(".ge-cell-1-1"),k.render(".ge-cell-1-2"),l.render(".ge-cell-2-1"),m.render(".ge-cell-2-2"),a.registerServerEvent("dashboard",b),a.enableServerEventQueue("dasboard"),a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerbroadcaster",
[{name:"eventqueue",value:"dashboard"}]),doNothing,doNothing),a.ajaxCall(URL_WEBSERVICE,a.ajaxRequestCreate("esb_registerlistener",[{name:"eventqueue",value:"dashboard"}]),doNothing,doNothing),e=t.title,a.element(b,".ge-form-title").text(e))}function n(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(c,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(c,b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,ge-tab-end")}var a=p,c=this,b=q,t=r,g=0,f=0,d=[],h,k,l,m;this.Form_allowMultipleInstances=
function(){return!1};this.Form_canClose=function(){return!0};this.Form_onBroadcast=function(a,b){("orientation"===a||"viewport"===a)&&"change"===b&&c.Form_onResize()};this.Form_onClick=function(){a.setFormFocus(c,b)};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onFocus=function(){n();c.Form_onResize()};this.Form_onLoad=function(){a.unbindEvents(b,"gb-form");a.unbindEvents(b,"gb-form-close");a.bindEvent(c,b,".gb-form","Form","onClick");a.bindEvent(c,b,".gb-form-close","FormClose","onClick");
a.bindEvent(c,b,".gb-form","Form","onDblClick");g=1;f=0;var e=a.ajaxRequestCreate("security_fetchcharts",[]);a.ajaxCall(URL_WEBSERVICE,e,s,a.ajaxError,doNothing,!0);n()};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(c,d){var f=a.getFormCanvasHeight(b)-20;a.element(b,".ge-content-panel").height(f+"px");a.element(b,".ge-thecontent").height("1000px")};this.FormClose_onClick=function(){a.closeForm(b)};this.TabEnd_onFocus=function(){};this.TabStart_onFocus=function(){}};
