// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function dash_frmWelcome(d,f,s){function h(){a.showForm("entity.frmForm",{entity:"systemform",formentity:"DEVICE",formcode:"DEVICE",mode:"edit",title:"My Device",relationship:"children",relativeid:"MYDEVICE",relative:"DEVICE",id:"MYDEVICE"})}function k(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"DEVICE",formentitydescription:"Device",formcode:"DEVICE",mode:"renderer",title:"My Devices",fixedfilter:[{field:"user_id",value:"MYSELF"}]})}function l(){a.unbindEvents(c,
"ge-tab-start,ge-tab-end");a.bindEvent(b,c,".ge-tab-start","TabStart","onFocus");a.bindEvent(b,c,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(c,"ge-tab-start,ge-close-button,ge-tab-end")}var a=d,b=this,c=f;d=a.toBoolean(a.getProperty("batch"));f=a.toBoolean(a.getProperty("default"));a.toBoolean(a.getProperty("isemployer"));a.toBoolean(a.getProperty("isindividual"));a.toBoolean(a.getProperty("owner"));a.toBoolean(a.getProperty("public"));var t=a.toBoolean(a.getProperty("developer")),u=a.toBoolean(a.getProperty("sysadmin")),
v=!(d||f||t||u);a.toBoolean(a.getProperty("enablebranches"))&&(a.getProperty("branchid"),a.getProperty("branchname"));a.hasCapability("mobile");var e=[],m,n,p,q,g="TRUE"==TESTSCROLL&&!a.hasCapability("regionscroll")&&a.hasCapability("mobile");g&&(a.element(c,".ge-content-panel").removeClass("gb-scrollable-panel"),a.element(c,".ge-thecontent").removeClass("gb-scrollable-content"),a.element(c,".gb-form").removeClass("gb-resizable"),a.element(c).css({position:"relative",height:"auto"}));var r,w=[{location:"root",
title:"Home",layout:[["SettingsButton","AccountButton","PrintingButton"]]},{location:"settings",title:"Settings",layout:["SettingsMyDeviceButton SettingsMyDevicesButton SettingsMyPasswordButton SettingsUserPreferencesButton SettingsMyUserButton SettingsMyClientsButton BackButton".split(" ")]},{location:"account",title:"Settings",layout:[["SettingsMyAccountButton","SettingsMyClientButton","SettingsMyProductsButton","SettingsViewCartButton","BackButton"]]},{location:"printing",title:"Printing",layout:["PrintingPrintJobsButton PrintingPrintJobArchiveButton PrintingMyDeviceButton PrintingMyDevicesButton PrintingPrintersMineButton PrintingPrintersPublicButton PrintingPrinterQueuesMineButton PrintingPrinterQueuesPublicButton PrintingApplicationHealthButton BackButton".split(" ")]}],
x=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"BackButton",caption:"< Back",classes:"",style:"",permissions:[],action:"navigate",actionData:"root",tip:"Click here to go back.",type:"linkitem"},{id:"SettingsButton",caption:"Settings >",classes:"",style:"",permissions:[],action:"navigate",actionData:"settings",tip:"Click here for easy configuration options.",type:"linkitem"},{id:"AccountButton",caption:"Account >",classes:"",style:"",permissions:[],
action:"navigate",actionData:"account",tip:"Click here for account options.",type:"linkitem"},{id:"PrintingButton",caption:"Printing and Devices >",classes:"",style:"",permissions:["VW_PRINTER","VW_PRINTERSTATUS","VW_PRINTSTATUS"],action:"navigate",actionData:"printing",tip:"Click here for easy printing options.",type:"linkitem"},{id:"SettingsMyDeviceButton",caption:"Edit My Current Device",classes:"",style:"",permissions:["VW_DEVICE"],action:function(){b.SettingsMyDevice_onClick()},actionData:null,
tip:"Click here to edit my current device.",type:"linkitem"},{id:"SettingsMyDevicesButton",caption:"My Devices",classes:"",style:"",permissions:["VW_DEVICE"],action:function(){b.SettingsMyDevices_onClick()},actionData:null,tip:"Click here to list my devices.",type:"linkitem"},{id:"SettingsUserPreferencesButton",caption:"Change My User Preferences",classes:"",style:"",permissions:["VW_USERSETTING"],action:function(){b.SettingsUserPreferences_onClick()},actionData:null,tip:"Click here to change my user preferences.",
type:"linkitem"},{id:"SettingsMyPasswordButton",caption:"Change My Password",classes:"",style:"",permissions:["CHPWD_USER"],action:function(){b.SettingsMyPassword_onClick()},actionData:null,tip:"Click here to change my password.",type:"linkitem"},{id:"SettingsMyUserButton",caption:"Edit My User",classes:"",style:"",permissions:["VW_USER"],action:function(){b.SettingsMyUser_onClick()},actionData:null,tip:"Click here to edit my user.",type:"linkitem"},{id:"SettingsMyClientButton",caption:"Edit Client Settings",
classes:"",style:"",permissions:["VW_CLIENT"],action:function(){b.SettingsMyClient_onClick()},actionData:null,tip:"Click here to edit client settings.",type:"linkitem"},{id:"SettingsMyAccountButton",caption:"Edit Account",classes:"",style:"",permissions:["VW_ACCOUNT"],action:function(){b.SettingsMyAccount_onClick()},actionData:null,tip:"Click here to edit account.",type:"linkitem"},{id:"SettingsMyProductsButton",caption:"My Products",classes:"",style:"",permissions:["xVW_CLIENTPRODUCT"],action:function(){b.SettingsMyProducts_onClick()},
actionData:null,tip:"Click here to list my products.",type:"linkitem"},{id:"SettingsViewCartButton",caption:"View Cart",classes:"",style:"",permissions:["VW_CART"],action:function(){b.SettingsViewCart_onClick()},actionData:null,tip:"Click here to view cart.",type:"linkitem"},{id:"SettingsMyClientsButton",caption:"View My Clients",classes:"",style:"",permissions:["VW_MYCLIENT"],action:function(){b.SettingsMyClients_onClick()},actionData:null,tip:"Click here to view my clients.",type:"linkitem"},{id:"PrintingPrintJobsButton",
caption:"Print Jobs",classes:"",style:"",permissions:["VW_PRINTJOB"],action:function(){b.PrintingPrintJobs_onClick()},actionData:null,tip:"Click here to list print jobs.",type:"linkitem"},{id:"PrintingPrintJobArchiveButton",caption:"Archived Print Jobs",classes:"",style:"",permissions:["VW_LOG_PRINTJOB"],action:function(){b.PrintingPrintJobArchive_onClick()},actionData:null,tip:"Click here to list archived print jobs.",type:"linkitem"},{id:"PrintingMyDeviceButton",caption:"Edit My Current Device",
classes:"",style:"",permissions:["VW_DEVICE"],action:function(){b.PrintingMyDevice_onClick()},actionData:null,tip:"Click here to edit my current device.",type:"linkitem"},{id:"PrintingMyDevicesButton",caption:"My Devices",classes:"",style:"",permissions:["VW_DEVICE"],action:function(){b.PrintingMyDevices_onClick()},actionData:null,tip:"Click here to list my devices.",type:"linkitem"},{id:"PrintingPrintersMineButton",caption:"My Printers",classes:"",style:"",permissions:["VW_PRINTER"],action:function(){b.PrintingPrintersMine_onClick()},
actionData:null,tip:"Click here to list my printers.",type:"linkitem"},{id:"PrintingPrintersPublicButton",caption:"Public Printers",classes:"",style:"",permissions:["VW_PRINTER"],action:function(){b.PrintingPrintersPublic_onClick()},actionData:null,tip:"Click here to list public printers.",type:"linkitem"},{id:"PrintingPrinterQueuesMineButton",caption:"My Private Printer Queues",classes:"",style:"",permissions:["VW_PRINTQUEUE"],action:function(){b.PrintingPrinterQueuesMine_onClick()},actionData:null,
tip:"Click here to list my private printer queues.",type:"linkitem"},{id:"PrintingPrinterQueuesPublicButton",caption:"Public Printer Queues",classes:"",style:"",permissions:["VW_PRINTQUEUE"],action:function(){b.PrintingPrinterQueuesPublic_onClick()},actionData:null,tip:"Click here to list public printer queues.",type:"linkitem"},{id:"PrintingApplicationHealthButton",caption:"Check Application Health",classes:"",style:"",permissions:["xVW_PRINTER"],action:function(){b.PrintingApplicationHealth_onClick()},
actionData:null,tip:"Click here to check application health.",type:"linkitem"}];this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!0};this.Form_onBroadcast=function(a,c){("orientation"===a||"viewport"===a)&&"change"===c&&b.Form_onResize()};this.Form_onClick=function(){a.setFormFocus(b,c)};this.Form_onDblClick=function(){a.formToFront(c)};this.Form_onFocus=function(){l();b.Form_onResize()};this.Form_onLoad=function(){if(v){r=new jDock(a,{map:w,tiles:x,alwayshidemorebutton:!0,
mode:"verticallinks"});r.render(c,".ge-button-panel");g?a.element(c,".gb-form").addClass("gs-content-autoheight"):a.resizeDockedForm(c);m=new dash_wgtChart(a,c,{chart:e.chart1});n=new dash_wgtChart(a,c,{chart:e.chart2});p=new dash_wgtChart(a,c,{chart:e.chart3});q=new dash_wgtChart(a,c,{chart:e.chart4});m.render(".ge-cell-1-1");n.render(".ge-cell-1-2");p.render(".ge-cell-2-1");q.render(".ge-cell-2-2");var y=s.title;a.element(c,".ge-form-title").text(y);a.unbindEvents(c,"gb-form");a.unbindEvents(c,
"gb-form-close");a.bindEvent(b,c,".gb-form","Form","onClick");a.bindEvent(b,c,".gb-form-close","FormClose","onClick");a.bindEvent(b,c,".gb-form","Form","onDblClick");l()}else a.closeForm(c)};this.Form_onPermissionCheck=function(){return!0};this.Form_onResize=function(b,e){var d=a.getFormCanvasHeight(c)-20;g?doNothing():(a.element(c,".ge-content-panel").height(d+"px"),a.element(c,".ge-thecontent").height("100%"))};this.FormClose_onClick=function(){a.closeForm(c)};this.SettingsMyDevice_onClick=function(){h()};
this.SettingsMyDevices_onClick=function(){k()};this.SettingsDispatchPreferences_onClick=function(){a.showForm("entity.frmForm",{entity:"systemform",formentity:"DISPATCHSETTING",formcode:"DISPATCHSETTING",mode:"edit",title:"Client Despatch Preferences",relationship:"children",relativeid:"MYCLIENT",relative:"DISPATCHSETTING",id:"MYCLIENT"})};this.SettingsUserPreferences_onClick=function(){a.showForm("entity.frmForm",{entity:"systemform",formentity:"USERSETTING",formcode:"USERSETTING",mode:"edit",title:"My User Preferences",
relationship:"children",relativeid:"MYSELF",relative:"USERSETTING",id:"MYSELF"})};this.SettingsMyPassword_onClick=function(){a.showForm("core.frmChangePassword",{mode:"editself"})};this.SettingsMyUser_onClick=function(){a.showForm("entity.frmForm",{entity:"systemform",formentity:"USER",formcode:"USER",mode:"edit",title:"My User",relationship:"children",relativeid:"MYSELF",relative:"USER",id:"MYSELF"})};this.SettingsMyClient_onClick=function(){a.showForm("entity.frmForm",{entity:"systemform",formentity:"CLIENTSETTING",
formcode:"CLIENTSETTING",mode:"edit",title:"Client Settings",relationship:"children",relativeid:"MYCLIENT",relative:"CLIENTSETTING",id:"MYCLIENT"})};this.SettingsMyAccount_onClick=function(){a.showForm("entity.frmForm",{entity:"systemform",formentity:"ACCOUNT",formcode:"ACCOUNT",mode:"edit",title:"Account",relationship:"children",relativeid:"MYACCOUNT",relative:"ACCOUNT",id:"MYACCOUNT"})};this.SettingsMyProducts_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"CLIENTPRODUCT",
formentitydescription:"My Products",formcode:"CLIENTPRODUCT",mode:"renderer",title:"My Products"})};this.SettingsViewCart_onClick=function(){a.showForm("core.frmPayment",{title:"Purchase Subscription",applicantname:a.getProperty("clientname"),mode:"selectproduct",producttypeheading:"Subscriptions",producttype:"subscription",filter:"PRODUCT",multi:!1})};this.SettingsMyClients_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"MYCLIENT",formentitydescription:"My Client",
formcode:"MYCLIENT",mode:"renderer",title:"My Clients"})};this.PrintingPrintJobs_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"PRINTJOB",formentitydescription:"Print Job",formcode:"PRINTJOB",mode:"renderer",title:"Print Jobs"})};this.PrintingPrintJobArchive_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"LOG_PRINTJOB",formentitydescription:"Print Job",formcode:"LOG_PRINTJOB",mode:"renderer",title:"Print Jobs (Archived)"})};
this.PrintingMyDevice_onClick=function(){h()};this.PrintingMyDevices_onClick=function(){k()};this.PrintingPrintersMine_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"PRINTER",formentitydescription:"Printer",formcode:"PRINTER",mode:"renderer",title:"My Private Printers",fixedfilter:[{field:"user_id",value:"MYSELF"},{field:"is_public",value:"N"}]})};this.PrintingPrintersPublic_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",
formentity:"PRINTER",formentitydescription:"Printer",formcode:"PRINTER",mode:"renderer",title:"Public Printers",fixedfilter:[{field:"is_public",value:"Y"}]})};this.PrintingPrinterQueuesMine_onClick=function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"PRINTQUEUE",formentitydescription:"Printer Queue",formcode:"PRINTQUEUE",mode:"renderer",title:"My Private Printer Queues",fixedfilter:[{field:"user_id",value:"MYSELF"},{field:"is_public",value:"N"}]})};this.PrintingPrinterQueuesPublic_onClick=
function(){a.showForm("entity.frmLister",{type:"form",entity:"systemform",formentity:"PRINTQUEUE",formentitydescription:"Printer Queue",formcode:"PRINTQUEUE",mode:"renderer",title:"My Public Printer Queues",fixedfilter:[{field:"user_id",value:"MYSELF"},{field:"is_public",value:"Y"}]})};this.PrintingApplicationHealth_onClick=function(){a.showForm("core.frmHealth")};this.NavOption_onClick=function(b){b=$(b).attr("navchild");a.element(c,".ge-option").hide();a.element(c,"."+b).show()};this.NavOption_onHover=
function(b){a.element(c,".ge-navoption").css("font-weight","normal");$(b).css("font-weight","bolder")};this.Button_onHover=function(b){a.element(c,".ge-button").css("font-weight","normal");$(b).css("font-weight","bolder");a.element(c,".ge-button").css("background-color","#f9f9f9");$(b).css("background-color","#edeae5")};this.TabEnd_onFocus=function(){};this.TabStart_onFocus=function(){}};
