// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function msg_frmMyMessage(C,D,E){function F(){l(!0)}function s(){var c=t.folderid,d=h=k="";n="";processArray(u,function(b){b.id==c&&(k=b.description,h=b.id);0===d.length&&(d=b.id);0===k.length&&(k=b.description);a.toBoolean(b.is_inbox)&&(n=b.id);a.toBoolean(b.is_system);a.toBoolean(b.is_archive)});0===h.length&&(h=n,0===h.length&&(h=d));a.element(b,".ge-form-title").html(k);a.unbindEvents(b,"ge-send-button,ge-close-button");a.bindEvent(e,b,".ge-send-button","ButtonSend","onClick")}function l(a){p=
a;v?f.disableButtons("SendButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty"):p?(f.disableButtons("SendButton","gs-darkblue-background-colour"),f.enableButtons("SendButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty")):(f.disableButtons("SendButton","gs-red-background-colour gs-glow-dirty"),f.enableButtons("SendButton","gs-darkblue-background-colour gs-glow-focusborder"));doNothing()}function G(){var c=H();0<c.length?a.dialogAlertScroll(c,
function(){}):(c=d.sender_id,d={subject:a.element(b,".ge-subject-field").val(),recipient:a.element(b,".ge-recipient-field").val(),recipient_id:c,message:a.element(b,".ge-message-field").val()},l(!0),I())}function w(c){c?a.element(b,".ge-archive-button").text("Unarchive"):a.element(b,".ge-archive-button").text("Archive")}function x(c){c?a.element(b,".ge-flag-button").text("Unflag"):a.element(b,".ge-flag-button").text("Flag")}function H(){var c="";0===$.trim(a.element(b,".ge-recipient-field").val()).length&&
(c+="<li>Recipient is required.</li>");0===$.trim(a.element(b,".ge-subject-field").val()).length&&(c+="<li>Subject is required.</li>");0===$.trim(a.element(b,".ge-message-field").val()).length&&(c+="<li>Message is required.</li>");0<c.length&&(c="<ul>"+c+"</ul>");return c}function y(){f=new jDock(a,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:q,tiles:J});f.render(b,".ge-button-panel")}function z(){renderBreadCrumbs(a,b,".ge-breadcrumbs",[{caption:"My Home",url:"#bbp.frmHome"},{caption:"My Messages",
url:"#msg.frmMyMessages"},{caption:k,url:""}]);s();a.element(b,".ge-label-subject").html(d.subject);a.element(b,".ge-label-recipient").html(d.recipient);a.element(b,".ge-label-sender").html(d.sender);a.element(b,".ge-label-sentdatetime").html(d.sentdatetime);a.element(b,".ge-label-message").html(d.message);if(a.toBoolean(d.isunread)){var c=a.ajaxRequestCreate("msg_messageupdatestatus",[{name:"params",value:{id:g,status:"N"}}]);a.ajaxCall(URL_WEBSERVICE,c,doNothing,a.ajaxError,doNothing,!0)}x(a.toBoolean(d.isflagged));
w(a.toBoolean(d.isarchived));K();a.resizeDockedForm(b)}function L(b){w(a.toBoolean(d.isarchived))}function M(b){x(a.toBoolean(d.isflagged))}function N(a){d=a[0];m++;r==m&&z()}function O(b){u=b.result;s();b=a.ajaxRequestCreate("msg_messagefetch",[{name:"id",value:g}]);a.ajaxCall(URL_WEBSERVICE,b,N,a.ajaxError,doNothing,!0)}function P(c){g=c[0].id;a.broadcast(b,"msg","Your Message has been Sent");l(!1);a.dialogAlertScroll("Message Sent",doNothing);a.closeForm(b);a.showForm("msg.frmMyMessages")}function I(){var b=
a.ajaxRequestCreate("msg_messagesend",[{name:"message",value:d}]);a.ajaxCall(URL_WEBSERVICE,b,P,a.ajaxError,F)}function A(b){b?(r=1,m=0,b=a.ajaxRequestCreate("msg_messagefoldersfetch",[]),a.ajaxCall(URL_WEBSERVICE,b,O,a.ajaxError,doNothing,!0)):(r=1,m=0,z())}function K(){a.unbindEvents(b,B);a.onDirty(b,B,function(){l(!0)})}var a=C,e=this,b=D,t=E,v=!1,p=!1,r=0,m=0,B="ge-recipient-field,ge-subject-field,ge-message-field",k="My Message",u=[],h="",n="",g=t.id,d=null,f,q=[{location:"root",title:"Home",
layout:[]}],Q=["CloseButton","ReplyButton","FlagButton","ArchiveButton"],R=["CloseButton","SendButton"],J=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour",permissions:[],action:function(){e.FormClose_onClick()},actionData:null,tip:"Click here to close the form builder.",type:"toolbarbutton"},{id:"ReplyButton",caption:"Reply",classes:"",permissions:[],action:function(){e.ButtonReply_onClick()},
actionData:null,tip:"Click here to reply.",type:"toolbarbutton"},{id:"FlagButton",caption:"Flag",classes:"ge-flag-button",permissions:[],action:function(){e.ButtonFlag_onClick()},actionData:null,tip:"Click here to flag.",type:"toolbarbutton"},{id:"ArchiveButton",caption:"Archive",classes:"ge-archive-button",permissions:[],action:function(){e.ButtonArchive_onClick()},actionData:null,tip:"Click here to Archive.",type:"toolbarbutton"},{id:"SendButton",caption:"Send",classes:"gb-cell-disabled",permissions:[],
action:function(){e.ButtonSend_onClick()},actionData:null,tip:"Click here to reply.",type:"toolbarbutton"}];this.Form_allowMultipleInstances=function(){return!0};this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return"C"};this.Form_isDirty=function(){return p};this.Form_onClick=function(){a.setFormFocus(e,b)};this.Form_onFocus=function(c){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(e,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(e,b,".ge-tab-end","TabEnd",
"onFocus");a.setTabOrder(b,"gb-tab-star,ge-tab-end");c=c.id;c!==g&&(g=c,A(!0))};this.Form_onLoad=function(){v=!1;q[0].layout=[Q];y();a.unbindEvents(b,"gb-form,ge-row-thread");a.bindEvent(e,b,".gb-form","Form","onClick");a.bindEvent(e,b,".gb-form-close","FormClose","onClick");a.bindEvent(e,b,".gb-formtitle-inner-panel","FormTitle","onClick");A(!0)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){a.formToFront(b)};this.Form_onResize=function(c,d){var e=a.getFormCanvasHeight(b)-
80;a.element(b,".ge-content-panel").height(e+"px");a.element(b,".ge-thecontent").height("100%")};this.FormClose_onClick=function(){a.closeForm(b)};this.ButtonBack_onClick=function(){a.closeForm(b)};this.ButtonReply_onClick=function(){var c="",c=0>d.subject.indexOf("Re")?"Re: "+d.subject:d.subject;a.element(b,".ge-label-subject").html(htmlEncode(c));a.element(b,".ge-subject-field").val(c);a.element(b,".ge-recipient-field").val(d.sender);a.element(b,".ge-form-title").html("Reply");q[0].layout=[R];y();
a.element(b,".ge-viewform-panel").hide();a.element(b,".ge-replyform-panel").show()};this.ButtonSend_onClick=function(){G()};this.ButtonArchive_onClick=function(){a.toBoolean(d.isarchived)?d.isarchived="N":d.isarchived="Y";var b=a.ajaxRequestCreate("msg_messagearchiveset",[{name:"id",value:g},{name:"isarchived",value:d.isarchived}]);a.ajaxCall(URL_WEBSERVICE,b,L,a.ajaxError,doNothing,!0)};this.ButtonFlag_onClick=function(){a.toBoolean(d.isflagged)?d.isflagged="N":d.isflagged="Y";var b=a.ajaxRequestCreate("msg_messageflagset",
[{name:"id",value:g},{name:"isflagged",value:d.isflagged}]);a.ajaxCall(URL_WEBSERVICE,b,M,a.ajaxError,doNothing,!0)};this.ButtonClose_onClick=function(){e.FormClose_onClick()};this.TabEnd_onFocus=function(){};this.TabStart_onFocus=function(){}};
