// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function msg_frmMyComposeMessage(m,n,y){function p(){e(!0)}function q(){var c=r();0<c.length?a.dialogAlertScroll(c,function(){}):(h={subject:a.element(b,".ge-subject-field").val(),recipient:a.element(b,".ge-recipient-field").val(),recipient_id:a.element(b,".ge-recipientid-field").val(),message:a.element(b,".ge-message-field").val()},e(!0),s())}function e(a){f=a;l?g.disableButtons("SendButton","gs-red-background-colour"):f?g.enableButtons("SendButton","gs-red-background-colour"):g.disableButtons("SendButton",
"gs-red-background-colour")}function t(){a.element(b,".ge-recipient-field").autocomplete({source:function(b,d){var e=a.ajaxRequestCreate("msg_messagerecipientsfetch",[{name:"recipient",value:b.term}]);a.ajaxCall(URL_WEBSERVICE,e,function(a){var b=[],c=0;processArray(a,function(a){b[c]={value:a.recipient,id:a.id};c++});d(b)},function(){d([])})},select:function(c,d){a.element(b,".ge-recipientid-field").val(d.item.id);a.element(b,".ge-recipient-field").focus()}});a.element(b,".ge-recipient-field").focus()}
function r(){var c="";0===$.trim(a.element(b,".ge-recipient-field").val()).length&&(c+="<li>Recipient is required.</li>");0===$.trim(a.element(b,".ge-subject-field").val()).length&&(c+="<li>Subject is required.</li>");0===$.trim(a.element(b,".ge-message-field").val()).length&&(c+="<li>Message is required.</li>");0<c.length&&(c="<ul>"+c+"</ul>");return c}function u(c){a.broadcast(b,"msg","Your Message has been Sent");e(!1);a.dialogAlert("Message Sent",doNothing);a.closeForm(b);a.showForm("msg.frmMyMessages")}
function s(){var b=a.ajaxRequestCreate("msg_messagesend",[{name:"message",value:h}]);a.ajaxCall(URL_WEBSERVICE,b,u,a.ajaxError,p)}function v(){a.unbindEvents(b,k);a.onDirty(b,k,function(){e(!0)})}var a=m,d=this,b=n,l=!1,f=!1,k="ge-recipient-field,ge-subject-field,ge-message-field",h=null,g,w=[{location:"root",title:"Home",layout:[["CloseButton","SendButton","BackButton"]]}],x=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",
classes:"gs-green-background-colour",permissions:[],action:function(){d.FormClose_onClick()},actionData:null,tip:"Click here to close the form builder.",type:"toolbarbutton"},{id:"SendButton",caption:"Send",classes:"",permissions:[],action:function(){d.SendButton_onClick()},actionData:null,tip:"Click here to send.",type:"toolbarbutton"}];this.Form_allowMultipleInstances=function(){return!0};this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return"C"};this.Form_isDirty=
function(){return f};this.Form_onClick=function(){a.setFormFocus(d,b)};this.Form_onDblClick=function(){a.formToFront(b)};this.Form_onFocus=function(){a.unbindEvents(b,"ge-tab-start,ge-tab-end");a.bindEvent(d,b,".ge-tab-start","TabStart","onFocus");a.bindEvent(d,b,".ge-tab-end","TabEnd","onFocus");a.setTabOrder(b,"ge-tab-start,"+k+",ge-tab-end")};this.Form_onLoad=function(){l=!1;var c=a.getViewPort().width,f=a.getViewPort().height;a.resizeAndRepositionForm(b,0.1*f,0.1*c,0.8*f,0.8*c);a.unbindEvents(b,
"gb-form,ge-row-thread,ge-close-button");a.bindEvent(d,b,".gb-form","Form","onClick");a.bindEvent(d,b,".gb-form","Form","onDblClick");a.bindEvent(d,b,".gb-form-close","FormClose","onClick");a.bindEvent(d,b,".gb-formtitle-inner-panel","FormTitle","onClick");a.bindEvent(d,b,".ge-close-button","ButtonClose","onClick");renderBreadCrumbs(a,b,".ge-breadcrumbs",[{caption:"My Home",url:"#bbp.frmHome"},{caption:"My Messages",url:"#!msg.frmMyMessages"},{caption:"Compose Message",url:""}]);g=new jDock(a,{alwaysvisiblebuttoncount:2,
enablemobiledropdown:!0,map:w,tiles:x});g.render(b,".ge-button-panel");h={id:"",sender_id:"",sender:"",recipient_id:"",recipient:"",subject:"",message:""};v();t();e(!1)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){a.formToFront(b)};this.Form_onResize=function(c,d){var e=a.getFormCanvasHeight(b)-80;a.element(b,".ge-content-panel").height(e+"px");a.element(b,".ge-thecontent").height("100%")};this.FormClose_onClick=function(){a.closeForm(b)};this.SendButton_onClick=
function(){q()};this.BackButton_onClick=function(){a.closeForm(b)};this.ButtonClose_onClick=function(){d.FormClose_onClick()};this.TabEnd_onFocus=function(){a.element(b,".ge-inbox-link").focus()};this.TabStart_onFocus=function(){a.element(b,".gb-send-button").focus()}};
