// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function msg_frmMyMessages(C,D,E){var s,t,u;function F(){b.element(a,".ge-appname-field").html(APP_NAME);var d=v.folderid,e="";m=l=f=k="";processArray(n,function(a){a.id==d&&(k=a.description,f=a.id);0===e.length&&(e=a.id);0===k.length&&(k=a.description);b.toBoolean(a.is_inbox)&&(l=a.id);b.toBoolean(a.is_system)&&(m=a.id);b.toBoolean(a.is_archive)&&(w=a.id)});0===f.length&&(f=l,0===f.length&&(f=e));var g="",g=g+'<a class="ge-button gb-button btn btn-success ge-close-button">Close</a>';processArray(n,
function(a){var d=getGUID(),e="";a.id==f&&(e=" btn-primary");g=b.toBoolean(a.is_inbox)?0<e.length?g+('<a data-folderid="'+htmlEncode(a.id)+'" class="ge-button gb-button btn ge-tablink '+e+'">'+htmlEncode(a.description)+'&nbsp;<span class="ge-unread-badge badge gb-hidden"></span></a>'):g+('<a data-folderid="'+htmlEncode(a.id)+'" class="ge-button gb-button btn btn-default ge-tablink ge-tablink-'+d+e+'">'+htmlEncode(a.description)+'&nbsp;<span class="ge-unread-badge badge gb-hidden"></span></a>'):0<
e.length?g+('<a data-folderid="'+htmlEncode(a.id)+'" class="ge-button gb-button btn ge-tablink'+e+'">'+htmlEncode(a.description)+"</a>"):g+('<a data-folderid="'+htmlEncode(a.id)+'" class="ge-button gb-button  btn btn-default ge-tablink ge-tablink-'+d+e+'">'+htmlEncode(a.description)+"</a>")});g+='<a class="ge-button gb-button btn btn-default ge-compose-button">Compose</a>';b.element(a,".ge-messagefolder-buttongroup").html(g);b.element(a,".ge-form-title").html(k);x();y();b.unbindEvents(a,"ge-compose-button,ge-showmore-button,ge-filtermsglist-option,ge-tablink,ge-search-input,ge-close-button");
b.unbindEvents(a,"ge-search-input,ge-searchclear-button");b.bindEvent(c,a,".ge-compose-button","btnComposeButton","onClick");b.bindEvent(c,a,".ge-showmore-button","btnShowMore","onClick");b.bindEvent(c,a,".ge-filtermsglist-option","dropdownFilterMsgListOption","onClick");b.bindEvent(c,a,".ge-tablink","btnTabLink","onClick");b.bindEvent(c,a,".ge-close-button","ButtonClose","onClick");b.bindEvent(c,a,".ge-searchclear-button","btnSearchClear","onClick");b.bindEvent(c,a,".ge-search-input","SearchField",
"onEnterKey")}function z(a){b.showForm("msg.frmMyMessage","id="+encodeURIComponent(a)+"&folderid="+encodeURIComponent(f))}function y(){renderBreadCrumbs(b,a,".ge-breadcrumbs",[{caption:"My Messages",url:"#!msg.frmMyMessages"},{caption:k,url:""}])}function G(a){n=a.result;F();h++;A==h&&B()}function x(){var a="";s=a=f==l?"msg_messageinboxlist":f==m?"msg_messagesystemlist":f==w?"msg_messagearchivelist":"msg_messagesentlist";t=[{name:"order",value:""},{name:"filter",value:p},{name:"offset",value:0},{name:"limit",
value:0}];u=[{id:"fromclient",field:"fromclient",name:"Sender/Recipient",sortable:"Y"},{id:"subject",field:"subject",name:"Subject",sortable:"Y"},{id:"message",field:"message",name:"Message",sortable:"N"},{id:"sentdatetime",field:"sentdatetime",name:"Date/Time",sortable:"Y"},{id:"is_flagged",field:"is_flagged",name:"Flagged",sortable:"Y"}]}function B(){q=new jDatatableRenderer(b,{cbOnSelection:c.Grid_onDblClick,cbOnSelectionChange:c.Grid_onSelectionChange,cbRowFormatter:H,columns:u,filterType:"normal",
parameters:t,extraParameters:[],multiSelect:!1,webServiceFunction:s});q.render(a,".ge-entity-grid")}function H(a,b,c){"Y"===b.isunread&&$(a).addClass("gb-DT-unread");f===l||f===m?$(a).find("td:first-child").html(b.fromuser):$(a).find("td:first-child").html(b.touser)}function r(){var d=$.trim(b.element(a,".ge-search-input").val()),e=b.element(a,".ge-filtermsg-value").val(),c=[{field:"subject",value:d}];if("flagged"===e||"unflagged"===e){var f="N";"flagged"===e&&(f="Y");c.push({field:"is_flagged",value:f})}else""!==
e&&c.push({field:"is_unread",value:e});q.search(d,[{name:"filter",value:c}])}var b=C,c=this,a=D,v=E,A=0,h=0,k="My Messages",p=[],n=[],f="",l="",m="",w="",q;this.Form_allowMultipleInstances=function(){return!1};this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return"C"};this.Form_isDirty=function(){return!1};this.Form_onClick=function(){b.setFormFocus(c,a)};this.Form_onDblClick=function(){b.formToFront(a)};this.Form_onFocus=function(d){b.unbindEvents(a,"ge-tab-start,ge-tab-end");
b.bindEvent(c,a,".ge-tab-start","TabStart","onFocus");b.bindEvent(c,a,".ge-tab-end","TabEnd","onFocus");b.setTabOrder(a,"gb-tab-star,ge-tab-end");void 0!==d.folderid&&(0<f.length&&f!==d.folderid)&&(v=d,f="");p=[]};this.Form_onLoad=function(){b.unbindEvents(a,"gb-form,ge-row-thread");b.bindEvent(c,a,".gb-form-close","FormClose","onClick");b.bindEvent(c,a,".gb-form","Form","onClick");b.bindEvent(c,a,".gb-form","Form","onDblClick");b.bindEvent(c,a,".gb-formtitle-inner-panel","FormTitle","onClick");A=
1;h=0;var d=b.ajaxRequestCreate("msg_messagefoldersfetch",[]);b.ajaxCall(URL_WEBSERVICE,d,G,b.ajaxError,doNothing,!0)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(a)};this.Form_onResize=function(a,b){};this.btnComposeButton_onClick=function(){b.showForm("msg.frmMyComposeMessage")};this.btnSearchClear_onClick=function(){b.element(a,".ge-search-input").val("");b.element(a,".ge-search-input").focus();r();h=0};this.SearchField_onEnterKey=function(){r();
h=0};this.dropdownFilterMsgListOption_onClick=function(d){d=b.element(d);var e=d.attr("data-optionvalue");b.element(a,".ge-filtermsg-value").val(e);r();h=0;d.parents(".ge-filtermsglist-dropdown").find(".dropdown-filtermsglist-buttonlabel").text(d.attr("data-label"))};this.btnTabLink_onClick=function(d){var e=htmlDecode(b.element(d).attr("data-folderid")),c=htmlDecode(b.element(d).html()),h=!1;f=e;k=c;h=!0;b.element(a,".ge-search-input").val("");p=[];b.element(a,".ge-tablink.btn-primary").removeClass("btn-primary").addClass("btn-default");
b.element(d).addClass("btn-primary").removeClass("btn-default");h&&(b.element(a,".ge-form-title").html(k),x(),B(),y())};this.MessageRow_onClickxxxx=function(a){var c=b.element(a).attr("data-msgid");b.element(a).removeClass("wr-message-unread").addClass("wr-message-read");z(c)};this.ButtonClose_onClick=function(){c.FormClose_onClick()};this.Grid_onDblClick=function(a){doNothing()};this.Grid_onSelectionChange=function(a){0<a.length&&z(a[0].id)};this.FormClose_onClick=function(){b.closeForm(a)};this.TabEnd_onFocus=
function(){};this.TabStart_onFocus=function(){}};
