// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function widgetformbuilder_wgtFormBuilder(U,V,W){function X(a,b){var c=[];processArray(a,function(a){a.sectioncodetemp==b&&(c=a.fields)});return c}function Y(){var a=0;processArray(f,function(b){processArray(b.fields,function(b){a++})});return a}function Z(a,b,c){var d=-1,e=-1;processArray(a,function(a){d++;a.sectioncodetemp==b&&(e=d)});0<=e&&(a[e].fields=c)}function A(a,b){processArray(f,function(c){c.p_name==a&&(c.p_value=b,c.p_valuedescription="")})}function B(a){var b="",c={},d=new X2JS({useDoubleQuotes:!0,
keepCData:!0});0<a.length&&(c={"form-template":{fields:{field:[]}}},processArray(a,function(a){c["form-template"].fields.field.push(aa(a))}),b=d.json2xml_str(c));return b}function aa(a){var b={};if("form"===e.internalmode)b._class=g(a.sectionclasses),b._label=g(a.sectiontitle),b._quantity=g(a.sectionquantity),b._name=g(a.sectioncode),b._colour=g(a.sectioncolour),b._sectionref=g(a.sectionref),b._sectiontype=g(a.sectiontype),"DATA"===a.sectiontype?b._type="datasection":"DATAHEADER"===a.sectiontype?
b._type="dataheadersection":"FORMHEADER"===a.sectiontype?b._type="formheadersection":"INTERNALUSEFORMHEADER"===a.sectiontype?b._type="internaluseformheadersection":"INTERNALUSEONLY"===a.sectiontype&&(b._type="internaluseonlysection"),b._tempname=g(a.sectioncodetemp);else{b._class=g(a.p_classes);b._colour=g(a.p_colour);b._fieldsource=g(a.p_source);b._fieldstyle=g(a.p_style);b._infovalue=g(a.p_info);b._label=g(a.p_label);b._length=g(a.p_length);b._lines=g(a.p_lines);b._name=g(a.p_name);b._quantity=
g(a.p_quantity);b._readonly=g(a.p_readonly);b._required=g(a.p_required);b._searchable=g(a.p_searchable);b._sortable=g(a.p_sortable);b._subtype=g(a.p_datatype);b._type=g(a.p_datatype);b._value=g(a.p_value);b._valuedescription=g(a.p_valuedescription);if("ENTITY"===b._name&&"Data Group Name"===b._label){var c=b._class,c=str_replace(c,"ge-dataformgroup-field",""),c=str_replace(c,"  "," ");b._class=c+" ge-dataformgroup-field"}var d;b.option=[];c={};for(d in a.p_selection){if("d_relatedlinks"===b._type){var c=
a.p_selection[d],f={};c.p_label&&(f.__text=g(c.p_label));c.p_permissions&&(f._permissions=g(c.p_permissions));c.p_command&&(f._command=g(c.p_command));c.p_parameters&&(f._parameters=g(c.p_parameters))}else c=a.p_selection[d],f={},c.p_code&&(f._value=g(c.p_code)),c.p_value&&(f.__text=g(c.p_value));c=f;b.option.push(c)}}void 0==b._fieldsource&&(b._fieldsource="");return b}function g(a){var b=a;"string"==typeof a&&(b=str_replace(b,">","__GT__"),b=str_replace(b,"<","__LT__"),b=str_replace(b,'"',"__QUOT__"),
b=str_replace(b,"'","__APOS__"),b=str_replace(b,"&","__AMP__"));void 0==b&&(b="");return b}function ba(a){var b=[];if(0<a.length){a=(new X2JS).xml_str2json(a)["form-template"].fields.field;var c=[];$.isArray(a)?c=a:c.push(a);"form"===e.internalmode?processArray(c,function(a){var c=X(t,a._tempname);b.push(L(a));Z(b,a._tempname,c)}):processArray(c,function(a){b.push(L(a))});t=b;u()}return b}function L(a){var b={},b="form"===e.internalmode?{sectionclasses:"",sectioncode:"",sectioncodetemp:"",sectioncolour:"",
sectionquantity:"",sectionref:"",sectiontitle:"",sectiontype:"",fields:[]}:{p_classes:"",p_colour:"",p_datatype:"",p_info:"",p_label:"",p_length:"",p_lines:"",p_name:"",p_quantity:"",p_readonly:"",p_required:"",p_searchable:"",p_selection:"",p_sortable:"",p_source:"",p_style:"",p_value:"",p_valuedescription:""};if("form"===e.internalmode)a._class&&(b.sectionclasses=h(a._class)),a._label&&(b.sectiontitle=h(a._label)),a._name&&(b.sectioncode=h(a._name)),a._quantity&&(b.sectionquantity=h(a._quantity)),
a._colour&&(b.sectioncolour=h(a._colour)),a._sectionref&&(b.sectionref=h(a._sectionref)),a._tempname&&(b.sectioncodetemp=h(a._tempname)),a._type&&("datasection"===a._type?b.sectiontype="DATA":"dataheadersection"===a._type?b.sectiontype="DATAHEADER":"formheadersection"===a._type?b.sectiontype="FORMHEADER":"internaluseformheadersection"===a._type?b.sectiontype="INTERNALUSEFORMHEADER":"internaluseonlysection"===a._type&&(b.sectiontype="INTERNALUSEONLY"));else if(a._class&&(b.p_classes=h(a._class)),a._colour&&
(b.p_colour=h(a._colour)),a._type&&(b.p_datatype=h(a._type)),a._infovalue&&(b.p_info=h(a._infovalue)),a._label&&(b.p_label=h(a._label)),a._length&&(b.p_length=h(a._length)),a._lines&&(b.p_lines=h(a._lines)),a._name&&(b.p_name=h(a._name)),a._quantity&&(b.p_quantity=h(a._quantity)),a._readonly&&(b.p_readonly=x(a._readonly)),a._required&&(b.p_required=x(a._required)),a._searchable&&(b.p_searchable=x(a._searchable)),a._sortable&&(b.p_sortable=x(a._sortable)),a._fieldsource&&(b.p_source=h(a._fieldsource)),
a._fieldstyle&&(b.p_style=h(a._fieldstyle)),a._value&&(b.p_value=h(a._value),b.p_valuedescription=""),"d_relatedlinks"===a._type){if(a.option){b.p_selection=[];var c={};if(1<a.option.length)for(var d in a.option)c=M(a.option[d]),Object.keys(c).length&&b.p_selection.push(c);else c=M(a.option),Object.keys(c).length&&b.p_selection.push(c)}}else if(a.option)for(c in b.p_selection=[],d={},a.option){d=a.option[c];var f={};d._value&&(f.p_code=h(d._value));d.__text&&(f.p_value=h(d.__text),f.p_valuedescription=
"");d=f;Object.keys(d).length&&b.p_selection.push(d)}return b}function M(a){var b={};a.__text&&(b.p_label=h(a.__text));a._permissions&&(b.p_permissions=h(a._permissions));a._command&&(b.p_command=h(a._command));a._parameters&&(b.p_parameters=h(a._parameters));return b}function x(a){return void 0===a?h("N"):h("Y")}function h(a){var b=a;"string"==typeof a&&(b=str_replace(b,"__AMP__","&"),b=str_replace(b,"__APOS__","'"),b=str_replace(b,"__QUOT__",'"'),b=str_replace(b,"__LT__","<"),b=str_replace(b,"__GT__",
">"));void 0==b&&(b="");return b}function C(){var a=N.data("formBuilder").formData;void 0!==a.location&&(a=c.element(d,".fb-temp").val());f=ba(a)}function D(){n(!0)}function ca(a,b){var d=c.ajaxRequestCreate("entity_entitysearchbycode",[{name:"entitycode",value:m},{name:"filter",value:[{field:"code",value:a.term}]},{name:"order",value:[{field:"code",ascending:!0}]}]);c.ajaxCall(URL_WEBSERVICE,d,function(a){var c=[],d=0;processArray(a,function(a){c[d]={value:a.code};d++});b(c)},c.ajaxError,doNothing,
!0)}function da(a,b){A("ENTITY",b.item.value);c.element(d,".ge-dataformgroup-field").focus()}function ea(){var a=fa();0<a.length?c.dialogAlertScroll(a,function(){}):(n(!1),"form"===e.internalmode?"add"===e.mode?O():"edit"===e.mode?ga():"copy"===e.mode&&O():"formsection"===e.internalmode&&(E=!0,c.closeForm(d)))}function n(a){F=a;G?p.disableButtons("SaveButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty"):F?(p.disableButtons("SaveButton","gs-darkblue-background-colour"),
p.enableButtons("SaveButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty"),p.disableButtons("CopyButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty")):(p.disableButtons("SaveButton","gs-red-background-colour gs-glow-dirty"),p.enableButtons("SaveButton","gs-darkblue-background-colour gs-glow-focusborder"),p.disableButtons("CopyButton","gs-red-background-colour gs-glow-dirty"),p.enableButtons("CopyButton","gs-darkblue-background-colour gs-glow-focusborder"))}
function P(a){var b=c.element(d,a).attr("label"),e=c.element(d,a).attr("sectionguid");a=c.element(d,a).attr("type");var g=[],h=-1,k=-1;processArray(f,function(a){h++;a.sectioncode==e&&(g=a.fields,k=h)});var l=JSON.stringify(g);E=!1;c.showFormPopup("widgetformbuilder.wgtFormBuilder","internalmode=formsection&title="+encodeURIComponent(b)+"&entity="+encodeURIComponent(m)+"&sectiontype="+encodeURIComponent(a)+"&sectioncode="+encodeURIComponent(e)+"&currentsection="+encodeURIComponent(l),function(a){a.isClosed&&
(f[k].fields=a.Data,n(!0))},!1,!0)}function q(a,b,c){var d=!1,e="";processArray(a,function(a){if(a.sectiontype==b&&(processArray(a.fields,function(a){if(a.p_name==c)return e=a.p_value,d=!0}),d))return!0});return e}function u(){"form"===e.internalmode&&processArray(f,function(a){a.sectioncodetemp=a.sectioncode})}function fa(){var a="",b=0,c="";if("form"===e.internalmode){processArray(f,function(d){b=d.fields.length;c=d.sectiontitle;0===b&&(a+="<li>There are no fields in the section "+c+"</li>")});
var d=q(f,"FORMHEADER","ENTITY"),g=q(f,"FORMHEADER","CODE"),h=q(f,"FORMHEADER","DESCRIPTION");0===d.length&&(a+="<li>Form Header Entity is required.</li>");0===g.length&&(a+="<li>Form Header Code is required.</li>");0===h.length&&(a+="<li>Form Header Description is required.</li>");d=Y();d>MAX_DATAFORM_FIELD_LIMIT&&(a+="<li>You have exceeded the "+MAX_DATAFORM_FIELD_LIMIT+" field form limit by "+(d-MAX_DATAFORM_FIELD_LIMIT)+" fields.</li>")}0<a.length&&(a="<ul>"+a+"</ul>");return a}function Q(){var a=
B(f);c.element(d,".fb-temp").html(a);N=c.element(d,".fb-temp").formBuilder(c,d,H);c.unbindEvents(d,"ge-cancel-button,ge-save-button,ge-section-button");c.element(d,".view-data").hide();c.element(d,".form-builder-save").hide();c.element(d,".clear-all").hide();c.element(d,".cb-wrap").css({"overflow-x":"hidden","overflow-y":"scroll"});c.element(d,".stage-wrap").css({"overflow-x":"hidden","overflow-y":"scroll"});ha();R();I();c.element(d,".fb-temp").focus();"form"===e.internalmode&&n(!1);void 0!==e.title&&
(l=l+" - "+e.title);"form"===e.internalmode&&(a=q(f,"FORMHEADER","CODE"),"add"===e.mode?l=e.title+" - New":"edit"===e.mode?l=e.title+" - Edit "+a:"view"===e.mode&&(l=e.title+" - View "+a));c.element(d,".ge-form-title").text(l);c.element(d,".ge-dataformgroup-field").autocomplete({autoFocus:!0,xdelay:500,source:ca,select:da});c.element(d,".stage-wrap").height(v-150+"px");c.element(d,".cb-wrap").height(v-150+"px")}function ia(a){c.broadcast(d,"entity",w+"listadded");e.mode="edit";s=a[0].id;"form"===
e.internalmode&&(a=q(f,"FORMHEADER","CODE"),l=e.title+" - Edit "+a,c.element(d,".ge-form-title").text(l))}function ja(a){t=f=a[0].jsondata;u();y++;z==y&&Q()}function ka(a){c.broadcast(d,"entity",w+"listedited");"form"===e.internalmode&&(a=q(f,"FORMHEADER","CODE"),l=e.title+" - Edit "+a,c.element(d,".ge-form-title").text(l));J(!0)}function O(){var a=q(f,"FORMHEADER","ENTITY"),a=c.ajaxRequestCreate("entity_formadd",[{name:"entitycode",value:m},{name:"formentitycode",value:a},{name:"jsondata",value:f}]);
c.ajaxCall(URL_WEBSERVICE,a,ia,c.ajaxError,D)}function J(a){a?(z=1,y=0,z=1,a=c.ajaxRequestCreate("entity_formfetch",[{name:"entitycode",value:m},{name:"entitydataid",value:s}]),c.ajaxCall(URL_WEBSERVICE,a,ja,c.ajaxError,D)):(y=z=0,Q())}function ga(){var a=q(f,"FORMHEADER","ENTITY"),a=c.ajaxRequestCreate("entity_formupdate",[{name:"entitycode",value:m},{name:"entitydataid",value:s},{name:"formentitycode",value:a},{name:"jsondata",value:f}]);c.ajaxCall(URL_WEBSERVICE,a,ka,c.ajaxError,D)}function ha(){c.onDirty(d,
S,function(){n(!0)})}function R(){c.unbindEvents(d,"fb-section-button,section-field,form-control");c.bindEvent(k,d,".fb-section-button","SectionButton","onClick");c.bindEvent(k,d,".section-field","SectionField","onDblClick");c.bindEvent(k,d,".form-control","FormControl","onChange");c.bindEvent(k,d,".form-control","FormControl","onKeyDown");c.bindEvent(k,d,".ge-yesno","YesNoControl","onChange")}function I(){c.unbindEvents(d,"ge-tab-start,ge-tab-end");c.bindEvent(k,d,".ge-tab-start","TabStart","onFocus");
c.bindEvent(k,d,".ge-tab-end","TabEnd","onFocus");c.setTabOrder(d,"ge-tab-start,CloseButton,"+S+",ge-tab-end")}var c=U,k=this,d=V,e=W,G=!1,F=!1,z=0,y=0,v=0,S="ge-form-title,fb-temp",N=null,E=!1,f=null,t=null;void 0!==e.currentsection&&(t=f=JSON.parse(e.currentsection),u());void 0===e.internalmode&&(e.internalmode="form");var r=e.sectiontype;void 0===r&&(r="");var s=e.id;void 0===s&&(s="");var m=e.entity;void 0===m&&(m="");var K=e.formentitydescription;void 0===K&&(K="");var w=e.formentity;void 0===
w&&(w="");var l="",H="",p,T=[{location:"root",title:"Home",layout:[["CloseButton","SaveButton","RenderButton"]]}];"form"===e.internalmode&&(T[0].layout=[["CloseButton","SaveButton","CopyButton","RenderButton"]]);var la=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CopyButton",caption:"Copy",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:[],action:function(){k.CopyButton_onClick()},actionData:null,tip:"Click here to copy form.",
type:"toolbarbutton"},{id:"CloseButton",caption:function(){var a="Close";"formsection"===e.internalmode&&(a="Cancel");return a},classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){k.FormClose_onClick()},actionData:null,tip:"Click here to close the form builder.",type:"toolbarbutton"},{id:"RenderButton",caption:"Render",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:["DEVELOPER"],action:function(){k.RenderButton_onClick()},actionData:null,
tip:"Click here to render form.",type:"toolbarbutton"},{id:"SaveButton",caption:function(){var a="Save";"formsection"===e.internalmode&&(a="OK");return a},classes:"gb-cell-disabled",permissions:[],action:function(){k.SaveButton_onClick()},actionData:null,tip:function(){var a="Click here to save.";"formsection"===e.internalmode&&(a="Click here to keep changes.");return a},type:"toolbarbutton"},{id:"ClearButton",caption:"Clear",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:[],
action:function(){k.ClearButton_onClick()},actionData:null,tip:"Click here to clear form.",type:"toolbarbutton"}];this.Form_isDirty=function(){return F};this.Form_onBroadcast=function(a,b,e){"hash"===a&&"change"===b&&c.closeForm(d)};this.Form_onClick=function(){c.setFormFocus(k,d)};this.Form_onDblClick=function(){c.formToFront(d)};this.Form_onFocus=function(){I()};this.Form_onLoad=function(){G=!1;if("form"===e.internalmode){var a=getGUID("g"),b=getGUID("g"),g=getGUID("g"),h="";"systemform"!==m&&(h=
getGUID("g"));f=[{sectionclasses:"btn btn-default fb-section-button",sectioncode:b,sectioncodetemp:b,sectioncolour:"",sectionref:"",sectiontitle:"Form Header",sectiontype:"FORMHEADER",fields:[{p_classes:"form-control",p_colour:"",p_datatype:"d_text",p_info:"",p_label:"Data Group Name",p_length:"20",p_name:"ENTITY",p_quantity:"1",p_readonly:"N",p_required:"N",p_searchable:"N",p_sortable:"N",p_source:"",p_style:"",p_value:h,p_valuedescription:""},{p_classes:"form-control",p_colour:"",p_datatype:"d_version",
p_info:"",p_label:"Form Version",p_length:"",p_name:"FORMVERSION",p_quantity:"1",p_readonly:"Y",p_required:"N",p_searchable:"N",p_sortable:"N",p_source:"",p_style:"",p_value:"1",p_valuedescription:""},{p_classes:"form-control",p_colour:"",p_datatype:"d_text",p_info:"",p_label:"Code",p_length:"40",p_name:"CODE",p_quantity:"1",p_readonly:"N",p_required:"Y",p_searchable:"Y",p_sortable:"Y",p_source:"",p_style:"",p_value:"",p_valuedescription:""},{p_classes:"form-control",p_colour:"",p_datatype:"d_text",
p_info:"",p_label:"Description",p_length:"40",p_name:"DESCRIPTION",p_quantity:"1",p_readonly:"N",p_required:"Y",p_searchable:"Y",p_sortable:"Y",p_source:"",p_style:"",p_value:"",p_valuedescription:""},{p_classes:"d_yesno",p_colour:"",p_datatype:"d_yesno",p_info:"",p_label:"Is Enabled?",p_length:"1",p_name:"ISENABLED",p_quantity:"1",p_readonly:"N",p_required:"N",p_searchable:"N",p_sortable:"N",p_source:"",p_style:"",p_value:"Y",p_valuedescription:""}]},{sectionclasses:"btn btn-default fb-section-button",
sectioncode:a,sectioncodetemp:a,sectioncolour:"",sectionref:"",sectiontitle:"Data Header",sectiontype:"DATAHEADER",fields:[{p_classes:"form-control",p_colour:"",p_datatype:"d_version",p_info:"",p_label:"Data Version",p_length:"",p_name:"DATAVERSION",p_quantity:"1",p_readonly:"Y",p_required:"N",p_searchable:"N",p_sortable:"N",p_source:"",p_style:"",p_value:"1",p_valuedescription:""}]},{sectionclasses:"btn btn-default fb-section-button",sectioncode:"INTERNALUSEFORMHEADER",sectioncodetemp:"INTERNALUSEFORMHEADER",
sectioncolour:"",sectionref:"",sectiontitle:"Internal Use Form header",sectiontype:"INTERNALUSEFORMHEADER",fields:[{p_colour:"",p_source:"",p_classes:"form-control",p_datatype:"d_text",p_info:"",p_label:"Submitted Date Time",p_length:"20",p_name:"SUBMITTEDDATETIME",p_quantity:"1",p_readonly:"N",p_required:"N",p_searchable:"N",p_sortable:"N",p_style:"",p_value:"",p_valuedescription:""},{p_colour:"",p_source:"",p_classes:"form-control",p_datatype:"d_text",p_info:"",p_label:"Submitted By Client",p_length:"20",
p_name:"SUBMITTEDBYCLIENT",p_quantity:"1",p_readonly:"N",p_required:"N",p_searchable:"N",p_sortable:"N",p_style:"",p_value:"",p_valuedescription:""},{p_colour:"",p_source:"",p_classes:"form-control",p_datatype:"d_text",p_info:"",p_label:"Submitted By User",p_length:"20",p_name:"SUBMITTEDBYUSER",p_quantity:"1",p_readonly:"N",p_required:"N",p_searchable:"N",p_sortable:"N",p_style:"",p_value:"",p_valuedescription:""}]},{sectionclasses:"btn btn-default fb-section-button",sectioncode:g,sectioncodetemp:g,
sectioncolour:"",sectionref:"",sectiontitle:"Form Fields",sectionquantity:"1",sectiontype:"DATA",fields:[{p_classes:"form-control",p_colour:"",p_datatype:"d_text",p_info:"",p_label:"Code",p_length:"40",p_name:"CODE",p_quantity:"1",p_readonly:"N",p_required:"Y",p_searchable:"Y",p_sortable:"Y",p_source:"",p_style:"",p_value:"",p_valuedescription:""},{p_classes:"form-control",p_colour:"",p_datatype:"d_text",p_info:"",p_label:"Description",p_length:"40",p_name:"DESCRIPTION",p_quantity:"1",p_readonly:"N",
p_required:"Y",p_searchable:"Y",p_sortable:"Y",p_source:"",p_style:"",p_value:"",p_valuedescription:""},{p_classes:"d_yesno",p_colour:"",p_datatype:"d_yesno",p_info:"",p_label:"Is Enabled?",p_length:"1",p_name:"ISENABLED",p_quantity:"1",p_readonly:"N",p_required:"N",p_searchable:"N",p_sortable:"N",p_source:"",p_style:"",p_value:"Y",p_valuedescription:""}]}];u();t=f;u()}a=c.getViewPort().width;b=c.getViewPort().height;c.resizeAndRepositionForm(d,0.1*b,0.1*a,0.8*b,0.8*a);G=!1;"form"===e.internalmode?
(l="Form Editor",H={disableFields:"formheadersection xinternaluseformheadersection dataheadersection internaluseformheadersection d_abnlookup d_audio d_barcode d_button d_chart d_codeeditor d_date d_description d_document d_gps d_heading d_html d_texthtml d_image d_list d_metadata d_multilinetext d_multilist d_number d_password d_relatedlinks d_text d_spacer d_time d_url d_version d_video d_yesno autocomplete button checkbox checkbox-group color date email file header hidden limitRole mitsukibo paragraph password radio-group rich-text roles select styles submit text textarea".split(" "),
messages:{xsection:"Data Section",label:"Title",name:"Code",xsectionref:"Ref"},entitycode:m,internalmode:e.internalmode,sectiontype:r}):"formsection"===e.internalmode&&(l="Section Editor",H="systemform"===m?{disableFields:"autocomplete button checkbox checkbox-group color d_abnlookup d_audio xd_metadata d_version d_video dataheadersection datasection date email file formheadersection header hidden internaluseformheadersection internaluseonlysection limitRole mitsukibo paragraph password radio-group rich-text roles select styles submit text textarea".split(" "),
xmessages:{section:"Section"},entitycode:m,internalmode:e.internalmode,sectiontype:r}:"formheadersection"===r?{disableFields:"autocomplete button checkbox checkbox-group color d_abnlookup d_audio d_barcode d_button d_chart d_codeeditor d_date d_description d_document d_gps d_heading d_html d_texthtml d_image d_list d_metadata d_multilinetext d_multilist d_number d_password d_relatedlinks d_spacer d_text d_texthtml d_time d_url d_version d_video d_yesno dataheadersection datasection date email file formheadersection header hidden internaluseformheadersection internaluseonlysection limitRole mitsukibo paragraph password radio-group rich-text roles select styles submit text textarea".split(" "),
xmessages:{section:"Section"},entitycode:m,internalmode:e.internalmode,sectiontype:r}:{disableFields:"autocomplete button checkbox checkbox-group color d_abnlookup d_audio d_codeeditor d_document d_html d_texthtml d_metadata d_multilist d_password d_relatedlinks d_version d_video dataheadersection datasection date email file formheadersection header hidden internaluseformheadersection internaluseonlysection limitRole mitsukibo paragraph password radio-group rich-text roles select styles submit text textarea".split(" "),
xmessages:{section:"Section"},entitycode:m,internalmode:e.internalmode,sectiontype:r});c.element(d,".gb-overflow").css("overflow-y","hidden");c.element(d,".gb-overflow").css("overflow-x","hidden");p=new jDock(c,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:T,tiles:la});p.render(d,".ge-button-panel");"form"===e.internalmode&&("edit"===e.mode||"view"===e.mode)?J(!0):J(!1);c.unbindEvents(d,"gb-form-close,gb-form,gb-formtitle-inner-panel");c.bindEvent(k,d,".gb-form-close","FormClose","onClick");
c.bindEvent(k,d,".gb-form","Form","onClick");c.bindEvent(k,d,".gb-form","Form","onDblClick");c.bindEvent(k,d,".gb-formtitle-inner-panel","FormTitle","onClick");c.bindEvent(k,d,".fb-temp","FormBuilder","onChange")};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){c.formToFront(d)};this.FormResult=function(){return{isClosed:E,Data:f}};this.Form_onResize=function(a,b){v=b;c.element(d,".stage-wrap").height(v-150+"px");c.element(d,".cb-wrap").height(v-150+"px")};this.ClearButton_onClick=
function(){c.element(d,".clear-all").trigger("click")};this.CopyButton_onClick=function(){n(!0);e.mode="copy";var a=q(f,"FORMHEADER","CODE");l=e.title+" - Copy "+a;c.element(d,".ge-form-title").text(l)};this.FormBuilder_onChange=function(){I();R();C()};this.FormClose_onClick=function(){c.closeForm(d)};this.RenderButton_onClick=function(){var a=JSON.stringify(f);c.showForm("entity.frmForm","mode=add&entity="+encodeURI(m)+"&formentity="+encodeURI(w)+"&formentityid="+encodeURI(s)+"&title="+encodeURI(K)+
"&jsondata="+a,function(a){})};this.SaveButton_onClick=function(){if(k.Form_isDirty())try{ea()}catch(a){n(!0)}};this.FormControl_onChange=function(a){var b=c.element(d,a).val(),e=c.element(d,a).parent().siblings(".frm-holder").find(".form-elements .name-wrap .form-control").val();c.element(d,a).prop("type");c.element(d,a).attr("value",b);c.element(d,a).parent().siblings(".frm-holder").find(".form-elements .value-wrap .form-control").attr("value",b);C();A(e,b);a=B(f);c.element(d,".fb-temp").html(a);
n(!0)};this.YesNoControl_onChange=function(a){var b=c.element(d,a).val(),e=c.element(d,a).parent().siblings(".frm-holder").find(".form-elements .name-wrap .form-control").val();"checkbox"===c.element(d,a).prop("type")&&(b=a.checked?"Y":"N");c.element(d,a).attr("value",b);c.element(d,a).parent().siblings(".frm-holder").find(".form-elements .value-wrap .form-control").attr("value",b);C();A(e,b);a=B(f);c.element(d,".fb-temp").html(a);n(!0)};this.FormControl_onKeyDown=function(a){n(!0)};this.SectionButton_onClick=
function(a){P(a)};this.SectionField_onDblClick=function(a){P(a)};this.TabEnd_onFocus=function(){c.element(d,".CloseButton").focus()};this.TabStart_onFocus=function(){c.element(d,".ge-code-field").focus()}};
