// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
if(REFRESH){var strSearch=location.search,strSearch=removeURLParameter(strSearch,"loggedin"),strSearch=removeURLParameter(strSearch,"theme");location=location.protocol+"//"+location.host+location.pathname+strSearch}else $(document).ready(function(){function c(){"TRUE"===ALLOW_STAY_LOGGEDIN?"TRUE"===LOGGEDIN?f(e):a():"TRUE"===LOGGEDIN?f(e):g()}function d(){var a=os().getProperty("theme");os().hasCapability("themes")&&0<a.length?location=location.protocol+"//"+location.host+location.pathname+"?loggedin=true&theme="+
encodeURIComponent(a):e()}function a(){var a=os().getAgent(),c=os().getBrowserCapabilities(),a=os().ajaxRequestCreate("public_authenticationcheck",[{name:"useragent",value:a},{name:"capabilities",value:c}]);os().ajaxCall(URL_WEBSERVICE,a,function(){f(d)},g,doNothing,!0)}function f(a){var c=os().ajaxRequestCreate("security_userinfo",[]);os().ajaxCall(URL_WEBSERVICE,c,function(b){setDesktopRegions(b.desktopregions);setPermissions(b.permissions);setProducts(b.products);os().setProperty("clientdb",b.clientdb);
os().setProperty("loginas",b.loginas);os().setProperty("client",b.clientid);os().setProperty("clientname",b.clientname);os().setProperty("businessname",b.businessname);os().setProperty("login",b.login);os().setProperty("username",b.username);os().setProperty("sysadmin",b.sysadmin);os().setProperty("developer",b.developer);os().setProperty("public",b.ispublic);os().setProperty("batch",b.isbatch);os().setProperty("default",b.isdefault);os().setProperty("owner",b.isowner);os().setProperty("licensed",
b.licensed);os().setProperty("expirydate",b.expirydate);os().setProperty("expirydays",b.expirydays);os().setProperty("selectedtheme",SELECTED_THEME);os().setProperty("isextend",!1);os().setProperty("ismdi",b.ismdi);k="TRUE"==TESTSCROLL&&!os().hasCapability("regionscroll")&&os().hasCapability("mobile");os().initialiseScrollbars(k);os().setProperty("defaultcountry",b.defaultcountry);os().setProperty("devicename",b.devicename);os().setProperty("theme",b.theme);os().setProperty("isemployer",b.isemployer);
os().setProperty("isindividual",b.isindividual);os().setProperty("isrto",b.isrto);os().setProperty("isvalidassessor",b.isvalidassessor);os().setProperty("enablebranches",b.enablebranches);os().setProperty("branchid",b.branchid);os().setProperty("branchname",b.branchname);b=os().toBoolean(b.displaytooltips);os().enableTips(b);LOGGEDIN=os().toBoolean(getProperty("public"))?"FALSE":"TRUE";os().toBoolean(os().getProperty("sysadmin"))?os().setBackground("gi-sysadmin-background"):"FALSE"===LOGGEDIN&&0<
LANDINGPAGE_VIDEOID.length&&os().isModuleLoaded("widgettube")&&os().hasCapability("tube")?doNothing():os().setBackground("gi-desktop-background");$(document).trigger("ospropertiesloaded");$.isFunction(a)&&a()},os().ajaxError,doNothing,!0)}function g(){var a=DEFAULT_ENTITY,c=DEFAULT_LOGIN,b=DEFAULT_PASSWORD,d=os().getAgent(),g=os().getBrowserCapabilities(),a=os().ajaxRequestCreate("public_login",[{name:"clientcode",value:a},{name:"login",value:c},{name:"password",value:b},{name:"stayloggedin",value:"N"},
{name:"useragent",value:d},{name:"capabilities",value:g}]);os().ajaxCall(URL_WEBSERVICE,a,function(){f(e)},os().ajaxError,doNothing,!0)}function e(){os().registerServerEvent("formqueue","system");os().enableServerEventQueue("formqueue");os().ajaxCall(URL_WEBSERVICE,os().ajaxRequestCreate("esb_registerbroadcaster",[{name:"eventqueue",value:"formqueue"}]),doNothing,doNothing);os().ajaxCall(URL_WEBSERVICE,os().ajaxRequestCreate("esb_registerlistener",[{name:"eventqueue",value:"formqueue"}]),doNothing,
doNothing);m?doNothing():($(window).hashchange(function(a){os().hashChange(location.hash)}),os().showTaskbar("core.frmTaskbar","",!1,function(){initialiseStartupItems(os(),function(){"TRUE"===LOGGEDIN?os().hideLanding(PUBLIC_LANDINGPAGEID):(os().hasCapability("mobile")?doNothing():0<LANDINGPAGE_VIDEOID.length&&(os().isModuleLoaded("widgettube")&&os().hasCapability("tube"))&&os().showForm("widgettube.wgtTube",{target:"#ge-widgettube-container"}),os().showLanding(PUBLIC_LANDINGPAGEID,"",!0),os().bindLandingForm(PUBLIC_LANDINGPAGEID,
PUBLIC_LANDINGPAGE,""),os().hashChange(location.hash))})}))}function h(a){os().initialiseViewPort()}var l="TRUE"===KEEPALIVE,m="TRUE"===STOP_HASHCHANGE,k=!1;"TRUE"===LOGGEDIN?os({progresscolour:PROGRESSCOLOUR,progress:"ge-progress",percentage:"ge-percentage",container:"ge-form-container",orientation:h,dependencies:"osfull",keepalive:l,unloadprompt:!0},function(){c()}):os({progresscolour:PROGRESSCOLOUR,progress:"ge-progress",percentage:"ge-percentage",container:"ge-form-container",orientation:h,dependencies:"osfull",
keepalive:l,unloadprompt:!1},function(){0<RESPONSEMESSAGE.length&&os().dialogAlert(RESPONSEMESSAGE,doNothing);c()})});function removeURLParameter(c,d){var a=c;0===a.indexOf("?")&&(a=a.substr(1));a=urlToJSONWithOmission(a,d);a=jsonToURL(a);return a=0<a.length?"?"+a.substr(1):"?uuid="+getGUID()}function jsonToURL(c){var d="",a;for(a in c)d+="&"+encodeURIComponent(a)+"="+encodeURIComponent(c[a]);return d}
function urlToJSONWithOmission(c,d){var a={};0<c.length&&(a=c.split("&").reduce(function(a,c,e,h){c=c.split("=");c[0]!=d&&(a[decodeURIComponent(c[0])]=decodeURIComponent(c[1]));return a},{}));return a};
