// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function entity_frmEntityChooser(p,T,U){function V(c){if(0<F.length){var a=F.split(",");processArray(a,function(a){"nomultiselect"===a&&(c.multiSelect=!1);"multiselect"===a&&(c.multiSelect=!0)})}return c}function z(c){var a=!1;processArray(A.actions,function(b){if(b.id==c||b.operationcode==c)a=$.isFunction(b.permissions)?b.permissions():0===b.permissions.length?!0:hasPermission(b.permissions);return a});return a}function W(c){var a;processArray(A.actions,function(b){var d=!1;if(b.id==c||b.operationcode==
c)a=b,d=!0;return d});return a}function G(c){var a,d="";if(z(c)){var e=W(c),H=m.returns,g=k.getSelection(H),f=e.multiSelect;void 0===f&&(f=!1);var l=e.requiresSelection;void 0===l&&(l=!0);var h=e.prompt;void 0===h&&(h=!1);if(h&&("DeleteButton"===c||"DELETE"===c||"DEL"===c))d="Continue and delete the "+m.title+" selection?";l?0<g.length&&(f?(a=[],processArray(g,function(c){void 0===H?a.push(c.id):a.push(c)})):a=void 0===H?g[0].id:g[0],void 0!==a&&$.isFunction(e.action)&&(0<d.length?b.dialogConfirm(d,
function(){e.action(c,a,e)}):e.action(c,a,e))):$.isFunction(e.action)&&(0<d.length?b.dialogConfirm(d,function(){e.action(c,null,e)}):e.action(c,null,e))}}function I(){var c=[];processArray(J,function(a){b.toBoolean(a.requiresselection)&&(a=a.code.split("_")[0]+"Button",c.push(a))});return c.join(",")}function X(){var c=[],a="",d="",e=["CloseButton"];processArray(J,function(f){var h=f.code,m=h.split("_")[0],k=h+"Button",n=null,n=void 0!==f.permissions?f.permissions:[];e.push(k);a={id:k,permissions:n,
multiSelect:b.toBoolean(f.allowmultiple),requiresSelection:b.toBoolean(f.requiresselection),prompt:!0,operation:m,operationcode:h,action:function(c,a,d){var e="";switch(c){case "ENTITYCHOOSERSELECT":g.SelectButton_onClick();break;default:c=d.operationcode,e="",void 0!==a&&null!==a&&(e=$.isArray(a)?a[0].id:a.id),a=b.ajaxRequestCreate("entity_customoperationexecute",[{name:"entitycode",value:l},{name:"id",value:e},{name:"operationcode",value:c}]),b.ajaxCall(URL_WEBSERVICE,a,Y,b.ajaxError)}}};d={id:k,
caption:f.description,classes:"",permissions:function(){return z(k)},action:G,actionData:h,tip:"Click here to "+f.description+".",type:"toolbarbutton"};c.push(a);P.push(d)});A={id:w,actions:c,broadcasts:[{messages:["added","deleted","edited"],action:"refresh"}]};B[0].layout[0]=e}function Q(){K++;if(R==K){q=new jDock(b,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:B,tiles:P});q.render(d,".ge-button-panel");q.disableButtons(I(),"disabled");var a={cbOnSelection:g.Grid_onDblClick,cbOnSelectionChange:g.Grid_onSelectionChange,
columns:m.columns,filterType:"string",parameters:m.params,extraParameters:[],returnFields:m.returns,webServiceFunction:m.ws},a=V(a);k=new jDatatableRenderer(b,a);k.render(d,".ge-entity-grid");a="";a=0<n.length?n:m.title;b.element(d,".ge-form-title").text(a);b.hasCapability("mobile")||b.element(d,".ge-search-input").focus()}}function Z(a){S=a.fields;F=a.flags;m.columns=S;m.returns=0<C.length?C:aa.returns.mode[f];Q()}function Y(a){k.refresh()}var b=p,g=this,d=T,a=U,w="",F="",R=0,K=0,m,A,k,S=[],J=[],
C=[],L=[];void 0!==a.resultfields&&0<a.resultfields.length&&(C=a.resultfields);var s=a.operationcode;void 0===s&&(s="");var l=a.entity;void 0===l&&(l="");var t=a.entityid;void 0===t&&(t="");var D=a.fixedfilter;void 0===a.fixedfilter&&(D=[]);var E=a.passedfilter;void 0===a.passedfilter&&(E=[]);var u=a.exclusive;void 0===u&&(u="N");var x=a.formcode;void 0===x&&(x="");var r=a.formentity;void 0===r&&(r="");var v=a.formentityid;void 0===v&&(v="");var f=a.mode;void 0===f&&(f="renderer");var y=a.searchkeyword;
void 0===y&&(y="");var n=a.title;void 0===n&&(n="");var h=a.type;void 0===h&&(h="");var M=a.relationship;void 0===M&&(M="");p=a.relationshipid;void 0===p&&(p="");var N=a.relativeid;void 0===N&&(N="");var O=a.relative;void 0===O&&(O="");p=a.relationshiptitle;void 0===p&&(p="");var q,B=[{location:"root",title:"Home",layout:[]}],P=[{id:"-",caption:"",classes:"",permissions:[],action:"",tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"",permissions:[],action:function(){g.FormClose_onClick()},
tip:"Click here to close the "+w+" list.",type:"toolbarbutton"}],ba={select:["CloseButton","ENTITYCHOOSERButton"],builder:["CloseButton","ENTITYCHOOSERButton"],renderer:["CloseButton","ENTITYCHOOSERButton"]},ca=[{code:"ENTITYCHOOSERSELECT",description:"Select",allowmultiple:"N",requiresselection:"Y",permissions:[]}],da=[{code:s,description:"Select",allowmultiple:"N",requiresselection:"Y",permissions:[s]}],ea=[{code:"DEL_DFDATA",description:"Delete",allowmultiple:"N",requiresselection:"Y",permissions:[]}],
aa={columns:{},returns:{mode:{select:["id"],invoke:["id"],deleteformgroup:["id","code","description"],builder:["id"],renderer:["id"]}}};this.Form_onBroadcast=function(a,b,d){var e;processArray(A.broadcasts,function(a){processArray(a.messages,function(c){var d=w+c;d.toLowerCase()==b.toLowerCase()?e=a.action:c.toLowerCase()==b.toLowerCase()&&(e=a.action);return void 0!==e});return void 0!==e});void 0!==e&&($.isFunction(e)?e():"refresh"===e&&k.refresh())};this.Form_onClick=function(){b.setFormFocus(g,
d)};this.Form_onDblClick=function(a,f,g){b.formToFront(d);g.stopPropagation();b.zoomFormInOut(d)};this.Form_onFocus=function(c){if(void 0!==c&&null!==c&&(a.entity!==c.entity||a.entityid!==c.entityid||a.fixedfilter!==c.fixedfilter||a.exclusive!==c.exclusive||a.formcode!==c.formcode||a.formentity!==c.formentity||a.formentityid!==c.formentityid||a.mode!==c.mode||a.searchkeyword!==c.searchkeyword||a.title!==c.title||a.title!==c.title||a.resultfields!==c.resultfields||a.type!==c.type))a=c,void 0!==a.resultfields&&
0<a.resultfields.length&&(C=a.resultfields),l=a.entity,void 0===l&&(l=""),t=a.entityid,void 0===t&&(t=""),D=a.fixedfilter,void 0===a.fixedfilter&&(D=[]),E=a.passedfilter,void 0===a.passedfilter&&(E=[]),u=a.exclusive,void 0===u&&(u="N"),x=a.formcode,void 0===x&&(x=""),r=a.formentity,void 0===r&&(r=""),v=a.formentityid,void 0===v&&(v=""),f=a.mode,void 0===f&&(f="renderer"),y=a.searchkeyword,void 0===y&&(y=""),n=a.title,void 0===n&&(n=""),h=a.type,void 0===h&&(h=""),g.Form_onLoad();b.unbindEvents(d,
"ge-tab-start,ge-tab-end");b.bindEvent(g,d,".ge-tab-start","TabStart","onFocus");b.bindEvent(g,d,".ge-tab-end","TabEnd","onFocus");c=B[0].layout[0].join(",");b.setTabOrder(d,"ge-tab-start,"+c+",ge-tab-end")};this.Form_onFocusLost=function(){};this.Form_onLoad=function(){b.element(d,".ge-form-title").text("");b.unbindEvents(d,"gb-form-close,gb-form,gb-formtitle-inner-panel");b.bindEvent(g,d,".gb-form-close","FormClose","onClick");b.bindEvent(g,d,".gb-form","Form","onClick");b.bindEvent(g,d,".gb-form",
"Form","onDblClick");b.bindEvent(g,d,".gb-formtitle-inner-panel","FormTitle","onClick");b.unbindEvents(d,"ge-search-input,ge-searchclear-button");b.bindEvent(g,d,".ge-searchclear-button","btnSearchClear","onClick");b.bindEvent(g,d,".ge-search-input","SearchField","onEnterKey");var a=b.getViewPort().width,k=b.getViewPort().height;b.resizeAndRepositionForm(d,0.1*k,0.1*a,0.8*k,0.8*a);w=l+"list";B[0].layout[0]=ba[f];a=null;"deleteformgroup"===f?a="entity_dataformentitylist":"form"===h?a="entity_formdatalist":
"entity"===h&&(a="entity_entitydatalist");m={id:w,ws:a,params:[{name:"entitycode",value:l},{name:"formentityid",value:v},{name:"formentitycode",value:r},{name:"entityid",value:t},{name:"order",value:""},{name:"filter",value:""},{name:"fixedfilter",value:D},{name:"passedfilter",value:E},{name:"exclusive",value:u},{name:"relationship",value:M},{name:"relativeid",value:N},{name:"relative",value:O},{name:"offset",value:0},{name:"limit",value:0}],columns:[],returns:["id"],title:n};R=2;K=0;a="";"form"===
h?a="entity_formdataheadersfetchbyentitycode":"entity"===h&&(a="entity_entitydataheadersfetchbyentitycode");a=b.ajaxRequestCreate(a,[{name:"entitycode",value:l},{name:"formentitycode",value:r}]);b.ajaxCall(URL_WEBSERVICE,a,Z,b.ajaxError);J="deleteformgroup"===f?ea:"invoke"===f?da:ca;X();Q()};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(d)};this.Form_onResize=function(a,f){b.element(d,".ge-entity-grid").width(a-20+"px");b.element(d,".ge-entity-grid").height(f-
150+"px");b.element(d,".ge-entity-grid");k.resize()};this.FormResult=function(){return L};this.FormClose_onClick=function(){L=[];b.closeForm(d)};this.Grid_onDblClick=function(a){"invoke"===f?z(s)&&G(s):z("ENTITYCHOOSERSELECT")&&G("ENTITYCHOOSERSELECT")};this.Grid_onSelectionChange=function(a){void 0!==q&&null!==q&&(0<a.length?q.enableButtons(I(),"disabled"):q.disableButtons(I(),"disabled"))};this.btnSearchClear_onClick=function(){k.search("");b.element(d,".ge-search-input").val("");b.element(d,".ge-search-input").focus()};
this.SearchField_onEnterKey=function(a){a=b.element(a).val();k.search(a)};this.SelectButton_onClick=function(){L=k.getSelection();b.closeForm(d)};this.TabEnd_onFocus=function(){b.element(d,".CloseButton").focus()};this.TabStart_onFocus=function(){}};
