// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function entity_frmForm(U,V,N){function G(){e.setDirty(!0)}function W(){var a=!1;"TRUE"===ENABLE_SAVEANDCLOSE&&D&&(a=!0,D=!1);return a}function X(){var a=!1;y&&(a=!0);return a}function Y(){var a=[["CloseButton","SaveButton","NewButton","PrintPreviewButton","PrintButton"]];y?a=[["CloseButton","SaveNewButton","NewButton","PrintPreviewButton","PrintButton"]]:"TRUE"===ENABLE_SAVEANDCLOSE&&(a=[["CloseButton","SaveCloseButton","NewButton","PrintPreviewButton","PrintButton"]]);"html"===f||"view"===f?hasPermission(["HIST_DATAFORM"])&&
(a=["CloseButton SaveButton NewButton PrintPreviewButton PrintButton PrevVersionButton NextVersionButton".split(" ")],y?a=["CloseButton SaveNewButton NewButton PrintPreviewButton PrintButton PrevVersionButton NextVersionButton".split(" ")]:"TRUE"===ENABLE_SAVEANDCLOSE&&(a=["CloseButton SaveCloseButton NewButton PrintPreviewButton PrintButton PrevVersionButton NextVersionButton".split(" ")])):"viewonly"===f&&(a=[["CloseButton","PrintPreviewButton","PrintButton"]]);z&&(hasPermission(["HIST_DATAFORM"])?
(a=["CloseButton SaveButton PrintPreviewButton PrintButton PrevVersionButton NextVersionButton".split(" ")],y?a=["CloseButton SaveNewButton PrintPreviewButton PrintButton PrevVersionButton NextVersionButton".split(" ")]:"TRUE"===ENABLE_SAVEANDCLOSE&&(a=["CloseButton SaveCloseButton PrintPreviewButton PrintButton PrevVersionButton NextVersionButton".split(" ")])):(a=[["CloseButton","SaveButton","PrintPreviewButton","PrintButton"]],y?a=[["CloseButton","SaveNewButton","PrintPreviewButton","PrintButton"]]:
"TRUE"===ENABLE_SAVEANDCLOSE&&(a=[["CloseButton","SaveCloseButton","PrintPreviewButton","PrintButton"]])));Z=[{location:"root",title:"Home",layout:a}]}function O(){var a=ga();0<a.length?(b.dialogAlertScroll(a,function(){}),D=!1):(e.setDirty(!1),"add"===f?ha(ia):"edit"===f&&ja(ka))}function ga(){var a=m.validate();0<a.length&&(a="<ul>"+a+"</ul>");return a}function aa(){h=new jDock(b,{map:Z,tiles:la});h.render(d,".ge-button-panel");e.setDirty(H)}function ba(){aa();m.setID(v);m.setDataID(l);m.render(d,
".ge-renderer-content",q);b.element(d,".ge-renderer-content").find('img[src="images/noimage.png"]').addClass("ge-noimage");b.element(d,".ge-noimage").parent("a").unbind("click");var a="";"html"!==f&&0<P.length&&(a="<strong>Last Modified on </strong>"+ca+" by "+P);var c=m.getSectionFieldByType("DATA","CODE"),k="",k="add"===f?r+" - New":"edit"===f?n+" - Edit "+c:"view"===f||"viewonly"===f?n+" - View "+c:n;b.element(d,".ge-form-title").text(htmlEncode(k));b.element(d,".ge-lastmodified-field").html(a);
da&&("add"===f&&hasPermission(["ADD_DFDATA","ADD_"+g.toUpperCase()]))&&(b.element(d,".ge-liner-savenewtoggle").show(),b.element(d,".ge-savenewtoggle-text-entityname").html(htmlEncode(r)),b.unbindEvents(d,"ge-fieldcontrol-savenandnew"),b.bindEvent(e,d,".ge-fieldcontrol-savenandnew","FieldControlSaveAndNewToggle","onChange"));ma();0<I.length?h.enableButtons("PrevVersionButton","gs-darkblue-background-colour gs-glow-focusborder"):h.disableButtons("PrevVersionButton","gs-darkblue-background-colour");
0<E.length||"Y"===J?h.enableButtons("NextVersionButton","gs-darkblue-background-colour gs-glow-focusborder"):h.disableButtons("NextVersionButton","gs-darkblue-background-colour");b.unbindEvents(d,"ge-cancel-button");b.bindEvent(e,d,".ge-cancel-button","CancelButton","onClick");Q?b.element(d,".gb-form").addClass("gs-content-autoheight"):b.resizeDockedForm(d);processArray(A,function(a){var c=a.section,e=a.field,f=a.value;a=a.description;0<f.length&&(c=b.massageClassName(c,e),0<a.length?(b.element(d,
"."+c+"epv").val(f),b.element(d,"."+c+"tds").val(a),b.element(d,"."+c+"epd").val(a)):b.element(d,"."+c).val(f))});ea();e.setDirty(!1)}function K(){L++;F==L&&ba()}function fa(){0===M&&b.ajaxError();M++}function ka(a){b.broadcast(d,c.type,g+"listedited",l);W()?b.closeForm(d):X()?e.NewButton_onClick():w(!0)}function ia(a){l=a[0].id;b.broadcast(d,c.type,g+"listadded",l);W()?b.closeForm(d):X()?e.NewButton_onClick():(f="edit",w(!0))}function na(a){b.hideBusyIndicator();m.clear();m.append(a[0].jsondata);
P=a[0].modifyuser;ca=a[0].modifydatetime;I=a[0].previd;E=a[0].nextid;K()}function oa(a){b.hideBusyIndicator();m.clear();m.append(a[0].jsondata);v=a[0].id;K()}function pa(a){K()}function ha(a){var c=b.ajaxRequestCreate("entity_formdataadd",[{name:"entitycode",value:p},{name:"formentitycode",value:g},{name:"submittoclientid",value:""},{name:"relativeid",value:s},{name:"relative",value:t},{name:"relationship",value:u},{name:"jsondata",value:m.getData()}]);b.ajaxCall(URL_WEBSERVICE,c,a,b.ajaxError,G)}
function w(a){if(a)if(b.showBusyIndicator(),F=2,M=L=0,a="",a=0<g.length?g:p,a=b.ajaxRequestCreate("entity_entityoperationsfetchbyentitycode",[{name:"entitycode",value:a}]),b.ajaxCall(URL_WEBSERVICE,a,pa,b.ajaxError),"add"===f)F++,a=b.ajaxRequestCreate("entity_formfetch",[{name:"entitycode",value:p},{name:"entitydataid",value:v},{name:"formcode",value:B},{name:"relativeid",value:s},{name:"relative",value:t},{name:"relationship",value:u},{name:"mode",value:f}]),b.ajaxCall(URL_WEBSERVICE,a,oa,fa,G),
R();else{if("edit"===f||"html"===f||"view"===f||"viewonly"===f){F++;a="Y";if("html"===f||"view"===f||"viewonly"===f||!1===k)a="N";a=b.ajaxRequestCreate("entity_formdatafetch",[{name:"entitycode",value:p},{name:"formentitycode",value:g},{name:"uselatestform",value:a},{name:"formentitydataid",value:l},{name:"formentitydatacode",value:C},{name:"submittoclientid",value:""},{name:"relativeid",value:s},{name:"relative",value:t},{name:"relationship",value:u},{name:"historyid",value:S},{name:"mode",value:f}]);
b.ajaxCall(URL_WEBSERVICE,a,na,fa,G);R()}}else F=1,M=L=0,ba(),R()}function R(){b.lazyLoadLogic(g,function(a){a&&(a="entityform_"+g.toLowerCase(),x=new window[a](U,V,N));K()})}function ja(a){var c=b.ajaxRequestCreate("entity_formdataupdate",[{name:"entitycode",value:p},{name:"formentitycode",value:g},{name:"formentitydataid",value:l},{name:"submittoclientid",value:""},{name:"relativeid",value:s},{name:"relative",value:t},{name:"relationship",value:u},{name:"jsondata",value:m.getData()}]);b.ajaxCall(URL_WEBSERVICE,
c,a,b.ajaxError,G)}function ma(){b.unbindEvents(d,T);b.onDirty(d,T,function(){e.setDirty(!0)})}function ea(){b.unbindEvents(d,"ge-tab-start,ge-tab-end");b.bindEvent(e,d,".ge-tab-start","TabStart","onFocus");b.bindEvent(e,d,".ge-tab-end","TabEnd","onFocus");b.setTabOrder(d,"ge-tab-start,CloseButton,NewButton,SaveButton,SaveCloseButton,PrevVersionButton,NextVersionButton,"+T+",ge-tab-end")}var b=U,e=this,d=V,c=N,x=null,q=!1,H=!1,F=0,L=0,M=0,T="ge-form-title",P="",ca="",m=null,S="",I="",E="",J="N",D=
!1;console.log("ENTITY_FRMFORM:"+JSON.stringify(N));var p=c.entity;void 0===p&&(p="");var B=c.formcode;void 0===B&&(B="");var g=c.formentity;void 0===g&&(g="");var r=c.formentitydescription;void 0===r&&(r="");var v=c.formentityid;void 0===v&&(v="");var z=b.toBoolean(c.forreview);void 0===z&&(z=!1);var l=c.id;void 0===l&&(l="");var C=c.code;void 0===C&&(C="");var f=c.mode;void 0===f&&(f="");var k=c.uselatestform;"true"===k?k=!0:"false"===k?k=!1:void 0===k&&(k=!0);var n=c.title;void 0===n&&(n="");0===
n.length&&(n=r);var u=c.relationship;void 0===u&&(u="");var s=c.relativeid;void 0===s&&(s="");var t=c.relative;void 0===t&&(t="");var Q="TRUE"==TESTSCROLL&&!b.hasCapability("regionscroll")&&b.hasCapability("mobile");Q&&(b.element(d,".ge-content-panel").removeClass("gb-scrollable-panel"),b.element(d,".ge-thecontent").removeClass("gb-scrollable-content"),b.element(d,".gb-form").removeClass("gb-resizable"),b.element(d).css({position:"relative",height:"auto"}));var y=!1,da=!0;void 0!==c.saveandnew&&0<
c.saveandnew.length&&(da=b.toBoolean(c.saveandnew));var A=c.defaults;void 0===A&&(A=[]);var h,Z=[{location:"root",title:"Home",layout:["CloseButton SaveButton SaveCloseButton SaveNewButton NewButton PrintPreviewButton PrintButton".split(" ")]}],la=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){e.FormClose_onClick()},actionData:null,
tip:"Click here to close the form.",type:"toolbarbutton"},{id:"NewButton",caption:"New",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:function(){return hasPermission(["ADD_DFDATA","ADD_"+g.toUpperCase()])},action:function(){e.NewButton_onClick()},actionData:null,tip:"Click here to create a new data.",type:"toolbarbutton"},{id:"SaveButton",caption:"Save",classes:"",permissions:function(){return hasPermission(["ADD_DFDATA","EDT_DFDATA","EDT_"+g.toUpperCase()])},action:function(){e.SaveButton_onClick()},
actionData:null,tip:"Click here to save.",type:"toolbarbutton"},{id:"SaveCloseButton",caption:"Save &amp; Close",classes:"",permissions:function(){return hasPermission(["ADD_DFDATA","EDT_DFDATA","EDT_"+g.toUpperCase()])},action:function(){e.SaveCloseButton_onClick()},actionData:null,tip:"Click here to save &amp; close.",type:"toolbarbutton"},{id:"SaveNewButton",caption:"Save &amp; New",classes:"",permissions:function(){return hasPermission(["ADD_DFDATA","EDT_DFDATA"])||hasPermission(["ADD_"+g.toUpperCase()])&&
hasPermission(["EDT_"+g.toUpperCase()])},action:function(){e.SaveNewButton_onClick()},actionData:null,tip:"Click here to save &amp; close.",type:"toolbarbutton"},{id:"PrevVersionButton",caption:"Previous version",classes:"",permissions:[],action:function(){e.PrevVersionButton_onClick()},actionData:null,tip:"Click here to view previous version.",type:"toolbarbutton"},{id:"NextVersionButton",caption:"Next version",classes:"",permissions:[],action:function(){e.NextVersionButton_onClick()},actionData:null,
tip:"Click here to view next version.",type:"toolbarbutton"},{id:"PrintPreviewButton",caption:"Print Preview",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:function(){return!1},action:function(){e.PrintPreviewButton_onClick()},actionData:null,tip:"Click here to print preview.",type:"toolbarbutton"},{id:"PrintButton",caption:"Print",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:function(){return!1},action:function(){e.PrintButton_onClick()},actionData:null,
tip:"Click here to print.",type:"toolbarbutton"}];this.Renderer_onEvent=function(a,b,c,d){null!==x&&$.isFunction(x.Renderer_onEvent)&&x.Renderer_onEvent(a,b,c,d)};this.Form_allowMultipleInstances=function(){return b.isMDI()};this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return getFormDesktopRegion(g)};this.Form_isDirty=function(){return H};this.Form_onBroadcast=function(a,b,c){};this.Form_onClick=function(){b.setFormFocus(e,d)};this.Form_onDblClick=function(a,c,e){b.formToFront(d);
e.stopPropagation();b.zoomFormInOut(d)};this.Form_onFocus=function(a){if(void 0!==a&&null!==a&&(c.entity!==a.entity||c.flags!==a.flags||c.formcode!==a.formcode||c.formentity!==a.formentity||c.formentitydescription!==a.formentitydescription||c.formentityid!==a.formentityid||c.forreview!==a.forreview||c.id!==a.id||c.mode!==a.mode||c.title!==a.title))c=a,p=c.entity,void 0===p&&(p=""),B=c.formcode,void 0===B&&(B=""),g=c.formentity,void 0===g&&(g=""),r=c.formentitydescription,void 0===r&&(r=""),v=c.formentityid,
void 0===v&&(v=""),z=b.toBoolean(c.forreview),void 0===z&&(z=!1),l=c.id,void 0===l&&(l=""),C=c.code,void 0===C&&(C=""),f=c.mode,void 0===f&&(f=""),k=c.uselatestform,"true"===k?k=!0:"false"===k?k=!1:void 0===k&&(k=!0),n=c.title,void 0===n&&(n=""),0===n.length&&(n=r),u=c.relationship,void 0===u&&(u=""),s=c.relativeid,void 0===s&&(s=""),t=c.relative,void 0===t&&(t=""),A=c.defaults,void 0===A&&(A=[]),e.Form_onLoad();ea()};this.Form_onLoad=function(){q=q=!1;if("html"===f||"view"===f||"viewonly"===f)q=
!0;m=new jFormRenderer(b,{cbRenderComplete:e.renderComplete,cbSetDirty:e.setDirty,flags:c.flags,formified:!1,htmlmode:!1,printpreview:!1,readonly:q,style:"accordion"},e);Y();b.unbindEvents(d,"gb-form-close,gb-form-print,gb-form,gb-formtitle-inner-panel");b.bindEvent(e,d,".gb-form-close","FormClose","onClick");b.bindEvent(e,d,".gb-form-print","FormPrint","onClick");b.bindEvent(e,d,".gb-form","Form","onClick");b.bindEvent(e,d,".gb-form","Form","onDblClick");b.bindEvent(e,d,".gb-formtitle-inner-panel",
"FormTitle","onClick");w(!0)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(d)};this.Form_onResize=function(a,c){var e=b.getFormCanvasHeight(d)-80;Q?doNothing():(b.element(d,".ge-content-panel").height(e+"px"),b.element(d,".ge-thecontent").height("100%"))};this.renderComplete=function(){if(null!==x&&$.isFunction(x.onRegister))x.onRegister(e,m)};this.setDirty=function(a){H=a;q?(h.disableButtons("SaveButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty"),
h.disableButtons("SaveCloseButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty"),h.disableButtons("SaveNewButton","gs-darkblue-background-colour gs-glow-focusborder gs-red-background-colour gs-glow-dirty")):H?(h.disableButtons("PrintPreviewButton,PrintButton","gs-darkblue-background-colour"),h.enableButtons("SaveButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty"),h.enableButtons("SaveCloseButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty"),
h.enableButtons("SaveNewButton","gs-red-background-colour gs-glow-focusborder gs-glow-dirty")):(h.disableButtons("SaveButton","gs-red-background-colour gs-glow-dirty"),h.disableButtons("SaveCloseButton","gs-red-background-colour gs-glow-dirty"),h.disableButtons("SaveNewButton","gs-red-background-colour gs-glow-dirty"),h.enableButtons("PrintPreviewButton,PrintButton","gs-darkblue-background-colour gs-glow-focusborder"))};this.CancelButton_onClick=function(){e.Form_isDirty()?b.dialogConfirm("Are you sure you want to continue?<br><br>Your changes have not been saved. To stay on the form so that you can save your changes, click Cancel.",
function(){e.setDirty(!1);b.closeForm(d)}):b.closeForm(d)};this.FormClose_onClick=function(){b.closeForm(d)};this.FormPrint_onClick=function(){var a=b.element(d,".ge-thecontent").clone(),c=$('<iframe id="print-iframe" style="display:none;"></iframe>');$("body").append(c);(c[0].contentDocument||c[0].contentWindow.document).body.appendChild(a[0]);c[0].contentWindow.print();c.remove()};this.NewButton_onClick=function(){e.Form_isDirty()?"html"!==f&&"view"!==f&&"viewonly"!==f?b.dialogConfirm("Are you sure you want to continue?<br><br>Your changes have not been saved. To stay on the form so that you can save your changes, click Cancel.",
function(){q=!1;l="";f="add";w(!0);b.element(".ge-thecontent").animate({scrollTop:0},"slow")}):(q=!1,l="",f="add",w(!0)):(q=!1,l="",f="add",w(!0))};this.SaveButton_onClick=function(){if(e.Form_isDirty())try{O()}catch(a){e.setDirty(!0)}};this.SaveCloseButton_onClick=function(){D=!0;if(e.Form_isDirty())try{O()}catch(a){e.setDirty(!0)}};this.SaveNewButton_onClick=function(){D=!1;if(e.Form_isDirty())try{O()}catch(a){e.setDirty(!0)}};this.PrintPreviewButton_onClick=function(){e.Form_isDirty()};this.PrintButton_onClick=
function(){e.Form_isDirty()};this.NextVersionButton_onClick=function(){if(0<E.length||"Y"===J)0===E.length&&(J="N"),S=E,w(!0)};this.PrevVersionButton_onClick=function(){0<I.length&&(J="Y",S=I,w(!0))};this.FieldControlSaveAndNewToggle_onChange=function(a){y=a.checked?!0:!1;Y();aa()};this.TabEnd_onFocus=function(){b.element(d,".CloseButton").focus()};this.TabStart_onFocus=function(){b.element(d,".ge-code-field").focus()}};
