// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function entity_frmHTMLForm(H,I,J){function Q(){doNothing()}function D(){f.setID(m);f.setDataID(l);f.render(a,".ge-renderer-content",w);b.element(a,".ge-renderer-content").find('img[src="images/noimage.png"]').addClass("ge-noimage");b.element(a,".ge-noimage").parent("a").unbind("click");var K=f.getSectionFieldByType("DATA","CODE"),L="",L="add"===g?h+" - New":"edit"===g?d+" - Edit "+K:"view"===g?0<c.title.length?c.title:d+" - View "+K:d;b.element(a,".ge-form-title").text(htmlEncode(L));b.element(a,
".ge-lastmodified-field").html("");b.unbindEvents(a,M);if($.isFunction(E.onRegister))E.onRegister(e,f);0<z.length?n.enableButtons("PrevVersionButton","gs-darkblue-background-colour gs-glow-focusborder"):n.disableButtons("PrevVersionButton","gs-darkblue-background-colour");0<x.length||"Y"===A?n.enableButtons("NextVersionButton","gs-darkblue-background-colour gs-glow-focusborder"):n.disableButtons("NextVersionButton","gs-darkblue-background-colour");b.unbindEvents(a,"ge-cancel-button");b.bindEvent(e,
a,".ge-cancel-button","CancelButton","onClick");b.resizeDockedForm(a);N()}function R(){0===B&&b.ajaxError();B++}function S(b){f.clear();f.append(b[0].jsondata);z=b[0].previd;x=b[0].nextid;p++;C==p&&D()}function F(c){c?(C=2,B=p=0,c=b.ajaxRequestCreate("entity_formdatafetch",[{name:"entitycode",value:q},{name:"formentitycode",value:k},{name:"uselatestform",value:"N"},{name:"formentitydataid",value:l},{name:"formentitydatacode",value:r},{name:"submittoclientid",value:""},{name:"relativeid",value:s},
{name:"relative",value:t},{name:"relationship",value:u},{name:"historyid",value:G}]),b.ajaxCall(URL_WEBSERVICE,c,S,R,Q)):(C=1,B=p=0,D());T()}function T(){b.lazyLoadLogic(k,function(b){b&&(b="entityform_"+k.toLowerCase(),E=new window[b](H,I,J));p++;C==p&&D()})}function O(c){var a=f.getHTML(!1),a=b.ajaxRequestCreate("print_printstuff",[{name:"printjobs",value:[{type:"formreport",preview:"Y",filter:[{field:"formreport_id",value:""},{field:"html",value:B64.encode(a)}]}]}]);b.ajaxCall(URL_WEBSERVICE,a,
function(a){b.showForm("core.frmPrintPreview",{title:"Form Report",url:APP_DOMAIN_PATH+a.path+a.tag+".html",hidden:!c})},b.ajaxError)}function N(){b.unbindEvents(a,"ge-tab-start,ge-tab-end");b.bindEvent(e,a,".ge-tab-start","TabStart","onFocus");b.bindEvent(e,a,".ge-tab-end","TabEnd","onFocus");b.setTabOrder(a,"ge-tab-start,CloseButton,PrevVersionButton,NextVersionButton,"+M+",ge-tab-end")}var b=H,e=this,a=I,c=J,E=null,w=!1,C=0,p=0,B=0,M="ge-form-title",f=null,G="",z="",x="",A="N",q=c.entity;void 0===
q&&(q="");var y=c.formcode;void 0===y&&(y="");var k=c.formentity;void 0===k&&(k="");var h=c.formentitydescription;void 0===h&&(h="");var m=c.formentityid;void 0===m&&(m="");var v=b.toBoolean(c.forreview);void 0===v&&(v=!1);var l=c.id;void 0===l&&(l="");var r=c.code;void 0===r&&(r="");var g=c.mode;void 0===g&&(g="");var d=c.title;void 0===d&&(d="");0===d.length&&(d=h);var u=c.relationship;void 0===u&&(u="");var s=c.relativeid;void 0===s&&(s="");var t=c.relative;void 0===t&&(t="");var n,P=[{location:"root",
title:"Home",layout:[["CloseButton","PrintPreviewButton","PrintButton"]]}],U=[{id:"-",caption:"",classes:"",permissions:[],action:"",actionData:null,tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"gs-green-background-colour gs-glow-focusborder",permissions:[],action:function(){e.FormClose_onClick()},actionData:null,tip:"Click here to close the form.",type:"toolbarbutton"},{id:"PrevVersionButton",caption:"Previous version",classes:"gb-cell-disabled",permissions:[],action:function(){e.PrevVersionButton_onClick()},
actionData:null,tip:"Click here to view previous version.",type:"toolbarbutton"},{id:"NextVersionButton",caption:"Next version",classes:"gb-cell-disabled",permissions:[],action:function(){e.NextVersionButton_onClick()},actionData:null,tip:"Click here to view next version.",type:"toolbarbutton"},{id:"PrintPreviewButton",caption:"Print Preview",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:function(){return!1},action:function(){e.PrintPreviewButton_onClick()},actionData:null,
tip:"Click here to print preview.",type:"toolbarbutton"},{id:"PrintButton",caption:"Print",classes:"gs-darkblue-background-colour gs-glow-focusborder",permissions:function(){return!1},action:function(){e.PrintButton_onClick()},actionData:null,tip:"Click here to print.",type:"toolbarbutton"}];this.Form_allowMultipleInstances=function(){return b.isMDI()};this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return"C"};this.Form_isDirty=function(){return!1};this.Form_onBroadcast=
function(b,c,a){doNothing()};this.Form_onClick=function(){b.setFormFocus(e,a)};this.Form_onDblClick=function(c,e,d){b.formToFront(a);d.stopPropagation();b.zoomFormInOut(a)};this.Form_onFocus=function(a){if(void 0!==a&&null!==a&&(c.entity!==a.entity||c.flags!==a.flags||c.formcode!==a.formcode||c.formentity!==a.formentity||c.formentitydescription!==a.formentitydescription||c.formentityid!==a.formentityid||c.forreview!==a.forreview||c.id!==a.id||c.mode!==a.mode||c.title!==a.title))c=a,q=c.entity,void 0===
q&&(q=""),y=c.formcode,void 0===y&&(y=""),k=c.formentity,void 0===k&&(k=""),h=c.formentitydescription,void 0===h&&(h=""),m=c.formentityid,void 0===m&&(m=""),v=b.toBoolean(c.forreview),void 0===v&&(v=!1),l=c.id,void 0===l&&(l=""),r=c.code,void 0===r&&(r=""),g=c.mode,void 0===g&&(g=""),d=c.title,void 0===d&&(d=""),0===d.length&&(d=h),u=c.relationship,void 0===u&&(u=""),s=c.relativeid,void 0===s&&(s=""),t=c.relative,void 0===t&&(t=""),e.Form_onLoad();N()};this.Form_onLoad=function(){w=w=!1;var d=[["CloseButton",
"PrintPreviewButton","PrintButton"]];w=!0;hasPermission(["HIST_DATAFORM"])&&(d=[["CloseButton","PrintPreviewButton","PrintButton","PrevVersionButton","NextVersionButton"]]);v&&(d=hasPermission(["HIST_DATAFORM"])?[["CloseButton","PrintPreviewButton","PrintButton","PrevVersionButton","NextVersionButton"]]:[["CloseButton","PrintPreviewButton","PrintButton"]]);f=new jFormRenderer(b,{flags:c.flags,formified:!1,htmlmode:!0,printpreview:!1,readonly:w,style:"accordion"},e);P=[{location:"root",title:"Home",
layout:d}];n=new jDock(b,{alwaysvisiblebuttoncount:2,enablemobiledropdown:!0,map:P,tiles:U});n.render(a,".ge-button-panel");b.unbindEvents(a,"gb-form-close,gb-form,gb-formtitle-inner-panel");b.bindEvent(e,a,".gb-form-close","FormClose","onClick");b.bindEvent(e,a,".gb-form","Form","onClick");b.bindEvent(e,a,".gb-form","Form","onDblClick");b.bindEvent(e,a,".gb-formtitle-inner-panel","FormTitle","onClick");F(!0)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(a)};
this.Form_onResize=function(c,d){var e=b.getFormCanvasHeight(a)-80;b.element(a,".ge-content-panel").height(e+"px");b.element(a,".ge-thecontent").height("100%")};this.CancelButton_onClick=function(){b.closeForm(a)};this.FormClose_onClick=function(){b.closeForm(a)};this.PrintPreviewButton_onClick=function(){O(!0)};this.PrintButton_onClick=function(){O(!1)};this.NextVersionButton_onClick=function(){if(0<x.length||"Y"===A)0===x.length&&(A="N"),G=x,F(!0)};this.PrevVersionButton_onClick=function(){0<z.length&&
(A="Y",G=z,F(!0))};this.TabEnd_onFocus=function(){b.element(a,".CloseButton").focus()};this.TabStart_onFocus=function(){b.element(a,".ge-code-field").focus()}};
