// Projly v20260922 =============================================================================
// Copyright (C) 2024 Projly Pty Ltd. Released under the MIT License.
//
// ==============================================================================================
// AWAF v20260922 ===============================================================================
// Copyright (C) 2012-2024 Mitsukibo Pty Ltd, Julian Cassin & Francis Weston. Released under the MIT License.

/*jsl:ignore*/
function entity_frmLister(Ra,Sa,Ta){var fa,oa,Aa,Ba,pa;function qa(){var a=!1;processArray(v,function(e){"branch_id"==e.field&&(e.value=t,a=!0)});a||v.push({field:"branch_id",value:t});s=JSON.stringify(v)}function Ca(){fa=Da.columns.mode[m];oa=Da.returns.mode[m];ra()}function sa(){"select"===m?Q=ta.mode.select:"deleteformgroup"===m?Q=ta.mode.deleteformgroup:"form"===q&&(Q=ta.entityType.form);Ea();Fa();ra()}function Ua(a){ca=a.multiSelect;if(0<D.length){var e=D.split(",");processArray(e,function(a){"multiselect"===
a&&(ca=!0);"nomultiselect"===a&&(ca=!1)})}a.multiSelect=ca;return a}function Va(a){var e;processArray(ga.actions,function(b){var c=!1;if(b.id==a||b.operationcode==a)e=b,c=!0;return c});return e}function ua(){var a=[];processArray(Q,function(e){if(b.toBoolean(e.requiresselection)){e=e.code;var c=e+"Button";"PUB_DATAFORM"===e?doNothing():a.push(c)}});return a.join(",")}function r(a){var e=!1;processArray(ga.actions,function(b){if(b.id==a||b.operationcode==a)e=$.isFunction(b.permissions)?b.permissions():
0===b.permissions.length?!0:hasPermission(b.permissions);return e});return e}function Ea(){var a="";"deleteformgroup"===m?a="entity_dataformentitylist":"form"===q?a="entity_formdatalist":"entity"===q&&(a="entity_entitydatalist");Aa=a;Ba=[{name:"entitycode",value:x},{name:"formentityid",value:R},{name:"formentitycode",value:l},{name:"entityid",value:U},{name:"order",value:""},{name:"filter",value:""},{name:"fixedfilter",value:s},{name:"relationship",value:I},{name:"relativeid",value:J},{name:"relative",
value:K},{name:"offset",value:0},{name:"limit",value:0}];fa=[];oa=M;pa=y}function Wa(){M=["id","code","description"];processArray(Q,function(a){a=a.parameters;if(0<a.length){a=str_replace(a,"%","__");a=b.urlToJSON(a);var e=a.idfield;void 0!==e&&M.push(e);e=a.descriptionfield;void 0!==e&&M.push(e);a=a.titlefield;void 0!==a&&M.push(a)}})}function va(a){var e="",e="",e=0<E.length?E+" - ":"";return e=str_replace(a,"~BRANCHNAME~",e)}function w(a){var e="";if(r(a)){var c=Va(a),h=n.getSelection(oa),e=c.multiSelect;
void 0===e&&(e=!1);e=c.requiresSelection;void 0===e&&(e=!0);e=c.prompt;if(0===e.length){var f=l.toUpperCase();if("DeleteButton"===a||"DELETE"===a||"DEL"===a||"DELDATA"===a||"DEL_DFDATA"===a||a==="DEL_"+f||a==="DELDATA_"+f)e="deleteformgroup"===m?"DELDATA"===a||"DELDATA_"+f?"Are you sure you want to delete the selected item(s)?<br /><br />All data including history will be permanently deleted.":"Are you sure you want to delete the selected item(s)?<br /><br />Form data and template will be permanently deleted.":
"Continue and delete the "+pa+" selection?"}$.isFunction(c.action)&&(0<e.length?b.dialogConfirm(e,function(){c.action(h)},c.description+" Confirmation"):c.action(h))}}function Ga(a){var e=!1;0<z.length&&processArray(z,function(b){a===b&&(e=!0)});return e}function Ha(a,e,c,h,N,p){h=str_replace(h,"%","__");var d={};d.branchid=t;d.branchname=E;d.code=void 0;d.component=F;d.description="";d.descriptionfield="description";d.entity=x;d.entitycode=x;d.entitydataid="";d.exclusive=V;d.fixedfilter=s;d.passfilter=
G;d.passedfilter=u;d.flags=c;d.forcedownload=!0;d.formcode=W;d.formentity=l;d.formentitycode=l;d.formentitydescription=X;d.formentityid=R;d.formified=!1;d.forreview=!1;d.hideoperations=k;d.id="";d.idfield="id";d.idlist=[];d.mode="add";d.operationcode=a;d.relationship=I;d.relative=K;d.relativeid=J;d.title=y;d.titlefield="";d.type=q;d.uselatestform=Y;switch(a.split("_")[0]){case "ADD":"builder"===m?(e="ADD",d.component=ha):(e="ADD",d.component=F);d.mode="add";break;case "DEL":case "DELETE":e="DELETE";
d.component="";d.mode="";break;case "EDT":case "EDIT":"builder"===m?(e="EDIT",d.component=ha):(e="EDIT",d.component=F);d.mode="edit";break;case "EXP":case "EXPORT":"builder"===m?(e="EXPORT",d.component=ha):(e="EXPORT",d.component=F);d.mode="export";break;case "VW":case "VIEW":"builder"===m?(e="VIEW",d.component=ha):(e="VIEW",d.component=F);d.mode="view";break;case "ADDTO":d.component=e;e="ADDTO";d.exclusive="Y";d.mode="";break;case "DL":case "DOWNLOAD":e="DOWNLOAD";d.component="";d.mode="";break;
case "INVOKE":d.component=e;e="INVOKE";d.exclusive="N";d.mode="";break;case "LIST":break;case "LISTFORMS":case "LISTITEMS":e="LISTFORMS";$.isArray(p)?(d.formentity=p[0].formentitycode,d.formentityid=p[0].id):(d.formentity=p.formentitycode,d.formentityid=p.id);d.entity="dataform";d.mode="renderer";d.type="form";break;case "MAKEFORM":d.component=e;e="MAKEFORM";b.dialogAlert("MAKEFORM is being used, this is to be deprecated.",doNothing);break;case "OPENFORM":d.component=e;e="SHOWFORM";break;case "SELECT":d.component=
e;e="SELECT";break;case "SHOWFORM":d.component=e;e="SHOWFORM";break;case "RUNCODE":d.component=e;e="RUNCODE";break;case "RUNCODETEST":d.component=e;e="RUNCODETEST";break;default:d.operationcode=0<e.length?e:a}var g={},g=void 0!==N&&null!==N?N:b.urlToJSON(h);void 0==g.descriptionfield&&(g.descriptionfield=d.descriptionfield);void 0==g.idfield&&(g.idfield=d.idfield);void 0==g.titlefield&&(g.titlefield=d.titlefield);$.isArray(p)?ca?0<p.length&&(processArray(p,function(a){d.idlist.push(a[g.idfield])}),
d.id=d.idlist[0],d.entitydataid=d.id):(0<p.length&&(d.idlist.push(p[0][g.idfield]),d.id=p[0][g.idfield],d.description=p[0][g.descriptionfield],d.entitydataid=d.id),0<g.titlefield.length&&(d.title=p[0][g.titlefield])):void 0!==p&&null!==p&&(d.id=p[g.idfield],d.description=p[g.descriptionfield],d.idlist.push(d.id),d.entitydataid=d.id,0<g.titlefield.length&&(d.title=p[g.titlefield]));h=str_replace(h,"%DESCRIPTION%",encodeURIComponent(d.description));h=str_replace(h,"__DESCRIPTION__",encodeURIComponent(d.description));
h=str_replace(h,"%RELATIONSHIP%",encodeURIComponent(I));h=str_replace(h,"__RELATIONSHIP__",encodeURIComponent(I));h=str_replace(h,"%RELATIVEID%",encodeURIComponent(J));h=str_replace(h,"__RELATIVEID__",encodeURIComponent(J));h=str_replace(h,"%RELATIVE%",encodeURIComponent(K));h=str_replace(h,"__RELATIVE__",encodeURIComponent(K));h=str_replace(h,"%SELECTED%",encodeURIComponent(d.id));h=str_replace(h,"__SELECTED__",encodeURIComponent(d.id));h=str_replace(h,"%LIST%",encodeURIComponent(JSON.stringify(d.idlist)));
h=str_replace(h,"__LIST__",encodeURIComponent(JSON.stringify(d.idlist)));h=str_replace(h,"%TITLE%",encodeURIComponent(d.title));h=str_replace(h,"__TITLE__",encodeURIComponent(d.title));h=str_replace(h,"__20"," ");c=b.urlToJSON(h);a={};void 0!==N&&null!==N&&$.extend(!0,a,N);$.extend(!0,a,c);if($.isArray(a.fixedfilter)){var r=d.id;processArray(a.fixedfilter,function(a){"string"===typeof a.value&&(a.value=str_replace(a.value,"%SELECTED%",r),a.value=str_replace(a.value,"__SELECTED__",r))})}void 0==a.branchid&&
(a.branchid=d.branchid);void 0==a.branchname&&(a.branchname=d.branchname);void 0==a.code&&(a.code=d.code);void 0==a.component&&(a.component=d.component);void 0==a.description&&(a.description=d.description);void 0==a.descriptionfield&&(a.descriptionfield=d.descriptionfield);void 0==a.entity&&(a.entity=d.entity);void 0==a.entitycode&&(a.entitycode=d.entitycode);void 0==a.entitydataid&&(a.entitydataid=d.entitydataid);void 0==a.exclusive&&(a.exclusive=d.exclusive);void 0==a.fixedfilter&&(a.fixedfilter=
d.fixedfilter);void 0==a.passfilter&&(a.passfilter=d.passfilter);void 0==a.passedfilter&&(a.passedfilter=d.passedfilter);void 0==a.searchfields&&(a.searchfields=d.searchfields);void 0==a.flags&&(a.flags=d.flags);void 0==a.forcedownload&&(a.forcedownload=d.forcedownload);void 0==a.formcode&&(a.formcode=d.formcode);void 0==a.formentity&&(a.formentity=d.formentity);void 0==a.formentitycode&&(a.formentitycode=d.formentitycode);void 0==a.formentitydescription&&(a.formentitydescription=d.formentitydescription);
void 0==a.formentityid&&(a.formentityid=d.formentityid);void 0==a.formified&&(a.formified=d.formified);void 0==a.forreview&&(a.forreview=d.forreview);void 0==a.hideoperations&&(a.hideoperations=d.hideoperations);void 0==a.id&&(a.id=d.id);void 0==a.idfield&&(a.idfield=d.idfield);void 0==a.idlist&&(a.idlist=d.idlist);void 0==a.mode&&(a.mode=d.mode);void 0==a.operationcode&&(a.operationcode=d.operationcode);void 0==a.relationship&&(a.relationship=d.relationship);void 0==a.relative&&(a.relative=d.relative);
void 0==a.relativeid&&(a.relativeid=d.relativeid);void 0==a.title&&(a.title=d.title);void 0==a.titlefield&&(a.titlefield=d.titlefield);void 0==a.type&&(a.type=d.type);void 0==a.uselatestform&&(a.uselatestform=d.uselatestform);switch(e){case "EDIT":a.mode="edit",N=a.operationcode.replace("EDT_","VW_"),hasPermission(N)&&(e="VIEW")}switch(e){case "ADD":Xa(a);break;case "DELETE":Ya(a);break;case "EDIT":Za(a);break;case "VIEW":$a(a);break;case "EXPORT":Ia();break;case "ADDTO":ab(a);break;case "INVOKE":bb(a);
break;case "DOWNLOAD":b.viewDocument(a.id,a.forcedownload);break;case "INSTALLFILEFORMAT":cb();break;case "INSTALLPROFILE":db();break;case "LIST":b.showForm(a.component,a);break;case "LISTFORMS":b.showForm(ia,a);break;case "MAKEFORM":b.makeForm(a.component,a);break;case "OPENFORM":b.showForm(a.component,a);break;case "SHOWFORM":b.showForm(a.component,a);break;case "SELECT":ja=n.getSelection(M);b.closeForm(f);break;case "RUNCODE":Ja(a);break;case "RUNCODETEST":Ja(a);break;default:wa(a)}}function Fa(){var a=
[],e="",c="",h=["CloseButton"];0<t.length&&h.push("BranchButton");processArray(Q,function(f){var g=f.code,d=g.split("_")[0],k=g+"Button",l=null,l=void 0!==f.permissions?f.permissions:[f.code];h.push(k);e={id:k,description:f.description,permissions:function(){return 0===l.length?!0:hasPermission(l)&&!Ga(f.code)},multiSelect:b.toBoolean(f.allowmultiple),requiresSelection:b.toBoolean(f.requiresselection),prompt:f.prompt,operation:d,operationcode:g,action:function(a){Ha(g,f.command,f.flags,f.parameters,
null,a)}};c={id:k,caption:f.description,classes:"",permissions:function(){return void 0!==f.permissions?0===f.permissions.length?!0:hasPermission(f.permissions)&&!Ga(f.code):r(k)},action:w,actionData:g,tip:"Click here to "+htmlEncode(f.description)+".",type:"toolbarbutton"};a.push(e);ka.push(c)});h.push("ClearSelectionButton");b.toBoolean(ENABLE_XDEVICE)&&h.push("MyDeviceButton");ga={id:Z,actions:a,broadcasts:[{messages:["added","deleted","edited"],action:"refresh"}]};la[0].layout[0]=h}function Xa(a){var e=
a.component;if(0===e.length||e===ia)e=xa;b.showForm(e,a)}function ab(a){b.showFormPopup(a.component,a,function(e){0<e.length&&(a.formentityid=e[0].id,a.id=e[0].id,a.description=e[0].description,a.idlist=e,a.operationcode=a.formentity,a.entitycode="addto_"+a.relative+"_",a.exclusive="N",wa(a))})}function bb(a){b.showFormPopup(a.component,a,function(e){0<e.length&&(a.formentityid=e[0].id,a.id=e[0].id,a.description=e[0].description,a.idlist=e,a.entitycode="invoke_"+a.relative+"_",a.exclusive="N",wa(a))})}
function Ja(a){a=b.jsonToNameValueArray(a);a=b.ajaxRequestCreate("entity_customoperationexecute",a);b.ajaxCall(URL_WEBSERVICE,a,function(a){try{var c=a.file_url;0<c.length&&b.lazyLoadApp(c)}catch(f){alert(f.message),console.log(f)}},b.ajaxError)}function wa(a){a=b.jsonToNameValueArray(a);a=b.ajaxRequestCreate("entity_customoperationexecute",a);b.ajaxCall(URL_WEBSERVICE,a,eb,b.ajaxError)}function Ya(a){a=b.jsonToNameValueArray(a);var e="";"form"===q?e="entity_formdatadelete":"entity"===q&&(e="entity_entitydatadelete");
0<e.length&&(a=b.ajaxRequestCreate(e,a),b.ajaxCall(URL_WEBSERVICE,a,fb,b.ajaxError))}function Za(a){if(void 0!==a.id){var e=a.component;if(0===e.length||e===ia)e=xa;b.showForm(e,a)}}function cb(){b.showFormPopup(Ka,{mode:LIST_FILEFORMATINSTALLABLE,resultfields:["id"],title:"Install File Format"},function(a){0<a.length&&(a=b.ajaxRequestCreate("import_fileformatinstall",[{name:"id",value:a[0].id}]),b.ajaxCall(URL_WEBSERVICE,a,function(){n.refresh(!1)},g.asyncError))})}function db(){b.showFormPopup(Ka,
{mode:LIST_PROFILEINSTALLABLE,resultfields:["id"],title:"Install Profile"},function(a){0<a.length&&(a=b.ajaxRequestCreate("security_profileinstall",[{name:"id",value:a[0].id}]),b.ajaxCall(URL_WEBSERVICE,a,function(){n.refresh(!1)},g.asyncError))})}function $a(a){if(void 0!==a.id){var e=a.component;if(0===e.length||e===ia)e=xa;b.showForm(e,a)}}function La(){O=new jDock(b,{map:la,tiles:ka});O.render(f,".ge-button-panel");O.disableButtons(ua(),"btn-primary");var a="",a=0<y.length?y:pa;b.element(f,".ge-form-title").text(a);
b.hasCapability("mobile")||b.element(f,".ge-search-input").focus();b.element(f,".ge-searchbar").hide();b.element(f,".ge-dispatchdate").hide();b.element(f,".ge-receiverstate").hide();if(0<A.length){b.element(f,".ge-searchbar").show();var a=-1<A.indexOf("dispatchdate"),e=-1<A.indexOf("receiverstate");a&&b.element(f,".ge-dispatchdate").show();e&&b.element(f,".ge-receiverstate").show()}b.element(f,".ge-search-input").val(H);gb();n.refresh(!1);0<H.length&&L()}function gb(){var a={cbOnGetFormHeight:g.Grid_onGetFormHeight,
cbOnSelection:g.Grid_onDblClick,cbOnSelectionChange:g.Grid_onSelectionChange,cbOnRowReorder:g.Grid_onRowReorder,cbOnPreRowReorder:g.Grid_onPreRowReorder,cbOnClickEvent:function(a,b,c,f,g){c.off("click");c.on("click",function(a){a.stopPropagation();Ha(f,f,"","",g,b)});c.trigger("click")},columns:fa,filterType:"string",parameters:Ba,extraParameters:[],multiSelect:!1,rowReorder:ma,webServiceFunction:Aa},a=Ua(a);n=new jDatatableRenderer(b,a);n.render(f,".ge-entity-grid")}function ra(){da++;S==da&&La()}
function eb(a){n.refresh()}function fb(a){n.refresh(!1);b.broadcast(f,"entity",Z+"deleted")}function hb(a){Ma=a.fields;D=0<D.length?D+(","+a.flags):a.flags;fa=Ma;ra()}function ib(a){var e,c=[],h;e={id:"DeviceNoneButton",caption:"None",classes:"",action:g.MyDeviceSelection_onClick,actionData:"NONE",tip:"Click here to select device",type:""};c.push(e);processArray(a,function(a){h=a.device;b.toBoolean(a.isselected)&&(h+='&nbsp;<i class="fa fa-check" aria-hidden="true"></i>');e={id:"Device-"+getGUID()+
"-Button",caption:h,classes:"",action:g.MyDeviceSelection_onClick,actionData:a.id,tip:"Click here to select device",type:""};c.push(e)});processArray(ka,function(a,b,e){"MyDeviceButton"===a.id&&(a.actionDataList=c,ka[e]=a)});ya&&(O.render(f,".ge-button-panel"),ya=!1)}function jb(a){Q=a;Wa();Ea();Fa();S=1;da=0;"deleteformgroup"===m?Ca():Na()}function kb(a){Oa()}function Pa(a){a?(S=1,da=0,"deleteformgroup"===m?(S=2,sa(),Ca()):"form"===q&&"dataform"===x||"select"===m?(S=2,sa(),Na()):0<l.length?(Qa(),
b.toBoolean(ENABLE_XDEVICE)&&(S++,Oa())):"form"===q?sa():Qa()):(S=2,da=0,La())}function lb(a,e,c,f){a=b.ajaxRequestCreate("entity_customoperationexecute",[{name:"entitycode",value:a},{name:"id",value:c},{name:"operationcode",value:e}]);b.ajaxCall(URL_WEBSERVICE,a,f,b.ajaxError)}function Ia(){var a="";"form"===q?a="entity_formdataexport":"entity"===q&&alert("not implemented");if(0<a.length){var e=n.getParams(),a=b.ajaxRequestCreate(a,e);b.ajaxCall(URL_WEBSERVICE,a,doNothing,b.ajaxError)}}function Na(){var a=
"";"form"===q?a="entity_formdataheadersfetchbyentitycode":"entity"===q&&(a="entity_entitydataheadersfetchbyentitycode");a=b.ajaxRequestCreate(a,[{name:"entitycode",value:x},{name:"formentitycode",value:l}]);b.ajaxCall(URL_WEBSERVICE,a,hb,b.ajaxError)}function Oa(){var a=b.ajaxRequestCreate("core_getcurrentdevices",[{name:"formentity",value:l}]);b.ajaxCall(URL_WEBSERVICE,a,ib,b.ajaxError)}function Qa(){var a="",a=0<l.length?l:x,a=b.ajaxRequestCreate("entity_entityoperationsfetchbyentitycode",[{name:"entitycode",
value:a}]);b.ajaxCall(URL_WEBSERVICE,a,jb,b.ajaxError)}function mb(){b.element(f,".ge-form-title").text("");b.unbindEvents(f,"gb-form-close,gb-form,gb-formtitle-inner-panel");b.bindEvent(g,f,".gb-form-close","FormClose","onClick");b.bindEvent(g,f,".gb-form","Form","onClick");b.bindEvent(g,f,".gb-form","Form","onDblClick");b.bindEvent(g,f,".gb-formtitle-inner-panel","FormTitle","onClick");b.unbindEvents(f,"ge-search-input,ge-searchclear-button");b.unbindEvents(f,"ge-dispatchdatefrom-input,ge-dispatchdateto-input,ge-receiverstate-input");
b.unbindEvents(f,"ge-dispatchdatefromclear-button,ge-dispatchdatetoclear-button,ge-receiverstateclear-button");b.bindEvent(g,f,".ge-searchclear-button","btnSearchClear","onClick");b.bindEvent(g,f,".ge-search-input","SearchField","onEnterKey");b.bindEvent(g,f,".ge-dispatchdatefromclear-button","btnDispatchDateFromClear","onClick");b.bindEvent(g,f,".ge-dispatchdatetoclear-button","btnDispatchDateToClear","onClick");b.bindEvent(g,f,".ge-receiverstateclear-button","btnReceiverStateClear","onClick");b.bindEvent(g,
f,".ge-dispatchdatefrom-input","DispatchDateFrom","onChange");b.bindEvent(g,f,".ge-dispatchdateto-input","DispatchDateTo","onChange");b.bindEvent(g,f,".ge-receiverstate-input","ReceiverState","onClick");b.bindDatePicker(f,".ge-btdatepicker",{dateFormat:DATE_OUTPUTFORMAT,showOtherMonths:!0,changeMonth:!0,changeYear:!0,yearRange:"c-75:c+5",onSelect:function(a,e){b.element(this).trigger("change")},onChangeMonthYear:function(a,e,c){c=new Date(b.element(this).datepicker("getDate"));c.setMonth(e-1);c.setYear(a);
b.element(this).datepicker("setDate",c);b.element(this).trigger("change")}})}function L(){var a=[];aa&&0<aa.length&&a.push({field:"dispatchdatefrom",value:aa});ba&&0<ba.length&&a.push({field:"dispatchdateto",value:ba});T&&0<T.length&&a.push({field:"receiverstate",value:T});n.search(H,a,[])}var b=Ra,g=this,f=Sa,c=Ta,ha="widgetformbuilder.wgtFormBuilder",Ka="core.frmRecordChooser",xa="entity.frmForm",ia="entity.frmLister",Z="list",S=0,da=0,ga,n,Ma=[],Q=[],ca=!1,M=["id"],ja=[],F=c.component;void 0===
F&&(F="");var x=c.entity;void 0===x&&(x="");var U=c.entityid;void 0===U&&(U="");var s="",v=[];try{void 0!==c.fixedfilter&&("string"===typeof c.fixedfilter&&0<c.fixedfilter.length?(s=c.fixedfilter,s=b.str_quotes(s),v=JSON.parse(s)):v=c.fixedfilter,s=JSON.stringify(v))}catch(ob){doNothing()}var G=c.passfilter,G=void 0!==G?b.toBoolean(G):!1,u,P=[];try{void 0===c.passedfilter?G&&(P=c.fixedfilter,u=JSON.stringify(v)):("string"===typeof c.passedfilter&&0<c.passedfilter.length?(u=c.passedfilter,u=b.str_quotes(u),
P=JSON.parse(u)):P=c.passedfilter,u=JSON.stringify(P))}catch(pb){doNothing()}var B="",A=[];try{void 0!==c.searchfields&&("string"===typeof c.searchfields&&0<c.searchfields.length?(B=c.searchfields,B=b.str_quotes(B),A=JSON.parse(B)):A=c.searchfields,B=JSON.stringify(A))}catch(qb){doNothing()}var t="",E="";b.toBoolean(b.getProperty("enablebranches"))&&(t=c.branchid,void 0===t&&(t=""),E=c.branchname,void 0===E&&(E=""),0<t.length&&qa());var V=c.exclusive;void 0===V&&(V="N");var W=c.formcode;void 0===
W&&(W="");var l=c.formentity;void 0===l&&(l="");var Z=l+Z,R=c.formentityid;void 0===R&&(R="");var m=c.mode;void 0===m&&(m="renderer");var H=c.searchkeyword;void 0===H&&(H="");var aa="",ba="",T="",C=c.title;void 0===C&&(C="");var y=C,y=va(C),X=c.formentitydescription;void 0===X&&(X=y);var Y=c.uselatestform;void 0===Y&&(Y=!0);var q=c.type;void 0===q&&(q="");var I=c.relationship;void 0===I&&(I="");var J=c.relativeid;void 0===J&&(J="");var K=c.relative;void 0===K&&(K="");var ea=c.relationshiptitle;void 0===
ea&&(ea="");var D=c.flags;void 0===D&&(D="");var k=c.hideoperations,z=[];'""'===k&&(k="");void 0===k?(k="",z=[]):("string"===typeof k&&0<k.length?(k=b.str_quotes(k),z=JSON.parse(k)):z=k,k=JSON.stringify(z));var ma=c.reorder,ma=void 0!==ma?b.toBoolean(ma):!1,na="",za="",ya=!1,O,la=[{location:"root",title:"Home",layout:[]}],ka=[{id:"-",caption:"",classes:"",permissions:[],action:"",tip:"",type:"blank"},{id:"CloseButton",caption:"Close",classes:"btn-success",permissions:[],action:function(){g.FormClose_onClick()},
tip:"Click here to close the "+c.formentitydescription+" list.",type:"toolbarbutton"},{id:"BranchButton",caption:"Branches",classes:"btn-primary",permissions:["MYBRANCHSELECT"],action:function(a){b.showFormPopup("entity.frmEntityChooser",a,function(b){if(0<b.length){var c=b[0].id;lb(a.entity,a.operation,c,function(a){t=c;E=a.branchname;y=C;y=va(C);qa();Pa(!0)})}},!1,!0)},actionData:{type:"form",entity:"systemform",formentity:"BRANCH",mode:"select",title:"Branch Selection",operation:"mybranchget"},
tip:"Click here to change the branch for this "+c.formentitydescription+" list.",type:"toolbarbutton"},{id:"MyDeviceButton",caption:"My Devices",classes:"btn-primary",permissions:function(){return!1},action:function(){return!1},actionDataList:[],tip:"Click here to select device",type:"toolbardevicebutton"}],nb={select:["CloseButton","SELECTButton"],listitems:["CloseButton","LISTITEMSButton"],builder:["CloseButton","ADDButton","EDTButton","DELButton","VWButton"],renderer:"CloseButton ClearSelectionButton ADDButton EDTButton DELButton VWButton MyDeviceButton".split(" "),
deleteformgroup:["CloseButton","DELButton"]},ta={mode:{select:[{code:"SELECT",description:"Select",allowmultiple:"N",requiresselection:"Y",permissions:[],prompt:""}],listitems:[{code:"LISTITEMS",description:"List Forms",allowmultiple:"N",requiresselection:"Y",permissions:[],prompt:""}],deleteformgroup:[{code:"DEL_DFDATA",description:"Permanently Delete",allowmultiple:"N",requiresselection:"Y",permissions:[],prompt:"Are you sure you want to permanently delete the data?<br />YOU WILL LOSE ALL DATA INCLUDING THE FORM TEMPLATE."},
{code:"DELDATA_DFDATA",description:"Delete All Data",allowmultiple:"N",requiresselection:"Y",permissions:[],prompt:"Are you sure you want to proceed?<br />This will clear all form submission for this form tempalate"}]},entityType:{form:[{code:"ADD_DFDATA",description:"Add",allowmultiple:"Y",requiresselection:"N",prompt:""},{code:"EDT_DFDATA",description:"Edit",allowmultiple:"N",requiresselection:"Y",prompt:""},{code:"DEL_DFDATA",description:"Delete",allowmultiple:"Y",requiresselection:"Y",prompt:""},
{code:"VW_DFDATA",description:"View",allowmultiple:"N",requiresselection:"Y",prompt:""},{code:"EXP_DFDATA",description:"Export",allowmultiple:"N",requiresselection:"Y",prompt:""}]}},Da={columns:{mode:{select:[{id:"rownum",field:"rownum",name:"#",sortable:"N"},{id:"code",field:"code",name:"Code",sortable:"Y"},{id:"description",field:"description",name:"Description",sortable:"Y"}],deleteformgroup:[{id:"rownum",field:"rownum",name:"#",sortable:"N"},{id:"description",field:"description",name:"Description",
sortable:"Y"},{id:"modifydatetime",field:"modifydatetime",name:"Created",sortable:"Y"}]}},returns:{mode:{select:["id","code","formentitycode","description"],deleteformgroup:["id","code","formentitycode","description"],builder:["id","code","description"],renderer:M}}};this.Grid_onGetFormHeight=function(){var a=b.element(f,".gb-form").height(),e=b.element(f,".ge-button-panel").height(),a=a-230;0<A.length&&(a-=10);40<e&&(a-=e-50);return a};this.Form_allowMultipleInstances=function(){return b.isMDI()};
this.Form_canClose=function(){return!0};this.Form_getDesktopRegion=function(){return getListerDesktopRegion(l)};this.Form_onBroadcast=function(a,b,c){var f;processArray(ga.broadcasts,function(a){processArray(a.messages,function(c){var d=Z+c;d.toLowerCase()==b.toLowerCase()?f=a.action:c.toLowerCase()==b.toLowerCase()&&(f=a.action);return void 0!==f});return void 0!==f});void 0!==f&&($.isFunction(f)?f():"refresh"===f&&n.refresh())};this.Form_onClick=function(){b.setFormFocus(g,f)};this.Form_onDblClick=
function(a,c,g){b.formToFront(f);g.stopPropagation();b.zoomFormInOut(f)};this.Form_onFocus=function(a){if(void 0!==a&&null!==a&&(c.returnfields!==a.returnfields||c.entity!==a.entity||c.entityid!==a.entityid||c.exclusive!==a.exclusive||c.branchid!==a.branchid||c.fixedfilter!==a.fixedfilter||c.passfilter!==a.passfilter||c.passedfilter!==a.passedfilter||c.searchfields!==a.searchfields||c.flags!==a.flags||c.formcode!==a.formcode||c.formentity!==a.formentity||c.formentitydescription!==a.formentitydescription||
c.formentityid!==a.formentityid||c.formified!==a.formified||c.hideoperations!==a.hideoperations||c.mode!==a.mode||c.searchkeyword!==a.searchkeyword||c.title!==a.title||c.type!==a.type||c.relationship!==a.relationship||c.relativeid!==a.relativeid||c.relationshiptitle!==a.relationshiptitle)){c=a;F=c.component;void 0===F&&(F="");x=c.entity;void 0===x&&(x="");U=c.entityid;void 0===U&&(U="");s="";v=[];try{void 0!==c.fixedfilter&&("string"===typeof c.fixedfilter&&0<c.fixedfilter.length?(s=c.fixedfilter,
s=b.str_quotes(s),v=JSON.parse(s)):v=c.fixedfilter,s=JSON.stringify(v))}catch(e){doNothing()}G=c.passfilter;G=void 0!==G?b.toBoolean(G):!1;try{void 0===c.passedfilter?G&&(P=c.fixedfilter,u=JSON.stringify(v)):("string"===typeof c.passedfilter&&0<c.passedfilter.length?(u=c.passedfilter,u=b.str_quotes(u),P=JSON.parse(u)):P=c.passedfilter,u=JSON.stringify(P))}catch(n){doNothing()}B="";A=[];try{void 0!==c.searchfields&&("string"===typeof c.searchfields&&0<c.searchfields.length?(B=c.searchfields,B=b.str_quotes(B),
A=JSON.parse(B)):A=c.searchfields,B=JSON.stringify(A))}catch(h){doNothing()}t=c.branchid;void 0===t&&(t="");E=c.branchname;void 0===E&&(E="");0<t.length&&qa();V=c.exclusive;void 0===V&&(V="N");W=c.formcode;void 0===W&&(W="");l=c.formentity;void 0===l&&(l="");R=c.formentityid;void 0===R&&(R="");m=c.mode;void 0===m&&(m="renderer");H=c.searchkeyword;void 0===H&&(H="");T=ba=aa="";C=c.title;void 0===C&&(C="");y=C;y=va(C);X=c.formentitydescription;void 0===X&&(X=y);Y=c.uselatestform;void 0===Y&&(Y=!0);
q=c.type;void 0===q&&(q="");I=c.relationship;void 0===I&&(I="");J=c.relativeid;void 0===J&&(J="");K=c.relative;void 0===K&&(K="");ea=c.relationshiptitle;void 0===ea&&(ea="");D=c.flags;void 0===D&&(D="");k=c.hideoperations;z=[];'""'===k&&(k="");void 0===k?(k="",z=[]):("string"===typeof k&&0<k.length?(k=b.str_quotes(k),z=JSON.parse(k)):z=k,k=JSON.stringify(z));g.Form_onLoad()}b.unbindEvents(f,"ge-tab-start,ge-tab-end");b.bindEvent(g,f,".ge-tab-start","TabStart","onFocus");b.bindEvent(g,f,".ge-tab-end",
"TabEnd","onFocus");a=la[0].layout[0].join(",");b.setTabOrder(f,"ge-tab-start,"+a+",ge-tab-end")};this.Form_onFocusLost=function(){};this.Form_onLoad=function(){mb();Z=l+"list";la[0].layout[0]=nb[m];Pa(!0)};this.Form_onPermissionCheck=function(){return!0};this.FormTitle_onClick=function(){b.formToFront(f)};this.Form_onResize=function(a,c){b.element(f,".ge-entity-grid").width(a-20+"px");n.resize()};this.FormResult=function(){return ja};this.FormClearSelection_onClick=function(){n.clearSelection()};
this.FormClose_onClick=function(){ja=[];b.closeForm(f)};this.FormExport_onClick=function(){Ia()};this.Grid_onDblClick=function(a){a="";0<l.length&&(a=l.toUpperCase(),r("LISTITEMS_"+a)?w("LISTITEMS_"+a):r("LISTITEMS")?w("LISTITEMS"):r("SELECT")?w("SELECT"):r("EDT_"+a)?w("EDT_"+a):r("EDT_DFDATA")?w("EDT_DFDATA"):r("EDT")?w("EDT"):r("EXP_DFDATA")?w("EXP_DFDATA"):r("EXP")?w("EXP"):r("VW_"+a)?w("VW_"+a):r("VW_DFDATA")?w("VW_DFDATA"):r("VW")&&w("VW"))};this.Grid_onSelectionChange=function(a){void 0!==O&&
null!==O&&(0<a.length?O.enableButtons(ua(),"btn-primary"):O.disableButtons(ua(),"btn-primary"))};this.Grid_onPreRowReorder=function(a,b,c){na=n.getDatatable().row(b.index).data().id};this.Grid_onRowReorder=function(a,c,f){a=l;n.getDatatable();f=c[0];c=c[c.length-1];f.oldData===na?za=f.newData:c.oldData===na&&(za=c.newData);c=b.ajaxRequestCreate("entity_entityreorder",[{name:"entitycode",value:a},{name:"sourceid",value:na},{name:"destinationid",value:za}]);b.ajaxCall(URL_WEBSERVICE,c,function(a){n.refresh()},
b.ajaxError)};this.btnSearchClear_onClick=function(){H="";L();b.element(f,".ge-search-input").val("");b.element(f,".ge-search-input").focus()};this.SearchField_onEnterKey=function(a){a=b.element(a).val();H=massageKeyword(a);L()};this.btnDispatchDateFromClear_onClick=function(){b.element(f,".ge-dispatchdatefrom-input").val("");b.element(f,".ge-dispatchdatefrom-input").focus();aa="";L()};this.btnDispatchDateToClear_onClick=function(){b.element(f,".ge-dispatchdateto-input").val("");b.element(f,".ge-dispatchdateto-input").focus();
ba="";L()};this.btnReceiverStateClear_onClick=function(){b.element(f,".ge-receiverstate-input").val("");b.element(f,".ge-receiverstate-input").focus();T="";L()};this.DispatchDateFrom_onChange=function(a){aa=b.element(f,".ge-dispatchdatefrom-input").val();L()};this.DispatchDateTo_onChange=function(a){ba=b.element(f,".ge-dispatchdateto-input").val();L()};this.ReceiverState_onClick=function(a){b.showFormPopup("entity.frmEntityChooser",{type:"form",entity:"systemform",formentity:"STATE",mode:"select",
title:"To State",resultfields:["id","description"]},function(a){0<a.length&&(T=a[0].description,b.element(f,".ge-receiverstate-input").val(T),L())},!1,!0)};this.SelectButton_onClick=function(){ja=n.getSelection(M);b.closeForm(f)};this.MyDeviceSelection_onClick=function(a){a=b.ajaxRequestCreate("core_saveuserformdevice",[{name:"deviceid",value:a},{name:"formentity",value:l}]);b.ajaxCall(URL_WEBSERVICE,a,kb,b.ajaxError);ya=!0};this.TabEnd_onFocus=function(){b.element(f,".CloseButton").focus()};this.TabStart_onFocus=
function(){}};
